import type { BaseRemnant2Item } from "#/games/remnant2/types/local-item";

type Remnant2AmuletItem = BaseRemnant2Item & {};

const AMULETS: Remnant2AmuletItem[] = [
	{
		category: "AMULET",
		name: "Abrasive Whetstone",
		imageUrl: "items/amulets/abrasivewhetstone.png",
		internalSlug: "Amulet_AbrasiveWhetstone_C",
		id: "6sqyf9",
		dlc: "BASE",
		searchableTags: ["Critical Chance"],
		description: [
			"When attacking a BLEEDING enemy, Critical Chance is increased by 15% and Critical Damage is increased by 15%.",
		],
		wikiUrl: "https://remnant2.wiki.gg/Abrasive_Whetstone",
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "AMULET",
		name: "Ankh of Power",
		imageUrl: "items/amulets/ankhofpower.png",
		internalSlug: "Amulet_AnkhOfPower_C",
		id: "ca8ada",
		dlc: "BASE",
		searchableTags: ["All Damage"],
		description: [
			"Grants 15% increase to all damage. Consuming a Relic increases the bonus to 25% for 15s.",
		],
		wikiUrl: "https://remnant2.wiki.gg/Ankh_of_Power",
		location: { world: "Root Earth", dungeon: ["Ashen Wasteland"] },
	},
	{
		category: "AMULET",
		name: "Beads of the Valorous",
		imageUrl: "items/amulets/beadsofthevalorous.png",
		internalSlug: "Amulet_BeadsOfTheValorous_C",
		id: "n8gqNY",
		dlc: "BASE",
		searchableTags: ["Damage Reduction", "Movement Speed", "Health"],
		description: [
			"Increases Damage Reduction and Movement Speed by 1% for every 5% of missing Max Health. Bonus is doubled at or below 50% Max Health. Max 10 stacks.",
		],
		wikiUrl: "https://remnant2.wiki.gg/Beads_of_the_Valorous",
		location: { world: "Yaesha", dungeon: "World Drop" },
	},
	{
		category: "AMULET",
		name: "Birthright of the Lost",
		imageUrl: "items/amulets/birthrightofthelost.png",
		internalSlug: "Amulet_BirthrightOfTheLost_C",
		id: "41ookr",
		dlc: "BASE",
		searchableTags: ["Perfect Dodge"],
		description: [
			"Increases All Damage by 10%. On Perfect Dodge, apply EXPOSED on the attacker and enemies with 3m of the wearer for 15s.",
		],
		wikiUrl: "https://remnant2.wiki.gg/Birthright_of_the_Lost",
		location: { world: "Losomn", dungeon: "World Drop" },
	},
	{
		category: "AMULET",
		name: "Brazen Amalgam",
		imageUrl: "items/amulets/brazenamalgam.png",
		internalSlug: "Amulet_BrazenAlloy_C",
		id: "mkroo2",
		dlc: "DLC3",
		searchableTags: [],
		description: [
			"Increases Critical Chance by 1.5% and Movement Speed while Aiming by 2.5% per second. Max 10 stacks. Dodge, Slide, or Flop removes stacks",
		],
		wikiUrl: "https://remnant2.wiki.gg/Brazen_Amalgam",
		location: { world: `N'Erud`, dungeon: ["Logistics Bridge"] },
	},
	{
		category: "AMULET",
		name: "Brewmaster's Cork",
		imageUrl: "items/amulets/brewmasterscork.png",
		internalSlug: "Amulet_BrewmastersCork_C",
		id: "6il3tm",
		dlc: "BASE",
		searchableTags: ["Damage Reduction"],
		description: [
			"Increases active Concoction limit by 2 and reduces all incoming damage by 2% for each active Concoction.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Brewmaster's_Cork`,
		location: { world: "Losomn", dungeon: "World Drop" },
	},
	{
		category: "AMULET",
		name: "Broken Pocket Watch",
		imageUrl: "items/amulets/brokenpocketwatch.png",
		internalSlug: "Amulet_BrokenPocketWatch_C",
		id: "sap1xm",
		dlc: "BASE",
		searchableTags: ["Stamina"],
		description: [
			"Increases Stamina Regeneration by 25 and reduces Stamina Cost by 50%.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Broken_Pocket_Watch`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "AMULET",
		name: "Butcher's Fetish",
		imageUrl: "items/amulets/butchersfetish.png",
		internalSlug: "Amulet_ButchersFetish_C",
		id: "67s1pu",
		dlc: "BASE",
		searchableTags: ["Critical Chance", "Charged Melee"],
		description: [
			"Increases Critical Chance by 15% and Critical Damage by 25% for 5s after striking an enemy with a Charged Melee Attack.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Butcher's_Fetish`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "AMULET",
		name: "Canine Keepsake",
		imageUrl: "items/amulets/caninekeepsake.png",
		internalSlug: "Amulet_CanineKeepsake_C",
		id: "z496hr",
		dlc: "BASE",
		searchableTags: [],
		communityTags: ["Misty Step"],
		description: [
			"Increases All Damage by 2.5%, Critical Chance by 1.5%, and Critical Damage by 1.5% for every 5% of total Health present as Grey Health. Max 10 stacks.",
		],
		wikiUrl: "https://remnant2.wiki.gg/Canine_Keepsake",
		location: { world: "Yaesha", dungeon: "World Drop" },
	},
	{
		category: "AMULET",
		name: "Cervine Keepsake",
		imageUrl: "items/amulets/cervinekeepsake.png",
		internalSlug: "Amulet_CervineKeepsake_C",
		id: "5sfzsd",
		dlc: "DLC2",
		searchableTags: ["Movement Speed"],
		description: [
			"On Relic Use, gain a stack of CALL OF THE DOE for 30s. Max 5 stacks.",
			"CALL OF THE DOE: Increases Movement Speed by 4% per stack. When CALL OF THE DOE expires, regain 1 Relic Charge per stack.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Cervine_Keepsake`,
		communityTags: [`Misty Step`],
		location: {
			world: "Yaesha",
			biome: "Floating Forests",
			injectable: "Shrine of the Doe",
		},
	},
	{
		category: "AMULET",
		name: "Cessation Bulbel",
		imageUrl: "items/amulets/cessationbulbel.png",
		internalSlug: "Amulet_CessationBulbel_C",
		id: "zXxT8K",
		dlc: "DLC3",
		searchableTags: ["All Damage"],
		description: [
			"Activating a Mod consumes all current SHIELD. For every 20 SHIELD consumed, increases All Damage dealt by 4% for 10s. Max 10 stacks.",
		],
		wikiUrl: "https://remnant2.wiki.gg/Cessation_Bulbel",
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "AMULET",
		name: "Chains of Amplification",
		imageUrl: "items/amulets/chainsofamplification.png",
		internalSlug: "Amulet_ChainsOfAmplification_C",
		id: "5sfzsx",
		dlc: "BASE",
		searchableTags: ["Status Effect", "All Damage"],
		description: [
			"Increases all damage dealt to targets suffering from a Status Effect by 20%.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Chains_of_Amplification`,
		location: { world: "Losomn", dungeon: "World Drop" },
	},
	{
		category: "AMULET",
		name: "Chef Medal",
		imageUrl: "items/amulets/chefmedal.png",
		internalSlug: "Amulet_ChefMedal_C",
		id: "9yuvc8",
		dlc: "DLC3",
		searchableTags: ["Perfect Dodge"],
		description: [
			"On Perfect Dodge, automatically trigger effects that require Relic Use to activate.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Chef_Medal`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "AMULET",
		name: "Cleansing Stone",
		imageUrl: "items/amulets/cleansingstone.png",
		internalSlug: "Amulet_CleansingStone_C",
		id: "nm7b6f",
		dlc: "BASE",
		searchableTags: ["Status Effect"],
		description: [
			"Reduces Duration of Elemental Status Effects against wearer by 50%. Relic use cleanses Elemental Status effects and grants 25% of wearers Max Health to all allies within 20m when cleansed.",
		],
		communityTags: [`AOE/Aura`],
		wikiUrl: `https://remnant2.wiki.gg/Cleansing_Stone`,
		location: { world: "Losomn", biome: "Burning City", injectable: "Rookery" },
	},
	{
		category: "AMULET",
		name: "Core Booster",
		imageUrl: "items/amulets/corebooster.png",
		internalSlug: "Amulet_CoreBooster_C",
		id: "wb4ixr",
		dlc: "BASE",
		searchableTags: ["Weakspot Damage"],
		description: [
			"Increases Weakspot damage by 50% for 10s after killing an enemy.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Core_Booster`,
		location: {
			world: `N'Erud`,
			dungeon: ["Ascension Spire"],
		},
	},
	{
		category: "AMULET",
		name: "Cost of Betrayal",
		imageUrl: "items/amulets/costofbetrayal.png",
		internalSlug: "Amulet_CostOfBetrayal_C",
		dlc: "DLC1",
		id: "hug5mz",
		searchableTags: ["All Damage", "Damage Reduction"],
		description: [
			"Reduces Relic Charges to 1. Increases All Damage by 25% when wearer has 1 Relic Charge. Increases incoming damage by 25% when wearer has no Relic Charge. After 15s of having no Relic Charges, regain 1 Relic Charge.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Cost_of_Betrayal`,
		location: { world: "Losomn", dungeon: ["Chamber of the Faithless"] },
	},
	{
		category: "AMULET",
		name: "Crisis Core",
		imageUrl: "items/amulets/crisiscore.png",
		internalSlug: "Amulet_CrisisCore_C",
		id: "L6noPy",
		dlc: "BASE",
		searchableTags: ["Perfect Dodge", "Damage Reduction"],
		description: [
			"When a single source of Enemy Damage exceeds 15% of Max Health, automatically trigger effects that require Perfect Dodge to activate and gain 15% Damage Reduction for 3s.",
			"Can only happen once every 3 seconds.",
		],
		wikiUrl: "https://remnant2.wiki.gg/Crisis_Core",
		location: { world: `N'Erud`, dungeon: "World Drop" },
	},

	{
		category: "AMULET",
		name: "Daredevil's Charm",
		imageUrl: "items/amulets/daredevilscharm.png",
		internalSlug: "Amulet_DaredevilsCharm_C",
		id: "ik580i",
		dlc: "BASE",
		searchableTags: [
			"All Damage",
			"Movement Speed",
			"Hardcore Reward",
			"Encumbrance",
		],
		description: [
			"Gain 7.5% to all damage dealt and 3.75% Movement Speed for each empty Armor slot.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Daredevil's_Charm`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "AMULET",
		name: "Death's Embrace",
		imageUrl: "items/amulets/deathembrace.png",
		internalSlug: "Amulet_DeathsEmbrace_C",
		id: "i13ipm",
		dlc: "BASE",
		searchableTags: ["All Damage"],
		description: [
			"Gain 15% to All Damage when Health is not completely full. When below 50% Health, gain an additional 10% bonus to All Damage and HASTE.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Death's_Embrace`,
		communityTags: [`Misty Step`],
		location: { world: "Yaesha", dungeon: ["The Forbidden Grove"] },
	},
	{
		category: "AMULET",
		name: "Death-Soaked Idol",
		imageUrl: "items/amulets/deathsoakedidol.png",
		internalSlug: "Amulet_DeathSoakedIdol_C",
		dlc: "DLC1",
		id: "ui1miz",
		searchableTags: ["All Damage", "Status Effect"],
		description: [
			"Increases All Damage by 6% for each entity within 20m suffering from a unique Negative Status Effect. Max 5 stacks.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Death-Soaked_Idol`,
		location: {
			world: "Losomn",
			biome: "Burning City",
			injectable: "Ethereal Manor",
		},
	},
	{
		category: "AMULET",
		name: "Decayed Margin",
		imageUrl: "items/amulets/decayedmargin.png",
		internalSlug: "Amulet_DecayedMargin_C",
		id: "dipf2o",
		dlc: "BASE",
		searchableTags: ["Lifesteal", "Melee Damage"],
		description: [
			"Melee hits gain 3% base damage dealt as Lifesteal. For each 25% missing Health, gain 3% additional Melee Lifesteal. When Health is full, gain 35% Melee Damage.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Decayed_Margin`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "AMULET",
		name: "Detonation Trigger",
		imageUrl: "items/amulets/detonationtrigger.png",
		internalSlug: "Amulet_DetonationTrigger_C",
		id: "3zi80a",
		dlc: "BASE",
		description: [
			"Increases Explosion damage by 25%. Explosions apply 165 → 495 BURNING damage over 5s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Detonation_Trigger`,
		location: {
			world: `N'Erud`,
			biome: `N'Erud Wasteland`,
			injectable: `Extraction Hub`,
		},
	},
	{
		category: "AMULET",
		name: "Difference Engine",
		imageUrl: "items/amulets/differenceengine.png",
		internalSlug: "Amulet_DifferenceEngine_C",
		id: "2zr6vu",
		dlc: "BASE",
		searchableTags: ["All Damage", "Lifesteal"],
		description: [
			"While a SHIELD is active, All Damage is increased by 20%, and 4.5% of Base Damage dealt is returned as Lifesteal.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Difference_Engine`,
		location: { world: `N'Erud`, dungeon: ["The Dark Conduit"] },
	},
	{
		category: "AMULET",
		name: "Downward Spiral",
		imageUrl: "items/amulets/downwardspiral.png",
		internalSlug: "Amulet_DownwardSpiral_C",
		id: "1k2x4r",
		dlc: "BASE",
		searchableTags: [
			"Fire Rate",
			"Melee Attack Speed",
			"Ranged Damage",
			"Melee Damage",
		],
		description: [
			"Increase Fire Rate by 10% and Melee Attack Speed by 15%. For every missing 10% of Max Health, gain 4% Ranged Damage (Max 20%) and 5% Melee Damage (Max 25%).",
		],
		wikiUrl: `https://remnant2.wiki.gg/Downward_Spiral`,
		location: { world: "Yaesha", dungeon: [`The Chimney`] },
	},
	{
		category: "AMULET",
		name: "Echo Chamber",
		imageUrl: "items/amulets/echochamber.png",
		internalSlug: "Amulet_EchoChamber_C",
		id: "rPV99a",
		dlc: "DLC3",
		searchableTags: [],
		communityTags: ["Explosive Damage"],
		description: [
			`Increases Explosive Damage by 10% and AOE Size by 25%. Inflicting Explosive Damage applies EXPOSED for 5s. Max 15s.`,
			`EXPOSED: Target receives 15% additional damage from all sources.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Echo_Chamber`,
		location: { world: `N'Erud`, dungeon: ["Athenaeum Wek"] },
	},
	{
		category: "AMULET",
		name: "Echo of the Forest",
		imageUrl: "items/amulets/echooftheforest.png",
		internalSlug: "Amulet_EchoOfTheForest_C",
		id: "2VokuK",
		dlc: "DLC2",
		searchableTags: [],
		description: [
			`On Relic Use, gain GIFT OF THE FOREST for 15s. When Gift of the Forest expires, Relic effect is recast.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Echo_of_the_Forest`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "AMULET",
		name: "Effigy Pendant",
		imageUrl: "items/amulets/effigypendant.png",
		internalSlug: "Amulet_EffigyPendant_C",
		id: "vkcf4e",
		dlc: "BASE",
		searchableTags: ["Grey Health", "All Damage", "Damage Reduction"],
		description: [
			`While Grey Health is present, gain 15% to all damage dealt, 10% damage reduction and 1 additional hit before Grey Health is removed.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Effigy_Pendant`,
		location: {
			world: "Losomn",
			biome: "Burning City",
			injectable: "Rookery",
		},
	},
	{
		category: "AMULET",
		name: "Effluvium Enhancer",
		imageUrl: "items/amulets/effluviumenhancer.png",
		internalSlug: "Amulet_EffluviumEnhancer_C",
		id: "kah85t",
		dlc: "BASE",
		description: ["Increases ACID damage by 25% and CORROSIVE damage by 50%."],
		wikiUrl: `https://remnant2.wiki.gg/Effluvium_Enhancer`,
		location: {
			world: `N'Erud`,
			dungeon: "Vendor",
		},
	},
	{
		category: "AMULET",
		name: "Emergency Switch",
		imageUrl: "items/amulets/emergencyswitch.png",
		internalSlug: "Amulet_EmergencySwitch_C",
		id: "8dcefr",
		dlc: "BASE",
		description: [
			"When below 50% Health, chance to consume Relic on use is reduced by 50%. Final Relic Charge is not consumed on use, but effect cannot be triggered again for 30s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Emergency_Switch`,
		location: { world: `N'Erud`, dungeon: "World Drop" },
	},
	{
		category: "AMULET",
		name: "Energized Neck Coil",
		imageUrl: "items/amulets/energizedneckcoil.png",
		internalSlug: "Amulet_EnergizedNeckCoil_C",
		id: "c52jp0",
		dlc: "BASE",
		searchableTags: ["Status Effect"],
		description: [
			"Increases Status Effect damage by 20%. Directly applying a damaging Status Effect creates a 2m Explosion for 20% of its full damage.",
			"Each target can be affected once every 5s.",
		],
		communityTags: [`AOE/Aura`, `Explosive Damage`],
		wikiUrl: `https://remnant2.wiki.gg/Energized_Neck_Coil`,
		location: { world: "Labyrinth", dungeon: ["Fractured Ingress"] },
	},
	{
		category: "AMULET",
		name: "Energy Diverter",
		imageUrl: "items/amulets/energydiverter.png",
		internalSlug: "Amulet_EnergyDiverter_C",
		id: "evwgwk",
		dlc: "BASE",
		searchableTags: ["Critical Chance", "All Damage"],
		description: [
			"While a SHIELD is active, gain 10% Critical Chance and 15% to All Damage dealt.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Energy_Diverter`,
		location: {
			world: `N'Erud`,
			dungeon: "Vendor",
		},
	},
	{
		category: "AMULET",
		name: "Escalation Protocol",
		imageUrl: "items/amulets/escalationprotocol.png",
		internalSlug: "Amulet_EscalationProtocol_C",
		id: "vxcn9e",
		dlc: "BASE",
		searchableTags: ["All Damage"],
		description: [
			`Increases all damage dealt by 2.5% for 10s after killing an enemy. Stacks 10x. Dealing damage refreshes the timer.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Escalation_Protocol`,
		location: { world: "Root Earth", dungeon: ["Corrupted Harbor"] },
	},
	{
		category: "AMULET",
		name: "Exhaust Valve",
		imageUrl: "items/amulets/exhaustvalve.png",
		internalSlug: "Amulet_ExhaustValve_C",
		id: "C22peH",
		dlc: "DLC3",
		searchableTags: ["Heat Generation", "Fire Rate"],
		description: [
			`Increases Heat Decay Rate by 25% and Weapons that Generate Heat no longer Overheat. At Max Heat, Fire Rate is reduced by 20%.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Exhaust_Valve`,
		location: { world: `N'Erud`, dungeon: ["Stagnant Manufactory"] },
	},
	{
		category: "AMULET",
		name: "Fragrant Thorn",
		imageUrl: "items/amulets/fragrantthorn.png",
		internalSlug: "Amulet_FragrantThorn_C",
		id: "Hx5iNF",
		dlc: "BASE",
		searchableTags: ["Status Effect", "All Damage"],
		description: [
			"Increases Status Effect Damage by 20%. Inflicting 4 or more unique Negative Status Effects on a target applies EXPOSED for 15s.",
			"EXPOSED: Target receives 15% additional damage from all sources.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Fragrant_Thorn`,
		location: { world: "Yaesha", dungeon: "World Drop" },
	},
	{
		category: "AMULET",
		name: "Full Moon Circlet",
		imageUrl: "items/amulets/fullmooncirclet.png",
		internalSlug: "Amulet_FullMoonCirclet_C",
		id: "8xn7hh",
		dlc: "BASE",
		searchableTags: ["Lifesteal"],
		description: [
			"Ranged damage Lifesteals 3% Base Damage dealt. At full health, Ranged damage is increased by 25%.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Full_Moon_Circlet`,
		communityTags: [`Misty Step`],
		location: { world: "Yaesha", dungeon: ["Imperial Gardens"] },
	},
	{
		category: "AMULET",
		name: "Gift of Euphoria",
		imageUrl: "items/amulets/giftofeuphoria.png",
		internalSlug: "Amulet_GiftOfEuphoria_C",
		dlc: "DLC1",
		id: "70ryol",
		searchableTags: ["Stamina", "Critical Chance"],
		description: [
			`Spending 20 Stamina grants 5% Critical Chance for 5s. Max 5 stacks.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Gift_of_Euphoria`,
		location: { world: "Losomn", dungeon: ["Walk of Rememberance"] },
	},
	{
		category: "AMULET",
		name: "Gift of Melancholy",
		imageUrl: "items/amulets/giftofmelancholy.png",
		internalSlug: "Amulet_GiftOfMelancholy_C",
		dlc: "DLC1",
		id: "65851b",
		searchableTags: ["All Damage", "Stamina"],
		description: [
			`Increases All Damage dealt by 25% when Stamina is at 100% for 7s.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Gift_of_Melancholy`,
		location: { world: "Losomn", dungeon: ["Pathway of the Fallen"] },
	},
	{
		category: "AMULET",
		name: "Gift of the Unbound",
		imageUrl: "items/amulets/giftoftheunbound.png",
		internalSlug: "Amulet_GiftOfTheUnbound_C",
		dlc: "DLC1",
		id: "u7am0w",
		searchableTags: ["Movement Speed"],
		description: [
			`Disables negative effects of Burden Rings and increases Movement Speed by 5% for each Burden lifted. (Max 20%).`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Gift_of_the_Unbound`,
		location: { world: "Losomn", dungeon: "Quest" },
	},
	{
		category: "AMULET",
		name: "Golden Ribbon",
		imageUrl: "items/amulets/goldribbon.png",
		internalSlug: "Amulet_GoldenRibbon_C",
		id: "m0l0u5",
		dlc: "BASE",
		searchableTags: ["Mod Damage"],
		description: [
			"Increases Mod damage by 25%. Activating a Mod grants HASTE for 15s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Golden_Ribbon`,
		location: {
			world: "Losomn",
			biome: "Fae Palace",
			injectable: "Silver and Gold",
		},
	},
	{
		category: "AMULET",
		name: "Gunfire Security Lanyard",
		imageUrl: "items/amulets/gunfiresecuritylanyard.png",
		internalSlug: "Amulet_GunfireSecurityLanyard_C",
		id: "wbqua6",
		dlc: "BASE",
		searchableTags: ["Reload Speed"],
		description: [
			`Automatically reloads Magazine over time. Does not work for single shot weapons.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Gunfire_Security_Lanyard`,
		location: { world: "The Backrooms", dungeon: "The Backrooms" },
	},
	{
		category: "AMULET",
		name: "Gunslinger's Charm",
		imageUrl: "items/amulets/gunslingerscharm.png",
		internalSlug: "Amulet_GunslingersCharm_C",
		id: "qqg64h",
		dlc: "BASE",
		searchableTags: ["Fire Rate", "Reload Speed"],
		description: [`Increases Fire Rate by 15% and Reload Speed by 25%.`],
		wikiUrl: `https://remnant2.wiki.gg/Gunslinger's_Charm`,
		location: { world: "Ward 13", dungeon: "Quest" },
	},
	{
		category: "AMULET",
		name: "Hallowed Egg",
		imageUrl: "items/amulets/hallowedegg.png",
		internalSlug: "Amulet_HallowedEgg_C",
		id: "pfew3v",
		dlc: "BASE",
		searchableTags: ["Melee Damage"],
		description: [
			"Spending at least 30% of a Firearm's magazine to deal damage increases Melee damage by 10% for 7s. Stacks 5x.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Hallowed_Egg`,
		location: {
			world: "Yaesha",
			biome: "Jungles of Yaesha",
			injectable: "Root Nexus",
		},
	},
	{
		category: "AMULET",
		name: `Hangman's Noose`,
		imageUrl: "items/amulets/hangmansnoose.png",
		internalSlug: "Amulet_HangmansNoose_C",
		id: "4zvuco",
		dlc: "BASE",
		searchableTags: [],
		description: [
			`Restricts Health to 50% and backfills with permanent Grey Health. All incoming damage is fully converted into Grey Health and Grey Health cannot be removed.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Hangman's_Noose`,
		location: { world: "Losomn", dungeon: "World Drop" },
	},
	{
		category: "AMULET",
		name: "Hyperconductor",
		imageUrl: "items/amulets/hyperconductor.png",
		internalSlug: "Amulet_Hyperconductor_C",
		id: "c0z3fy",
		dlc: "BASE",
		searchableTags: ["Skill Duration"],
		description: [
			`Doubles Base Skill Charges but increases all Skill Cooldowns by 25%.`,
			`Doubles base N'Erudian Energy Reserves for Turret and Drone.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Hyperconductor`,
		location: { world: `N'Erud`, dungeon: ["Terminus Station"] },
	},
	{
		category: "AMULET",
		name: "Index of the Scribe",
		imageUrl: "items/amulets/indexofthescribe.png",
		internalSlug: "Amulet_IndexOfTheScribe_C",
		dlc: "DLC1",
		id: "3lzs0c",
		searchableTags: ["Mod Damage", "Weakspot Damage"],
		description: [`Increases Mod and Skill Weakspot Damage by 35%.`],
		wikiUrl: `https://remnant2.wiki.gg/Index_of_the_Scribe`,
		location: { world: "Losomn", dungeon: ["Forlorn Coast"] },
	},
	{
		category: "AMULET",
		name: "Indignant Fetish",
		imageUrl: "items/amulets/indignantfetish.png",
		internalSlug: "Amulet_IndignantFetish_C",
		id: "dqhstq",
		dlc: "BASE",
		searchableTags: ["Damage Reduction", "All Damage"],
		description: [
			`Taking damage from any source increase All Damage dealt by 20% and reduces All Incoming Damage by 10%. Lasts 15s.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Indignant_Fetish`,
		location: { world: "Losomn", dungeon: "World Drop" },
	},
	{
		category: "AMULET",
		name: "Inert Overcharger",
		imageUrl: "items/amulets/inertovercharger.png",
		internalSlug: "Amulet_InertOvercharger_C",
		id: "k8d15f",
		dlc: "BASE",
		searchableTags: ["Fire Rate", "Reload Speed", "Recoil"],
		description: [
			`Standing completely still for 0.5s increases Fire Rate by 20%, Reload Speed by 15%, and reduces Recoil by 50%. Lasts 2s after moving.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Inert_Overcharger`,
		location: { world: `N'Erud`, dungeon: "World Drop" },
	},
	{
		category: "AMULET",
		name: "Insipid Talon",
		imageUrl: "items/amulets/insipidtalon.png",
		internalSlug: "Amulet_InsipidTalon_C",
		id: "65ygbg",
		dlc: "DLC2",
		searchableTags: ["All Damage"],
		description: [
			`On Perfect Dodge, increases All Damage dealt by 2% and Damage Reduction by 1% for 10s. Max 15 stacks.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Insipid_Talon`,
		location: { world: "Losomn", dungeon: ["Chamber of the Faithless"] },
	},
	{
		category: "AMULET",
		name: "Insulation Driver",
		imageUrl: "items/amulets/insulationdriver.png",
		internalSlug: "Amulet_InsulationDriver_C",
		id: "k1oijc",
		dlc: "BASE",
		searchableTags: ["All Damage"],
		description: [
			`While BULWARK is active, gain 15% to all damage dealt and HASTE.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Insulation_Driver`,
		location: {
			world: `N'Erud`,
			biome: `N'Erud Underworld`,
			injectable: `Sewage Facility`,
		},
	},
	{
		category: "AMULET",
		name: "Jester's Bell",
		imageUrl: "items/amulets/jestersbell.png",
		internalSlug: "Amulet_JestersBell_C",
		id: "lpv0qq",
		dlc: "BASE",
		searchableTags: ["All Damage"],
		description: [
			`Casting a Mod or Skill increases All Damage by 15% for 20s. Increases Cast Speed by 35%.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Jester's_Bell`,
		location: { world: "Losomn", dungeon: ["Beatific Palace"] },
	},
	{
		category: "AMULET",
		name: "Kinetic Shield Exchanger",
		imageUrl: "items/amulets/kineticshieldexchanger.png",
		internalSlug: "Amulet_KineticShieldExchanger_C",
		id: "femylz",
		dlc: "BASE",
		searchableTags: ["Mod Damage", "Mod Power"],
		description: [
			`While a SHIELD is active, gain 25% Mod damage and generate 30% additional Mod power.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Kinetic_Shield_Exchanger`,
		location: { world: `N'Erud`, dungeon: "World Drop" },
	},
	{
		category: "AMULET",
		name: "Kuri Kuri Charm",
		imageUrl: "items/amulets/kurikuricharm.png",
		internalSlug: "Amulet_KuriKuriCharm_C",
		id: "04yl4w",
		dlc: "BASE",
		searchableTags: ["Relic Use Speed"],
		description: [
			`For every 10% of Health missing (Max 50%), gain 10% increased Relic Use Speed and 7% chance to not consume a Relic Charge.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Kuri_Kuri_Charm`,
		location: {
			world: "Yaesha",
			biome: "Jungles of Yaesha",
			injectable: "Koara Kuri Nest",
		},
	},
	{
		category: "AMULET",
		name: "Laemir Censer",
		imageUrl: "items/amulets/laemircenser.png",
		internalSlug: "Amulet_LaemirCenser_C",
		id: "hwpkls",
		dlc: "BASE",
		searchableTags: ["Mod Cost", "Mod Duration"],
		description: [`Increases Mod Duration by 50%. Increases Mod Cost by 10%.`],
		wikiUrl: `https://remnant2.wiki.gg/Laemir_Censer`,
		location: { world: "Yaesha", dungeon: ["Forgotten Field"] },
	},
	{
		category: "AMULET",
		name: "Legacy Protocol",
		imageUrl: "items/amulets/legacyprotocol.png",
		internalSlug: "Amulet_LegacyProtocol_C",
		id: "a7axvo",
		dlc: "BASE",
		searchableTags: ["Reduce Skill Cooldown", "Skill Duration"],
		description: [
			`Reduces Skill Cooldowns by 20% and increases Skill Duration by 15%.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Legacy_Protocol`,
		location: { world: `N'Erud`, dungeon: "World Drop" },
	},
	{
		category: "AMULET",
		name: "Leto's Amulet",
		imageUrl: "items/amulets/letosamulet.png",
		internalSlug: "Amulet_LetosAmulet_C",
		id: "rpxs8n",
		dlc: "BASE",
		searchableTags: ["Encumbrance", "Stamina"],
		description: [`Reduces Encumbrance by 40% and Stamina Cost by 35%.`],
		wikiUrl: `https://remnant2.wiki.gg/Leto's_Amulet`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		modifiers: {
			weightPercentage: -0.4,
		},
	},
	{
		category: "AMULET",
		name: "Magnifying Glass",
		imageUrl: "items/amulets/magnifyingglass.png",
		internalSlug: "Amulet_MagnifyingGlass_C",
		id: "zo9Dkk",
		dlc: "BASE",
		searchableTags: ["Skill Duration", "Mod Duration"],
		description: [
			`Increases Skill and Mod Duration by 30% and their AOE or Aura Sizes by 20%.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Magnifying_Glass`,
		location: { world: "Losomn", dungeon: "World Drop" },
	},
	{
		category: "AMULET",
		name: "Matriarch's Insignia",
		imageUrl: "items/amulets/matriarchinsignia.png",
		internalSlug: "Amulet_MatriarchsInsignia_C",
		id: "jlch5h",
		dlc: "BASE",
		searchableTags: ["Melee Damage", "Stamina"],
		description: [
			`Increases Melee Damage by 35% and causes all successful Melee Attacks to restore 10 Stamina.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Matriarch's_Insignia`,
		location: { world: "Yaesha", dungeon: [`The Widow's Court`] },
	},
	{
		category: "AMULET",
		name: "Moon Stone",
		imageUrl: "items/amulets/moonstone.png",
		internalSlug: "Amulet_MoonStone_C",
		id: "zo9Dkd",
		dlc: "DLC2",
		searchableTags: ["Reload Speed", "Ranged Damage"],
		description: [
			`Increases Reload Speed by 15%. Every third manual Reload will reload both Firearms and increases Ranged Damage by 15% for 10s.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Moon_Stone`,
		location: {
			world: "Yaesha",
			biome: "Ziggurats",
			injectable: `Moon's Path`,
		},
	},
	{
		category: "AMULET",
		name: "Navigator's Pendant",
		imageUrl: "items/amulets/navigatorpendant.png",
		internalSlug: "Amulet_NavigatorsPendant_C",
		id: "pd4ez1",
		dlc: "BASE",
		searchableTags: ["Stamina", "Encumbrance", "Health"],
		description: [`Grants 25 Health, 25 Stamina, and -10 Armor Encumbrance.`],
		wikiUrl: `https://remnant2.wiki.gg/Navigator's_Pendant`,
		communityTags: [`Navigator's Set`],
		location: { world: `N'Erud`, dungeon: ["Forgotten Prison"] },
		modifiers: {
			health: 25,
			stamina: 25,
			weightPercentage: -0.1,
		},
	},
	{
		category: "AMULET",
		name: "Neckbone Necklace",
		imageUrl: "items/amulets/neckbonenecklace.png",
		internalSlug: "Amulet_NeckboneNecklace_C",
		id: "r11n5x",
		dlc: "BASE",
		searchableTags: ["Status Effect", "All Damage"],
		description: [
			`Reduces the Damage of STATUS Effects applied to wearer by 50%. Gain 25% increased Damage when suffering from a STATUS or BLIGHT Effect.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Neckbone_Necklace`,
		location: { world: "Losomn", dungeon: ["The Great Hall"] },
	},
	{
		category: "AMULET",
		name: "Necklace of Flowing Life",
		imageUrl: "items/amulets/necklaceofflowinglife.png",
		internalSlug: "Amulet_NecklaceOfFlowingLife_C",
		id: "8q9cj1",
		dlc: "BASE",
		searchableTags: ["Grey Health", "Mod Power"],
		description: [
			`Increases Grey Health conversion by an additional 100%. When Grey Health Conversion triggers, gain 5x the amount as Mod Power.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Necklace_of_Flowing_Life`,
		communityTags: [`Misty Step`],
		location: {
			world: "Yaesha",
			biome: "Undead Tombs",
			injectable: "Hidden Crypt",
		},
	},
	{
		category: "AMULET",
		name: "Necklace of Supremacy",
		imageUrl: "items/amulets/necklaceofsupremacy.png",
		internalSlug: "Amulet_NecklaceOfSupremacy_C",
		id: "dm67y5",
		dlc: "BASE",
		searchableTags: ["All Damage"],
		description: [
			`After 5s of not being damaged, increases all damage dealt by 15%. If Health is full, damage bonus increases to 30%.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Necklace_of_Supremacy`,
		location: { world: "Yaesha", dungeon: ["Forgotten Field"] },
	},
	{
		category: "AMULET",
		name: "Nightmare Spiral",
		imageUrl: "items/amulets/nightmarespiral.png",
		internalSlug: "Amulet_NightmareSpiral_C",
		id: "mewmtq",
		dlc: "BASE",
		searchableTags: ["Lifesteal", "Heal", "Healing Effectiveness"],
		description: [
			`Gain 10% of base Ranged damage dealt as Lifesteal. Reduces Healing Effectiveness by 95%.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Nightmare_Spiral`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "AMULET",
		name: "Nightweaver's Grudge",
		imageUrl: "items/amulets/nightweavergrudge.png",
		internalSlug: "Amulet_NightweaversGrudge_C",
		id: "0aaso1",
		dlc: "BASE",
		searchableTags: ["Critical Chance", "Status Effect"],
		description: [
			`Gain 15% Critical Chance and HASTE when within 20m of an entity suffering from a Status Effect.`,
		],
		communityTags: [`AOE/Aura`],
		wikiUrl: `https://remnant2.wiki.gg/Nightweaver's_Grudge`,
		location: { world: "Losomn", dungeon: ["Tormented Asylum"] },
	},
	{
		category: "AMULET",
		name: "Nimue's Ribbon",
		imageUrl: "items/amulets/nimuesribbon.png",
		internalSlug: "Amulet_NimuesRibbon_C",
		id: "sqsdvj",
		dlc: "BASE",
		searchableTags: ["Healing Effectiveness"],
		description: [
			`Increase Relic Healing Effectiveness by 50% Activating a Relic grants HASTE for 25s.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Nimue's_Ribbon`,
		location: { world: "Losomn", dungeon: [`Nimue's Retreat`] },
	},
	{
		category: "AMULET",
		name: "One-Eyed Joker Idol",
		imageUrl: "items/amulets/oneeyedjokeridol.png",
		internalSlug: "Amulet_OneEyedJokerIdol_C",
		id: "yl1ah9",
		dlc: "BASE",
		searchableTags: ["Neutral Backdash", "Critical Chance"],
		description: [
			`Neutral Backdash creates a Magic Card lasting 1s. If Card absorbs enemy damage, gain 25% Critical Chance for 5s. Neutral Backdash costs 15% additional Stamina.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/One-Eyed_Joker_Idol`,
		location: { world: "Losomn", dungeon: ["Malefic Palace"] },
	},
	{
		category: "AMULET",
		name: "One True King Sigil",
		imageUrl: "items/amulets/onetruekingsigil.png",
		internalSlug: "Amulet_OneTrueKingSigil_C",
		id: "j5ew1m",
		dlc: "BASE",
		searchableTags: ["Mod Damage"],
		description: [
			`Increases Mod damage by 20%. Enhances the effect of Faerin's Sigil and Faelin's Sigil by 50% per Sigil equipped.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/One_True_King_Sigil`,
		location: { world: "Losomn", dungeon: [`Nimue's Retreat`] },
	},
	{
		category: "AMULET",
		name: "Onyx Pendulum",
		imageUrl: "items/amulets/onyxpendulam.png",
		internalSlug: "Amulet_OnyxPendulum_C",
		id: "ps6umu",
		dlc: "BASE",
		searchableTags: ["Ranged Damage"],
		description: [
			`Dealing 100 Base Firearm damage adds stacks which multiplies the damage of stowed firearm by 1.02x for 15s. Stacks 10x.`,
		],
		communityTags: [`Multiplicative`],
		wikiUrl: `https://remnant2.wiki.gg/Onyx_Pendulum`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "AMULET",
		name: "Ornate Amulet",
		imageUrl: `items/amulets/ornateamulet.png`,
		internalSlug: "Amulet_OrnateAmulet_C",
		id: "xz3z4k",
		dlc: "DLC3",
		searchableTags: [],
		description: [
			`Activating a Skill increases All Damage by 5% for 10s. Max 5 stacks.`,
		],
		wikiUrl: "https://remnant2.wiki.gg/Ornate_Amulet",
		location: { world: "Ward 13", dungeon: "Quest" },
	},
	{
		category: "AMULET",
		name: "Participation Medal",
		imageUrl: "items/amulets/participationmedal.png",
		internalSlug: "Amulet_ParticipationMedal_C",
		id: "588hoi",
		dlc: "BASE",
		searchableTags: ["Health", "Stamina", "Movement Speed", "Damage Reduction"],
		description: [
			`Increase Health by 10, Stamina by 10, Movement Speed by 10%, and Damage Reduction by 10%.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Participation_Medal`,
		location: { world: "Any", dungeon: "Quest" },
		modifiers: {
			health: 10,
			stamina: 10,
		},
	},
	{
		category: "AMULET",
		name: "Profane Soul Stone",
		imageUrl: "items/amulets/profanesoulstone.png",
		internalSlug: "Amulet_ProfaneSoulStone_C",
		id: "YsS9NW",
		dlc: "DLC2",
		searchableTags: ["Summon", "Damage Reduction", "Movement Speed"],
		description: [
			`Increases Summon Damage by 30% and Summon Movement Speed by 15%. Reduces total Damage Reduction by 10% per active Summon.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Profane_Soul_Stone`,
		location: { world: "Yaesha", dungeon: ["Infested Abyss"] },
	},
	{
		category: "AMULET",
		name: "Quantum Memory",
		imageUrl: "items/amulets/quantummemory.png",
		internalSlug: "Amulet_QuantumMemory_C",
		id: "542njq",
		dlc: "DLC3",
		searchableTags: ["Reload Speed", "Perfect Dodge"],
		description: [
			`Combat Slide reloads currently equipped Firearm. Perfect Dodge Combat Slide reloads both firearms.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Quantum_Memory`,
		location: {
			world: `N'Erud`,
			biome: `Towers of N'Erud`,
			injectable: `Crop Lab`,
		},
	},
	{
		category: "AMULET",
		name: "Range Finder",
		imageUrl: "items/amulets/rangefinder.png",
		internalSlug: "Amulet_RangeFinder_C",
		id: "t7x0op",
		dlc: "BASE",
		searchableTags: ["Ranged Damage", "Weakspot Damage"],
		description: [
			`After killing an enemy, gain 10% Ranged damage and 2m Firearm Range. Stacks 3x Lasts 10s. Ranged Weakspot Hits will refresh duration.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Range_Finder`,
		location: {
			world: `N'Erud`,
			dungeon: "Vendor",
		},
	},
	{
		category: "AMULET",
		name: "Ravager's Mark",
		imageUrl: "items/amulets/ravagermark.png",
		internalSlug: "Amulet_RavagersMark_C",
		id: "gh0gk6",
		dlc: "BASE",
		searchableTags: ["All Damage"],
		description: [
			`Increases all damage dealt to BLEEDING targets by 20%. Bonus increases to 30% for targets with 50% or lower Health.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Ravager's_Mark`,
		communityTags: [`Misty Step`],
		location: { world: `Yaesha`, dungeon: [`Ravager's Lair`] },
	},
	{
		category: "AMULET",
		name: "Reaction Chain",
		imageUrl: "items/amulets/reactionchain.png",
		internalSlug: "Amulet_ReactionChain_C",
		id: "k1cwam",
		dlc: "BASE",
		searchableTags: [],
		description: [
			`Increases Mod Damage by 20%. Activating a Mod generates 50% of Mod Power Spent to the Stowed Weapon's Mod.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Reaction_Chain`,
		location: { world: `N'Erud`, dungeon: "World Drop" },
	},
	{
		category: "AMULET",
		name: "Red Doe Sigil",
		imageUrl: "items/amulets/reddoesigil.png",
		internalSlug: "Amulet_RedDoeSigil_C",
		id: "xxp0ri",
		dlc: "BASE",
		searchableTags: ["Healing Effectiveness"],
		description: [
			`Increases Relic Healing Effectiveness by 30% which doubles when the wearer's Health is below 50%.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Red_Doe_Sigil`,
		communityTags: [`Misty Step`],
		location: { world: "Yaesha", dungeon: ["The Red Throne"] },
	},
	{
		category: "AMULET",
		name: "Reed of the Vaunnt",
		imageUrl: "items/amulets/reedofthevaunnt.png",
		internalSlug: "Amulet_ReedOfTheVaunnt_C",
		id: "U2Vekv",
		dlc: "BASE",
		searchableTags: ["Mod Power"],
		description: [
			`Activating a Mod increases Mod Generation by 15% for 10s. Mod Charges have 20% chance not to be consumed on use.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Reed_of_the_Vaunnt`,
		location: { world: "Yaesha", dungeon: "World Drop" },
	},
	{
		category: "AMULET",
		name: "Relay Device",
		imageUrl: "items/amulets/relaydevice.png",
		internalSlug: "Amulet_RelayDevice_C",
		id: "fwtqy6",
		dlc: "DLC3",
		searchableTags: ["Ranged Damage"],
		description: [
			`Swapping Firearms increases Ranged Damage by 20% for 1.5s plus an additional 0.5s for each round in the Magazine. Max 15s.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Relay_Device`,
		location: { world: `N'Erud`, dungeon: ["Withered Necropolis"] },
	},
	{
		category: "AMULET",
		name: "Rusted Navigator's Pendant",
		imageUrl: "items/amulets/rustednavigatorpendant.png",
		internalSlug: "Amulet_RustedNavigatorsPendant_C",
		id: "iq6zyc",
		dlc: "BASE",
		searchableTags: ["Health", "Stamina", "Encumbrance"],
		description: ["Grants 20 Health, 20 Stamina and -15 Armor Encumbrance."],
		wikiUrl: `https://remnant2.wiki.gg/Rusted_Navigator's_Pendant`,
		communityTags: [`Navigator's Set`],
		location: { world: `N'Erud`, dungeon: [`Astropath's Respite`] },
		modifiers: {
			health: 20,
			stamina: 20,
			weight: -15,
		},
	},
	{
		category: "AMULET",
		name: "Samoflange",
		imageUrl: "items/amulets/samoflange.png",
		internalSlug: "Amulet_Samoflange_C",
		id: "z7ivk2",
		dlc: "BASE",
		searchableTags: ["Damage Reduction"],
		description: [
			`Direct Damage taken from enemies grants an additional 60% Damage Reduction for 5s. Once the defensive buff expires, all incoming damage to wearer is increased by 15% for 10s.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Samoflange`,
		location: { world: `N'Erud`, dungeon: [`Tower of the Unseen`] },
	},
	{
		category: "AMULET",
		name: "Scavenger's Bauble",
		imageUrl: "items/amulets/scavengerbauble.png",
		internalSlug: "Amulet_ScavengersBauble_C",
		id: "j2jso0",
		dlc: "BASE",
		description: [
			`Increases Scrap pickups by 50%. Automatically pick up any nearby crafting materials.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Scavenger's_Bauble`,
		location: { world: "Yaesha", dungeon: "World Drop" },
	},
	{
		category: "AMULET",
		name: "Shaed Bloom Crystal",
		internalSlug: `Amulet_ShadeBloomCrystal_C`,
		imageUrl: "items/amulets/shadebloomfloret.png",
		id: "ib2as6",
		dlc: "BASE",
		searchableTags: ["All Damage", "Elemental Damage"],
		description: [
			`Gain a 35% damage bonus. Every 5s, the bonus switches between Physical and Elemental damage.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Shaed_Bloom_Crystal`,
		location: { world: "Losomn", dungeon: [`Malefic Palace`] },
	},
	{
		category: "AMULET",
		name: "Shock Device",
		imageUrl: "items/amulets/shockdevice.png",
		internalSlug: "Amulet_ShockDevice_C",
		id: "9z1g8f",
		dlc: "BASE",
		description: [
			"Increases SHOCK damage by 25% and OVERLOADED damage by 50%.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Shock_Device`,
		location: { world: "Losomn", dungeon: ["Morrow Parish"] },
	},
	{
		category: "AMULET",
		name: "Short Circuit",
		imageUrl: "items/amulets/shortcircuit.png",
		internalSlug: "Amulet_ShortCircuit_C",
		id: "yuW4pJ",
		dlc: "DLC3",
		searchableTags: [
			"Critical Chance",
			"Critical Damage",
			"Reduce Skill Cooldown",
		],
		description: [
			`While a SHIELD is active, increases Critical Chance and Critical Damage by 10% and Skill Cooldowns are reduced by 6% once every 5s.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Short_Circuit`,
		location: {
			world: `N'Erud`,
			biome: `N'Erud Underworld`,
			injectable: "Power Hub",
		},
	},
	{
		category: "AMULET",
		name: "Silver Ribbon",
		imageUrl: "items/amulets/silverribbon.png",
		internalSlug: "Amulet_SilverRibbon_C",
		id: "k8j2r3",
		dlc: "BASE",
		searchableTags: ["Skill Damage"],
		description: [
			"Increases Skill damage by 25%. Activating a Skill grants HASTE for 15s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Silver_Ribbon`,
		location: {
			world: "Losomn",
			biome: "Fae Palace",
			injectable: "Silver and Gold",
		},
	},
	{
		category: "AMULET",
		name: "Sinister Totem",
		imageUrl: "items/amulets/sinistertotem.png",
		internalSlug: "Amulet_SinisterTotem_C",
		id: "qwguja",
		dlc: "BASE",
		searchableTags: ["Status Effect"],
		description: [
			`Applying or refreshing a Negative Status Effect to an enemy increases Status Damage by 1% for 15s. Max 50 stacks.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Sinister_Totem`,
		location: { world: "Yaesha", dungeon: "World Drop" },
	},
	{
		category: "AMULET",
		name: "Soul Anchor",
		imageUrl: "items/amulets/soulanchor.png",
		internalSlug: "Amulet_SoulAnchor_C",
		id: "6amich",
		dlc: "BASE",
		searchableTags: ["Summon", "All Damage"],
		description: [
			"Increase All Damage by 20% while at least 1 Summon is active.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Soul_Anchor`,
		location: { world: "Yaesha", dungeon: "Vendor" },
	},
	{
		category: "AMULET",
		name: "Soul Stone",
		imageUrl: "items/amulets/soulstone.png",
		internalSlug: "Amulet_SoulStone_C",
		id: "z7ivk3",
		dlc: "DLC2",
		searchableTags: ["Summon", "Movement Speed"],
		description: [
			`Increases Summon Damage by 30% and Summon Movement Speed by 30%.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Soul_Stone`,
		location: { world: "Labyrinth", dungeon: "Vendor" },
	},
	{
		category: "AMULET",
		name: "Spirit Wisp Amulet",
		imageUrl: "items/amulets/spiritwispamulet.png",
		internalSlug: "Amulet_SpiritWispAmulet_C",
		id: "n1y24e",
		dlc: "BASE",
		searchableTags: ["Reduce Skill Cooldown", "Mod Power"],
		description: [
			`Activating a Mod reduces current Skill Cooldowns by 3% for every 300 Mod Power spent.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Spirit_Wisp_Amulet`,
		location: { world: "Losomn", dungeon: [`Tiller's Rest`] },
	},
	{
		category: "AMULET",
		name: "Stalker's Brand",
		imageUrl: "items/amulets/stalkersbrand.png",
		internalSlug: "Amulet_StalkersBrand_C",
		id: "rcyafk",
		dlc: "BASE",
		searchableTags: ["Ranged Damage", "Melee Damage"],
		description: [
			`Gain 12.5% Ranged and 15% Melee damage. Bonus doubles versus enemies not targeting wearer.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Stalker's_Brand`,
		location: { world: "Yaesha", dungeon: "World Drop" },
	},
	{
		category: "AMULET",
		name: "Stoneshaper's Chisel",
		imageUrl: "items/amulets/stoneshaperchisel.png",
		internalSlug: "Amulet_StoneshapersChisel_C",
		id: "41ookg",
		dlc: "DLC2",
		searchableTags: ["All Damage"],
		description: [
			`After not using the primary fire of a weapon for 10s. All Damage is increased by 25%. Primary fire of a weapon instantly cancels the effect.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Stoneshaper's_Chisel`,
		location: { world: "Yaesha", dungeon: ["Ancient Canopy"] },
	},
	{
		category: "AMULET",
		name: "Talisman of the Sun",
		imageUrl: "items/amulets/talismanofthesun.png",
		internalSlug: "Amulet_TalismanOfTheSun_C",
		id: "8jy9hv",
		dlc: "BASE",
		description: ["Increases FIRE damage by 25% and BURNING damage by 50%."],
		wikiUrl: `https://remnant2.wiki.gg/Talisman_of_the_Sun`,
		communityTags: [`Misty Step`],
		location: {
			world: "Yaesha",
			biome: "Floating Forests",
			injectable: `Island Jump`,
		},
	},
	{
		category: "AMULET",
		name: `Timekeeper's Forfeit`,
		imageUrl: "items/amulets/timekeepersforfeit.png",
		internalSlug: "Amulet_TimekeepersForfeit_C",
		id: "t4ho4m",
		dlc: "DLC3",
		searchableTags: [],
		description: [
			`Increases Status Effect Damage by 50%. Applying a Status Effect to an enemy also applies it to the wearer.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Timekeeper's_Forfeit`,
		location: { world: "Ward 13", dungeon: "Quest" },
	},
	{
		category: "AMULET",
		name: "Toxic Release Valve",
		imageUrl: "items/amulets/toxicreleasevalve.png",
		internalSlug: "Amulet_ToxicReleaseValve_C",
		id: "nevpy5",
		dlc: "BASE",
		description: [
			`Swapping Firearms releases a Toxic Cloud, which deals 60.5-170.5 ACID Damage to all enemies within 7m and applies CORROSION dealing 280 ACID damage over 7s.`,
			`Can only happen once every 3s.`,
		],
		communityTags: [`AOE/Aura`],
		wikiUrl: `https://remnant2.wiki.gg/Toxic_Release_Valve`,
		location: { world: `N'Erud`, dungeon: [`Dormant N'Erudian Facility`] },
	},
	{
		category: "AMULET",
		name: "Twisted Idol",
		imageUrl: "items/amulets/twistedidol.png",
		internalSlug: "Amulet_TwistedIdol_C",
		id: "776kn2",
		dlc: "BASE",
		searchableTags: ["Encumbrance", "Damage Reduction"],
		description: [
			`Increases Armor Effectiveness by 35% and reduces Encumbrance by 20.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Twisted_Idol`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		modifiers: {
			armorPercentage: 0.35,
			weight: -20,
		},
	},
	{
		category: "AMULET",
		name: "Vengeance Idol",
		imageUrl: "items/amulets/vengeanceidol.png",
		internalSlug: "Amulet_VengeanceIdol_C",
		id: "1ucgis",
		dlc: "BASE",
		searchableTags: ["All Damage"],
		description: [
			`Increases all damage dealt by 30% when the wearer's Health is below 50%.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Vengeance_Idol`,
		location: { world: "Yaesha", dungeon: "World Drop" },
	},
	{
		category: "AMULET",
		name: "Void Idol",
		imageUrl: "items/amulets/voididol.png",
		internalSlug: "Amulet_VoidIdol_C",
		id: "rctnex",
		dlc: "BASE",
		searchableTags: ["Reload Speed"],
		description: [
			"Increases Reload Speed by 30%. Reloads only require 50% of magazine from reserves to fully reload.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Void_Idol`,
		location: {
			world: `N'Erud`,
			dungeon: "Vendor",
		},
	},
	{
		category: "AMULET",
		name: "Volatile Cartridge",
		imageUrl: "items/amulets/volatilecartridge.png",
		internalSlug: "Amulet_VolatileCartridge_C",
		id: "up6mi1",
		dlc: "DLC3",
		searchableTags: [],
		description: [
			`Increases Explosive Critical Chance and Explosive Critical Damage by 1% for every 5% of Max Health protected by a SHIELD.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Volatile_Cartridge`,
		location: { world: "Ward 13", dungeon: "Quest" },
	},
	{
		category: "AMULET",
		name: "Weightless Weight",
		imageUrl: "items/amulets/weightlessweight.png",
		internalSlug: "Amulet_WeightlessWeight_C",
		id: "b9l389",
		dlc: "BASE",
		searchableTags: ["Movement Speed", "Stamina", "Encumbrance"],
		description: [
			"Increases Movement Speed by 0.75% and reduces Stamina Cost of all actions by 0.75% for every 5 points of Armor Encumbrance.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Weightless_Weight`,
		location: { world: "Losomn", dungeon: "World Drop" },
	},
	{
		category: "AMULET",
		name: "Whispering Marble",
		imageUrl: "items/amulets/whisperingmarble.png",
		internalSlug: "Amulet_WhisperingMarble_C",
		id: "2e2hh5",
		dlc: "BASE",
		searchableTags: ["Damage Reduction", "All Damage"],
		description: [
			`Grants 3 stacks of BULWARK. Increases All Damage by 2% per stack of BULWARK.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Whispering_Marble`,
		location: { world: "Losomn", dungeon: "World Drop" },
	},
	{
		category: "AMULET",
		name: "Worn Dog Tags",
		imageUrl: "items/amulets/worndogtag.png",
		internalSlug: "Amulet_WornDogTags_C",
		id: "69dogy",
		dlc: "DLC2",
		searchableTags: ["Fire Rate", "Reload Speed", "Charged Shot"],
		description: [
			`Increases Fire Rate and Reload Speed by 15% and Decreases Weapon Charge Time by 15%.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Worn_Dog_Tags`,
		location: { world: "Yaesha", dungeon: ["Luminous Vale"] },
	},
	{
		category: "AMULET",
		name: "Zero Divide",
		imageUrl: "items/amulets/zerodivide.png",
		internalSlug: "Amulet_ZeroDivide_C",
		id: "ryS67y",
		dlc: "BASE",
		searchableTags: ["Ammo Reserves", "Ranged Damage"],
		description: [
			`Gain Infinite Reserve Ammo and increases Ranged Damage by 15%.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Zero_Divide`,
		location: { world: `N'Erud`, dungeon: "World Drop" },
	},
	{
		category: "AMULET",
		name: "Zero Hour",
		imageUrl: "items/amulets/zerohour.png",
		internalSlug: "Amulet_ZeroHour_C",
		id: "ozin1d",
		dlc: "BASE",
		searchableTags: [],
		description: [
			`Increases All Damage by 20% and Critical Chance by 10%. Each Weight Class above LIGHT reduces All Damage bonus by 5% and Critical Chance by 2.5%.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Zero_Hour`,
		location: { world: `N'Erud`, dungeon: "World Drop" },
	},
];

export { AMULETS, type Remnant2AmuletItem };
