import type { BaseRemnant2Item } from "#/games/remnant2/types/local-item";

type Remnant2ArmorItem = BaseRemnant2Item & {
	set?: string;
};

const ARMORS: Remnant2ArmorItem[] = [
	{
		category: "HELM",
		name: "Academic's Hat",
		internalSlug: "Armor_Head_Alchemist_C",
		imageUrl: "items/armors/academicshat.png",
		id: "9qo2gg",
		dlc: "BASE",
		set: "Academic's Set",
		modifiers: {
			armor: 12.7,
			weight: 5.2,
			resistBleed: 1,
			resistFire: 0,
			resistShock: 0,
			resistBlight: 2,
			resistToxin: 3,
		},
		description: [
			`A soft and durable felt hat fashioned to stylize, not necessarily protect, the most important part of your body.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Academic's_Hat`,
		location: {
			world: "Losomn",
			dungeon: [`The Great Sewers`, `Tiller's Rest`],
		},
	},
	{
		category: "HELM",
		name: "Bandit's Mask",
		internalSlug: "Armor_Head_Bandit_C",
		imageUrl: "items/armors/banditsmask.png",
		id: "v66pgu",
		dlc: "BASE",
		set: "Bandit Set",
		modifiers: {
			armor: 6.8,
			weight: 2.7,
			resistBleed: 2,
			resistFire: 0,
			resistShock: 0,
			resistBlight: 3,
			resistToxin: 3,
		},
		description: [
			`The helm of the bandit armor is a haunting symbol of the ruthless opportunism that arose after the cataclysmic destruction of Earth. Yet, for those who wear it, it also represents a means of survival in a world where mercy is a scarce commodity`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Bandit's_Mask`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "HELM",
		name: "Battle Helmet",
		internalSlug: "Armor_Head_Army_C",
		imageUrl: "items/armors/battlehelmet.png",
		id: "nathem",
		dlc: "DLC2",
		set: "Battle Set",
		modifiers: {
			armor: 13.1,
			weight: 5.3,
			resistBleed: 5,
			resistFire: 2,
			resistShock: 0,
			resistBlight: 0,
			resistToxin: 0,
		},
		description: [
			`This helmet looks heavier than it is, which isn't all that surprising, considering it isn't bulletproof. Still, it's useful for protecting against falling debris, and if the angle's just right, it may get lucky and deflect a stray bullet or two. I wouldn't count on it, though.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Battle_Helmet`,
		location: { world: "Yaesha", dungeon: [`Proving Grounds`] },
	},
	{
		category: "HELM",
		name: "Bloodless Crown",
		imageUrl: "items/armors/bloodlesscrown.png",
		internalSlug: "Armor_Head_BloodlessCrown_C",
		id: "o5fNZw",
		dlc: "DLC2",
		modifiers: {
			armor: 6.6,
			weight: 2.7,
			resistBleed: 15,
			resistFire: -3,
			resistShock: 3,
			resistToxin: -3,
			resistBlight: -3,
		},
		description: [
			`The weight of this crown is heavy, so much heavier than you might have guessed. Though aged, the shining metal has been carefully preserved, and the crown jewel radiates with a passionate fury you can scarcely comprehend.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Bloodless_Crown`,
		location: { world: "Yaesha", dungeon: [`Goddess's Rest`] },
	},
	{
		category: "HELM",
		name: "Bruiser Helmet",
		internalSlug: "Armor_Head_Challenger_C",
		imageUrl: "items/armors/bruiserhelmet.png",
		id: "bd4pam",
		dlc: "BASE",
		set: "Bruiser Set",
		modifiers: {
			armor: 17.6,
			weight: 8.1,
			resistBleed: 1,
			resistFire: 2,
			resistShock: 0,
			resistBlight: 0,
			resistToxin: 1,
		},
		description: [
			`The visibility in this helmet leaves much to be desired, but that's not really the point. It goes a long way in keeping your head on your shoulders.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Bruiser_Helmet`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "HELM",
		name: "Crimson Guard Shroud",
		internalSlug: "Armor_Head_CrimsonGuard_C",
		dlc: "DLC1",
		imageUrl: "items/armors/crimsonguardshroud.png",
		id: "ce8izt",
		set: "Crimson Guard Set",
		modifiers: {
			armor: 15.6,
			weight: 6.7,
			resistBleed: 2,
			resistFire: 2,
			resistShock: 0,
			resistBlight: 2,
			resistToxin: 0,
		},
		description: [
			`The hooded mask wreathes you in a vicious, fiery visage that evokes both fear and admiration. The incandescent eye slits color your vision with the hues of hellfire.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Crimson_Guard_Shroud`,
		location: { world: "Losomn", dungeon: "Quest" },
	},
	{
		category: "HELM",
		name: "Crown of the Red Prince",
		internalSlug: "Armor_Head_RedPrince_C",
		imageUrl: "items/armors/crownoftheredprince.png",
		id: "pu3duv",
		dlc: "BASE",
		modifiers: {
			armor: 6,
			weight: 6,
			resistBleed: -6,
			resistFire: 25,
			resistShock: -6,
			resistBlight: 13,
			resistToxin: -6,
		},
		description: [
			`A flashy, flame-hot diadem that demands respect and attention in equal measure...were there any subjects left to offer such sentiments. `,
		],
		wikiUrl: `https://remnant2.wiki.gg/Crown_of_the_Red_Prince`,
		location: { world: "Losomn", dungeon: ["Gilded Chambers"] },
	},
	{
		category: "HELM",
		name: "Cultist Hat",
		internalSlug: "Armor_Head_Cultist_C",
		imageUrl: "items/armors/cultisthat.png",
		id: "x9jrx1",
		dlc: "BASE",
		set: "Cultist Set",
		modifiers: {
			armor: 11.1,
			weight: 4.6,
			resistBleed: 1,
			resistFire: 1,
			resistShock: 1,
			resistBlight: 1,
			resistToxin: 1,
		},
		description: [
			`A simple and unassuming headpiece that belies its storied past. Once worn by members of a secretive and enigmatic cult. It now serves as a symbol of redemption for those who have turned their backs on the group's teachings.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Cultist_Hat`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "HELM",
		name: "Dandy Topper",
		imageUrl: "items/armors/dandytopper.png",
		internalSlug: "Armor_Head_TopHat_C",
		id: "vZL5tu",
		dlc: "BASE",
		modifiers: {
			armor: 12.8,
			weight: 5.3,
			resistBleed: 0,
			resistFire: 0,
			resistShock: 0,
			resistBlight: 5,
			resistToxin: 0,
		},
		description: [
			"Lovingly crafted by a skilled hatter who clearly takes great pride in their work. After being exposed to endless days of rain, the shell began to separate from the crown, so a woven cord was tied around the center to hold it in place—for now.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Dandy_Topper`,
		location: { world: "Losomn", dungeon: ["Forlorn Coast"] },
	},
	{
		category: "HELM",
		name: "Dendroid Mask",
		internalSlug: "Armor_Head_Invader_C",
		imageUrl: "items/armors/dendroidmask.png",
		id: "y7fa8n",
		dlc: "BASE",
		set: "Dendroid Set",
		modifiers: {
			armor: 7.7,
			weight: 3.1,
			resistBleed: 2,
			resistFire: 0,
			resistShock: 0,
			resistBlight: 0,
			resistToxin: 2,
		},
		description: [
			`It's like putting your head inside the monsters you've been killing all this time. It's comfortable enough though, so long as you don't think about where it's been. `,
		],
		wikiUrl: `https://remnant2.wiki.gg/Dendroid_Mask`,
		location: { world: "Root Earth", dungeon: ["Ashen Wasteland"] },
	},
	{
		category: "HELM",
		name: "Disciple Headpiece",
		internalSlug: "Armor_Head_Invoker_C",
		imageUrl: "items/armors/discipleheadpiece.png",
		id: "y7fa8d",
		dlc: "DLC2",
		set: "Disciple Set",
		modifiers: {
			armor: 16,
			weight: 7.2,
			resistBleed: 0,
			resistFire: 2,
			resistShock: 2,
			resistBlight: 0,
			resistToxin: 1,
		},
		description: [
			`The unwavering visage of Lydusa carves the shape of this mask. Though her sisters wandered far and wide, Lydusa seldom traveled at all, for stone by its nature is unmoving and lonely.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Disciple_Headpiece`,
		location: { world: "Yaesha", dungeon: ["Ancient Canopy"] },
	},
	{
		category: "HELM",
		name: "Elder Headdress",
		internalSlug: "Armor_Head_Elder_C",
		imageUrl: "items/armors/elderheaddress.png",
		id: "fek1ml",
		dlc: "BASE",
		set: "Elder Set",
		modifiers: {
			armor: 7.5,
			weight: 3,
			resistBleed: 0,
			resistFire: 3,
			resistShock: 0,
			resistBlight: 2,
			resistToxin: 0,
		},
		description: [
			`This headpiece hails from the wild and mysterious world of Yaesha. Its smooth,
      featureless. design is both eerie and elegant, painted a stark white and adorned
      with luxuriant fur and imposing horns.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Elder_Headdress`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "HELM",
		name: "Fae Royal Headcover",
		internalSlug: "Armor_Head_FaeRoyalGuard_C",
		imageUrl: "items/armors/faeroyalheadcover.png",
		id: "88kdl6",
		dlc: "BASE",
		set: "Fae Royal Set",
		modifiers: {
			armor: 15.4,
			weight: 6.6,
			resistBleed: 2,
			resistFire: 2,
			resistShock: 0,
			resistBlight: 2,
			resistToxin: 0,
		},
		description: [
			`It feels like you're not wearing any helmet at all - you'd swear you could even feel the wind in your hair. Yet it turns an arrow as effectively as any steel. `,
		],
		wikiUrl: `https://remnant2.wiki.gg/Fae_Royal_Headcover`,
		location: { world: "Losomn", dungeon: [`Postulant's Parlor`] },
	},
	{
		category: "HELM",
		name: "Field Medic Hat",
		internalSlug: "Armor_Head_FieldCap_C",
		imageUrl: "items/armors/fieldmedichat.png",
		id: "48nh1x",
		dlc: "BASE",
		modifiers: {
			armor: 10.6,
			weight: 4.4,
			resistBleed: 0,
			resistFire: 0,
			resistShock: 0,
			resistBlight: 2,
			resistToxin: 1,
		},
		description: [
			`While it may shield your eyes from the sun, it's not particularly protective against the dangers of the Root. `,
		],
		wikiUrl: `https://remnant2.wiki.gg/Field_Medic_Hat`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "HELM",
		name: "Field Medic Mask",
		internalSlug: "Armor_Head_Medic_C",
		imageUrl: "items/armors/fieldmedicmask.png",
		id: "e1waki",
		dlc: "BASE",
		set: "Field Medic Set",
		modifiers: {
			armor: 10.6,
			weight: 4.4,
			resistBleed: 0,
			resistFire: 0,
			resistShock: 0,
			resistBlight: 2,
			resistToxin: 1,
		},
		description: [
			`This face covering protects you from contagions without obstructing your sight. You feel like a creature from another world in this thing. Perhaps that's fitting. `,
		],
		wikiUrl: `https://remnant2.wiki.gg/Field_Medic_Mask`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "HELM",
		name: "High Noon Hat",
		internalSlug: "Armor_Head_Gunslinger_C",
		imageUrl: "items/armors/highnoonhat.png",
		id: "94xkn1",
		dlc: "BASE",
		set: "High Noon Set",
		modifiers: {
			armor: 11.7,
			weight: 4.9,
			resistBleed: 0,
			resistFire: 1,
			resistShock: 1,
			resistBlight: 0,
			resistToxin: 1,
		},
		description: [
			`Something about this hat just feels right. Paired with a bandana, it keeps the sun and elements from hindering your all-important aim. `,
		],
		wikiUrl: `https://remnant2.wiki.gg/High_Noon_Hat`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "HELM",
		name: "Knotted Helm",
		internalSlug: "Armor_Head_summoner_C",
		imageUrl: "items/armors/knottedhelm.png",
		id: "oab1w0",
		dlc: "BASE",
		set: "Knotted Set",
		modifiers: {
			armor: 15.5,
			weight: 6.9,
			resistBleed: 0,
			resistFire: 0,
			resistShock: 0,
			resistBlight: 1,
			resistToxin: 2,
		},
		description: [
			`A hauntingly familiar visage, convincing enough to still be alive. To truly know your enemy, you must get inside its head. Literally. `,
		],
		wikiUrl: `https://remnant2.wiki.gg/Knotted_Helm`,
		location: { world: "Yaesha", dungeon: "Vendor" },
	},
	{
		category: "HELM",
		name: "Labyrinth Headplate",
		internalSlug: "Armor_Head_Archon_C",
		imageUrl: "items/armors/labyrinthheadplate.png",
		id: "im7fm2",
		dlc: "BASE",
		set: "Labyrinth Set",
		modifiers: {
			armor: 12.9,
			weight: 5.4,
			resistBleed: 0,
			resistFire: 2,
			resistShock: 3,
			resistBlight: 0,
			resistToxin: 0,
		},
		description: [
			`This helmet is reminiscent of a statue from a time long, long before. `,
		],
		wikiUrl: `https://remnant2.wiki.gg/Labyrinth_Headplate`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "HELM",
		name: "Leto Mark 1 Helmet",
		internalSlug: "Armor_Head_Leto1_C",
		imageUrl: "items/armors/letomark1helmet.png",
		id: "kc4dc0",
		dlc: "BASE",
		set: "Leto Mark 1 Set",
		modifiers: {
			armor: 22.6,
			weight: 11.9,
			resistBleed: 3,
			resistFire: 4,
			resistShock: 2,
			resistBlight: 2,
			resistToxin: 4,
		},
		description: [
			`Reinforced and designed to completely enclose the head, providing maximum protection against the dangers of the Root`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Leto_Mark_1_Helmet`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "HELM",
		name: "Leto Mark II Helmet",
		internalSlug: "Armor_Head_Leto2_C",
		imageUrl: "items/armors/letomark2helmet.png",
		id: "sdsybp",
		dlc: "BASE",
		set: "Leto Mark II Set",
		modifiers: {
			armor: 21.8,
			weight: 11.1,
			resistBleed: 2,
			resistFire: 3,
			resistShock: 1,
			resistBlight: 1,
			resistToxin: 2,
		},
		description: [
			`While this ironclad helmet is somewhat difficult to breathe in, you feel secure knowing even the heaviest weapon would have little chance of cracking into your skull. `,
		],
		wikiUrl: `https://remnant2.wiki.gg/Leto_Mark_II_Helmet`,
		location: { world: "Ward 13", dungeon: "World Drop" },
	},
	{
		category: "HELM",
		name: "Lodestone Crown",
		imageUrl: "items/armors/lodestonecrown.png",
		id: "pjt7nj",
		internalSlug: "Armor_Head_LodestoneCrown_C",
		dlc: "BASE",
		modifiers: {
			armor: 6.5,
			weight: 2.6,
			resistBleed: 2,
			resistFire: 0,
			resistShock: -1,
			resistBlight: 5,
			resistToxin: 0,
		},
		description: [
			`This crown was worn by King Kolket himself. It could be heresy for a paxultek to wear such an artifact, but there are few left among the Pan who would even recognize it as their own.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Lodestone_Crown`,
		communityTags: [`Lodestone Set`],
		location: { world: "Yaesha", dungeon: ["The Lament"] },
	},
	{
		category: "HELM",
		name: `Mudtooth's Hat`,
		imageUrl: "items/armors/mudtoothshat.png",
		internalSlug: "Armor_Head_MudtoothsHat_C",
		id: "u7PqrJ",
		dlc: "DLC2",
		modifiers: {
			armor: 10.6,
			weight: 4.4,
			resistBleed: 1,
			resistFire: 1,
			resistShock: 1,
			resistBlight: 2,
			resistToxin: 1,
		},
		wikiUrl: `https://remnant2.wiki.gg/Mudtooth's_Hat`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		description: [
			`A hat that once belonged to some kind of man in black. Or did it? Mudtooth went through some kind of crazy experience to get this thing, though the details are a little muddled. Either that, or he found it in a dumpster. You're going to choose to believe it's the former.`,
		],
	},
	{
		category: "HELM",
		name: "Nanoplated Transmitter",
		internalSlug: "Armor_Head_Warden_C",
		imageUrl: "items/armors/nanoplatedtransmitter.png",
		id: "2x3sxo",
		dlc: "DLC3",
		set: "Nanoplated Set",
		modifiers: {
			armor: 12.4,
			weight: 5,
			resistBleed: 2,
			resistFire: 1,
			resistShock: 0,
			resistToxin: 0,
			resistBlight: 2,
		},
		wikiUrl: `https://remnant2.wiki.gg/Nanoplated_Transmitter`,
		location: { world: `N'Erud`, dungeon: [`Withered Necropolis`] },
		description: [
			`The wide, dish-shaped helmet functions as a long-range radar to translate the wearer's thoughts into commands for their drone.`,
			`“Cae'Loa Iturius was nominated to the Convocation on account of her innovative genius. However, she preferred the company of machines and artificial intelligence and rarely appeared in the public eye. Of the five Seekers, she was the least resistant to accepting my analysis of Alepsis-Taura.”`,
		],
	},
	{
		category: "HELM",
		name: "Navigator's Helm",
		internalSlug: "Armor_Head_PilotsHelm_C",
		imageUrl: "items/armors/navigatorshelm.png",
		id: "ovnzhv",
		dlc: "BASE",
		modifiers: {
			armor: 16,
			weight: 7.6,
			resistBleed: -1,
			resistFire: -1,
			resistShock: 2,
			resistBlight: -1,
			resistToxin: 3,
		},
		description: [
			`It's hard to imagine someone piloting an entire world, but that's who this helm was for. The sockets allowed them to speak with N'Erud directly. N'Erud had dozens of pilots, all working in concert-both with each other and with the world itself. `,
		],
		wikiUrl: `https://remnant2.wiki.gg/Navigator's_Helm`,
		communityTags: [`Navigator's Set`],
		location: {
			world: `N'Erud`,
			biome: `N'Erud Wasteland`,
			injectable: `Extraction Hub`,
		},
	},
	{
		category: "HELM",
		name: "Nightstalker Shroud",
		internalSlug: "Armor_Head_Hunter_C",
		imageUrl: "items/armors/nightstalkershroud.png",
		id: "zy1ce3",
		dlc: "BASE",
		set: "Nightstalker Set",
		modifiers: {
			armor: 10.9,
			weight: 4.5,
			resistBleed: 0,
			resistFire: 1,
			resistShock: 1,
			resistBlight: 3,
			resistToxin: 0,
		},
		description: [
			`A hunting mask with advanced respirator capabilities. It purifies yet does nothing to mask the stench of death that permeates the air. `,
		],
		wikiUrl: `https://remnant2.wiki.gg/Nightstalker_Shroud`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "HELM",
		name: "Phetyr Sensor",
		internalSlug: "Armor_Head_NerudWarrior_C",
		imageUrl: "items/armors/phetyrsensor.png",
		id: "3emu93",
		dlc: "DLC3",
		set: "Phetyr Set",
		modifiers: {
			armor: 19.8,
			weight: 9.8,
			resistBleed: 3,
			resistFire: 3,
			resistShock: 3,
			resistToxin: 4,
			resistBlight: 5,
		},
		description: [""],
		wikiUrl: `https://remnant2.wiki.gg/Phetyr_Sensor`,
		location: { world: `N'Erud`, dungeon: [`Logistics Bridge`] },
	},
	{
		category: "HELM",
		name: "Radiant Visage",
		internalSlug: "Armor_Head_Radiant_C",
		imageUrl: "items/armors/radiantvisage.png",
		id: "hv4oqq",
		dlc: "BASE",
		set: "Radiant Set",
		modifiers: {
			armor: 17.2,
			weight: 7.9,
			resistBleed: 1,
			resistFire: 1,
			resistShock: 3,
			resistBlight: 1,
			resistToxin: 0,
		},
		description: [
			`The cowl is a striking blue, which contrasts with the large, featureless golden mask that covers the face of the wearer. This armor was highly coveted and only granted to those few who were recognized as the "Radiant Ones." `,
		],
		wikiUrl: `https://remnant2.wiki.gg/Radiant_Visage`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "HELM",
		name: "Realmwalker Beret",
		internalSlug: "Armor_Head_Explorer_C",
		imageUrl: "items/armors/realmwalkerberet.png",
		id: "abhqna",
		dlc: "BASE",
		set: "Realmwalker Set",
		modifiers: {
			armor: 7.2,
			weight: 2.9,
			resistBleed: 0,
			resistFire: 0,
			resistShock: 1,
			resistBlight: 1,
			resistToxin: 0,
		},
		description: [
			`This hat once belonged to Founder Ford. He was only a captain then-a much younger Ford, from a long time and many lives ago. `,
		],
		wikiUrl: `https://remnant2.wiki.gg/Realmwalker_Beret`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "HELM",
		name: "Red Widow Headdress",
		internalSlug: "Armor_Head_RedWidow_C",
		imageUrl: "items/armors/redwidowheaddress.png",
		id: "k6zlwn",
		dlc: "BASE",
		set: "Red Widow Set",
		modifiers: {
			armor: 13.2,
			weight: 5.6,
			resistBleed: 2,
			resistFire: 0,
			resistShock: 0,
			resistBlight: 2,
			resistToxin: 0,
		},
		description: [
			`The horns of this helmet are ornamental, designed to be displayed in addition to the Pan wearer's own horns-which themselves protrude from additional openings in the armor-to create a truly frightening visage. `,
		],
		wikiUrl: `https://remnant2.wiki.gg/Red_Widow_Headdress`,
		location: { world: "Yaesha", dungeon: ["The Lament"] },
	},
	{
		category: "HELM",
		name: "Space Worker Mask",
		internalSlug: "Armor_Head_SpaceWorker_C",
		imageUrl: "items/armors/spaceworkermask.png",
		id: "n3vlkq",
		dlc: "BASE",
		set: "Space Worker Set",
		modifiers: {
			armor: 7,
			weight: 2.8,
			resistBleed: 1,
			resistFire: 0,
			resistShock: 2,
			resistBlight: 0,
			resistToxin: 2,
		},
		description: [
			`People (Mudtooth mostly) tell stories of how, before the Root, humans could fly into space. It's probably not true, but if it were, they'd need something like this to keep them alive out there. `,
		],
		wikiUrl: `https://remnant2.wiki.gg/Space_Worker_Mask`,
		location: { world: `N'Erud`, dungeon: [`Void Vessel Facility`] },
	},
	{
		category: "HELM",
		name: "Technician Helmet",
		internalSlug: "Armor_Head_Engineer_C",
		imageUrl: "items/armors/technicianhelmet.png",
		id: "gsctum",
		dlc: "BASE",
		set: "Technician Set",
		modifiers: {
			armor: 16.6,
			weight: 7.5,
			resistBleed: 0,
			resistFire: 1,
			resistShock: 2,
			resistBlight: 0,
			resistToxin: 2,
		},
		description: [
			`An overwhelming amount of information shines within the helmet's display, the vast majority of it incomprehensible. Whether that's because it's a foreign language or the helmet has been damaged by whatever destroyed this place is anybody's guess. `,
		],
		wikiUrl: `https://remnant2.wiki.gg/Technician_Helmet`,
		location: {
			world: `N'Erud`,
			dungeon: [`The Eon Vault`, `Timeless Horizon`],
		},
	},
	{
		category: "HELM",
		name: "Trainer Cap",
		internalSlug: "Armor_Head_Handler_C",
		imageUrl: "items/armors/trainercap.png",
		id: "m8wgy9",
		dlc: "BASE",
		set: "Trainer Set",
		modifiers: {
			armor: 10,
			weight: 4.1,
			resistBleed: 0,
			resistFire: 0,
			resistShock: 0,
			resistBlight: 0,
			resistToxin: 1,
		},
		description: [
			`For some reason, your head feels naked without this simple baseball cap with a fox logo. That aside, it keeps the sun out of your eyes, and that's all you ask of it.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Trainer_Cap`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "HELM",
		name: "True Crimson Crown",
		internalSlug: "Armor_Head_TrueCrimsonCrown_C",
		imageUrl: "items/armors/truecrimsoncrown.png",
		id: "gsctud",
		dlc: "BASE",
		set: "True Crimson Set",
		modifiers: {
			armor: 16.6,
			weight: 10,
			resistBleed: -6,
			resistFire: 35,
			resistShock: -6,
			resistBlight: -6,
			resistToxin: -6,
		},
		description: [
			`Unified at long last, this enigmatic mask and flaming diadem signify that its wearer is not only forever loyal to the Red King but stands as his most favoured equal.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/True_Crimson_Crown`,
		location: { world: "Losomn", dungeon: [`Nimue's Retreat`] },
	},
	{
		category: "HELM",
		name: "Void Skull",
		internalSlug: "Armor_Head_Void_C",
		imageUrl: "items/armors/voidskull.png",
		id: "s7tvfn",
		dlc: "BASE",
		set: "Void Set",
		modifiers: {
			armor: 15.9,
			weight: 7.1,
			resistBleed: 0,
			resistFire: 1,
			resistShock: 2,
			resistBlight: 0,
			resistToxin: 1,
		},
		description: [
			`The skull-like helm hails from the inhospitable world of Rhom, where survival demands more than just strength and cunning. Fashioned from a mysterious material, its surface glimmers with an otherworldly sheen that seems to shift and change with the light. Its sleek and angular lines, reminiscent of some alien technology, evoke a sense of unease in those who gaze upon it. `,
		],
		wikiUrl: `https://remnant2.wiki.gg/Void_Skull`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "HELM",
		name: "Zealot's Hat",
		internalSlug: "Armor_Head_Ritualist_C",
		dlc: "DLC1",
		imageUrl: "items/armors/zealotshat.png",
		id: "ts1v89",
		set: "Zealot's Set",
		modifiers: {
			armor: 11.3,
			weight: 4.7,
			resistBleed: 1,
			resistFire: 0,
			resistShock: 1,
			resistBlight: 2,
			resistToxin: 2,
		},
		description: [
			`A large-brimmed hat that manages to strike fear in those who see it despite its simplistic and unintimidating design. Its main use is to cast its wearer's face in
      a shadow as dark as the deeds they seek to commit under black of night.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Zealot's_Hat`,
		location: { world: "Losomn", dungeon: ["Forlorn Coast"] },
	},

	// #region TORSO

	{
		category: "TORSO",
		name: "Academic's Overcoat",
		internalSlug: "Armor_Body_Alchemist_C",
		imageUrl: "items/armors/academicsovercoat.png",
		id: "zk8f7a",
		dlc: "BASE",
		set: `Academic's Set`,
		modifiers: {
			armor: 49.2,
			weight: 20.8,
			resistBleed: 2,
			resistFire: 0,
			resistShock: 0,
			resistBlight: 3,
			resistToxin: 6,
		},
		description: [
			`Donning this uniform makes you feel a touch smarter, and you can't help but straighten the necktie whenever it slips loose.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Academic's_Overcoat`,
		location: {
			world: "Losomn",
			dungeon: [`The Great Sewers`, `Tiller's Rest`],
		},
	},
	{
		category: "TORSO",
		name: "Bandit Jacket",
		internalSlug: "Armor_Body_Bandit_C",
		imageUrl: "items/armors/banditjacket.png",
		id: "h04d6v",
		dlc: "BASE",
		set: "Bandit Set",
		modifiers: {
			armor: 27.2,
			weight: 10.8,
			resistBleed: 3,
			resistFire: 0,
			resistShock: 0,
			resistBlight: 2,
			resistToxin: 2,
		},
		description: [
			`Little more than a coat, stitched together from scraps of leather and whatever else could be scavenged from the wasteland. While it may provide a small degree of protection against the elements, it's hardly suitable for combat and is more of a fashion statement than anything else.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Bandit_Jacket`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "TORSO",
		name: "Battle Shirt",
		internalSlug: "Armor_Body_Army_C",
		imageUrl: "items/armors/battleshirt.png",
		id: "batshi",
		dlc: "DLC2",
		set: "Battle Set",
		modifiers: {
			armor: 31.6,
			weight: 12.8,
			resistBleed: 2,
			resistFire: 3,
			resistShock: 0,
			resistBlight: 2,
			resistToxin: 2,
		},
		description: [
			`A simple, standard-issue army shirt made from a durable canvas composite. It's seen a lot of action but was clearly carefully maintained. There appears to be some kind of tag above the pocket, but whatever it once said, time washed it away long ago.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Battle_Shirt`,
		location: { world: "Yaesha", dungeon: [`Proving Grounds`] },
	},
	{
		category: "TORSO",
		name: "Bruiser Bodyplate",
		internalSlug: "Armor_Body_Challenger_C",
		imageUrl: "items/armors/bruiserbodyplate.png",
		id: "trz2cm",
		dlc: "BASE",
		set: "Bruiser Set",
		modifiers: {
			armor: 70.2,
			weight: 32.4,
			resistBleed: 2,
			resistFire: 6,
			resistShock: 0,
			resistBlight: 0,
			resistToxin: 2,
		},
		description: [
			`This thing is difficult to put on or take off and makes you feel like a walking tank. In the thick of battle, that's exactly what you're looking for.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Bruiser_Bodyplate`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "TORSO",
		name: "Crimson Guard Plate",
		internalSlug: "Armor_Body_CrimsonGuard_C",
		dlc: "DLC1",
		imageUrl: "items/armors/crimsonguardplate.png",
		id: "hz7ddb",
		set: "Crimson Guard Set",
		modifiers: {
			armor: 60.8,
			weight: 26.8,
			resistBleed: 4,
			resistFire: 3,
			resistShock: 0,
			resistBlight: 2,
			resistToxin: 0,
		},
		description: [
			`This heavy suit of armor encumbers your shoulders with weight befitting the burdens of a sovereign. It emits a faint heat, as if forged from an ever-hot metal.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Crimson_Guard_Plate`,
		location: { world: "Losomn", dungeon: "Quest" },
	},
	{
		category: "TORSO",
		name: "Cultist Duster",
		internalSlug: "Armor_Body_Cultist_C",
		imageUrl: "items/armors/cultistduster.png",
		id: "w4emjx",
		dlc: "BASE",
		set: "Cultist Set",
		modifiers: {
			armor: 44.6,
			weight: 18.4,
			resistBleed: 1,
			resistFire: 1,
			resistShock: 2,
			resistBlight: 2,
			resistToxin: 3,
		},
		description: [
			`More symbolic than functional, it's adorned with trinkets and ornaments instead of providing significant protection. The coat's drab color blends in with the bleak, post-apocalyptic landscape, serving as a visible sign of the wearer's allegiance to the Root`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Cultist_Duster`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "TORSO",
		name: "Dendroid Chest",
		internalSlug: "Armor_Body_Invader_C",
		imageUrl: "items/armors/dendroidchest.png",
		id: "uoddub",
		dlc: "BASE",
		set: "Dendroid Set",
		modifiers: {
			armor: 30.8,
			weight: 12.4,
			resistBleed: 4,
			resistFire: 0,
			resistShock: 0,
			resistBlight: 2,
			resistToxin: 5,
		},
		description: [
			`Fibrous tentacles wrap themselves around your chest. Up until now, you've resolutely avoided this situation.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Dendroid_Chest`,
		location: { world: "Root Earth", dungeon: ["Ashen Wasteland"] },
	},
	{
		category: "TORSO",
		name: "Disciple Mantle",
		internalSlug: "Armor_Body_Invoker_C",
		imageUrl: "items/armors/disciplemantle.png",
		id: "ddddub",
		dlc: "DLC2",
		set: "Disciple Set",
		modifiers: {
			armor: 64,
			weight: 28.8,
			resistBleed: 0,
			resistFire: 4,
			resistShock: 5,
			resistBlight: 0,
			resistToxin: 2,
		},
		description: [
			`The pauldrons bear the mirrored faces of Meidra and Kaeula, who always journeyed together in their ethereal wanderings, for Meidra's flowers could not bloom so lovely without Kaeula's rains.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Disciple_Mantle`,
		location: { world: "Yaesha", dungeon: ["Ancient Canopy"] },
	},
	{
		category: "TORSO",
		name: "Elder Raiment",
		internalSlug: "Armor_Body_Elder_C",
		imageUrl: "items/armors/elderraiment.png",
		id: "zu64t4",
		dlc: "BASE",
		set: "Elder Set",
		modifiers: {
			armor: 29.6,
			weight: 12,
			resistBleed: 0,
			resistFire: 4,
			resistShock: 0,
			resistBlight: 4,
			resistToxin: 2,
		},
		description: [
			`A distinctive piece of protective gear originating from Yaesha. Its vibrant red color and fur adornments make it stand out, serving as a symbol of the wearer's status and skill. While it may not provide as much protection as some other types of armor, its lightweight construction and flexible design allow for exceptional mobility and ease of movement in combat.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Elder_Raiment`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "TORSO",
		name: "Fae Royal Bodyplate",
		internalSlug: "Armor_Body_FaeRoyalGuard_C",
		imageUrl: "items/armors/faeroyalbodyplate.png",
		id: "0sm6sn",
		dlc: "BASE",
		set: "Fae Royal Set",
		modifiers: {
			armor: 60,
			weight: 26.4,
			resistBleed: 4,
			resistFire: 3,
			resistShock: 0,
			resistBlight: 2,
			resistToxin: 0,
		},
		description: [
			`The royal guard do not wear insignias on their chests nor crests on their shield. It is assumed their identify is clear from their grab and the confidence with which they carry themselves.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Fae_Royal_Bodyplate`,
		location: { world: "Losomn", dungeon: [`Postulant's Parlor`] },
	},
	{
		category: "TORSO",
		name: "Field Medic Overcoat",
		internalSlug: "Armor_Body_Medic_C",
		imageUrl: "items/armors/fieldmedicovercoat.png",
		id: "m07a0z",
		dlc: "BASE",
		set: "Field Medic Set",
		modifiers: {
			armor: 42.8,
			weight: 17.6,
			resistBleed: 9,
			resistFire: 0,
			resistShock: 0,
			resistBlight: 3,
			resistToxin: 0,
		},
		description: [
			`A long coat over a plate of armor. The metal could be thicker, sure, but your primary concern is safe and speedy travel to the wounded.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Field_Medic_Overcoat`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "TORSO",
		name: "High Noon Duds",
		internalSlug: "Armor_Body_Gunslinger_C",
		imageUrl: "items/armors/highnoonduds.png",
		id: "uszg5g",
		dlc: "BASE",
		set: "High Noon Set",
		modifiers: {
			armor: 47.1,
			weight: 19.6,
			resistBleed: 0,
			resistFire: 4,
			resistShock: 4,
			resistBlight: 0,
			resistToxin: 2,
		},
		description: [
			`A rugged amalgamation of canvas, denim, leather, and steel. These different materials all serve the same purpose of keeping you covered without inhibiting aiming mobility.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/High_Noon_Duds`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "TORSO",
		name: "Knotted Cage",
		internalSlug: "Armor_Body_summoner_C",
		imageUrl: "items/armors/knottedcage.png",
		id: "n92z22",
		dlc: "BASE",
		set: "Knotted Set",
		modifiers: {
			armor: 62.2,
			weight: 27.6,
			resistBleed: 1,
			resistFire: 0,
			resistShock: 0,
			resistBlight: 3,
			resistToxin: 7,
		},
		description: [
			`Tightly coiled bark shrouds you like a second ribcage. Its embrace is surprisingly-and frighteningly-comforting.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Knotted_Cage`,
		location: { world: "Yaesha", dungeon: "Vendor" },
	},
	{
		category: "TORSO",
		name: "Labyrinth Mantle",
		internalSlug: "Armor_Body_Archon_C",
		imageUrl: "items/armors/labyrinthmantle.png",
		id: "ivwkr5",
		dlc: "BASE",
		set: "Labyrinth Set",
		modifiers: {
			armor: 51,
			weight: 21.6,
			resistBleed: 0,
			resistFire: 4,
			resistShock: 6,
			resistBlight: 0,
			resistToxin: 0,
		},
		description: [
			`Though the cloth and tassels possess a seemingly primitive design, the pure energy wracking down your spine reminds you otherwise.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Labyrinth_Mantle`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "TORSO",
		name: "Leto Mark 1 Armor",
		internalSlug: "Armor_Body_Leto1_C",
		imageUrl: "items/armors/letomark1armor.png",
		id: "y1xt79",
		dlc: "BASE",
		set: "Leto Mark 1 Set",
		modifiers: {
			armor: 90.4,
			weight: 47.5,
			resistBleed: 4,
			resistFire: 5,
			resistShock: 5,
			resistBlight: 5,
			resistToxin: 5,
		},
		description: [
			`An impressive prototype engineered to safeguard against any danger from the Root, but its cutting-edge technology sacrifices agility and mobility in exchange for unparalleled protection `,
		],
		wikiUrl: `https://remnant2.wiki.gg/Leto_Mark_1_Armor`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "TORSO",
		name: "Leto Mark II Armor",
		internalSlug: "Armor_Body_Leto2_C",
		imageUrl: "items/armors/letomark2armor.png",
		id: "ioksvz",
		dlc: "BASE",
		set: "Leto Mark II Set",
		modifiers: {
			armor: 88.8,
			weight: 45.2,
			resistBleed: 3,
			resistFire: 4,
			resistShock: 4,
			resistBlight: 5,
			resistToxin: 3,
		},
		description: [
			`A masterpiece of impenetrability. Even though quick maneuvering is near impossible in this metal behemoth, you can't help but be impressed by the ingenuity of the design and the inspired craftsmanship.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Leto_Mark_II_Armor`,
		location: { world: "Ward 13", dungeon: "World Drop" },
	},
	{
		category: "TORSO",
		name: "Nanoplated Vestments",
		internalSlug: "Armor_Body_Warden_C",
		imageUrl: "items/armors/nanoplatedvestments.png",
		id: "4rt0f9",
		dlc: "DLC3",
		set: "Nanoplated Set",
		modifiers: {
			armor: 29.6,
			weight: 12,
			resistBleed: 4,
			resistFire: 2,
			resistShock: 0,
			resistToxin: 0,
			resistBlight: 4,
		},
		wikiUrl: `https://remnant2.wiki.gg/Nanoplated_Vestments`,
		location: { world: `N'Erud`, dungeon: [`Withered Necropolis`] },
		description: [
			`The light-plated design of this armor protects not only flesh, but a[sic] highly advanced artificial nervous system that conducts stellar energy to power the entire suit.`,
			`“Risynth Neko's reputation as a Seeker faltered in recent cycles due to a rumor arising about his addiction to ambit ember. His reputation was not the only one damaged during the civil debates regarding N'Erud jump,[sic] but it was one of the most momentous.”`,
		],
	},
	{
		category: "TORSO",
		name: "Nightstalker Garb",
		internalSlug: "Armor_Body_Hunter_C",
		imageUrl: "items/armors/nightstalkergarb.png",
		id: "lqrdx5",
		dlc: "BASE",
		set: "Nightstalker Set",
		modifiers: {
			armor: 43.6,
			weight: 18,
			resistBleed: 2,
			resistFire: 3,
			resistShock: 2,
			resistBlight: 2,
			resistToxin: 0,
		},
		description: [
			`This old coat is shabby, but who's really looking? The wealth of interior ammunition pockets more than makes up for it.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Nightstalker_Garb`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "TORSO",
		name: "Phetyr Chassis",
		internalSlug: "Armor_Body_NerudWarrior_C",
		imageUrl: "items/armors/phetyrchassis.png",
		id: "smq21h",
		dlc: "DLC3",
		set: "Phetyr Set",
		modifiers: {
			armor: 80.6,
			weight: 39.9,
			resistBleed: 4,
			resistFire: 6,
			resistShock: 6,
			resistToxin: 7,
			resistBlight: 3,
		},
		description: [""],
		wikiUrl: `https://remnant2.wiki.gg/Phetyr_Chasis`,
		location: { world: `N'Erud`, dungeon: [`Logistics Bridge`] },
	},
	{
		category: "TORSO",
		name: "Radiant Protector",
		internalSlug: "Armor_Body_Radiant_C",
		imageUrl: "items/armors/radiantprotector.png",
		id: "dd5s6k",
		dlc: "BASE",
		set: "Radiant Set",
		modifiers: {
			armor: 69,
			weight: 31.6,
			resistBleed: 2,
			resistFire: 2,
			resistShock: 4,
			resistBlight: 1,
			resistToxin: 0,
		},
		description: [
			`A dazzling sight, its golden surface featuring a stunning sun burst pattern etched into the chest. Adorned with blue gems embedded in the shoulders this armor is fit for only the most esteemed members of the Laemir`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Radiant_Protector`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "TORSO",
		name: "Realmwalker Tunic",
		internalSlug: "Armor_Body_Explorer_C",
		imageUrl: "items/armors/realmwalkertunic.png",
		id: "2h9xgj",
		dlc: "BASE",
		set: "Realmwalker Set",
		modifiers: {
			armor: 29,
			weight: 11.6,
			resistBleed: 3,
			resistFire: 2,
			resistShock: 3,
			resistBlight: 4,
			resistToxin: 0,
		},
		description: [
			`It's not even frayed. How is that possible? Unless the World Stones did the same thing to Ford's clothes as they did to Ford himself.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Realmwalker_Tunic`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "TORSO",
		name: "Red Widow Raiment",
		internalSlug: "Armor_Body_RedWidow_C",
		imageUrl: "items/armors/redwidowraiment.png",
		id: "lude4p",
		dlc: "BASE",
		set: "Red Widow Set",
		modifiers: {
			armor: 52.8,
			weight: 22.4,
			resistBleed: 5,
			resistFire: 0,
			resistShock: 0,
			resistBlight: 4,
			resistToxin: 1,
		},
		description: [
			`This chest piece must be hundreds -thousands- of years old, yet it shows no signis of rust or decay. One can only imagine a Pan king or queen wearing such  majestic regalia.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Red_Widow_Raiment`,
		location: { world: "Yaesha", dungeon: ["The Lament"] },
	},
	{
		category: "TORSO",
		name: "Space Worker Body",
		internalSlug: "Armor_Body_SpaceWorker_C",
		imageUrl: "items/armors/spaceworkerbody.png",
		id: "jwanjw",
		dlc: "BASE",
		set: "Space Worker Set",
		modifiers: {
			armor: 28,
			weight: 11.2,
			resistBleed: 1,
			resistFire: 1,
			resistShock: 4,
			resistBlight: 0,
			resistToxin: 2,
		},
		description: [
			`It's made of some material you don't recognize - thick but highly pliable, did the Drzyr expect to get struck by out there?`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Space_Worker_Body`,
		location: { world: `N'Erud`, dungeon: [`Void Vessel Facility`] },
	},
	{
		category: "TORSO",
		name: "Survivor Overcoat",
		internalSlug: "Armor_Body_Survivor_C",
		imageUrl: "items/armors/survivorovercoat.png",
		id: "jr8r1l",
		dlc: "BASE",
		set: "Survivor Set",
		modifiers: {
			armor: 39.2,
			weight: 16,
			resistBleed: 3,
			resistFire: 2,
			resistShock: 2,
			resistBlight: 2,
			resistToxin: 2,
		},
		description: [
			`A combination of a sturdy metal chest plate and a worn, leather trench coat that provides some protection against the elements. It's clear that the are together with practicality in mind, rather than aesthetics.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Survivor_Overcoat`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "TORSO",
		name: "Technician Bodyplate",
		internalSlug: "Armor_Body_Engineer_C",
		imageUrl: "items/armors/technicianbodyplate.png",
		id: "0c35xs",
		dlc: "BASE",
		set: "Technician Set",
		modifiers: {
			armor: 66.4,
			weight: 30,
			resistBleed: 0,
			resistFire: 2,
			resistShock: 6,
			resistBlight: 0,
			resistToxin: 2,
		},
		description: [
			`The Xul were engineers and builders, but this armor was made to withstand a grenade blast. Was this built for safety or something else?`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Technician_Bodyplate`,
		location: {
			world: `N'Erud`,
			dungeon: [`The Eon Vault`, `Timeless Horizon`],
		},
	},
	{
		category: "TORSO",
		name: "Trainer Clothes",
		internalSlug: "Armor_Body_Handler_C",
		imageUrl: "items/armors/trainerclothes.png",
		id: "ldli1k",
		dlc: "BASE",
		set: "Trainer Set",
		modifiers: {
			armor: 40,
			weight: 16.4,
			resistBleed: 3,
			resistFire: 0,
			resistShock: 4,
			resistBlight: 1,
			resistToxin: 3,
		},
		description: [
			`This isn't just any denim jacket, it's your denim jacket. It's not especial pale. 7 ready, but it's comfortable, and in it you feel ready for anything.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Trainer_Clothes`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "TORSO",
		name: "Void Carapace",
		internalSlug: "Armor_Body_Void_C",
		imageUrl: "items/armors/voidcarapace.png",
		id: "rmq9je",
		dlc: "BASE",
		set: "Void Set",
		modifiers: {
			armor: 63.6,
			weight: 28.4,
			resistBleed: 0,
			resistFire: 3,
			resistShock: 4,
			resistBlight: 0,
			resistToxin: 4,
		},
		description: [
			`Crafted from the same mysterious material as the Void gloves, helm, and greaves, the chest armor completes the set's unsettling aesthetic. Its angular design is both practical and intimidating, providing unparalleled protection against the deadly environments and creatures of Rhom.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Void_Carapace`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "TORSO",
		name: "Zealot's Overcoat",
		internalSlug: "Armor_Body_Ritualist_C",
		dlc: "DLC1",
		imageUrl: "items/armors/zealotsovercoat.png",
		id: "ym0mau",
		set: "Zealot's Set",
		modifiers: {
			armor: 45.2,
			weight: 18.8,
			resistBleed: 2,
			resistFire: 0,
			resistShock: 1,
			resistBlight: 3,
			resistToxin: 3,
		},
		description: [
			`This long and tattered cloak is ideal for skulking about in the dead of night in pursuance of iniquitous aims. If you ever see the back of this cloak ahead of you, you would do well to run. If you ever see its wearer facing you, it is already too late.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Zealot's_Overcoat`,
		location: { world: "Losomn", dungeon: ["Forlorn Coast"] },
	},

	// #region LEGS

	{
		category: "LEGS",
		name: "Academic's Trousers",
		internalSlug: "Armor_Legs_Alchemist_C",
		imageUrl: "items/armors/academicstrousers.png",
		id: "9b43cb",
		dlc: "BASE",
		set: `Academic's Set`,
		modifiers: {
			armor: 24.6,
			weight: 10.4,
			resistBleed: 2,
			resistFire: 0,
			resistShock: 0,
			resistBlight: 1,
			resistToxin: 4,
		},
		description: [
			`Expensive-looking shoes fit for a lecture hall...that wouldn't last a week outside it.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Academic's_Trousers`,
		location: {
			world: "Losomn",
			dungeon: [`The Great Sewers`, `Tiller's Rest`],
		},
	},
	{
		category: "LEGS",
		name: "Bandit Trousers",
		internalSlug: "Armor_Legs_Bandit_C",
		imageUrl: "items/armors/bandittrousers.png",
		id: "zdv44y",
		dlc: "BASE",
		set: "Bandit Set",
		modifiers: {
			armor: 13.6,
			weight: 5.4,
			resistBleed: 2,
			resistFire: 0,
			resistShock: 0,
			resistBlight: 1,
			resistToxin: 2,
		},
		description: [
			`Consists of a pair of basic slacks and sturdy boots. While it may not offer much in terms of protection, it allows for easy movement and agility in the dangerous terrain of the ruined cityscapes. The simplicity of the design is a testament to the practicality of the bandits, who prioritize functionality over aesthetics.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Bandit_Trousers`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "LEGS",
		name: "Battle Slacks",
		internalSlug: "Armor_Legs_Army_C",
		imageUrl: "items/armors/battleslacks.png",
		id: "battra",
		dlc: "DLC2",
		set: "Battle Set",
		modifiers: {
			armor: 15.8,
			weight: 6.4,
			resistBleed: 1,
			resistFire: 1,
			resistShock: 0,
			resistBlight: 2,
			resistToxin: 1,
		},
		description: [
			`A rugged pair of army pants complete with a functional, nondescript belt, a belt buckle, and a set of worn leather boots. They're designed to withstand whatver the mission demands of a soldier.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Battle_Slacks`,
		location: { world: "Yaesha", dungeon: [`Proving Grounds`] },
	},
	{
		category: "LEGS",
		name: "Bruiser Boots",
		internalSlug: "Armor_Legs_Challenger_C",
		imageUrl: "items/armors/bruiserboots.png",
		id: "pof5ii",
		dlc: "BASE",
		set: "Bruiser Set",
		modifiers: {
			armor: 35,
			weight: 16.2,
			resistBleed: 1,
			resistFire: 4,
			resistShock: 0,
			resistBlight: 0,
			resistToxin: 2,
		},
		description: [
			`While they're not exactly aesthetic, you're more comfortable in twice-temper steel and repurposed tire tread than you care to admit.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Bruiser_Boots`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "LEGS",
		name: "Crimson Guard Sabatons",
		internalSlug: "Armor_Legs_CrimsonGuard_C",
		dlc: "DLC1",
		imageUrl: "items/armors/crimsonguardsabatons.png",
		id: "zk58sf",
		set: "Crimson Guard Set",
		modifiers: {
			armor: 30.4,
			weight: 13.4,
			resistBleed: 2,
			resistFire: 3,
			resistShock: 0,
			resistBlight: 2,
			resistToxin: 0,
		},
		description: [
			`The crimson greaves clink and clank as you walk, announcing your presence to those honored enough to know it. Each sabaton tapers to a sharp, defiant point.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Crimson_Guard_Sabatons`,
		location: { world: "Losomn", dungeon: "Quest" },
	},
	{
		category: "LEGS",
		name: "Cultist Britches",
		internalSlug: "Armor_Legs_Cultist_C",
		imageUrl: "items/armors/cultistbritches.png",
		id: "mr4hn3",
		dlc: "BASE",
		set: "Cultist Set",
		modifiers: {
			armor: 22.2,
			weight: 9.2,
			resistBleed: 1,
			resistFire: 1,
			resistShock: 1,
			resistBlight: 2,
			resistToxin: 2,
		},
		description: [
			`Simple slacks and boots made of cloth and wrapped in rope. Cultists rely on their unwavering devotion to the Root for their safety instead.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Cultist_Britches`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "LEGS",
		name: "Dendroid Leggings",
		internalSlug: "Armor_Legs_Invader_C",
		imageUrl: "items/armors/dendroidleggings.png",
		id: "zwh3mb",
		dlc: "BASE",
		set: "Dendroid Set",
		modifiers: {
			armor: 15.4,
			weight: 6.2,
			resistBleed: 3,
			resistFire: 0,
			resistShock: 0,
			resistBlight: 2,
			resistToxin: 2,
		},
		description: [
			`The deadwood boots are surprisingly snug. You're not sure what you expected shodding your feet inside the bloodthirsty branches of the Root, but it wasn't this cushioned comfort.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Dendroid_Leggings`,
		location: { world: "Root Earth", dungeon: ["Ashen Wasteland"] },
	},
	{
		category: "LEGS",
		name: "Disciple Greaves",
		internalSlug: "Armor_Legs_Invoker_C",
		imageUrl: "items/armors/disciplegreaves.png",
		id: "udddub",
		dlc: "DLC2",
		set: "Disciple Set",
		modifiers: {
			armor: 32,
			weight: 14.4,
			resistBleed: 0,
			resistFire: 2,
			resistShock: 3,
			resistBlight: 0,
			resistToxin: 1,
		},
		description: [
			`You can feel all of Yaesha beneath the soles of these heavy greaves: the soft loam of the soil, the plush of green clovers, and the cold chill of a gurgling stream. You walk with the ease of those who were born of the forest.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Disciple_Greaves`,
		location: { world: "Yaesha", dungeon: ["Ancient Canopy"] },
	},
	{
		category: "LEGS",
		name: "Elder Leggings",
		internalSlug: "Armor_Legs_Elder_C",
		imageUrl: "items/armors/elderleggings.png",
		id: "tfvyyg",
		dlc: "BASE",
		set: "Elder Set",
		modifiers: {
			armor: 14.8,
			weight: 6,
			resistBleed: 0,
			resistFire: 3,
			resistShock: 0,
			resistBlight: 2,
			resistToxin: 1,
		},
		description: [
			`Designed for both form and function. Made from durable yet lightweight materials, they allow for a full range of movement and flexibility in combat.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Elder_Leggings`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "LEGS",
		name: "Fae Royal Greaves",
		internalSlug: "Armor_Legs_FaeRoyalGuard_C",
		imageUrl: "items/armors/faeroyalgreaves.png",
		id: "pi4h8k",
		dlc: "BASE",
		set: "Fae Royal Set",
		modifiers: {
			armor: 30,
			weight: 13.2,
			resistBleed: 2,
			resistFire: 3,
			resistShock: 0,
			resistBlight: 2,
			resistToxin: 0,
		},
		description: [
			`Although apparently made of steel, they feel lighter than any boots you've eve worn.
      No... you feel lighter when wearing them.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Fae_Royal_Greaves`,
		location: { world: "Losomn", dungeon: [`Postulant's Parlor`] },
	},
	{
		category: "LEGS",
		name: "Field Medic Trousers",
		internalSlug: "Armor_Legs_Medic_C",
		imageUrl: "items/armors/fieldmedictrousers.png",
		id: "eqcfyt",
		dlc: "BASE",
		set: "Field Medic Set",
		modifiers: {
			armor: 21.4,
			weight: 8.8,
			resistBleed: 4,
			resistFire: 0,
			resistShock: 0,
			resistBlight: 2,
			resistToxin: 0,
		},
		description: [
			`With an assortment of pockets, pouches, and loops for your various concoctions you're essentially a walking apothecary.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Field_Medic_Trousers`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "LEGS",
		name: "High Noon Soles",
		internalSlug: "Armor_Legs_Gunslinger_C",
		imageUrl: "items/armors/highnoonsoles.png",
		id: "yccols",
		dlc: "BASE",
		set: "High Noon Set",
		modifiers: {
			armor: 23.4,
			weight: 9.8,
			resistBleed: 0,
			resistFire: 3,
			resistShock: 2,
			resistBlight: 0,
			resistToxin: 2,
		},
		description: [
			`Durable pants with spurred boots and a strip of leather for a belt. The only accent is an imposing skull on the belt buckle, a constant reminder that death is always lurking in the shadows.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/High_Noon_Soles`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "LEGS",
		name: "Knotted Greaves",
		internalSlug: "Armor_Legs_summoner_C",
		imageUrl: "items/armors/knottedgreaves.png",
		id: "b48zw1",
		dlc: "BASE",
		set: "Knotted Set",
		modifiers: {
			armor: 31.1,
			weight: 13.8,
			resistBleed: 1,
			resistFire: 0,
			resistShock: 0,
			resistBlight: 2,
			resistToxin: 4,
		},
		description: [
			`These boots are surprisingly light and agile, carrying you through foliage and bramble with ease. They seem to know where to go before you even lift you foot.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Knotted_Greaves`,
		location: { world: "Yaesha", dungeon: "Vendor" },
	},
	{
		category: "LEGS",
		name: "Labyrinth Treads",
		internalSlug: "Armor_Legs_Archon_C",
		imageUrl: "items/armors/labyrinthtreads.png",
		id: "td29nk",
		dlc: "BASE",
		set: "Labyrinth Set",
		modifiers: {
			armor: 25.5,
			weight: 10.8,
			resistBleed: 0,
			resistFire: 3,
			resistShock: 4,
			resistBlight: 0,
			resistToxin: 0,
		},
		description: [
			`The grime of a thousand different worlds mars the side of boots that walk in one place where all paths converge.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Labyrinth_Treads`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "LEGS",
		name: "Leto Mark 1 Leggings",
		internalSlug: "Armor_Legs_Leto1_C",
		imageUrl: "items/armors/letomark1leggings.png",
		id: "59uhgg",
		dlc: "BASE",
		set: "Leto Mark 1 Set",
		modifiers: {
			armor: 45.2,
			weight: 23.7,
			resistBleed: 4,
			resistFire: 3,
			resistShock: 4,
			resistBlight: 4,
			resistToxin: 3,
		},
		description: [
			`Offering unparalleled protection at the cost of speed and agility. Although it hinders movement, the armor's strength allows its wearer to withstand even the most vicious attacks without fear of serious injury.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Leto_Mark_1_Leggings`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "LEGS",
		name: "Leto Mark II Leggings",
		internalSlug: "Armor_Legs_Leto2_C",
		imageUrl: "items/armors/letomark2leggings.png",
		id: "t8auqk",
		dlc: "BASE",
		set: "Leto Mark II Set",
		modifiers: {
			armor: 44.4,
			weight: 22.6,
			resistBleed: 3,
			resistFire: 2,
			resistShock: 3,
			resistBlight: 3,
			resistToxin: 2,
		},
		description: [
			`Strong yet streamlined. Practical yet aesthetic. Although you can't expect to make a quick getaway in these, they're just what you need to stand strong against the looming threat of destruction. The care and attention to detail t| went into them is something to behold.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Leto_Mark_II_Leggings`,
		location: { world: "Ward 13", dungeon: "World Drop" },
	},
	{
		category: "LEGS",
		name: "Nanoplated Waist",
		internalSlug: "Armor_Legs_Warden_C",
		imageUrl: "items/armors/nanoplatedwaist.png",
		id: "im4rk0",
		dlc: "DLC3",
		set: "Nanoplated Set",
		modifiers: {
			armor: 14.8,
			weight: 6,
			resistBleed: 3,
			resistFire: 2,
			resistShock: 0,
			resistToxin: 0,
			resistBlight: 2,
		},
		wikiUrl: `https://remnant2.wiki.gg/Nanoplated_Waist`,
		location: { world: `N'Erud`, dungeon: [`Withered Necropolis`] },
		description: [
			`These boots end in a foot with three long toes, which help augment the wearer's balance and flexibility, allowing them to navigate complex and unforeseen environments.`,
			`“Maxim Lar'Veli, the People's Seeker, was nominated to the Convocation despite his relatively low status within House Al'Maruun due to his earnest nature and passionate dedication to his people. He elected himself to stay awake alongside the Seeker Primis while the rest of the Drzyr entered cryostasis. For that short while, Precept Surus and I were his only confidants.”`,
		],
	},
	{
		category: "LEGS",
		name: "Nightstalker Pants",
		internalSlug: "Armor_Legs_Hunter_C",
		imageUrl: "items/armors/nightstalkerpants.png",
		id: "l6utx1",
		dlc: "BASE",
		set: "Nightstalker Set",
		modifiers: {
			armor: 21.8,
			weight: 9,
			resistBleed: 2,
			resistFire: 2,
			resistShock: 1,
			resistBlight: 1,
			resistToxin: 0,
		},
		description: [
			`Thin shoes that fit perfectly and feel like they practically disappear on your feet. They're ideal for stealthy maneuvering while stalking your prey.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Nightstalker_Pants`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "LEGS",
		name: "Phetyr Locomotor",
		internalSlug: "Armor_Legs_NerudWarrior_C",
		imageUrl: "items/armors/phetyrlocomotor.png",
		id: "pd68a7",
		dlc: "DLC3",
		set: "Phetyr Set",
		modifiers: {
			armor: 43.8,
			weight: 21.7,
			resistBleed: 2,
			resistFire: 2,
			resistShock: 3,
			resistToxin: 4,
			resistBlight: 2,
		},
		description: [""],
		wikiUrl: `https://remnant2.wiki.gg/Phetyr_Locomotor`,
		location: { world: `N'Erud`, dungeon: [`Logistics Bridge`] },
	},
	{
		category: "LEGS",
		name: "Radiant Greaves",
		internalSlug: "Armor_Legs_Radiant_C",
		imageUrl: "items/armors/radiantgreaves.png",
		id: "vsg3ue",
		dlc: "BASE",
		set: "Radiant Set",
		modifiers: {
			armor: 34.5,
			weight: 15.8,
			resistBleed: 1,
			resistFire: 1,
			resistShock: 3,
			resistBlight: 1,
			resistToxin: 0,
		},
		description: [
			`Gleaming golden plates overlap and protect the wearer's feet and shins. Originally designed to be worn by the Pan, it's impressive how the armor can be adapted to fit human proportions without sacrificing its durability or protective properties.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Radiant_Greaves`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "LEGS",
		name: "Realmwalker Pantaloons",
		internalSlug: "Armor_Legs_Explorer_C",
		imageUrl: "items/armors/realmwalkerpantaloons.png",
		id: "4sy6z9",
		dlc: "BASE",
		set: "Realmwalker Set",
		modifiers: {
			armor: 14.5,
			weight: 5.8,
			resistBleed: 2,
			resistFire: 1,
			resistShock: 2,
			resistBlight: 3,
			resistToxin: 0,
		},
		description: [`There is hardly a world where these boots haven't tread.`],
		wikiUrl: `https://remnant2.wiki.gg/Realmwalker_Pantaloons`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "LEGS",
		name: "Red Widow Leggings",
		internalSlug: "Armor_Legs_RedWidow_C",
		imageUrl: "items/armors/redwidowleggings.png",
		id: "e4fbbu",
		dlc: "BASE",
		set: "Red Widow Set",
		modifiers: {
			armor: 26.2,
			weight: 11.2,
			resistBleed: 3,
			resistFire: 0,
			resistShock: 0,
			resistBlight: 3,
			resistToxin: 1,
		},
		description: [
			`Even though this armor was designed to be worn by a Pan warrior, you are still able wear it and benefit from its protection.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Red_Widow_Leggings`,
		location: { world: "Yaesha", dungeon: ["The Lament"] },
	},
	{
		category: "LEGS",
		name: "Space Worker Legs",
		internalSlug: "Armor_Legs_SpaceWorker_C",
		imageUrl: "items/armors/spaceworkerleggings.png",
		id: "rsyilr",
		dlc: "BASE",
		set: "Space Worker Set",
		modifiers: {
			armor: 14,
			weight: 5.6,
			resistBleed: 1,
			resistFire: 1,
			resistShock: 3,
			resistBlight: 0,
			resistToxin: 2,
		},
		description: [
			`The magnets in the boots are far stronger than those in the gloves. It's unclear how they know when to activate, but they do so on their own. Massive as N'Erud is, it must not provide enough gravity to ensure its workers remain attached to...`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Space_Worker_Legs`,
		location: { world: `N'Erud`, dungeon: [`Void Vessel Facility`] },
	},
	{
		category: "LEGS",
		name: "Survivor Leggings",
		internalSlug: "Armor_Legs_Survivor_C",
		imageUrl: "items/armors/survivorleggings.png",
		id: "gv2eqj",
		dlc: "BASE",
		set: "Survivor Set",
		modifiers: {
			armor: 19.6,
			weight: 8,
			resistBleed: 1,
			resistFire: 1,
			resistShock: 1,
			resistBlight: 1,
			resistToxin: 2,
		},
		description: [
			`Provides minimal protection, but serve the purpose of covering up skin to prevent minor cuts and scrapes while trekking through rough terrain.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Survivor_Leggings`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "LEGS",
		name: "Technician Greaves",
		internalSlug: "Armor_Legs_Engineer_C",
		imageUrl: "items/armors/techniciangreaves.png",
		id: "m16oqd",
		dlc: "BASE",
		set: "Technician Set",
		modifiers: {
			armor: 33.2,
			weight: 15,
			resistBleed: 0,
			resistFire: 1,
			resistShock: 3,
			resistBlight: 0,
			resistToxin: 2,
		},
		description: [
			`Designed for stability rather than speed. Plant your weight in these things, and you'd be very difficult to move.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Technician_Greaves`,
		location: {
			world: `N'Erud`,
			dungeon: [`The Eon Vault`, `Timeless Horizon`],
		},
	},
	{
		category: "LEGS",
		name: "Trainer Workboots",
		internalSlug: "Armor_Legs_Handler_C",
		imageUrl: "items/armors/trainerworkboots.png",
		id: "olwicb",
		dlc: "BASE",
		set: "Trainer Set",
		modifiers: {
			armor: 20,
			weight: 8.2,
			resistBleed: 1,
			resistFire: 0,
			resistShock: 1,
			resistBlight: 1,
			resistToxin: 2,
		},
		description: [
			`Durable pants that are used to handling more than a little dirt and fur. The canteen is for your companion, while the flask is all yours.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Trainer_Workboots`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "LEGS",
		name: "Void Greaves",
		internalSlug: "Armor_Legs_Void_C",
		imageUrl: "items/armors/voidgreaves.png",
		id: "73lqjk",
		dlc: "BASE",
		set: "Void Set",
		modifiers: {
			armor: 31.8,
			weight: 14.2,
			resistBleed: 0,
			resistFire: 2,
			resistShock: 2,
			resistBlight: 0,
			resistToxin: 3,
		},
		description: [
			`A sturdy pair of footwear, expertly crafted from the same unknown material the other Void armor pieces. Their angular design and jagged edges give their wearer an intimidating and fearsome look. But these boots are more than fashion statement-they provided unparalleled protection and stability in the treacherous environments of Rhom.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Void_Greaves`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "LEGS",
		name: "Zealot's Seaboots",
		internalSlug: "Armor_Legs_Ritualist_C",
		dlc: "DLC1",
		imageUrl: "items/armors/zealotsseaboots.png",
		id: "sem0s8",
		set: "Zealot's Set",
		modifiers: {
			armor: 22.6,
			weight: 9.4,
			resistBleed: 2,
			resistFire: 0,
			resistShock: 1,
			resistBlight: 2,
			resistToxin: 2,
		},
		description: [
			`Tall wading boots and toughened leather may protect your legs from the unruly waters of Losomn, but they will do nothing to guard against the treacherous creatures that lurk just beneath those sullied waves, thirsting for the blood of those who stray too far from shore.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Zealot's_Seaboots`,
		location: { world: "Losomn", dungeon: ["Forlorn Coast"] },
	},

	// #region GLOVES

	{
		category: "GLOVES",
		name: "Academic's Gloves",
		internalSlug: "Armor_Gloves_Alchemist_C",
		set: "Academic's Set",
		imageUrl: "items/armors/academicsgloves.png",
		id: "f4tb3k",
		dlc: "BASE",
		modifiers: {
			armor: 12.3,
			weight: 5.2,
			resistBleed: 0,
			resistFire: 0,
			resistShock: 0,
			resistBlight: 1,
			resistToxin: 2,
		},
		description: [
			`The initials of the Dran who once owned these - and misplaced them often - are embroidered on the wool-lined inside.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Academic's_Gloves`,
		location: {
			world: "Losomn",
			dungeon: [`The Great Sewers`, `Tiller's Rest`],
		},
	},
	{
		category: "GLOVES",
		name: "Bandit Gloves",
		internalSlug: "Armor_Gloves_Bandit_C",
		imageUrl: "items/armors/banditgloves.png",
		id: "b7j8ys",
		dlc: "BASE",
		set: "Bandit Set",
		modifiers: {
			armor: 6.8,
			weight: 2.7,
			resistBleed: 2,
			resistFire: 0,
			resistShock: 0,
			resistBlight: 1,
			resistToxin: 2,
		},
		description: [
			`The bandit gloves are rough, patched together from scraps of leather and cloth, a testament to their owner's resourcefulness, and willingness to do whatever it takes to survive. Despite their rough and worn appearance, the gloves provide unexpected durability and protection amidst the unforgiving ruins of the city.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Bandit_Gloves`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "GLOVES",
		name: "Battle Gloves",
		internalSlug: "Armor_Gloves_Army_C",
		imageUrl: "items/armors/battlegloves.png",
		id: "batglo",
		dlc: "DLC2",
		set: "Battle Set",
		modifiers: {
			armor: 7.9,
			weight: 3.2,
			resistBleed: 1,
			resistFire: 1,
			resistShock: 0,
			resistBlight: 1,
			resistToxin: 1,
		},
		description: [
			`This pair of leather army gloves couldn't be more to the point. They help guard against knicks and cuts and will help you keep a strong grip even in extreme conditions. It's not the most effective gear you've ever seen, but it's better than nothing.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Battle_Gloves`,
		location: { world: "Yaesha", dungeon: [`Proving Grounds`] },
	},
	{
		category: "GLOVES",
		name: "Bruiser Gloves",
		internalSlug: "Armor_Gloves_Challenger_C",
		imageUrl: "items/armors/bruisergloves.png",
		id: "80xuqr",
		dlc: "BASE",
		set: "Bruiser Set",
		modifiers: {
			armor: 17.6,
			weight: 8.1,
			resistBleed: 1,
			resistFire: 2,
			resistShock: 0,
			resistBlight: 0,
			resistToxin: 1,
		},
		description: [
			`These gauntlets are as tough as steel, as hard as stone, and up for whatever dangers or challenges come their way. They suit you well.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Bruiser_Gloves`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "GLOVES",
		name: "Crimson Guard Gauntlets",
		internalSlug: "Armor_Gloves_CrimsonGuard_C",
		dlc: "DLC1",
		imageUrl: "items/armors/crimsonguardgauntlets.png",
		id: "ms9geh",
		set: "Crimson Guard Set",
		modifiers: {
			armor: 15.2,
			weight: 6.7,
			resistBleed: 1,
			resistFire: 1,
			resistShock: 0,
			resistBlight: 1,
			resistToxin: 0,
		},
		description: [
			`These gauntlets line your forearms with sharp, yet elegant edges, though they lack the sharpened claws that would make a proper bloodthirsty Fae of you.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Crimson_Guard_Gauntlets`,
		location: { world: "Losomn", dungeon: "Quest" },
	},
	{
		category: "GLOVES",
		name: "Cultist Gloves",
		internalSlug: "Armor_Gloves_Cultist_C",
		imageUrl: "items/armors/cultistgloves.png",
		id: "6jrywg",
		dlc: "BASE",
		set: "Cultist Set",
		modifiers: {
			armor: 11.1,
			weight: 4.6,
			resistBleed: 0,
			resistFire: 1,
			resistShock: 1,
			resistBlight: 1,
			resistToxin: 1,
		},
		description: [
			`An unusual piece of attire that consist of leather and rope wrappings that encircle the wearer's wrists. These unconventional gloves were favored by the members of a mysterious cult that valued secrecy and esoteric knowledge above all else`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Cultist_Gloves`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "GLOVES",
		name: "Dendroid Grips",
		internalSlug: "Armor_Gloves_Invader_C",
		imageUrl: "items/armors/dendroidgrips.png",
		id: "6oy3xp",
		dlc: "BASE",
		set: "Dendroid Set",
		modifiers: {
			armor: 7.7,
			weight: 3.1,
			resistBleed: 1,
			resistFire: 0,
			resistShock: 0,
			resistBlight: 1,
			resistToxin: 1,
		},
		description: [
			`Against all logic, these gloves feel natural. Like extensions of who you were meant to be.
      Seems like that should bother you more.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Dendroid_Grips`,
		location: { world: "Root Earth", dungeon: ["Ashen Wasteland"] },
	},
	{
		category: "GLOVES",
		name: "Disciple Vambraces",
		internalSlug: "Armor_Gloves_Invoker_C",
		imageUrl: "items/armors/disciplevambraces.png",
		id: "6dy3xp",
		dlc: "DLC2",
		set: "Disciple Set",
		modifiers: {
			armor: 16,
			weight: 7.2,
			resistBleed: 0,
			resistFire: 1,
			resistShock: 2,
			resistBlight: 0,
			resistToxin: 0,
		},
		description: [
			`The gauntlets taper to sharp points, reminding one that everything in Yaesha is deadly, even those who seem too beautiful to be so.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Disciple_Vambraces`,
		location: { world: "Yaesha", dungeon: ["Ancient Canopy"] },
	},
	{
		category: "GLOVES",
		name: "Elder Gloves",
		internalSlug: "Armor_Gloves_Elder_C",
		imageUrl: "items/armors/eldergloves.png",
		id: "1ijl54",
		dlc: "BASE",
		set: "Elder Set",
		modifiers: {
			armor: 7.5,
			weight: 3,
			resistBleed: 0,
			resistFire: 2,
			resistShock: 0,
			resistBlight: 1,
			resistToxin: 1,
		},
		description: [
			`Features striking loops of gold that add an ornate touch to the otherwise plain design. Curiously, these embellishments are only present on the left-hand glove, making it stand out from its counterpart on the right.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Elder_Gloves`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "GLOVES",
		name: "Fae Royal Vambraces",
		internalSlug: "Armor_Gloves_FaeRoyalGuard_C",
		imageUrl: "items/armors/faeroyalvambraces.png",
		id: "6005lk",
		dlc: "BASE",
		set: "Fae Royal Set",
		modifiers: {
			armor: 15,
			weight: 6.6,
			resistBleed: 1,
			resistFire: 1,
			resistShock: 0,
			resistBlight: 1,
			resistToxin: 0,
		},
		description: [
			`Suitable for archery or swordplay - for killing of any sort really.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Fae_Royal_Vambraces`,
		location: { world: "Losomn", dungeon: [`Postulant's Parlor`] },
	},
	{
		category: "GLOVES",
		name: "Field Medic Gloves",
		internalSlug: "Armor_Gloves_Medic_C",
		imageUrl: "items/armors/fieldmedicgloves.png",
		id: "7ic3gp",
		dlc: "BASE",
		set: "Field Medic Set",
		modifiers: {
			armor: 10.6,
			weight: 4.4,
			resistBleed: 2,
			resistFire: 0,
			resistShock: 0,
			resistBlight: 1,
			resistToxin: 1,
		},
		description: [
			`At a glance it's clear that these fingerless gloves won't keep you warm or offer much protection. Even still, you wear them because they provide improved grip without impacting precision.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Field_Medic_Gloves`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "GLOVES",
		name: "High Noon Armguards",
		internalSlug: "Armor_Gloves_Gunslinger_C",
		imageUrl: "items/armors/highnoonarmguards.png",
		id: "afu61j",
		dlc: "BASE",
		set: "High Noon Set",
		modifiers: {
			armor: 11.7,
			weight: 4.9,
			resistBleed: 0,
			resistFire: 2,
			resistShock: 2,
			resistBlight: 0,
			resistToxin: 1,
		},
		description: [
			`Metal arm guards paired with well-worn gloves that are more comfortable gripping a warm gun than reaching for a handshake. They're tasked with protecting your greatest asset - your trigger finger.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/High_Noon_Armguards`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "GLOVES",
		name: "Knotted Gloves",
		internalSlug: "Armor_Gloves_summoner_C",
		imageUrl: "items/armors/knottedgloves.png",
		id: "07mqqe",
		dlc: "BASE",
		set: "Knotted Set",
		modifiers: {
			armor: 15.5,
			weight: 6.9,
			resistBleed: 1,
			resistFire: 0,
			resistShock: 0,
			resistBlight: 1,
			resistToxin: 2,
		},
		description: [
			`The deadwood claws fit you almost too snug, making it difficult to remember where bark ends and your own flesh begins.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Knotted_Gloves`,
		location: { world: "Yaesha", dungeon: "Vendor" },
	},
	{
		category: "GLOVES",
		name: "Labyrinth Gauntlets",
		internalSlug: "Armor_Gloves_Archon_C",
		imageUrl: "items/armors/labyrinthgauntlets.png",
		id: "bhw19m",
		dlc: "BASE",
		set: "Labyrinth Set",
		modifiers: {
			armor: 12.9,
			weight: 5.4,
			resistBleed: 0,
			resistFire: 1,
			resistShock: 2,
			resistBlight: 0,
			resistToxin: 0,
		},
		description: [
			`Craggy, uneven stone melds tightly to your hands and forearms, as if the skin of something that once was has at last found new purchase.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Labyrinth_Gauntlets`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "GLOVES",
		name: "Leto Mark 1 Gloves",
		internalSlug: "Armor_Gloves_Leto1_C",
		imageUrl: "items/armors/letomark1gloves.png",
		id: "2lqg9t",
		dlc: "BASE",
		set: "Leto Mark 1 Set",
		modifiers: {
			armor: 22.6,
			weight: 11.9,
			resistBleed: 2,
			resistFire: 1,
			resistShock: 2,
			resistBlight: 2,
			resistToxin: 3,
		},
		description: [
			`Offering unparalleled protection against the unpredictable dangers of The Root, but the trade-off, is that they can be cumbersome and restrict dexterity, making it difficult to perform intricate tasks.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Leto_Mark_1_Gloves`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "GLOVES",
		name: "Leto Mark II Gloves",
		internalSlug: "Armor_Gloves_Leto2_C",
		imageUrl: "items/armors/letomark2gloves.png",
		id: "nfxk7i",
		dlc: "BASE",
		set: "Leto Mark II Set",
		modifiers: {
			armor: 21.8,
			weight: 11.1,
			resistBleed: 2,
			resistFire: 1,
			resistShock: 2,
			resistBlight: 1,
			resistToxin: 3,
		},
		description: [
			`These gauntlets are sturdy enough to hold up even against the Root: They're tough and intimidating while providing the bare-minimum level of dexterity for,a steady grip on your weapon of choice. Just don't plan on completing any tasks that require subtlety when wearing these.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Leto_Mark_II_Gloves`,
		location: { world: "Ward 13", dungeon: "World Drop" },
	},
	{
		category: "GLOVES",
		name: "Nanoplated Hands",
		internalSlug: "Armor_Gloves_Warden_C",
		imageUrl: "items/armors/nanoplatedhands.png",
		id: "1asxjo",
		dlc: "DLC3",
		set: "Nanoplated Set",
		modifiers: {
			armor: 7.4,
			weight: 3,
			resistBleed: 1,
			resistFire: 1,
			resistShock: 0,
			resistToxin: 0,
			resistBlight: 1,
		},
		wikiUrl: `https://remnant2.wiki.gg/Nanoplated_Hands`,
		location: { world: `N'Erud`, dungeon: [`Withered Necropolis`] },
		description: [
			`These lithe vambraces taper to tightly fitted gloves made of thin, malleable metal sourced from passing asteroids caught in N'Erud's gravitational pull.`,
			`“Axion Cadyar was a high-ranking member of House Al'Maruun and the eldest of the Convocation. It was only his demoralizing temper that kept him from becoming Seeker Primis. Though he and I engaged in countless debates, he could never shake his distrust of my artificial design.”`,
		],
	},
	{
		category: "GLOVES",
		name: "Nightstalker Gloves",
		internalSlug: "Armor_Gloves_Hunter_C",
		imageUrl: "items/armors/nightstalkergloves.png",
		id: "xl7dm2",
		dlc: "BASE",
		set: "Nightstalker Set",
		modifiers: {
			armor: 10.9,
			weight: 4.5,
			resistBleed: 2,
			resistFire: 1,
			resistShock: 1,
			resistBlight: 7,
			resistToxin: 0,
		},
		description: [
			`A single glove and arm wrap are all you need or want for arm protection. The only defense you can truly rely on is a loaded gun and a clear shot.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Nightstalker_Gloves`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "GLOVES",
		name: "Phetyr Crushers",
		internalSlug: "Armor_Gloves_NerudWarrior_C",
		imageUrl: "items/armors/phetyrcrushers.png",
		id: "i21ob4",
		dlc: "DLC3",
		set: "Phetyr Set",
		modifiers: {
			armor: 17.4,
			weight: 8.6,
			resistBleed: 2,
			resistFire: 2,
			resistShock: 1,
			resistToxin: 2,
			resistBlight: 1,
		},
		description: [""],
		wikiUrl: `https://remnant2.wiki.gg/Phetyr_Crushers`,
		location: { world: `N'Erud`, dungeon: [`Logistics Bridge`] },
	},
	{
		category: "GLOVES",
		name: "Radiant Bracers",
		internalSlug: "Armor_Gloves_Radiant_C",
		imageUrl: "items/armors/radiantbracers.png",
		id: "rjm014",
		dlc: "BASE",
		set: "Radiant Set",
		modifiers: {
			armor: 17.2,
			weight: 7.9,
			resistBleed: 1,
			resistFire: 1,
			resistShock: 2,
			resistBlight: 0,
			resistToxin: 0,
		},
		description: [
			`The fingerless leather gloves provide exceptional dexterity to the wearer, while the vambraces are adorned with a blue gem that gives the wearer access to the volatile energy stored within.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Radiant_Bracers`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "GLOVES",
		name: "Realmwalker Gloves",
		internalSlug: "Armor_Gloves_Explorer_C",
		imageUrl: "items/armors/realmwalkergloves.png",
		id: "47ak51",
		dlc: "BASE",
		set: "Realmwalker Set",
		modifiers: {
			armor: 7.2,
			weight: 2.9,
			resistBleed: 0,
			resistFire: 1,
			resistShock: 1,
			resistBlight: 1,
			resistToxin: 0,
		},
		description: [
			`Ford's gloves were designed for warmth and dexterity. The soldier who wore these was not swinging blades or forging metal. He was pulling triggers and throwing grenades`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Realmwalker_Gloves`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "GLOVES",
		name: "Red Widow Bracers",
		internalSlug: "Armor_Gloves_RedWidow_C",
		imageUrl: "items/armors/redwidowbracers.png",
		id: "7uqilq",
		dlc: "BASE",
		set: "Red Widow Set",
		modifiers: {
			armor: 13.1,
			weight: 5.6,
			resistBleed: 2,
			resistFire: 0,
			resistShock: 0,
			resistBlight: 2,
			resistToxin: 0,
		},
		description: [
			`These gloves are light, with openings for the fingers to allow the wearer maximum dexterity - a neccesary consideration for traditional Pan weaponry.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Red_Widow_Bracers`,
		location: { world: "Yaesha", dungeon: ["The Lament"] },
	},
	{
		category: "GLOVES",
		name: "Space Worker Gloves",
		internalSlug: "Armor_Gloves_SpaceWorker_C",
		imageUrl: "items/armors/spaceworkergloves.png",
		id: "6clcha",
		dlc: "BASE",
		set: "Space Worker Set",
		modifiers: {
			armor: 7,
			weight: 2.8,
			resistBleed: 1,
			resistFire: 1,
			resistShock: 1,
			resistBlight: 0,
			resistToxin: 1,
		},
		description: [
			`Electromagnets are worked into the grip, activating automatically when the hand closes. Seems like a useful feature, so long as everything/you work with is metal.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Space_Worker_Gloves`,
		location: { world: `N'Erud`, dungeon: [`Void Vessel Facility`] },
	},
	{
		category: "GLOVES",
		name: "Survivor Gloves",
		internalSlug: "Armor_Gloves_Survivor_C",
		imageUrl: "items/armors/survivorgloves.png",
		id: "ws5jah",
		dlc: "BASE",
		set: "Survivor Set",
		modifiers: {
			armor: 9.8,
			weight: 4,
			resistBleed: 1,
			resistFire: 1,
			resistShock: 1,
			resistBlight: 1,
			resistToxin: 1,
		},
		description: [
			`Made of durable leather and include a makeshift wrist guard consisting of a metal plate secured by leather straps, providing addition protection to the wearer's wrists without sacrificing dexterity.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Survivor_Gloves`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "GLOVES",
		name: "Technician Gloves",
		internalSlug: "Armor_Gloves_Engineer_C",
		imageUrl: "items/armors/techniciangloves.png",
		id: "11wear",
		dlc: "BASE",
		set: "Technician Set",
		modifiers: {
			armor: 16.6,
			weight: 7.5,
			resistBleed: 0,
			resistFire: 1,
			resistShock: 2,
			resistBlight: 0,
			resistToxin: 1,
		},
		description: [
			`A tingle runs across your palm within these gloves - like bugs skittering over your hand.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Technician_Gloves`,
		location: {
			world: `N'Erud`,
			dungeon: [`The Eon Vault`, `Timeless Horizon`],
		},
	},
	{
		category: "GLOVES",
		name: "Trainer Bracer",
		internalSlug: "Armor_Gloves_Handler_C",
		imageUrl: "items/armors/trainerbracer.png",
		id: "tgd095",
		dlc: "BASE",
		set: "Trainer Set",
		modifiers: {
			armor: 10.1,
			weight: 4.1,
			resistBleed: 2,
			resistFire: 0,
			resistShock: 3,
			resistBlight: 1,
			resistToxin: 1,
		},
		description: [
			`An arm guard that also functions as a bite sleeve for training on the subtle nuances of when and who to bite.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Trainer_Bracer`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "GLOVES",
		name: "Void Wraps",
		internalSlug: "Armor_Gloves_Void_C",
		imageUrl: "items/armors/voidwraps.png",
		id: "a527cd",
		dlc: "BASE",
		set: "Void Set",
		modifiers: {
			armor: 15.9,
			weight: 7.1,
			resistBleed: 0,
			resistFire: 1,
			resistShock: 1,
			resistBlight: 0,
			resistToxin: 1,
		},
		description: [
			`Crafted from an enigmatic substance that resembles hardened bone in appearance. These gloves are a powerful tool in the hands of those who would wield the void, drawing energy from the emptiness between worlds to unleash devastating attacks. But with great power comes great cost, and those who dare to wear these gloves must be prepared to pay the price.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Void_Wraps`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "HELM",
		name: "Welding Goggles",
		internalSlug: "Armor_Head_WeldingGoggles_C",
		imageUrl: "items/armors/weldinggoggles.png",
		id: "81jid6",
		dlc: "BASE",
		modifiers: {
			armor: 9,
			weight: 4,
			resistBleed: 0,
			resistFire: 3,
			resistShock: 0,
			resistToxin: 0,
			resistBlight: 0,
		},
		description: [
			`Straightforward and utilitarian, these goggles feature a sturdy strap that holds the thick lenses firmly in place, shielding the wearer's eyes from sparks, intense light, and flying debris.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Welding_Goggles`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "GLOVES",
		name: "Zealot's Wraps",
		internalSlug: "Armor_Gloves_Ritualist_C",
		dlc: "DLC1",
		imageUrl: "items/armors/zealotswraps.png",
		id: "irt51q",
		set: "Zealot's Set",
		modifiers: {
			armor: 11.3,
			weight: 4.7,
			resistBleed: 1,
			resistFire: 0,
			resistShock: 0,
			resistBlight: 1,
			resistToxin: 1,
		},
		description: [
			`Long gloves fit like a vice around your arms, the pressure quickening your pulse and increasing your awareness. Your hands are well protected with the exception of a few exposed fingertips, intentionally left unguarded in case a given ritual requires quick access to fresh blood.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Zealot's_Wraps`,
		location: { world: "Losomn", dungeon: ["Forlorn Coast"] },
	},
];

export { ARMORS, type Remnant2ArmorItem };
