import type { BaseRemnant2Item } from "#/games/remnant2/types/local-item";

type Remnant2FusionItem = BaseRemnant2Item & {
	index?: number;
	fragmentIds?: string[];
};

const FUSIONS: Remnant2FusionItem[] = [
	{
		category: "FUSION",
		name: "Athletic",
		fragmentIds: ["c0hy5s", "kp0rff"],
		imageUrl: "items/fusions/yellow-blue.png",
		id: "62uunk",
		dlc: "BASE",
		description: ["Movement Speed + Evade Speed"],
		wikiUrl: `https://remnant2.wiki.gg/List_of_fusions`,
		location: undefined,
	},
	{
		category: "FUSION",
		name: "Capacitor",
		fragmentIds: ["6tby7d", "3ngjzr"],
		imageUrl: "items/fusions/red-yellow.png",
		id: "ck7ms0",
		dlc: "BASE",
		description: ["Firearm Charge Time + Heat Generation"],
		wikiUrl: `https://remnant2.wiki.gg/List_of_fusions`,
		location: undefined,
	},
	{
		category: "FUSION",
		name: "Cleric",
		fragmentIds: ["y52c32", "omefk5"],
		imageUrl: "items/fusions/blue-yellow.png",
		id: "zr00kz",
		dlc: "BASE",
		description: ["Healing Effectiveness + Use Speed"],
		wikiUrl: `https://remnant2.wiki.gg/List_of_fusions`,
		location: undefined,
	},
	{
		category: "FUSION",
		name: "Flash",
		fragmentIds: ["51y6ih", "omefk5"],
		imageUrl: "items/fusions/yellow-yellow.png",
		id: "6ybk0o",
		dlc: "BASE",
		description: ["Casting Speed + Use Speed"],
		wikiUrl: `https://remnant2.wiki.gg/List_of_fusions`,
		location: undefined,
	},
	{
		category: "FUSION",
		name: "Grip",
		fragmentIds: ["oiiiu2", "h9e463"],
		imageUrl: "items/fusions/yellow-yellow.png",
		id: "d6hgip",
		dlc: "BASE",
		description: ["Weapon Spread + Firearm Swap Speed"],
		wikiUrl: `https://remnant2.wiki.gg/List_of_fusions`,
		location: undefined,
	},
	{
		category: "FUSION",
		name: "Gunfighter",
		fragmentIds: ["w8ruyt", "5wuf2j"],
		imageUrl: "items/fusions/red-yellow.png",
		id: "w962ng",
		dlc: "BASE",
		description: ["Ranged Fire Rate + Reload Speed"],
		wikiUrl: `https://remnant2.wiki.gg/List_of_fusions`,
		location: undefined,
	},
	{
		category: "FUSION",
		name: "Hulk",
		fragmentIds: ["j87rzn", "qqmdc0"],
		imageUrl: "items/fusions/blue-blue.png",
		id: "t2myua",
		dlc: "BASE",
		description: ["Health Bonus + Stamina Bonus"],
		modifiers: {
			healthPercentage: 0.1,
			staminaPercentage: 0.15,
		},
		wikiUrl: `https://remnant2.wiki.gg/List_of_fusions`,
		location: undefined,
	},
	{
		category: "FUSION",
		name: "Longevity",
		fragmentIds: ["c2t1p6", "7c8uka"],
		imageUrl: "items/fusions/yellow-yellow.png",
		id: "ynxc2m",
		dlc: "BASE",
		description: ["Mod Duration + Skill Duration"],
		wikiUrl: `https://remnant2.wiki.gg/List_of_fusions`,
		location: undefined,
	},
	{
		category: "FUSION",
		name: "Mage",
		fragmentIds: ["zkr2us", "pk57hf"],
		imageUrl: "items/fusions/red-yellow.png",
		id: "m1h26g",
		dlc: "BASE",
		description: ["Mod Damage + Mod Generation"],
		wikiUrl: `https://remnant2.wiki.gg/List_of_fusions`,
		location: undefined,
	},
	{
		category: "FUSION",
		name: "Meta",
		fragmentIds: ["oszz4u", "0qxyqo"],
		imageUrl: "items/fusions/red-red.png",
		id: "g58d3p",
		dlc: "BASE",
		description: ["Weakspot Damage + Critical Damage"],
		wikiUrl: `https://remnant2.wiki.gg/List_of_fusions`,
		location: undefined,
	},
	{
		category: "FUSION",
		name: "Munitions",
		fragmentIds: ["dp184t", "3aqiq5"],
		imageUrl: "items/fusions/red-yellow.png",
		id: "wi41h6",
		dlc: "BASE",
		description: ["Ranged Critical Chance + Ammo Reserves"],
		wikiUrl: `https://remnant2.wiki.gg/List_of_fusions`,
		location: undefined,
	},
	{
		category: "FUSION",
		name: "Pirate",
		fragmentIds: ["wlnbc1", "yu7d57"],
		imageUrl: "items/fusions/red-red.png",
		id: "n5mt1u",
		dlc: "BASE",
		description: ["Ranged Damage + Melee Damage"],
		wikiUrl: `https://remnant2.wiki.gg/List_of_fusions`,
		location: undefined,
	},
	{
		category: "FUSION",
		name: "Protected",
		fragmentIds: ["alp59n", "h6sk9p"],
		imageUrl: "items/fusions/blue-blue.png",
		id: "x59m5x",
		dlc: "BASE",
		description: ["Shield Amount + Base Armor"],
		modifiers: {
			armor: 15,
		},
		wikiUrl: `https://remnant2.wiki.gg/List_of_fusions`,
		location: undefined,
	},
	{
		category: "FUSION",
		name: "Pugilist",
		fragmentIds: ["t8jgpe", "4gbcn0"],
		imageUrl: "items/fusions/red-blue.png",
		id: "jeu7d6",
		dlc: "BASE",
		description: ["Melee Speed + Base Stamina"],
		modifiers: {
			stamina: 15,
		},
		wikiUrl: `https://remnant2.wiki.gg/List_of_fusions`,
		location: undefined,
	},
	{
		category: "FUSION",
		name: "Revitalize",
		fragmentIds: ["bzxa98", "2bqp66"],
		imageUrl: "items/fusions/blue-yellow.png",
		id: "3fenef",
		dlc: "BASE",
		description: ["Health Regeneration + Skill Cooldown"],
		wikiUrl: `https://remnant2.wiki.gg/List_of_fusions`,
		location: undefined,
	},
	{
		category: "FUSION",
		name: "Rogue",
		fragmentIds: ["m16fn9", "kp0rff"],
		imageUrl: "items/fusions/red-blue.png",
		id: "q0ox6z",
		dlc: "BASE",
		description: ["Melee Critical Chance + Evade Speed"],
		wikiUrl: `https://remnant2.wiki.gg/List_of_fusions`,
		location: undefined,
	},
	{
		category: "FUSION",
		name: "Sapper",
		fragmentIds: ["73x1rg", "1pddio"],
		imageUrl: "items/fusions/red-blue.png",
		id: "ht9ok0",
		dlc: "BASE",
		description: ["Explosive Damage + Damage Reduction"],
		wikiUrl: `https://remnant2.wiki.gg/List_of_fusions`,
		location: undefined,
	},
	{
		category: "FUSION",
		name: "Selfless",
		fragmentIds: ["0jam5w", "y52c32"],
		imageUrl: "items/fusions/blue-blue.png",
		id: "0dm69i",
		dlc: "BASE",
		description: ["Revive Speed + Healing Effectiveness"],
		wikiUrl: `https://remnant2.wiki.gg/List_of_fusions`,
		location: undefined,
	},
	{
		category: "FUSION",
		name: "Sniper",
		fragmentIds: ["wlnbc1", "i5kymp"],
		imageUrl: "items/fusions/red-yellow.png",
		id: "26o0ys",
		dlc: "BASE",
		description: ["Ranged Damage + Weapon Ideal Range"],
		wikiUrl: `https://remnant2.wiki.gg/List_of_fusions`,
		location: undefined,
	},
	{
		category: "FUSION",
		name: "Tank",
		fragmentIds: ["1pddio", "7u1bma"],
		imageUrl: "items/fusions/blue-blue.png",
		id: "3b43hx",
		dlc: "BASE",
		description: ["Damage Reduction + Armor Bonus"],
		modifiers: {
			armorPercentage: 0.1,
		},
		wikiUrl: `https://remnant2.wiki.gg/List_of_fusions`,
		location: undefined,
	},
	{
		category: "FUSION",
		name: "Threshold",
		fragmentIds: ["j87rzn", "aci99s"],
		imageUrl: "items/fusions/blue-blue.png",
		id: "6p6ssk",
		dlc: "BASE",
		description: ["Health Bonus + Grey Health Conversion"],
		modifiers: {
			healthPercentage: 0.1,
		},
		wikiUrl: `https://remnant2.wiki.gg/List_of_fusions`,
		location: undefined,
	},
	{
		category: "FUSION",
		name: "Warrior",
		fragmentIds: ["yu7d57", "t8jgpe"],
		imageUrl: "items/fusions/red-red.png",
		id: "oxap1d",
		dlc: "BASE",
		description: ["Melee Damage + Melee Speed"],
		wikiUrl: `https://remnant2.wiki.gg/List_of_fusions`,
		location: undefined,
	},
	{
		category: "FUSION",
		name: "Wizard",
		fragmentIds: ["iyp5r3", "o5sd30"],
		imageUrl: "items/fusions/red-red.png",
		id: "g9u4i3",
		dlc: "BASE",
		description: ["Mod Critical Chance + Skill Critical Chance"],
		wikiUrl: `https://remnant2.wiki.gg/List_of_fusions`,
		location: undefined,
	},
];

export { FUSIONS, type Remnant2FusionItem };
