import type { BaseRemnant2Item } from "#/games/remnant2/types/local-item";

type Remnant2RelicFragmentItem = BaseRemnant2Item & {
	color?: "red" | "blue" | "yellow" | "legendary";
	index?: number;
};

const RELIC_FRAGMENTS: Remnant2RelicFragmentItem[] = [
	{
		category: "RELIC_FRAGMENT",
		name: "Ammo Reserves",
		imageUrl: "items/relicfragments/ammo-reserves-on.png",
		internalSlug: "RelicFragment_AmmoReserves_C",
		color: "yellow",
		id: "3aqiq5",
		dlc: "BASE",
		searchableTags: ["Ammo Reserves"],
		description: ["Increases Ammo Reserves by 25%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Allegiance",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_Allegiance_C",
		color: "legendary",
		id: "8vcd8r",
		dlc: "BASE",
		searchableTags: [],
		description: ["Cannot Kill or Be Killed by Friendly Fire Damage."],
		wikiUrl: "https://remnant2.wiki.gg/Allegiance",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Altruistic",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_Altruistic_C",
		color: "legendary",
		id: "4d6v1v",
		dlc: "BASE",
		searchableTags: [],
		description: ["Lifesteal applies 50% of Stolen Health to Allies."],
		wikiUrl: "https://remnant2.wiki.gg/Altruistic",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Armor Bonus",
		imageUrl: "items/relicfragments/generic-blue-on.png",
		internalSlug: "RelicFragment_ArmorEffectiveness_C",
		color: "blue",
		id: "7u1bma",
		dlc: "BASE",
		searchableTags: ["Damage Reduction"],
		description: ["Increases Armor Effectiveness by 10%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
		modifiers: { armorPercentage: 0.1 },
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Artful Dodger",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_ArtfulDodger_C",
		color: "legendary",
		id: "1n8874",
		dlc: "BASE",
		searchableTags: [],
		description: [
			"All Dodges trigger Perfect Dodge Mechanics. Cooldown of 3 seconds.",
		],
		wikiUrl: "https://remnant2.wiki.gg/Artful_Dodger",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Base Armor",
		imageUrl: "items/relicfragments/base-armor-on.png",
		internalSlug: "RelicFragment_ArmorFlat_C",
		color: "blue",
		id: "h6sk9p",
		dlc: "BASE",
		searchableTags: ["Armor Increase"],
		description: ["Increases Armor by 15."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
		modifiers: { armor: 15 },
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Base Health",
		imageUrl: "items/relicfragments/base-health-on.png",
		internalSlug: "RelicFragment_HealthFlat_C",
		color: "blue",
		id: "6qz6t1",
		dlc: "BASE",
		searchableTags: ["Health"],
		description: ["Increases Health by 10."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
		modifiers: { health: 10 },
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Base Stamina",
		imageUrl: "items/relicfragments/base-stamina-on.png",
		internalSlug: "RelicFragment_StaminaFlat_C",
		color: "blue",
		id: "4gbcn0",
		dlc: "BASE",
		searchableTags: ["Stamina"],
		description: ["Increases Stamina by 15."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		modifiers: { stamina: 15 },
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Bodyguard",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_Bodyguard_C",
		color: "legendary",
		id: "1d6g98",
		dlc: "BASE",
		searchableTags: [],
		description: ["Cannot be One-Shot while at Max Health Capacity."],
		wikiUrl: "https://remnant2.wiki.gg/Bodyguard",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Boundless Energy",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_BoundlessEnergy_C",
		color: "legendary",
		id: "6myusj",
		dlc: "BASE",
		searchableTags: [],
		description: [`Grants Infinite N'Erudian Energy.`],
		wikiUrl: "https://remnant2.wiki.gg/Boundless_Energy",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Brutality",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_Brutality_C",
		color: "legendary",
		id: "s6fkpj",
		dlc: "BASE",
		searchableTags: [],
		description: ["All Damage Dealt and Received is increased by 100%."],
		wikiUrl: "https://remnant2.wiki.gg/Brutality",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Cast Speed",
		imageUrl: "items/relicfragments/casting-speed-on.png",
		internalSlug: "RelicFragment_CastSpeed_C",
		color: "yellow",
		id: "51y6ih",
		dlc: "BASE",
		searchableTags: ["Mod Cast Speed", "Skill Cast Speed"],
		description: ["Increases Mod & Skill Cast Speed by 20%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Consumable Duration",
		imageUrl: "items/relicfragments/consumable-duration-on.png",
		internalSlug: "RelicFragment_CriticalDamage_C",
		color: "yellow",
		id: "xqklut",
		dlc: "BASE",
		description: ["Increases Consumable Duration by 20%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Critical Damage",
		imageUrl: "items/relicfragments/critical-damage-on.png",
		internalSlug: "RelicFragment_CriticalDamage_C",
		color: "red",
		id: "0qxyqo",
		dlc: "BASE",
		searchableTags: ["Critical Damage"],
		description: ["Increases Critical Damage by 10%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Critical Situation",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_CriticalSituation_C",
		color: "legendary",
		id: "p66eoa",
		dlc: "BASE",
		searchableTags: [],
		description: ["Grants 35% All Critical Chance within LIGHT Weight Class."],
		wikiUrl: "https://remnant2.wiki.gg/Critical_Situation",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Damage Reduction",
		imageUrl: "items/relicfragments/damage-reduction-on.png",
		internalSlug: "RelicFragment_DamageReduction_C",
		color: "blue",
		id: "1pddio",
		dlc: "BASE",
		searchableTags: ["Damage Reduction"],
		description: ["Increases Damage Reduction by 5%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Dark Omen",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_DarkOmen_C",
		color: "legendary",
		id: "w26htj",
		dlc: "BASE",
		searchableTags: [],
		description: [
			"Dodges become Mist Step, costing Health instead of Stamina.",
		],
		wikiUrl: "https://remnant2.wiki.gg/Dark_Omen",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Defense Measures",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_DefensiveMeasures_C",
		color: "legendary",
		id: "y7d3aq",
		dlc: "BASE",
		searchableTags: [],
		description: ["Increases SHIELD Maximum by 100%."],
		wikiUrl: "https://remnant2.wiki.gg/Defense_Measures",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Evade Distance",
		imageUrl: "items/relicfragments/evade-distance-on.png",
		internalSlug: "RelicFragment_EvadeDistance_C",
		color: "blue",
		id: "qmc3th",
		dlc: "BASE",
		searchableTags: [],
		description: ["Increases Evade Distance by 10%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Evade Speed",
		imageUrl: "items/relicfragments/evade-speed-on.png",
		internalSlug: "RelicFragment_EvadeSpeed_C",
		color: "blue",
		id: "kp0rff",
		dlc: "BASE",
		searchableTags: [],
		description: ["Increases Evade Speed by 10%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Exhausted",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_Exhausted_C",
		color: "legendary",
		id: "z2gbi3",
		dlc: "BASE",
		searchableTags: [],
		description: ["Increases Heat Decay Rate by 250%."],
		wikiUrl: "https://remnant2.wiki.gg/Exhausted",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Explosive Damage",
		imageUrl: "items/relicfragments/explosive-damage-on.png",
		internalSlug: "RelicFragment_ExplosiveDamage_C",
		color: "red",
		id: "73x1rg",
		dlc: "BASE",
		searchableTags: [],
		description: ["Increases Explosive Damage by 10%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Firearm Charge Time",
		imageUrl: "items/relicfragments/firearm-charge-time-on.png",
		internalSlug: "RelicFragment_RangedChargeSpeed_C",
		color: "red",
		id: "6tby7d",
		dlc: "BASE",
		searchableTags: [],
		description: ["Decreases Ranged Weapon Charge Time by 10%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Firearm Swap Speed",
		imageUrl: "items/relicfragments/weapon-swap-on.png",
		internalSlug: "RelicFragment_WeaponSwapSpeed_C",
		color: "yellow",
		id: "h9e463",
		dlc: "BASE",
		description: ["Increases Firearm Swap Speed by 20%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Fleet Footed",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_FleetFooted_C",
		color: "legendary",
		id: "ky7tqc",
		dlc: "BASE",
		searchableTags: [],
		description: ["Increases Dodge Weight Threshold by 100."],
		wikiUrl: "https://remnant2.wiki.gg/Fleet_Footed",
		modifiers: { weightThreshold: 100 },
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Full Hearted",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_FullHearted_C",
		color: "legendary",
		id: "kteco4",
		dlc: "BASE",
		searchableTags: [],
		description: ["Increases Relic Charges by 100%."],
		wikiUrl: "https://remnant2.wiki.gg/Full_Hearted",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Gigantic",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_Gigantic_C",
		color: "legendary",
		id: "ign3v0",
		dlc: "BASE",
		searchableTags: [],
		description: ["Grants 50 Health and Stamina."],
		wikiUrl: "https://remnant2.wiki.gg/Gigantic",
		modifiers: { health: 50, stamina: 50 },
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "God Tear",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_GodTear_C",
		color: "legendary",
		id: "o8of2m",
		dlc: "BASE",
		searchableTags: [],
		description: ["Reduces Cheat Death Cooldowns by 50%."],
		wikiUrl: "https://remnant2.wiki.gg/God_Tear",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Grey Health Conversion",
		imageUrl: "items/relicfragments/grey-health-conversion-on.png",
		internalSlug: "RelicFragment_GreyHealthRate_C",
		color: "blue",
		id: "aci99s",
		dlc: "BASE",
		searchableTags: ["Grey Health"],
		description: ["Increases Grey Health Conversion Rate by 15%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Healing Effectiveness",
		imageUrl: "items/relicfragments/healing-effectiveness-on.png",
		internalSlug: "RelicFragment_HealingEffectiveness_C",
		color: "blue",
		id: "y52c32",
		dlc: "BASE",
		searchableTags: ["Healing Effectiveness"],
		description: ["Increases Healing Effectiveness by 15%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Health Bonus",
		imageUrl: "items/relicfragments/health-bonus-on.png",
		internalSlug: "RelicFragment_Health_C",
		color: "blue",
		id: "j87rzn",
		dlc: "BASE",
		searchableTags: ["Health"],
		description: ["Increases Health by 10%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		modifiers: { healthPercentage: 0.1 },
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Health Regeneration",
		imageUrl: "items/relicfragments/health-regeneration-on.png",
		internalSlug: "RelicFragment_HealthRegen_C",
		color: "blue",
		id: "bzxa98",
		dlc: "BASE",
		searchableTags: [],
		description: ["Increases Passive Health Regeneration by 1 HP/s."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Heat Generation",
		imageUrl: "items/relicfragments/heat-generation-on.png",
		internalSlug: "RelicFragment_HeatGenReduction_C",
		color: "yellow",
		id: "3ngjzr",
		dlc: "BASE",
		searchableTags: [],
		description: ["Reduces Heat Generation by 15%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Heavy Drinker",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_HeavyDrinker_C",
		color: "legendary",
		id: "fant12",
		dlc: "BASE",
		searchableTags: [],
		description: ["Increases Concoction Limit by 5."],
		wikiUrl: "https://remnant2.wiki.gg/Heavy_Drinker",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Hyperactive",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_Hyperactive_C",
		color: "legendary",
		id: "g1iifk",
		dlc: "BASE",
		searchableTags: [],
		description: [`Increases HASTE Effectiveness by 100%.`],
		wikiUrl: "https://remnant2.wiki.gg/Hyperactive",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Immovable",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_Immovable_C",
		color: "legendary",
		id: "fieh22",
		dlc: "BASE",
		searchableTags: [],
		description: ["Cannot be Staggered while BULWARK is active."],
		wikiUrl: "https://remnant2.wiki.gg/Immovable",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Impervious",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_Impervious_C",
		color: "legendary",
		id: "1mb66f",
		dlc: "BASE",
		searchableTags: [],
		description: ["Reduces All Incoming Damage by 30%."],
		wikiUrl: "https://remnant2.wiki.gg/Impervious",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Insult to Injury",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_InsultToInjury_C",
		color: "legendary",
		id: "503nnp",
		dlc: "BASE",
		searchableTags: [],
		description: ["Applying any Negative Status Effect applies EXPOSED."],
		wikiUrl: "https://remnant2.wiki.gg/Insult_to_Injury",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Jack of All Trades",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_JackOfAllTrades_C",
		color: "legendary",
		id: "tfmy98",
		dlc: "BASE",
		searchableTags: [],
		description: ["Increases All Damage by 40%."],
		wikiUrl: "https://remnant2.wiki.gg/Jack_of_All_Trades",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Luck of the Devil",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_LuckOfTheDevil_C",
		color: "legendary",
		id: "vma9nj",
		dlc: "BASE",
		searchableTags: [],
		description: ["Gain EXTREME luck."],
		wikiUrl: "https://remnant2.wiki.gg/Luck_of_the_Devil",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Master Killer",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_MasterKiller_C",
		color: "legendary",
		id: "b3jspj",
		dlc: "BASE",
		searchableTags: [],
		description: ["Multiplies Weakspot Damage by 1.35x."],
		wikiUrl: "https://remnant2.wiki.gg/Master_Killer",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Melee Critical Chance",
		internalSlug: "RelicFragment_MeleeCritChance_C",
		imageUrl: "items/relicfragments/melee-critical-chance-on.png",
		color: "red",
		id: "m16fn9",
		dlc: "BASE",
		searchableTags: ["Critical Chance", "Melee Critical Chance"],
		description: ["Increases Melee Critical Chance by 7.5%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Melee Damage",
		imageUrl: "items/relicfragments/melee-damage-on.png",
		internalSlug: "RelicFragment_MeleeDamage_C",
		color: "red",
		id: "yu7d57",
		dlc: "BASE",
		searchableTags: ["Melee Damage"],
		description: ["Increases Melee Damage by 10%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Melee Speed",
		imageUrl: "items/relicfragments/melee-speed-on.png",
		internalSlug: "RelicFragment_MeleeAttackSpeed_C",
		color: "red",
		id: "t8jgpe",
		dlc: "BASE",
		searchableTags: ["Melee Attack Speed"],
		description: ["Increases Total Melee Attack Speed by 10%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Mod Critical Chance",
		imageUrl: "items/relicfragments/mod-critical-chance-on.png",
		internalSlug: "RelicFragment_ModCritChance_C",
		color: "red",
		id: "iyp5r3",
		dlc: "BASE",
		searchableTags: [],
		description: ["Increases Mod Critical Chance by 7.5%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Mod Damage",
		imageUrl: "items/relicfragments/mod-damage-on.png",
		internalSlug: "RelicFragment_ModDamage_C",
		color: "red",
		id: "zkr2us",
		dlc: "BASE",
		searchableTags: ["Mod Damage"],
		description: ["Increases Mod Damage by 10%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Mod Duration",
		imageUrl: "items/relicfragments/mod-duration-on.png",
		internalSlug: "RelicFragment_ModDuration_C",
		color: "yellow",
		id: "c2t1p6",
		dlc: "BASE",
		searchableTags: ["Mod Duration"],
		description: ["Increases Mod Duration by 15%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Mod Generation",
		imageUrl: "items/relicfragments/mod-generation-on.png",
		internalSlug: "RelicFragment_ModGeneration_C",
		color: "yellow",
		id: "pk57hf",
		dlc: "BASE",
		searchableTags: [],
		description: ["Increases Mod Generation by 10%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Movement Speed",
		imageUrl: "items/relicfragments/movement-speed-on.png",
		internalSlug: "RelicFragment_MovementSpeed_C",
		color: "yellow",
		id: "c0hy5s",
		dlc: "BASE",
		searchableTags: ["Movement Speed"],
		description: ["Increases Movement Speed by 10%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		modifiers: { staminaPercentage: 0.15 },
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Outlaw",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_Outlaw_C",
		color: "legendary",
		id: "jf6i48",
		dlc: "BASE",
		searchableTags: [],
		description: ["Reloading Reloads both Weapons."],
		wikiUrl: "https://remnant2.wiki.gg/Outlaw",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Overpowered",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_Overpowered_C",
		color: "legendary",
		id: "s6n7x3",
		dlc: "BASE",
		searchableTags: [],
		description: ["Increases Mod Generation by 50%."],
		wikiUrl: "https://remnant2.wiki.gg/Overpowered",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Peak Conditioning",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_PeakConditioning_C",
		color: "legendary",
		id: "34g3gm",
		dlc: "BASE",
		searchableTags: [],
		description: ["Grants Infinite Stamina."],
		wikiUrl: "https://remnant2.wiki.gg/Peak_Conditioning",
		location: undefined,
		modifiers: { stamina: 99999 },
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Physician",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_Physician_C",
		color: "legendary",
		id: "qn0gc0",
		dlc: "BASE",
		searchableTags: [],
		description: ["Increases Healing Effectiveness by 100%."],
		wikiUrl: "https://remnant2.wiki.gg/Physician",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Power Fantasy",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_PowerFantasy_C",
		color: "legendary",
		id: "udn5v4",
		dlc: "BASE",
		searchableTags: [],
		description: [
			"Increases Explosive Critical Chance and Critical Damage by 30%.",
		],
		wikiUrl: "https://remnant2.wiki.gg/Power_Fantasy",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Power Trip",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_PowerTrip_C",
		color: "legendary",
		id: "o3w3u5",
		dlc: "BASE",
		searchableTags: [],
		description: ["Doubles Mod Charges."],
		wikiUrl: "https://remnant2.wiki.gg/Power_Trip",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Prime Time",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_PrimeTime_C",
		color: "legendary",
		id: "8140zw",
		dlc: "BASE",
		searchableTags: [],
		description: ["Enables Prime Perk for Secondary Archetype."],
		wikiUrl: "https://remnant2.wiki.gg/Prime_Time",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Projectile Speed",
		imageUrl: "items/relicfragments/projectile-speed-on.png",
		internalSlug: "RelicFragment_ProjectileSpeed_C",
		color: "yellow",
		id: "xut36z",
		dlc: "BASE",
		searchableTags: ["Projectile Speed"],
		description: ["Increases Projectile Speed by 15%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Ranged Critical Chance",
		internalSlug: "RelicFragment_RangedCritChance_C",
		imageUrl: "items/relicfragments/ranged-critical-chance-on.png",
		color: "red",
		id: "dp184t",
		dlc: "BASE",
		searchableTags: ["Critical Chance"],
		description: ["Increases Ranged Critical Chance by 7.5%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Ranged Damage",
		imageUrl: "items/relicfragments/ranged-damage-on.png",
		internalSlug: "RelicFragment_RangedDamage_C",
		color: "red",
		id: "wlnbc1",
		dlc: "BASE",
		searchableTags: ["Ranged Damage"],
		description: ["Increases Ranged Damage by 10%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Ranged Fire Rate",
		imageUrl: "items/relicfragments/ranged-fire-rate-on.png",
		internalSlug: "RelicFragment_RangedFireRate_C",
		color: "red",
		id: "w8ruyt",
		dlc: "BASE",
		searchableTags: ["Fire Rate"],
		description: ["Increases Ranged Fire Rate by 10%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Reload Speed",
		imageUrl: "items/relicfragments/reload-speed-on.png",
		internalSlug: "RelicFragment_ReloadSpeed_C",
		color: "yellow",
		id: "5wuf2j",
		dlc: "BASE",
		searchableTags: ["Reload Speed"],
		description: ["Increases Reload Speed by 10%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Reverberation",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_Reverberation_C",
		color: "legendary",
		id: "qx4bbk",
		dlc: "BASE",
		searchableTags: [],
		description: ["Increases Stamina Recovery by 200 per second."],
		wikiUrl: "https://remnant2.wiki.gg/Reverberation",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Revive Speed",
		imageUrl: "items/relicfragments/revive-speed-on.png",
		internalSlug: "RelicFragment_ReviveSpeed_C",
		color: "blue",
		id: "0jam5w",
		dlc: "BASE",
		description: ["Increases Revive Speed by 20%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Sadistic",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_Sadistic_C",
		color: "legendary",
		id: "6onvd3",
		dlc: "BASE",
		searchableTags: [],
		description: [
			"Status Effect Damage has a 50% chance to deal 2x more damage per tick.",
		],
		wikiUrl: "https://remnant2.wiki.gg/Sadistic",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Sharpshooter",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_Sharpshooter_C",
		color: "legendary",
		id: "7mw049",
		dlc: "BASE",
		searchableTags: [],
		description: ["Increases Ranged Damage by 60%."],
		wikiUrl: "https://remnant2.wiki.gg/Sharpshooter",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Shield Amount",
		imageUrl: "items/relicfragments/shield-amount-on.png",
		internalSlug: "RelicFragment_ShieldEffectiveness_C",
		color: "blue",
		id: "alp59n",
		dlc: "BASE",
		description: ["Increases Shield Effectiveness by 10%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Shield Duration",
		imageUrl: "items/relicfragments/shield-duration-on.png",
		internalSlug: "RelicFragment_ShieldDuration_C",
		color: "blue",
		id: "f5mi7x",
		dlc: "BASE",
		searchableTags: [],
		description: ["Increases Shield Duration by 10%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Size Matters",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_SizeMatters_C",
		color: "legendary",
		id: "n0r6bv",
		dlc: "BASE",
		searchableTags: [],
		description: ["Doubles Magazine Size for non Single Shot Weapons."],
		wikiUrl: "https://remnant2.wiki.gg/Size_Matters",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Skill Cooldown",
		imageUrl: "items/relicfragments/skill-cooldown-on.png",
		internalSlug: "RelicFragment_SkillCooldown_C",
		color: "yellow",
		id: "2bqp66",
		dlc: "BASE",
		searchableTags: ["Reduce Skill Cooldown"],
		description: ["Reduces Skill Cooldowns by 10%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Skill Critical Chance",
		imageUrl: "items/relicfragments/skill-critical-chance-on.png",
		internalSlug: "RelicFragment_SkillCritChance_C",
		color: "red",
		id: "o5sd30",
		dlc: "BASE",
		searchableTags: [],
		description: ["Increases Skill Critical Chance by 7.5%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Skill Damage",
		imageUrl: "items/relicfragments/skill-damage-on.png",
		internalSlug: "RelicFragment_SkillDamage_C",
		color: "red",
		id: "fuhykd",
		dlc: "BASE",
		searchableTags: ["Skill Damage"],
		description: ["Increases Skill Damage by 10%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Skill Duration",
		imageUrl: "items/relicfragments/skill-duration-on.png",
		internalSlug: "RelicFragment_SkillDuration_C",
		color: "yellow",
		id: "7c8uka",
		dlc: "BASE",
		searchableTags: ["Skill Duration"],
		description: ["Increases Skill Duration by 15%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Soulmate",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_Soulmate_C",
		color: "legendary",
		id: "zo1rt6",
		dlc: "BASE",
		searchableTags: [],
		description: ["Increases Summon Limit by 1."],
		wikiUrl: "https://remnant2.wiki.gg/Soulmate",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Spectrum",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_Spectrum_C",
		color: "legendary",
		id: "wbu60g",
		dlc: "BASE",
		searchableTags: [],
		description: ["Gain Bonuses Based on Color of Fragments within the Prism."],
		wikiUrl: "https://remnant2.wiki.gg/Spectrum",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Speed Demon",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_SpeedDemon_C",
		color: "legendary",
		id: "f80hyz",
		dlc: "BASE",
		searchableTags: [],
		description: ["Grants Maximum Movement Speed Bonuses."],
		wikiUrl: "https://remnant2.wiki.gg/Speed_Demon",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Stamina Bonus",
		imageUrl: "items/relicfragments/stamina-bonus-on.png",
		internalSlug: "RelicFragment_Stamina_C",
		color: "blue",
		id: "qqmdc0",
		dlc: "BASE",
		searchableTags: ["Stamina"],
		description: ["Increases Stamina by 15%."],
		modifiers: { staminaPercentage: 0.15 },
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Status Damage",
		imageUrl: "items/relicfragments/status-damage-on.png",
		internalSlug: "RelicFragment_StatusDamage_C",
		color: "red",
		id: "32immt",
		dlc: "BASE",
		searchableTags: [],
		description: ["Increases Status Effect Damage by 15%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Steel Plating",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_SteelPlating_C",
		color: "legendary",
		id: "nqq5t5",
		dlc: "BASE",
		searchableTags: [],
		description: ["Increases Armor by 150."],
		wikiUrl: "https://remnant2.wiki.gg/Steel_Plating",
		location: undefined,
		modifiers: { armor: 150 },
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Traitor",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_Traitor_C",
		color: "legendary",
		id: "cya6q1",
		dlc: "BASE",
		searchableTags: [],
		description: ["Maxes out Core Traits."],
		wikiUrl: "https://remnant2.wiki.gg/Traitor",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Unbreakable",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_Unbreakable_C",
		color: "legendary",
		id: "0xj2m6",
		dlc: "BASE",
		searchableTags: [],
		description: [`Grey Health cannot be removed.`],
		wikiUrl: "https://remnant2.wiki.gg/Unbreakable",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Unbridled",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_Unbridled_C",
		color: "legendary",
		id: "p3trdc",
		dlc: "BASE",
		searchableTags: [],
		description: ["Reduces all Skill Cooldowns by Half."],
		wikiUrl: "https://remnant2.wiki.gg/Unbridled",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Use Speed",
		imageUrl: "items/relicfragments/use-speed-on.png",
		internalSlug: "RelicFragment_ConsumableSpeed_C",
		color: "yellow",
		id: "omefk5",
		dlc: "BASE",
		searchableTags: ["Relic Use Speed"],
		description: ["Increases Relic and Consumable Use Speed by 15%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Vaccinated",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_Vaccinated_C",
		color: "legendary",
		id: "8jm01f",
		dlc: "BASE",
		searchableTags: [],
		description: ["Immune to Negative Status Effects."],
		wikiUrl: "https://remnant2.wiki.gg/Vaccinated",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Weakspot Damage",
		imageUrl: "items/relicfragments/weakspot-damage-on.png",
		internalSlug: "RelicFragment_WeakspotDamage_C",
		color: "red",
		id: "oszz4u",
		dlc: "BASE",
		searchableTags: ["Weakspot Damage"],
		description: ["Increases Weakspot Damage by 15%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Weapon Ideal Range",
		imageUrl: "items/relicfragments/weapon-ideal-range-on.png",
		internalSlug: "RelicFragment_IdealRange_C",
		color: "yellow",
		id: "i5kymp",
		dlc: "BASE",
		searchableTags: [],
		description: ["Increases Ideal Weapon Range by 2m."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Weapon Spread",
		imageUrl: "items/relicfragments/weapon-spread-on.png",
		internalSlug: "RelicFragment_WeaponSpread_C",
		color: "yellow",
		id: "oiiiu2",
		dlc: "BASE",
		searchableTags: ["Spread"],
		description: ["Reduces Weapon Spread by 15%."],
		wikiUrl: "https://remnant2.wiki.gg/Relic_Fragment",
		location: undefined,
	},
	{
		category: "RELIC_FRAGMENT",
		name: "Wrecking Ball",
		imageUrl: "items/prisms/legendaryprism.png",
		internalSlug: "RelicFragment_WreckingBall_C",
		color: "legendary",
		id: "t2ro08",
		dlc: "BASE",
		searchableTags: [],
		description: ["Increases Explosive Critical Chance by 100%."],
		wikiUrl: "https://remnant2.wiki.gg/Wrecking_Ball",
		location: undefined,
	},
];

export { RELIC_FRAGMENTS, type Remnant2RelicFragmentItem };
