import type { BaseRemnant2Item } from "#/games/remnant2/types/local-item";

type Remnant2RelicItem = BaseRemnant2Item & {};

const RELICS: Remnant2RelicItem[] = [
	{
		category: "RELIC",
		name: "Bloodless Heart",
		imageUrl: "items/relics/bloodlessheart.png",
		internalSlug: "Relic_Consumable_BloodlessHeart_C",
		id: "LQho3X",
		dlc: "DLC2",
		description: [
			"Innate 50% Use Speed bonus. On use, grants a SHIELD that prevents nearly all damage for 3s.",
			"Cannot prevent certain death mechanics.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Bloodless_Heart`,
		location: { world: "Yaesha", dungeon: [`Goddess's Rest`] },
	},
	{
		category: "RELIC",
		name: "Blooming Heart",
		imageUrl: "items/relics/bloomingheart.png",
		internalSlug: "Relic_Consumable_BloomingHeart_C",
		id: "soyjpp",
		dlc: "BASE",
		description: [
			"On use, heals for 35% of Max Health over 5s. Spawns 3 Healing Orbs which grant 35% of caster's Max Health over 5s. Orbs last 20s. Recasting removes previous Orbs.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Blooming_Heart`,
		location: {
			world: "Yaesha",
			biome: "Floating Forests",
			injectable: "Tower",
		},
	},
	{
		category: "RELIC",
		name: "Broken Heart",
		imageUrl: "items/relics/brokenheart.png",
		internalSlug: "Relic_Consumable_BrokenHeart_C",
		dlc: "DLC1",
		id: "m71h9m",
		description: [
			"Innate 50% Use Speed Bonus. Passively grants or removes 2 Health per sec until Health reaches 50%. On use, sets Health to 50%.",
			"Not affected by other healing items or perks.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Broken_Heart`,
		location: { world: "Losomn", dungeon: "Quest" },
	},
	{
		category: "RELIC",
		name: "Constrained Heart",
		imageUrl: "items/relics/constrainedheart.png",
		internalSlug: "Relic_Consumable_ConstrainedHeart_C",
		id: "rlezcg",
		dlc: "BASE",
		description: [
			"On use, regenerates 20 Health per second for 5s and grants 2 Stacks of BULWARK while heal is active.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Constrained_Heart`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "RELIC",
		name: "Crystal Heart",
		imageUrl: "items/relics/crystalheart.png",
		internalSlug: "Relic_Consumable_CrystalHeart_C",
		id: "67tfbl",
		dlc: "BASE",
		description: [
			"On use, regenerates 100% of Max Health over 10s. Movement Speed is reduced by 50%, and incoming damage is reduced by 25%. Lasts 10s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Crystal_Heart`,
		location: { world: `N'Erud`, dungeon: [`The Dark Conduit`] },
	},
	{
		category: "RELIC",
		name: "Decayed Heart",
		imageUrl: "items/relics/decayedheart.png",
		internalSlug: "Relic_Consumable_DecayedHeart_C",
		id: "vhjydw",
		dlc: "BASE",
		description: [
			"On use, causes the next 3 instances of enemy damage taken to trigger 40 Health regeneration over 3s. Lasts 30s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Decayed_Heart`,
		location: { world: "Root Earth", dungeon: ["Corrupted Harbor"] },
	},
	{
		category: "RELIC",
		name: "Diverting Heart",
		imageUrl: "items/relics/divertingheart.png",
		internalSlug: "Relic_Consumable_DivertingHeart_C",
		id: "96f26y",
		dlc: "BASE",
		searchableTags: ["Reduce Skill Cooldown"],
		description: [
			"Does not provide standard healing. On use, reduces Skill Cooldowns by 1s per second. Lasts 15s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Diverting_Heart`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "RELIC",
		name: "Dragon Heart",
		imageUrl: "items/relics/dragonheart.png",
		internalSlug: "Consumable_DragonHeart_C",
		id: "f96bom",
		dlc: "BASE",
		description: ["On use, Heals 70 Health over 0.5s."],
		wikiUrl: `https://remnant2.wiki.gg/Dragon_Heart`,
		location: { world: "Ward 13", dungeon: "Quest" },
	},
	{
		category: "RELIC",
		name: "Enlarged Heart",
		imageUrl: "items/relics/enlargedheart.png",
		internalSlug: "Relic_Consumable_EnlargedHeart_C",
		id: "4y2xb3",
		dlc: "BASE",
		description: [
			"Innate Double Use Speed. On use, heals 140 Health over 0.5s. Relic capacity is halved.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Enlarged_Heart`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "RELIC",
		name: "Gossamer Heart",
		imageUrl: "items/relics/gossamerheart.png",
		internalSlug: "Relic_Consumable_GossamerHeart_C",
		id: "4yjd4c",
		dlc: "DLC3",
		description: [
			"Innate base Evade Window Frames increased by 1. On use, increases Evade Window Bonus Frames by an additional 2 for 15s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Gossamer_Heart`,
		location: {
			world: `N'Erud`,
			biome: `Towers of N'Erud`,
			injectable: `Crop Lab`,
		},
	},
	{
		category: "RELIC",
		name: "Latent Heart",
		imageUrl: "items/relics/latentheart.png",
		internalSlug: "Relic_Consumable_LatentHeart_C",
		id: "x66ure",
		dlc: "DLC3",
		description: [
			"On use, absorbs 95% incoming damage for 5s. Upon expiring, the absorbed damage is then applied to the wearer at a rate of 10% of the total absorbed damage per second for 10s.",
			"Damage reduction does not apply to SHIELD.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Latent_Heart`,
		location: { world: `N'Erud`, dungeon: ["Agronomy Sector"] },
	},
	{
		category: "RELIC",
		name: "Lifeless Heart",
		imageUrl: "items/relics/lifelessheart.png",
		internalSlug: "Relic_Consumable_LifelessHeart_C",
		id: "k1de0f",
		dlc: "BASE",
		description: [
			"Innate 50% Use Speed Bonus, but provides no healing. Relic capacity is doubled.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Lifeless_Heart`,
		location: { world: "Yaesha", dungeon: "Quest" },
	},
	{
		category: "RELIC",
		name: "Paper Heart",
		imageUrl: "items/relics/paperheart.png",
		internalSlug: "Relic_Consumable_PaperHeart_C",
		dlc: "DLC1",
		id: "n9fm2r",
		description: [
			"On use, heals 100% Max Health and grants 10 Stacks of PAPER HEALTH. After 10s, each Stack is converted to 10% Grey Health.",
			"Dealing 75 Base Damage from any source removes 1 Stack of PAPER HEALTH.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Paper_Heart`,
		location: { world: "Losomn", dungeon: ["Chamber of the Faithless"] },
	},
	{
		category: "RELIC",
		name: "Profane Heart",
		imageUrl: "items/relics/profaneheart.png",
		internalSlug: "Relic_Consumable_profaneHeart_C",
		id: "4v7sf4",
		dlc: "DLC2",
		searchableTags: ["Lifesteal"],
		description: [
			"Innate 3% Lifesteal bonus. On use, increases all Lifesteal Efficacy by 50% for 15s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Profane_Heart`,
		location: { world: "Yaesha", dungeon: ["Infested Abyss"] },
	},
	{
		category: "RELIC",
		name: "Pulsing Heart",
		imageUrl: "items/relics/pulsingheart.png",
		internalSlug: "Relic_Consumable_PulsingHeart_C",
		id: "xfwkzp",
		dlc: "BASE",
		description: [
			"On use, pulses every 3s, healing allies within 7m for 20 Health over 0.5s per pulse. Lasts 15s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Pulsing_Heart`,
		location: { world: "Yaesha", dungeon: [`Endaira's End`] },
	},
	{
		category: "RELIC",
		name: "Quilted Heart",
		imageUrl: "items/relics/quiltedheart.png",
		internalSlug: "Relic_Consumable_QuiltedHeart_C",
		id: "4v7sf3",
		dlc: "BASE",
		description: [
			"Does not provide standard healing. On use, negates Stamina Drain and cause Evades to heal for 15 Health over 0.25s. Lasts 20s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Quilted_Heart`,
		location: {
			world: "Losomn",
			biome: "Streets of Losomn",
			injectable: `Oracle's Refuge`,
		},
	},
	{
		category: "RELIC",
		name: "Reprocessed Heart",
		imageUrl: "items/relics/reprocessedheart.png",
		internalSlug: "Relic_Consumable_ReprocessedHeart_C",
		id: "06pxhy",
		dlc: "BASE",
		searchableTags: ["Grey Health"],
		description: [
			"On use, converts 5 Health as Grey Health to 40 Mod Power per second for 25s for both weapons. Cannot die from conversion.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Reprocessed_Heart`,
		location: { world: "Labyrinth", dungeon: ["Entangled Gauntlet"] },
	},
	{
		category: "RELIC",
		name: "Resonating Heart",
		imageUrl: "items/relics/resonatingheart.png",
		internalSlug: "Relic_Consumable_ResonatingHeart_C",
		id: "6ruk95",
		dlc: "BASE",
		description: [
			"On use, regenerates 50% of Max Health over 5s. When heal ends, any overhealed Health to self is Doubled and awarded over the next 20s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Resonating_Heart`,
		location: { world: "Root Earth", dungeon: ["Ashen Wasteland"] },
	},
	{
		category: "RELIC",
		name: "Ripened Heart",
		imageUrl: "items/relics/ripenedheart.png",
		internalSlug: "Relic_Consumable_RipenedHeart_C",
		id: "5azu1p",
		dlc: "BASE",
		description: [
			"On use, heals 35 Health over 0.5s and an additional 70 over 5s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Ripened_Heart`,
		location: { world: "Ward 13", dungeon: "Quest" },
	},
	{
		category: "RELIC",
		name: "Runed Heart",
		imageUrl: "items/relics/runedheart.png",
		internalSlug: "Relic_Consumable_RunedHeart_C",
		id: "yb7v4c",
		dlc: "BASE",
		description: [
			"On use, increases Health Regeneration by 5 and generates 500 Mod Power over 10s for both weapons.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Runed_Heart`,
		location: { world: "Labyrinth", dungeon: ["Entangled Gauntlet"] },
	},
	{
		category: "RELIC",
		name: "Salvaged Heart",
		imageUrl: "items/relics/salvagedheart.png",
		internalSlug: "Relic_Consumable_SalvagedHeart_C",
		id: "2rnl2d",
		dlc: "BASE",
		description: [
			"Innate 25% Use Speed bonus. On use, heals 30 Health over 0.25s and restores 300% of current Grey Health.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Salvaged_Heart`,
		location: {
			world: `N'Erud`,
			dungeon: "Vendor",
		},
	},
	{
		category: "RELIC",
		name: "Shielded Heart",
		imageUrl: "items/relics/shieldedheart.png",
		internalSlug: "Relic_Consumable_ShieldedHeart_C",
		id: "sge99k",
		dlc: "BASE",
		description: [
			"On use, grants a SHIELD for 100% of Max Health. Lasts 20s or until SHIELD is removed by damage.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Shielded_Heart`,
		location: { world: `N'Erud`, dungeon: ["Tower of the Unseen"] },
	},
	{
		category: "RELIC",
		name: "Siphon Heart",
		imageUrl: "items/relics/siphonheart.png",
		internalSlug: "Relic_Consumable_SiphonHeart_C",
		id: "3awf5n",
		dlc: "BASE",
		description: [
			"On use, grants 10% of base damage dealt as Lifesteal for 15s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Siphon_Heart`,
		location: {
			world: `N'Erud`,
			dungeon: ["Ascension Spire"],
		},
	},
	{
		category: "RELIC",
		name: "Tormented Heart",
		imageUrl: "items/relics/tormentedheart.png",
		internalSlug: "Relic_Consumable_TormentedHeart_C",
		id: "rtmajx",
		dlc: "BASE",
		description: [
			"Innate 25% Relic Use Speed bonus. On use, deals 150 - 450 Explosive Damage to enemies within 5m and Lifesteals 20% of damage dealt.",
		],
		communityTags: [`AOE/Aura`, `Explosive Damage`],
		wikiUrl: `https://remnant2.wiki.gg/Tormented_Heart`,
		location: { world: "Losomn", dungeon: ["Tormented Asylum"] },
	},
	{
		category: "RELIC",
		name: "Tranquil Heart",
		imageUrl: "items/relics/tranquilheart.png",
		internalSlug: "Relic_Consumable_TranquilHeart_C",
		id: "thgp2z",
		dlc: "BASE",
		description: [
			"Passively grants 2 Health Regeneration per second. On use, doubles All Health Regeneration for 15s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Tranquil_Heart`,
		location: { world: "Losomn", dungeon: [`Nimue's Retreat`] },
	},
	{
		category: "RELIC",
		name: "Unsullied Heart",
		imageUrl: "items/relics/unsulliedheart.png",
		internalSlug: "Relic_Consumable_UnsulliedHeart_C",
		id: "pj4ika",
		dlc: "BASE",
		description: ["On use, heals for 100% of Current Health over 0.5s."],
		wikiUrl: `https://remnant2.wiki.gg/Unsullied_Heart`,
		location: { world: "Losomn", dungeon: ["Beatific Palace"] },
	},
	{
		category: "RELIC",
		name: "Void Heart",
		imageUrl: "items/relics/voidheart.png",
		internalSlug: "Relic_Consumable_VoidHeart_C",
		id: "weaetb",
		dlc: "BASE",
		description: [
			"On use, reduces incoming damage by 50% for 4s. When buff ends, heals 100% of missing Health over 0.75s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Void_Heart`,
		location: { world: `N'Erud`, dungeon: ["Alepsis-Taura"] },
	},
];

export { RELICS, type Remnant2RelicItem };
