import type { Enemy } from '@/games/remnant2/data/enemies/types/enemy';

const aberrationEnemies = [
  {
    slug: 'ug7BZq',
    name: 'Abyssal Dreadnought',
    dlc: 'BASE',
    category: 'aberration',
    imageUrl: '/enemies/aberration/abyssal_dreadnought.jpg',
    wikiLink: undefined,
    modifiers: {
      resistBleed: 15,
      resistFire: -15,
      resistShock: -15,
      resistAcid: 15,
    },
  },
  {
    slug: 'bp8Z4T',
    name: 'Arcanum Diviner',
    category: 'aberration',
    imageUrl: '/enemies/aberration/arcanum_diviner.jpg',
    wikiLink: undefined,
    modifiers: {
      resistFire: 10,
      resistAcid: 10,
    },
  },
  {
    slug: '8gjtp0',
    name: 'Astral Harvester',
    category: 'aberration',
    imageUrl: '/enemies/aberration/astral_harvester.jpg',
    wikiLink: undefined,
    modifiers: undefined,
  },
  {
    name: 'Atrophy',
    category: 'aberration',
    imageUrl: '/enemies/aberration/atrophy1.jpg',
    location: { world: 'Yaesha', dungeon: [`Endaira's End`] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Atrophy',
    slug: 'a88PFZ',
    modifiers: undefined,
  },
  {
    name: 'Bane',
    category: 'aberration',
    imageUrl: '/enemies/aberration/bane.jpg',
    location: { world: 'Root Earth', dungeon: ['Twilight Vale'] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Bane',
    slug: '73DHnC',
    modifiers: undefined,
  },
  {
    name: 'Barghest the Vile',
    category: 'aberration',
    imageUrl: '/enemies/aberration/barghest_the_vile.jpg',
    location: { world: 'Losomn', dungeon: [`Harvester's Reach`] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Barghest+the+Vile',
    slug: '8Xi7nS',
    modifiers: undefined,
  },
  {
    slug: 'H2iB8c',
    name: 'Bastion',
    dlc: 'BASE',
    category: 'aberration',
    imageUrl: '/enemies/aberration/bastion.jpg',
    location: { world: 'Labyrinth', dungeon: ['Labyrinth'] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Bastion',
    modifiers: {
      resistBleed: 'immune',
      resistFire: 50,
      resistShock: 50,
      resistAcid: -25,
    },
    notes: 'Immune to Bleeding Status',
  },
  {
    slug: 'LZe8So',
    name: 'Befouled Larva',
    dlc: 'BASE',
    category: 'aberration',
    imageUrl: '/enemies/aberration/befouled_larva.jpg',
    wikiLink: undefined,
    modifiers: {
      resistBleed: 15,
      resistFire: -15,
      resistShock: -10,
      resistAcid: 10,
    },
  },
  {
    name: 'Blightspawn',
    category: 'aberration',
    imageUrl: '/enemies/aberration/blightspawn.jpg',
    wikiLink: 'https://remnant2.wiki.fextralife.com/Blightspawn',
    slug: '57h9GC',
    modifiers: undefined,
  },
  {
    slug: 'Z7cMX3',
    name: 'Charred Sentry',
    dlc: 'DLC2',
    category: 'aberration',
    imageUrl: '/enemies/aberration/charred_sentry.png',
    wikiLink: 'https://remnant2.wiki.fextralife.com/Charred+Sentry',
    modifiers: undefined,
  },
  {
    slug: 'htUq3D',
    name: 'C.E. Sigma',
    dlc: 'BASE',
    category: 'aberration',
    imageUrl: '/enemies/aberration/ce_sigma.jpg',
    wikiLink: undefined,
    modifiers: {
      resistBleed: 50,
      resistFire: 15,
      resistShock: -15,
      resistAcid: -15,
    },
    notes: 'htUq3D',
  },
  {
    slug: 'LTegp8',
    name: 'C.E. Theta',
    dlc: 'BASE',
    category: 'aberration',
    imageUrl: '/enemies/aberration/ce_theta.jpg',
    wikiLink: undefined,
    modifiers: {
      resistBleed: 50,
      resistFire: 15,
      resistShock: -15,
      resistAcid: -15,
    },
  },
  {
    slug: '8gdAsr',
    name: 'Cursed Wretch',
    dlc: 'DLC1',
    category: 'aberration',
    imageUrl: '/enemies/aberration/cursed_wretch.jpg',
    location: { world: 'Losomn', dungeon: ['The Forgotten Commune'] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Cursed+Wretch',
    modifiers: {
      resistBleed: 5,
      resistFire: 5,
      resistShock: 5,
      resistAcid: 5,
    },
  },
  {
    name: 'Deathsower',
    category: 'aberration',
    imageUrl: '/enemies/aberration/deathsower.jpg',
    wikiLink: undefined,
    slug: '9WF4mB',
    modifiers: undefined,
  },
  {
    slug: 'BfQM69',
    name: 'Deceitful Augur',
    category: 'aberration',
    imageUrl: '/enemies/aberration/deceitful_augur1.jpg',
    wikiLink: undefined,
    modifiers: undefined,
  },
  {
    name: 'Defiler',
    category: 'aberration',
    imageUrl: '/enemies/aberration/defiler.jpg',
    location: { world: 'Yaesha', dungeon: ['Forgotten Field'] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Defiler',
    slug: 'y55dZT',
    modifiers: undefined,
  },
  {
    slug: 'y38EwN',
    name: 'Desolate Stalker',
    category: 'aberration',
    imageUrl: '/enemies/aberration/desolate_stalker2.jpg',
    wikiLink: undefined,
    modifiers: undefined,
  },
  {
    slug: 'z4NeZM',
    name: 'Dire Fiend',
    dlc: 'DLC1',
    category: 'aberration',
    imageUrl: '/enemies/aberration/dire_fiend.jpg',
    wikiLink: 'https://remnant2.wiki.fextralife.com/Dire+Fiend',
    modifiers: {
      resistBleed: 5,
      resistFire: 5,
      resistShock: 5,
      resistAcid: 5,
    },
  },
  {
    slug: '2yRGvb',
    name: 'E.D. Alpha',
    dlc: 'BASE',
    category: 'aberration',
    imageUrl: '/enemies/aberration/ed_alpha.jpg',
    location: { world: `N'Erud`, dungeon: ['Tower of the Unseen'] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/E+D+Alpha',
    modifiers: {
      resistBleed: 50,
      resistFire: 5,
      resistShock: 5,
      resistAcid: 5,
    },
  },
  {
    slug: 'ddJow9',
    name: 'E.D.V.A.',
    dlc: 'BASE',
    category: 'aberration',
    imageUrl: '/enemies/aberration/edva.jpg',
    wikiLink: undefined,
    modifiers: {
      resistBleed: 50,
      resistFire: 10,
      resistShock: -15,
      resistAcid: -15,
    },
  },
  {
    slug: 'J3FKtE',
    name: 'Emberkeeper',
    category: 'aberration',
    imageUrl: '/enemies/aberration/emberkeeper.jpg',
    wikiLink: undefined,
    modifiers: undefined,
  },
  {
    slug: 'kJdrM9',
    name: 'Emberwatcher',
    category: 'aberration',
    imageUrl: '/enemies/aberration/emberwatcher.jpg',
    wikiLink: undefined,
    modifiers: undefined,
  },
  {
    name: 'Fester',
    category: 'aberration',
    imageUrl: '/enemies/aberration/fester.jpg',
    location: { world: 'Yaesha', dungeon: [`Endaira's End`] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Fester',
    slug: 'Qpta3f',
    modifiers: undefined,
  },
  {
    slug: 'WYX6tH',
    name: 'Fetid Corpse',
    dlc: 'BASE',
    category: 'aberration',
    imageUrl: '/enemies/aberration/fetid_corpse.jpg',
    location: { world: `N'Erud`, dungeon: ['Void Vessel Facility'] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Fetid+Corpse',
    modifiers: {
      resistBleed: 5,
      resistFire: 5,
      resistShock: 5,
      resistAcid: 5,
    },
  },
  {
    slug: '2zRPQ5',
    name: 'Firth: The Oathkeeper',
    dlc: 'BASE',
    category: 'aberration',
    imageUrl: '/enemies/aberration/firth_the_oathkeeper.jpg',
    location: { world: 'Losomn', dungeon: ['Malefic Palace'] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Firth:+The+Oathkeeper',
    modifiers: {
      resistBleed: 5,
      resistFire: 5,
      resistShock: 5,
      resistAcid: 5,
    },
  },
  {
    slug: 'E4dD3r',
    name: 'Flintblade Marauder',
    dlc: 'BASE',
    category: 'aberration',
    imageUrl: '/enemies/aberration/flintblade_marauder.jpg',
    wikiLink: undefined,
    modifiers: {
      resistBleed: -10,
    },
  },
  {
    slug: 'E5j8Ge',
    name: 'Flintblade Prowler',
    dlc: 'BASE',
    category: 'aberration',
    imageUrl: '/enemies/aberration/flintblade_prowler.jpg',
    wikiLink: undefined,
    modifiers: {
      resistBleed: -10,
    },
  },
  {
    slug: 'As28CR',
    name: 'Gorecarver',
    dlc: 'DLC1',
    category: 'aberration',
    imageUrl: '/enemies/aberration/gorecarver.jpg',
    location: { world: 'Losomn', dungeon: ['Derelict Lighthouse'] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Gorecarver',
    modifiers: {
      resistBleed: 5,
      resistFire: 5,
      resistShock: 5,
      resistAcid: 5,
    },
  },
  {
    name: 'Goreglut',
    category: 'aberration',
    imageUrl: '/enemies/aberration/goreglut.jpg',
    wikiLink: undefined,
    slug: 'ae4tUj',
    modifiers: undefined,
  },
  {
    slug: '2zr34P',
    name: 'Gorge',
    dlc: 'BASE',
    category: 'aberration',
    imageUrl: '/enemies/aberration/gorge.jpg',
    location: {
      world: 'Losomn',
      dungeon: [
        "Cotton's Kiln",
        "Butcher's Quarter",
        'Sunken Haunt',
        'Derelict Lighthouse',
      ],
    },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Gorge',
    modifiers: {
      resistBleed: 5,
      resistFire: 5,
      resistShock: 5,
      resistAcid: 5,
    },
  },
  {
    slug: 'Shoq7M',
    name: 'Grimshot',
    dlc: 'BASE',
    category: 'aberration',
    imageUrl: '/enemies/aberration/grimshot1.jpg',
    wikiLink: undefined,
    modifiers: {
      resistBleed: -10,
    },
  },
  {
    slug: 'tYVip3',
    name: 'Highborn Stalker',
    dlc: 'BASE',
    category: 'aberration',
    imageUrl: '/enemies/aberration/highborn_stalker.jpg',
    wikiLink: undefined,
    modifiers: undefined,
  },
  {
    slug: 'n1y0i0',
    name: 'Inverted Shambler',
    dlc: 'DLC3',
    category: 'aberration',
    imageUrl: '/enemies/aberration/inverted_shambler.jpg',
    wikiLink: undefined,
    modifiers: undefined,
  },
  {
    slug: 'cTNC5t',
    name: 'Lichwing',
    category: 'aberration',
    imageUrl: '/enemies/aberration/lichwing.jpg',
    wikiLink: undefined,
    modifiers: undefined,
  },
  {
    slug: '5QcPV9',
    name: 'Little Gorge',
    dlc: 'DLC1',
    category: 'aberration',
    imageUrl: '/enemies/aberration/little_gorge1.jpg',
    location: { world: 'Losomn', dungeon: ['Forlorn Coast'] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Little+Gorge',
    modifiers: undefined,
  },
  {
    slug: 'n9BjJm',
    name: 'Maleficient Glimmer',
    dlc: 'BASE',
    category: 'aberration',
    imageUrl: '/enemies/aberration/maleficient_glimmer1.jpg',
    wikiLink: undefined,
    modifiers: {
      resistBleed: 5,
      resistFire: 5,
      resistShock: 5,
      resistAcid: 5,
    },
  },
  {
    slug: 'fALQ5i',
    name: 'Malpractitioner',
    dlc: 'BASE',
    category: 'aberration',
    imageUrl: '/enemies/aberration/malpractitioner.jpg',
    wikiLink: undefined,
    modifiers: undefined,
  },
  {
    slug: '3GvXys',
    name: 'Mangled Atoner',
    dlc: 'DLC1',
    category: 'aberration',
    imageUrl: '/enemies/aberration/mangled_atoner.jpg',
    location: { world: 'Losomn', dungeon: ['Forlorn Coast'] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Mangled+Atoner',
    modifiers: {
      resistBleed: 5,
      resistFire: 10,
      resistShock: 5,
      resistAcid: 5,
    },
  },
  {
    name: 'Mantagora',
    category: 'aberration',
    imageUrl: '/enemies/aberration/mantagora.jpg',
    location: { world: 'Yaesha', dungeon: ['Imperial Gardens'] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Mantagora',
    slug: 'UdHg8g',
    modifiers: undefined,
  },
  {
    slug: 'ypiHR2',
    name: 'Mournshot',
    dlc: 'BASE',
    category: 'aberration',
    imageUrl: '/enemies/aberration/mournshot.jpg',
    wikiLink: undefined,
    modifiers: {
      resistBleed: -10,
    },
  },
  {
    slug: 'xqfa2m',
    name: 'Netherbound Specter',
    dlc: 'DLC3',
    category: 'aberration',
    imageUrl: '/enemies/aberration/netherbound_specter.jpg',
    wikiLink: undefined,
    modifiers: undefined,
  },
  {
    slug: 'Ls6k9S',
    name: 'Plaguebringer',
    category: 'aberration',
    imageUrl: '/enemies/aberration/plaguebringer.jpg',
    wikiLink: undefined,
    modifiers: undefined,
  },
  {
    name: 'Progeny',
    category: 'aberration',
    imageUrl: '/enemies/aberration/progeny.jpg',
    location: {
      world: `N'Erud`,
      dungeon: [
        'The Putrid Domain',
        'Vault of the Formless',
        'Void Vessel Facility',
        'The Hatchery',
        'The Dark Conduit',
      ],
    },
    wikiLink: 'https://remnant2.wiki.fextralife.com/The+Progeny',
    modifiers: undefined,
    slug: '2SpwWM',
  },
  {
    name: 'Protector of the Grove',
    category: 'aberration',
    imageUrl: '/enemies/aberration/protector_of_the_grove.png',
    wikiLink: undefined,
    modifiers: undefined,
    slug: 'Xqp2j6',
  },
  {
    name: 'Restless Spirit',
    category: 'aberration',
    imageUrl: '/enemies/aberration/restless_spirit.jpg',
    location: {
      world: `N'Erud`,
      dungeon: [
        `Astropath's Respite`,
        'Spectrum Nexus',
        'Terminus Station',
        'Tower of the Unseen',
      ],
    },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Restless+Spirit',
    modifiers: undefined,
    slug: '9sBqhu',
  },
  {
    slug: '2Af6cZ',
    name: 'Ripsaw',
    dlc: 'BASE',
    category: 'aberration',
    imageUrl: '/enemies/aberration/ripsaw.jpg',
    location: { world: 'Losomn', dungeon: ['Morrow Parish'] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Ripsaw',
    modifiers: {
      resistBleed: 5,
      resistFire: 5,
      resistShock: 5,
      resistAcid: 5,
    },
  },
  {
    name: 'Rot',
    category: 'aberration',
    imageUrl: '/enemies/aberration/rot.jpg',
    location: {
      world: 'Yaesha',
      dungeon: ['The Chimney', 'The Twisted Chantry'],
    },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Rot',
    modifiers: undefined,
    slug: 'DZB6Ut',
  },
  {
    name: 'Ruinweaver',
    category: 'aberration',
    imageUrl: '/enemies/aberration/ruinweaver.jpg',
    wikiLink: undefined,
    modifiers: undefined,
    slug: '4N9moU',
  },
  {
    slug: '4SkkwG',
    name: 'Scorchslinger',
    dlc: 'BASE',
    category: 'aberration',
    imageUrl: '/enemies/aberration/scorchslinger.jpg',
    wikiLink: undefined,
    modifiers: {
      resistBleed: -10,
      resistFire: 10,
    },
  },
  {
    slug: 'tRC6Br',
    name: 'Scorchstrike',
    dlc: 'BASE',
    category: 'aberration',
    imageUrl: '/enemies/aberration/scorchstrike.jpg',
    wikiLink: undefined,
    modifiers: {
      resistBleed: -10,
      resistFire: 10,
    },
  },
  {
    name: 'S.D. OA7',
    category: 'aberration',
    imageUrl: '/enemies/aberration/sd_0a7.jpg',
    location: { world: `N'Erud`, dungeon: [`Dormant N'Erudian Facility`] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/S.D.+0A7',
    modifiers: undefined,
    slug: 'YwbM9W',
  },
  {
    name: 'S.D. OC1',
    category: 'aberration',
    imageUrl: '/enemies/aberration/sd_oc1.jpg',
    wikiLink: undefined,
    modifiers: undefined,
    slug: 'xMYk33',
  },
  {
    name: 'S.D.R. 17',
    category: 'aberration',
    imageUrl: '/enemies/aberration/sdr17.jpg',
    wikiLink: undefined,
    slug: 'WFZqz9',
    modifiers: undefined,
  },
  {
    slug: '9jGvP5',
    name: 'Seer of the Veil',
    dlc: 'BASE',
    category: 'aberration',
    imageUrl: '/enemies/aberration/seer_of_the_veil.jpg',
    wikiLink: undefined,
    modifiers: {
      resistFire: 5,
      resistShock: -5,
      resistAcid: 10,
    },
    notes: 'Immune to Corroded Status',
  },
  {
    name: 'Severed Husk',
    category: 'aberration',
    imageUrl: '/enemies/aberration/severed_husk1.jpg',
    wikiLink: undefined,
    slug: 'wnJEw3',
    modifiers: undefined,
  },
  {
    slug: 'xL33mc',
    name: 'Shadowrend Warden',
    dlc: 'BASE',
    category: 'aberration',
    imageUrl: '/enemies/aberration/shadowrend_warden.jpg',
    wikiLink: undefined,
    modifiers: {
      resistBleed: 15,
      resistShock: -10,
    },
  },
  {
    slug: 'Tai6KG',
    name: 'Sliverwing Marauder',
    dlc: 'BASE',
    category: 'aberration',
    imageUrl: '/enemies/aberration/silverwing_marauder1.jpg',
    wikiLink: undefined,
    modifiers: undefined,
  },
  {
    slug: 'h8nNGJ',
    name: 'Sorrow Weaver',
    category: 'aberration',
    imageUrl: '/enemies/aberration/sorrow_weaver.jpg',
    wikiLink: undefined,
    modifiers: undefined,
  },
  {
    slug: 'a23o9m',
    name: 'Soulshrieker',
    category: 'aberration',
    imageUrl: '/enemies/aberration/soulshrieker.jpg',
    wikiLink: undefined,
    modifiers: undefined,
  },
  {
    name: 'Squalid Creeper',
    category: 'aberration',
    imageUrl: '/enemies/aberration/squalid_creeper1.jpg',
    wikiLink: undefined,
    modifiers: undefined,
    slug: 'cD4JJv',
  },
  {
    name: 'Stonewing Lurker',
    category: 'aberration',
    imageUrl: '/enemies/aberration/stonewing_lurker.png',
    wikiLink: undefined,
    modifiers: undefined,
    slug: 'Xwrqi2',
  },
  {
    name: 'Talonscythe',
    category: 'aberration',
    imageUrl: '/enemies/aberration/talonscythe.jpg',
    wikiLink: undefined,
    modifiers: undefined,
    slug: 'k5VEbQ',
  },
  {
    name: 'The Bloodless Heir',
    category: 'aberration',
    imageUrl: '/enemies/aberration/the_bloodless_heir.png',
    wikiLink: undefined,
    modifiers: undefined,
    slug: 'ox4KUX',
  },
  {
    slug: 'gCm5Ry',
    name: 'The Emissary',
    category: 'aberration',
    imageUrl: '/enemies/aberration/the_emissary.png',
    wikiLink: 'https://remnant2.wiki.fextralife.com/The+Emissary',
    modifiers: undefined,
  },
  {
    slug: '6o2WBN',
    name: 'The Executioner',
    dlc: 'BASE',
    category: 'aberration',
    imageUrl: '/enemies/aberration/executioner.jpg',
    wikiLink: 'https://remnant2.wiki.fextralife.com/The+Executioner',
    modifiers: {
      resistBleed: 5,
      resistFire: 5,
      resistShock: 5,
      resistAcid: 5,
    },
  },
  {
    slug: 'Cqqgq8',
    name: 'The Fractured',
    category: 'aberration',
    imageUrl: '/enemies/aberration/the_fractured.png',
    wikiLink: undefined,
    modifiers: undefined,
  },
  {
    slug: 'ir929t',
    name: 'The Prototype',
    category: 'aberration',
    imageUrl: '/enemies/aberration/the_prototype.jpg',
    wikiLink: undefined,
    modifiers: undefined,
  },
  {
    slug: '5xJq5F',
    name: 'Thunderpiercer',
    dlc: 'DLC1',
    category: 'aberration',
    imageUrl: '/enemies/aberration/thunderpiercer.jpg',
    location: { world: 'Losomn', dungeon: ['Derelict Lighthouse'] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Thunderpiercer',
    modifiers: {
      resistBleed: -10,
    },
  },
  {
    slug: 'SRrDo3',
    name: 'Tortured Flame',
    dlc: 'BASE',
    category: 'aberration',
    imageUrl: '/enemies/aberration/tortured_flame.jpg',
    wikiLink: undefined,
    modifiers: {
      resistBleed: -10,
      resistFire: 50,
      resistMelee: -35,
    },
    notes: 'Immune to Burning Status',
  },
  {
    slug: 'n668ip',
    name: 'V. Sentinel-23',
    category: 'aberration',
    dlc: 'DLC3',
    imageUrl: '/enemies/aberration/v_sentinel_23.jpg',
    wikiLink: undefined,
    modifiers: undefined,
  },
  {
    slug: '7KEpUS',
    name: 'Veilstalker',
    category: 'aberration',
    imageUrl: '/enemies/aberration/veilstalker.jpg',
    wikiLink: undefined,
    modifiers: undefined,
  },
  {
    slug: 'yyL5ZQ',
    name: 'Venomspine',
    category: 'aberration',
    imageUrl: '/enemies/aberration/venomspine.jpg',
    wikiLink: undefined,
    modifiers: undefined,
  },
  {
    slug: 'U7NzP4',
    name: 'Vilethorn Brawler',
    dlc: 'BASE',
    category: 'aberration',
    imageUrl: '/enemies/aberration/vilethorn_brawler.jpg',
    wikiLink: undefined,
    modifiers: {
      resistBleed: -10,
    },
  },
  {
    slug: 'xSk9aN',
    name: 'Vilethorn Scrapper',
    dlc: 'BASE',
    category: 'aberration',
    imageUrl: '/enemies/aberration/vilethorn_scrapper.jpg',
    wikiLink: undefined,
    modifiers: {
      resistBleed: -10,
    },
  },
  {
    slug: 'g0ji1x',
    name: 'Void Amalgamate',
    category: 'aberration',
    dlc: 'DLC3',
    imageUrl: '/enemies/aberration/void_amalgamate.jpg',
    wikiLink: undefined,
    modifiers: undefined,
  },
  {
    slug: 'Y5Ak63',
    name: 'Void Illusion',
    category: 'aberration',
    imageUrl: '/enemies/aberration/void_illusion.jpg',
    wikiLink: undefined,
    modifiers: undefined,
  },
  {
    name: 'Voidmaw',
    category: 'aberration',
    imageUrl: '/enemies/aberration/voidmaw.jpg',
    wikiLink: undefined,
    slug: '38urCi',
    modifiers: undefined,
  },
  {
    name: 'Voidmite',
    category: 'aberration',
    imageUrl: '/enemies/aberration/voidmite.jpg',
    wikiLink: undefined,
    slug: 'Ly4tNo',
    modifiers: undefined,
  },
  {
    name: 'W.D. 109',
    category: 'aberration',
    imageUrl: '/enemies/aberration/wd_109.jpg',
    location: {
      world: `N'Erud`,
      dungeon: [
        'Void Vessel Facility',
        'The Putrid Domain',
        'Vault of the Formless',
        'The Hatchery',
        'The Dark Conduit',
      ],
    },
    wikiLink: 'https://remnant2.wiki.fextralife.com/W+D+109',
    modifiers: undefined,
    slug: 'FH5Ttb',
  },
  {
    name: 'Weald Stalker and Gnarled Archer',
    category: 'aberration',
    imageUrl: '/enemies/aberration/weald_stalker_and_gnarled_archer.jpg',
    location: { world: 'Yaesha', dungeon: ['Floating Forests'] },
    wikiLink:
      'https://remnant2.wiki.fextralife.com/The+Weald+Stalker+and+The+Gnarled+Archer',
    modifiers: undefined,
    slug: 'os8Epw',
  },
  {
    name: 'Wither',
    category: 'aberration',
    imageUrl: '/enemies/aberration/wither.jpg',
    location: { world: 'Yaesha', dungeon: ['The Lament'] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Wither',
    modifiers: undefined,
    slug: 'o8tCDP',
  },
  {
    slug: '64wuWP',
    name: 'Wraithliege',
    dlc: 'DLC1',
    category: 'aberration',
    imageUrl: '/enemies/aberration/wraithliege.jpg',
    location: { world: 'Losomn', dungeon: ['Pathway of the Fallen'] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Wraithliege',
    modifiers: {
      resistBleed: 10,
      resistFire: -5,
      resistShock: -10,
    },
  },
  {
    name: 'Wretched Crawler',
    category: 'aberration',
    imageUrl: '/enemies/aberration/wretched_crawler.jpg',
    wikiLink: undefined,
    slug: 'Pa46sk',
    modifiers: undefined,
  },
] as const satisfies Enemy[];

export { aberrationEnemies };
