import type { Enemy } from '@/games/remnant2/data/enemies/types/enemy';

const bossEnemies = [
  {
    slug: 'Ws384W',
    name: 'Abomination',
    dlc: 'BASE',
    category: 'boss',
    location: { world: `N'Erud`, dungeon: [`The Putrid Domain`] },
    imageUrl: '/enemies/boss/abomination1.jpg',
    wikiLink: 'https://remnant2.wiki.fextralife.com/Abomination',
    modifiers: {
      resistBleed: 15,
      resistFire: -15,
      resistShock: -15,
      resistAcid: 15,
    },
  },
  {
    slug: 'fwh6yy',
    name: 'Amalgam Duo',
    dlc: 'DLC3',
    category: 'boss',
    imageUrl: '/enemies/boss/amalgams.jpg',
    wikiLink: undefined,
    modifiers: undefined,
  },
  {
    name: 'Befouled Altar',
    category: 'boss',
    imageUrl: '/enemies/boss/befouled_altar1.jpg',
    location: { world: 'Losomn', dungeon: ['The Forgotten Commune'] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Befouled+Altar',
    modifiers: undefined,
    slug: 'eN7hxx',
  },
  {
    name: 'Bloat King',
    category: 'boss',
    imageUrl: '/enemies/boss/bloat_king2.jpg',
    location: { world: 'Losomn', dungeon: ['The Great Sewers'] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Bloat+King',
    modifiers: undefined,
    slug: '3efMrV',
  },
  {
    name: 'Bruin, Blade of the King',
    category: 'boss',
    imageUrl: '/enemies/boss/bruin1.jpg',
    dlc: 'DLC1',
    location: { world: 'Losomn', dungeon: ['Glistering Cloister'] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Bruin,+Blade+of+the+King',
    modifiers: undefined,
    slug: 'wEexW3',
  },
  {
    name: 'Cancer',
    category: 'boss',
    imageUrl: '/enemies/boss/cancer.jpg',
    location: { world: 'Root Earth', dungeon: ['Ashen Wasteland'] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Cancer',
    modifiers: undefined,
    slug: 'jEFi2h',
  },
  {
    name: 'Cinderclad Forge',
    category: 'boss',
    dlc: 'DLC2',
    imageUrl: '/enemies/boss/cinderclad_monolith.png',
    wikiLink: 'https://remnant2.wiki.fextralife.com/Cinderclad+Monolith',
    modifiers: undefined,
    slug: 'dA3qvW',
  },
  {
    slug: '73ZNjb',
    name: 'Fae Knight Council',
    dlc: 'BASE',
    category: 'boss',
    imageUrl: '/enemies/boss/fae_knight_council.jpg',
    location: { world: 'Losomn', dungeon: ['Council Chamber'] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/The+Council',
    modifiers: {
      resistBleed: 15,
      resistFire: 15,
      resistAcid: -10,
    },
  },
  {
    slug: '7utUfw',
    name: 'Gwendil: The Unburnt',
    dlc: 'BASE',
    category: 'boss',
    location: { world: 'Losomn', dungeon: [`Cotton's Kiln`] },
    imageUrl: '/enemies/boss/gwendil1.jpg',
    wikiLink: 'https://remnant2.wiki.fextralife.com/Gwendil+The+Unburnt',
    modifiers: {
      resistBleed: -10,
      resistFire: 20,
      resistShock: -15,
    },
  },
  {
    name: `Kaeula's Shadow`,
    category: 'boss',
    imageUrl: '/enemies/boss/kaeula.jpg',
    location: { world: 'Yaesha', dungeon: [`Kaeula's Rest`] },
    wikiLink: `https://remnant2.wiki.fextralife.com/Kaeula's+Shadow`,
    modifiers: undefined,
    slug: 'E7LieX',
  },
  {
    name: 'Legion',
    category: 'boss',
    imageUrl: '/enemies/boss/legion.jpg',
    location: { world: 'Yaesha', dungeon: ['The Twisted Chantry'] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Legion',
    modifiers: undefined,
    slug: 'dtB8ac',
  },
  {
    slug: 'BvjT2V',
    name: 'Magister Dullain',
    dlc: 'BASE',
    category: 'boss',
    location: { world: 'Losomn', dungeon: ['Shattered Gallery'] },
    imageUrl: '/enemies/boss/magister_dullain.jpg',
    wikiLink: 'https://remnant2.wiki.fextralife.com/Magister+Dullain',
    modifiers: {
      resistFire: 15,
      resistShock: -10,
      resistAcid: 20,
    },
    notes: 'Immune to Corroded Status',
  },
  {
    name: 'Master of Feasts',
    category: 'boss',
    imageUrl: '/enemies/boss/master_of_feasts.jpg',
    location: { world: 'Losomn', dungeon: ['The Great Hall'] },
    wikiLink: undefined,
    modifiers: undefined,
    slug: 'GkCc3H',
  },
  {
    name: 'Mother Mind',
    category: 'boss',
    imageUrl: '/enemies/boss/mother_mind.jpg',
    location: { world: 'Yaesha', dungeon: ['The Nameless Nest'] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Mother+Mind',
    modifiers: undefined,
    slug: 'HTbt5M',
  },
  {
    name: `N'Erudian Reaper`,
    category: 'boss',
    imageUrl: '/enemies/boss/nerudian_reaper.jpg',
    slug: '7s3vyh',
    wikiLink: undefined,
    modifiers: undefined,
  },
  {
    slug: 'JBn8ob',
    name: 'Primogenitor',
    dlc: 'BASE',
    category: 'boss',
    imageUrl: '/enemies/boss/primogenitor.jpg',
    location: { world: `N'Erud`, dungeon: ['The Hatchery'] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Primogenitor',
    modifiers: undefined,
  },
  {
    name: 'Root Nexus (Normal)',
    category: 'boss',
    imageUrl: '/enemies/boss/root_nexus_normal.jpg',
    location: { world: 'Yaesha', dungeon: ['The Forgotten Grove'] },
    wikiLink: undefined,
    modifiers: undefined,
    slug: 'tuJA9Q',
  },
  {
    name: 'Root Nexus (Fields)',
    category: 'boss',
    imageUrl: '/enemies/boss/root_nexus_fields.jpg',
    location: { world: 'Yaesha', dungeon: ['Forgotten Field'] },
    wikiLink: undefined,
    modifiers: undefined,
    slug: '4Hg99W',
  },
  {
    name: 'Seed Contraption',
    category: 'boss',
    imageUrl: '/enemies/boss/seed_contraption.jpg',
    location: { world: 'Yaesha', dungeon: ['The Chimney'] },
    wikiLink: undefined,
    modifiers: undefined,
    slug: '2HnPj9',
  },
  {
    name: 'Shrewd',
    category: 'boss',
    imageUrl: '/enemies/boss/shrewd.jpg',
    location: { world: 'Yaesha', dungeon: ['The Expanding Glade'] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Shrewd',
    modifiers: undefined,
    slug: 'tfuw8P',
  },
  {
    slug: '3GZ6k2',
    name: 'The Astropath',
    dlc: 'BASE',
    category: 'boss',
    imageUrl: '/enemies/boss/astropath.jpg',
    location: { world: `N'Erud`, dungeon: [`Astropath's Respite`] },
    wikiLink: `https://remnant2.wiki.fextralife.com/The+Astropath`,
    modifiers: {
      resistBleed: 'immune',
    },
    notes: 'Immune to Bleeding Status',
  },
  {
    slug: 'wb22RX',
    name: "The Custodian's Eye",
    dlc: 'BASE',
    category: 'boss',
    location: { world: `N'Erud`, dungeon: ['Spectrum Nexus'] },
    imageUrl: '/enemies/boss/custodians_eye.jpg',
    wikiLink: `https://remnant2.wiki.fextralife.com/The+Custodian's+Eye`,
    modifiers: {
      resistBleed: 25,
      resistFire: 25,
      resistShock: -15,
      resistAcid: -15,
    },
  },
  {
    slug: 'm2vW25',
    name: 'The Huntress',
    dlc: 'BASE',
    category: 'boss',
    location: {
      world: 'Losomn',
      dungeon: ['Brocwithe Quarter', 'Forsaken Quarter', 'Ironborough'],
    },
    imageUrl: '/enemies/boss/huntress1.jpg',
    wikiLink: 'https://remnant2.wiki.fextralife.com/The+Huntress',
    modifiers: {
      resistBleed: -10,
      resistFire: -10,
      resistAcid: 15,
    },
  },
  {
    slug: '35mW3e',
    name: 'The Red Prince',
    dlc: 'BASE',
    category: 'boss',
    imageUrl: '/enemies/boss/red_prince.jpg',
    location: { world: 'Losomn', dungeon: ['Gilded Chambers'] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/The+Red+Prince',
    modifiers: {
      resistBleed: 10,
      resistFire: 20,
      resistShock: -10,
    },
  },
  {
    slug: 'P2tk7e',
    name: 'The Stonewarden',
    category: 'boss',
    dlc: 'DLC2',
    imageUrl: '/enemies/boss/the_stonewarden.png',
    wikiLink: 'https://remnant2.wiki.fextralife.com/The+Stonewarden',
    modifiers: undefined,
  },
  {
    slug: 'S8mXCm',
    name: 'The Sunken Witch',
    dlc: 'DLC1',
    category: 'boss',
    imageUrl: '/enemies/boss/sunken_witch.jpg',
    location: { world: 'Losomn', dungeon: ['Sunken Haunt'] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Sunken+Witch',
    modifiers: {
      resistFire: -5,
    },
  },
  {
    name: 'Venom',
    category: 'boss',
    imageUrl: '/enemies/boss/venom.jpg',
    location: { world: 'Root Earth', dungeon: ['Corrupted Harbor'] },
    wikiLink: 'https://remnant2.wiki.fextralife.com/Venom',
    modifiers: undefined,
    slug: '5GEAx3',
  },
] as const satisfies Enemy[];

export { bossEnemies };
