import type { Enemy } from "#/games/remnant2/enemy-data/types/enemy";

const enemies = [
	{
		slug: "aaL9vR",
		name: "Barnacle Base",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistFire: -10,
		},
	},
	{
		slug: "co6zUD",
		name: "Barnacle Crab",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistBleed: 15,
			resistFire: -15,
			resistShock: -10,
			resistAcid: 10,
		},
	},
	{
		slug: "mytK6V",
		name: "Barnacle Crab Hatchery",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistBleed: 15,
			resistFire: -15,
			resistShock: -10,
			resistAcid: 10,
		},
		notes: "Mini crabs (?)",
	},
	{
		slug: "u5zS7Z",
		name: "Barnacle Hatchery",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistBleed: 15,
			resistFire: -15,
			resistShock: -10,
			resistAcid: 10,
		},
	},
	{
		slug: "vz7HU3",
		name: "Dran Shotgunner",
		dlc: "DLC1",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistBleed: -10,
		},
	},
	{
		slug: "dvNi8s",
		name: "Engineering Drone",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistBleed: 50,
			resistFire: 10,
			resistShock: -10,
			resistAcid: -15,
		},
	},
	{
		slug: "3UVmMc",
		name: "Engineering Drone Small Drone",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistBleed: 50,
		},
	},
	{
		slug: "4GT9aa",
		name: "Engineering Drone Variant",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistBleed: 50,
			resistFire: 10,
			resistShock: -15,
			resistAcid: -15,
		},
	},
	{
		slug: "oYyyh7",
		name: "Fae Bone Harvester",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistBleed: 15,
			resistFire: -10,
			resistAcid: 10,
		},
	},
	{
		slug: "n7bhQF",
		name: "Fae Bone Harvester Albino",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistBleed: 15,
			resistFire: -10,
			resistAcid: 10,
		},
		notes: "Alchemist Event",
	},
	{
		slug: "XXeJ46",
		name: "Fae Executioner",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistBleed: 15,
			resistAcid: -5,
		},
	},
	{
		slug: "7TQzrc",
		name: "Fae Feastmaster",
		dlc: "DLC1",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistBleed: 15,
			resistAcid: -5,
		},
	},
	{
		slug: "g7iGJv",
		name: "Fae Impaler",
		dlc: "DLC1",
		category: "enemy",
		wikiLink: undefined,
		modifiers: undefined,
	},
	{
		slug: "T4GJyN",
		name: "Fae Iron Maiden",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistBleed: 10,
			resistShock: -10,
			resistAcid: -5,
		},
	},
	{
		slug: "8UMqKJ",
		name: "Fae Knight Golden",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistBleed: 10,
			resistFire: -5,
			resistShock: -10,
		},
	},
	{
		slug: "bjFqc6",
		name: "Fae Knight Shaed",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistBleed: 10,
			resistFire: -5,
			resistShock: -10,
		},
	},
	{
		slug: "UHva9T",
		name: "Fae Painless",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistBleed: 10,
		},
	},
	{
		slug: "J7xN9S",
		name: "Fae Penitent",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistFire: 10,
			resistAcid: -10,
		},
	},
	{
		slug: "8o9cRY",
		name: "Fae Penitent (Healer)",
		dlc: "DLC1",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistAcid: -10,
		},
	},
	{
		slug: "t8W3qT",
		name: "Fae Royal Archer",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistShock: -10,
		},
	},
	{
		slug: "5gpmSx",
		name: "Fae Soldier",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: undefined,
	},
	{
		slug: "EHHn7v",
		name: "Fae Soldier Armored",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistBleed: 15,
			resistShock: -10,
		},
	},
	{
		slug: "N48baF",
		name: "Forgotten",
		dlc: "DLC1",
		category: "enemy",
		wikiLink: undefined,
		modifiers: undefined,
	},
	{
		slug: "g5VkSC",
		name: "Forgotten (Purple)",
		dlc: "DLC1",
		category: "enemy",
		wikiLink: undefined,
		modifiers: undefined,
	},
	{
		slug: "S4jqVf",
		name: "Granadier Dran",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistBleed: -10,
			resistFire: 10,
		},
	},
	{
		slug: "z4yZY4",
		name: "Hollowed",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistFire: -5,
			resistShock: -5,
			resistMelee: -15,
		},
	},
	{
		slug: "6A4c7x",
		name: "Hollowed Psyker",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistBleed: 10,
			resistFire: -10,
			resistShock: -10,
			resistAcid: 10,
		},
	},
	{
		slug: "hB86F8",
		name: "Labyrinth Creature",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistBleed: "immune",
			resistFire: 50,
			resistShock: 50,
			resistAcid: -25,
		},
		notes: "Immune to Bleeding Status",
	},
	{
		slug: "BvoK6t",
		name: "Labyrinth Creature 0 Arms",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistBleed: "immune",
			resistFire: 50,
			resistShock: 50,
			resistAcid: -25,
		},
		notes: "Immune to Bleeding Status",
	},
	{
		slug: "qsAuH9",
		name: "Labyrinth Creature Elite",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistBleed: "immune",
			resistFire: 50,
			resistShock: 50,
			resistAcid: -25,
		},
		notes: "Immune to Bleeding Status",
	},
	{
		slug: "EX99Ua",
		name: "Labyrinth Pillar",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistBleed: "immune",
			resistFire: 50,
			resistShock: 50,
			resistAcid: -25,
		},
		notes: "Immune to Bleeding Status",
	},
	{
		slug: "eAt3EK",
		name: "Labyrinth Sphere",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistBleed: "immune",
			resistFire: 50,
			resistShock: 50,
			resistAcid: -25,
		},
		notes: "Immune to Bleeding Status",
	},
	{
		slug: "DW5qp9",
		name: "Labyrinth Watcher",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistBleed: "immune",
			resistFire: 50,
			resistShock: 50,
			resistAcid: -25,
		},
		notes: "Immune to Bleeding Status",
	},
	{
		slug: "gLut8N",
		name: "Luminescent Bloat",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistBleed: 15,
			resistFire: -10,
			resistShock: 15,
			resistAcid: -10,
		},
	},
	{
		slug: "73xW7r",
		name: "Phantom (Green)",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistBleed: "immune",
		},
		notes: "Immune to Bleeding Status",
	},
	{
		slug: "hR6Bp4",
		name: "Phantom (Orange)",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistBleed: "immune",
		},
		notes: "Immune to Bleeding Status",
	},
	{
		slug: "h2FQkM",
		name: "Phantom (Pink)",
		dlc: "BASE",
		category: "enemy",
		wikiLink: undefined,
		modifiers: {
			resistBleed: "immune",
		},
		notes: "Immune to Bleeding Status",
	},
] as const satisfies Enemy[];

export { enemies };
