import type { Enemy } from "#/games/remnant2/enemy-data/types/enemy";

const worldBossEnemies = [
	{
		name: "Alepsis Taura",
		category: "world boss",
		imageUrl: "/enemies/worldboss/alepsis-taura.jpg",
		wikiLink: "https://remnant.wiki/Alepsis-Taura",
		slug: "m1dxsf",
		modifiers: undefined,
		// location: { world: `N'Erud` }, // TODO
	},
	{
		name: "Annihilation",
		category: "world boss",
		imageUrl: "/enemies/worldboss/annihilation1.jpg",
		location: { world: "Root Earth", dungeon: ["Blackened Citadel"] },
		wikiLink: "https://remnant2.wiki.fextralife.com/Annihilation",
		slug: "g9FwDF",
		modifiers: undefined,
	},
	{
		name: "Corrupted Ravager",
		category: "world boss",
		imageUrl: "/enemies/worldboss/ravager.jpg",
		location: { world: "Yaesha", dungeon: [`Ravager's Lair`] },
		wikiLink: "https://remnant2.wiki.fextralife.com/Corrupted+Ravager",
		slug: "4zrNaX",
		modifiers: undefined,
	},
	{
		name: "Corruptor",
		category: "world boss",
		imageUrl: "/enemies/worldboss/corruptor.jpg",
		location: { world: "Yaesha", dungeon: ["The Great Bole"] },
		wikiLink: "https://remnant2.wiki.fextralife.com/Corruptor",
		slug: "6ABbmi",
		modifiers: undefined,
	},
	{
		slug: "8xK6gM",
		name: "Faelin",
		dlc: "BASE",
		category: "world boss",
		location: { world: "Losomn", dungeon: ["Beatific Gallery"] },
		imageUrl: "/enemies/worldboss/faelin1.jpg",
		wikiLink: "https://remnant2.wiki.fextralife.com/Faelin",
		modifiers: {
			resistBleed: 25,
			resistFire: 15,
			resistAcid: -15,
		},
	},
	{
		slug: "aJ8Tru",
		name: "Faerin",
		dlc: "BASE",
		category: "world boss",
		location: { world: "Losomn", dungeon: ["Malefic Gallery"] },
		imageUrl: "/enemies/worldboss/faerin1.jpg",
		wikiLink: "https://remnant2.wiki.fextralife.com/Faerin",
		modifiers: {
			resistBleed: 25,
			resistFire: 15,
			resistAcid: -15,
		},
	},
	{
		slug: "R4iYM2",
		name: "Lydusa",
		dlc: "DLC2",
		category: "world boss",
		imageUrl: "/enemies/worldboss/lydusa.jpg",
		wikiLink: "https://remnant2.wiki.fextralife.com/Lydusa",
		modifiers: undefined,
	},
	{
		slug: "hZ7siN",
		name: "Labyrinth Sentinel",
		dlc: "BASE",
		category: "world boss",
		location: { world: "Labyrinth", dungeon: ["Labyrinth"] },
		imageUrl: "/enemies/worldboss/labyrinth_sentinel.jpg",
		wikiLink: "https://remnant2.wiki.fextralife.com/Labyrinth+Sentinel",
		modifiers: {
			resistBleed: "immune",
			resistFire: "immune",
			resistShock: "immune",
			resistAcid: "immune",
		},
		notes: "Immune to all Statuses",
	},
	{
		name: `Sha'Hala: Guardian of N'Erud`,
		category: "world boss",
		imageUrl: "/enemies/worldboss/sha_hala_normal.jpg",
		location: { world: `N'Erud`, dungeon: [`Sentinel's Keep`] },
		wikiLink: `https://remnant2.wiki.fextralife.com/Sha'Hala+Spectral+Guardian+of+N'Erud`,
		slug: "2ZmDKS",
		modifiers: undefined,
	},
	{
		name: `Sha'Hala: Spectral Guardian of N'Erud`,
		category: "world boss",
		imageUrl: "/enemies/worldboss/sha_hala_metaphysical.jpg",
		location: { world: `N'Erud`, dungeon: [`Sentinel's Keep`] },
		wikiLink: `https://remnant2.wiki.fextralife.com/Sha'Hala+Spectral+Guardian+of+N'Erud`,
		slug: "S3JrnD",
		modifiers: undefined,
	},
	{
		name: `Tal'Ratha`,
		category: "world boss",
		imageUrl: "/enemies/worldboss/tal_ratha_normal1.jpg",
		location: { world: `N'Erud`, dungeon: [`Forgotten Prison`] },
		wikiLink: `https://remnant2.wiki.fextralife.com/Tal+Ratha`,
		slug: "bFt8JS",
		modifiers: undefined,
	},
	{
		name: `Tal'Ratha (Metaphysical)`,
		category: "world boss",
		imageUrl: "/enemies/worldboss/tal_ratha_metaphysical.jpg",
		location: { world: `N'Erud`, dungeon: [`Forgotten Prison`] },
		wikiLink: `https://remnant2.wiki.fextralife.com/Tal+Ratha+(Metaphysical)`,
		slug: "d5c8bN",
		modifiers: undefined,
	},
	{
		slug: "9TzbrC",
		name: "The Nightweaver",
		dlc: "BASE",
		category: "world boss",
		location: { world: "Losomn", dungeon: ["Tormented Asylum"] },
		imageUrl: "/enemies/worldboss/nightweaver.jpg",
		wikiLink: "https://remnant2.wiki.fextralife.com/Nightweaver",
		modifiers: {
			resistBleed: 20,
			resistFire: -10,
			resistShock: -10,
			resistAcid: 10,
		},
	},
	{
		slug: "Fjy5pF",
		name: "The One True King",
		dlc: "DLC1",
		category: "world boss",
		imageUrl: "/enemies/worldboss/one_true_king1.jpg",
		location: { world: "Losomn", dungeon: ["Chamber of the Faithless"] },
		wikiLink: "https://remnant2.wiki.fextralife.com/One+True+King",
		modifiers: undefined,
	},
] as const satisfies Enemy[];

export { worldBossEnemies };
