services:
  toolkitsgg:
    container_name: toolkitsgg-prod
    build:
      context: .
      dockerfile: src/prod.Dockerfile # TODO create this Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        RESEND_KEY: ${RESEND_KEY}
        NEXT_SERVER_ACTIONS_ENCRYPTION_KEY: ${NEXT_SERVER_ACTIONS_ENCRYPTION_KEY}

        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
        NEXT_PUBLIC_CLOUDFRONT_URL: ${NEXT_PUBLIC_CLOUDFRONT_URL}
    env_file:
      - .env.production
    restart: always
    ports:
      - 3000:3000
    networks:
      - toolkitsgg_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  toolkitsgg_network:
    external: true