services:
  toolkitsgg:
    container_name: toolkitsgg-development
    build:
      context: .
      dockerfile: src/development.Dockerfile # TODO create this Dockerfile

    # Set environment variables based on the .env file
    env_file:
      - .env.development
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    restart: always
    ports:
      - 3000:3000
    networks:
      - toolkitsgg_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  toolkitsgg_network:
    external: true