import type { BaseRemnant2Item } from "#/games/remnant2/core/types";

type Remnant2MutatorItem = BaseRemnant2Item<"gun" | "melee"> & {
	maxLevelBonus: string[];
};

const MUTATORS: Remnant2MutatorItem[] = [
	{
		name: "Bandit",
		category: "MUTATOR",
		subcategory: "gun",
		imageUrl: "items/mutators/bandit.png",
		internalSlug: "MetaGem_Bandit_C",
		id: "f9tqot",
		dlc: "BASE",
		searchableTags: ["Ammo Reserves", "Fire Rate"],
		description: [
			"Increases Magazine Capacity of this weapon by 20% - 45%.",
			"Bows: Increases Reserve Size of this weapon by 20% - 45%.",
		],
		maxLevelBonus: [
			"When Ammo is returned to this weapon, it gains 10% increased Fire Rate for 3s. Duration can increase up to 10s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Bandit_(Mutator)`,
		location: {
			world: "Yaesha",
			biome: "Floating Forests",
			injectable: "Broken Tomb",
		},
	},
	{
		category: "MUTATOR",
		name: "Battle Mage",
		subcategory: "melee",
		imageUrl: "items/mutators/battle_mage.png",
		internalSlug: "MetaGem_BattleMage_C",
		dlc: "BASE",
		id: "y5hY8J",
		searchableTags: ["Mod Power", "Melee Damage"],
		description: [
			"Skill activation grants Mage Strike for 10s, increasing Melee Mod Generation by 25% - 50%.",
		],
		maxLevelBonus: ["Mage Strike also increases Melee Damage by 15%."],
		wikiUrl: `https://remnant2.wiki.gg/Battle_Mage`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "MUTATOR",
		name: "Battery",
		subcategory: "gun",
		imageUrl: "items/mutators/battery.png",
		internalSlug: "MetaGem_Battery_C",
		id: "n5zhws",
		dlc: "BASE",
		searchableTags: ["Weakspot Damage"],
		description: [
			"Increases Weakspot Damage by 10% - 20% for every 400 Mod Power Spent by the attached weapon's mod. Max 3 stacks. Lasts 10s.",
		],
		maxLevelBonus: [
			"At Max Stacks, gain 10% Critical Chance on Weakspot Hits.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Battery`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "MUTATOR",
		name: "Bottom Heavy",
		subcategory: "gun",
		imageUrl: "items/mutators/bottom_heavy.png",
		internalSlug: "MetaGem_BottomHeavy_C",
		id: "8lg493",
		dlc: "BASE",
		searchableTags: ["Fire Rate", "Reload Speed"],
		description: [
			"Grants 7% Fire Rate. Increases 1% - 2% for every 10% of Magazine missing.",
		],
		maxLevelBonus: [
			"Reload Speed is increased by 1.5% for every 10% Magazine missing.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Bottom_Heavy`,
		location: { world: "Any", dungeon: "Aberration" },
	},
	{
		category: "MUTATOR",
		name: "Bulletweaver",
		subcategory: "gun",
		imageUrl: "items/mutators/bulletweaver.png",
		internalSlug: "MetaGem_Bulletweaver_C",
		id: "cr22cp",
		dlc: "BASE",
		searchableTags: ["Fire Rate", "Mod Power"],
		description: [
			"Mod use increases Fire Rate of this weapon by 10% - 20%  for 15s.",
		],
		maxLevelBonus: ["Increases Mod Generation for this weapon by 15%."],
		wikiUrl: `https://remnant2.wiki.gg/Bulletweaver`,
		location: { world: "Yaesha", biome: "Ziggurats", injectable: "Library" },
	},
	{
		category: "MUTATOR",
		name: "Charged Wounds",
		subcategory: "gun",
		imageUrl: "items/mutators/chargedwounds.png",
		internalSlug: "MetaGem_ChargedWounds_C",
		id: "77hc49",
		dlc: "DLC3",
		searchableTags: [],
		description: [
			"Increases this weapon's Fire Rate and Reload Speed by 2.5% - 5% per OVERLOADED entity within 15m. Max 5 stacks.",
		],
		maxLevelBonus: [
			"This weapon's Ranged Weakspot and Ranged Critical Hits apply OVERLOADED, dealing 75 - 225 SHOCK damage over 10s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Charged_Wounds`,
		location: { world: `N'Erud`, dungeon: "Quest" },
	},
	{
		category: "MUTATOR",
		name: "Deadly Calm",
		subcategory: "gun",
		imageUrl: "items/mutators/deadly_calm.png",
		internalSlug: "MetaGem_DeadlyCalm_C",
		id: "ssvo08",
		dlc: "BASE",
		searchableTags: ["Ranged Damage", "Critical Chance"],
		description: [
			"Continuously Aiming increases Ranged Damage by up to 10% - 25% over 3s.",
		],
		maxLevelBonus: [`Ranged Critical Hit Chance increased by 10%.`],
		wikiUrl: `https://remnant2.wiki.gg/Deadly_Calm`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "MUTATOR",
		name: "Dervish",
		subcategory: "melee",
		imageUrl: "items/mutators/dervish.png",
		internalSlug: "MetaGem_Dervish_C",
		id: "9htayl",
		dlc: "BASE",
		searchableTags: ["Reduce Skill Cooldown", "Melee Damage"],
		description: [
			"Increases Melee Damage by 20% - 40% for 10s when activating a Skill.",
		],
		maxLevelBonus: [
			`After dealing 350 base Melee damage, reduce Skill Cooldowns by 3%.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Dervish`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "MUTATOR",
		name: "Detonator",
		subcategory: "gun",
		imageUrl: "items/mutators/detonator.png",
		internalSlug: "MetaGem_Detonator_C",
		id: "fgs17j",
		dlc: "DLC3",
		searchableTags: [],
		communityTags: ["Explosive Damage", "AOE/Aura"],
		description: [
			"Each 10% of this weapon's magazine spent, cause an explosion for 5 - 10 Explosive Damage to targets within 0.5m of impact location.",
		],
		maxLevelBonus: [`Increases this weapon's explosive damage by 20%.`],
		wikiUrl: `https://remnant2.wiki.gg/Detonator`,
		location: { world: `N'Erud`, dungeon: ["Agronomy Sector"] },
	},
	{
		category: "MUTATOR",
		name: "Disengage",
		subcategory: "melee",
		imageUrl: "items/mutators/disengage.png",
		internalSlug: "MetaGem_Disengage_C",
		id: "3kadzw",
		dlc: "BASE",
		searchableTags: ["Neutral Dodge", "Perfect Neutral Evade"],
		description: [
			"Melee Strikes increase the damage of the next Backdash Evade Attack by 5% - 15%. Max 3 Stacks. Lasts 7.5s.",
		],
		maxLevelBonus: ["Perfect Neutral Evades grant 3 stacks."],
		wikiUrl: `https://remnant2.wiki.gg/Disengage`,
		location: {
			world: `N'Erud`,
			biome: `N'Erud Underworld`,
			injectable: "Store Room",
		},
	},
	{
		category: "MUTATOR",
		name: "Dreadful",
		subcategory: "gun",
		imageUrl: "items/mutators/dreadful.png",
		internalSlug: "MetaGem_Dreadful_C",
		dlc: "DLC1",
		id: "zcqbti",
		searchableTags: ["Ranged Damage", "Grey Health", "Reload Speed"],
		description: [
			"Increases Ranged Damage by 1% - 2% for every 5% of total Health present as Grey Health. Max 20% increase.",
		],
		maxLevelBonus: [
			`Increases Reload Speed for this weapon by 25% while Grey Health is present.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Dreadful`,
		location: { world: "Losomn", dungeon: ["Forlorn Coast"] },
	},
	{
		category: "MUTATOR",
		name: "Edgelord",
		subcategory: "melee",
		imageUrl: "items/mutators/edgelord.png",
		internalSlug: "MetaGem_Edgelord_C",
		id: "mpxowx",
		dlc: "BASE",
		searchableTags: [
			"Melee Charge Speed",
			"Melee Attack Speed",
			"Charged Melee",
			"Lifesteal",
		],
		description: [
			"Increases Melee Charge Speed by 15% - 35% and Melee Attack Speed by 10%.",
		],
		maxLevelBonus: [
			`Gain 3% of based Charged Melee Damage dealt as Lifesteal.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Edgelord`,
		location: { world: "Any", dungeon: "Aberration" },
	},
	{
		category: "MUTATOR",
		name: "Executor",
		subcategory: "melee",
		imageUrl: "items/mutators/executor.png",
		internalSlug: "MetaGem_Executor_C",
		dlc: "DLC1",
		id: "pynv5l",
		searchableTags: [
			"Status Effect",
			"Melee Charge Speed",
			"Melee Attack Speed",
		],
		description: [
			"Charged Melee Attacks increase the duration of Negative Status Effects on enemies by 10% - 30% of the original duration. Cannot exceed original max duration.",
		],
		maxLevelBonus: [
			`Increases Melee Charge Speed and Melee Attack Speed by 5% per entity within 20m with a Negative Status Effect. Max 4 stacks.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Executor`,
		location: { world: "Losomn", dungeon: ["Forlorn Coast"] },
	},
	{
		category: "MUTATOR",
		name: "Extender",
		subcategory: "gun",
		imageUrl: "items/mutators/extender.png",
		internalSlug: "MetaGem_Extender_C",
		id: "pszxmh",
		dlc: "BASE",
		searchableTags: ["Magazine Capacity", "Reload Speed"],
		description: [
			"Increases Magazine Capacity of this weapon by 20% - 45%.",
			"Bows: Increases Reserve Size of this weapon by 20% - 45%.",
		],
		maxLevelBonus: ["Increases Reload Speed of this weapon by 20%."],
		wikiUrl: `https://remnant2.wiki.gg/Extender`,
		location: {
			world: "Yaesha",
			biome: "Undead Tombs",
			injectable: "Sarcophagus",
		},
	},
	{
		category: "MUTATOR",
		name: "Failsafe",
		subcategory: "gun",
		imageUrl: "items/mutators/failsafe.png",
		internalSlug: "MetaGem_Failsafe_C",
		id: "0xx8tz",
		dlc: "BASE",
		searchableTags: ["Mod Damage"],
		description: ["Attached Mod deals 10% - 25% additional Mod Damage."],
		maxLevelBonus: [
			`Attached Mod use gains a 15% chance to not consume charge.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Failsafe`,
		location: { world: `N'Erud`, dungeon: [`Dormant N'Erudian Facility`] },
	},
	{
		category: "MUTATOR",
		name: "Far-Sighted",
		subcategory: "gun",
		imageUrl: "items/mutators/far-sighted.png",
		internalSlug: "MetaGem_FarSighted_C",
		id: "QJdhx2",
		dlc: "DLC2",
		searchableTags: ["Ranged Damage"],
		description: [
			"Increases Ranged Damage of this weapon by 1.25% - 2.5% for every 2.5m from the shooter to the target. Max 25%.",
		],
		maxLevelBonus: [
			"Increases this weapon's Ideal, Falloff, and Max Range by 5m.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Far-Sighted`,
		location: { world: "Yaesha", dungeon: "Aberration" },
	},
	{
		category: "MUTATOR",
		name: "Feedback",
		subcategory: "gun",
		imageUrl: "items/mutators/feedback.png",
		internalSlug: "MetaGem_Feedback_C",
		id: "75qok3",
		dlc: "BASE",
		searchableTags: ["Mod Power", "Mod Damage"],
		description: [
			"Using this weapon's Mod generates 10% - 20% of single charge value as passive Mod Power over 10s. Does not stack.",
		],
		maxLevelBonus: [
			"Mod Damage generates 15% of Base Damage dealt as Mod Power.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Feedback`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "MUTATOR",
		name: "Fetid Wounds",
		subcategory: "gun",
		imageUrl: "items/mutators/fetid_wounds.png",
		internalSlug: "MetaGem_FetidWounds_C",
		id: "b07g02",
		dlc: "BASE",
		searchableTags: [
			"Critical Chance",
			"Status Effect",
			"Weakspot Damage",
			"Critical Hit",
		],
		description: [
			"Increases Critical Chance of this weapon by 1% - 3% per unique Negative Status Effect on the enemy. Max 15% increase.",
		],
		maxLevelBonus: [
			`This weapon's Ranged Weakspot and Ranged Critical Hits apply CORRODED, dealing 75 CORROSIVE damage over 10s.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Fetid_Wounds`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "MUTATOR",
		name: "Ghost Shell",
		subcategory: "gun",
		imageUrl: "items/mutators/ghost_shell.png",
		internalSlug: "MetaGem_GhostShell_C",
		id: "85c7yj",
		dlc: "BASE",
		searchableTags: [
			"Weakspot Hit",
			"Weakspot Damage",
			"Weakspot Critical Chance",
		],
		description: [
			"Every 3rd consecutive Weakspot Hits deals 20% - 40% additional damage.",
		],
		maxLevelBonus: [`Increases Weakspot Critical Chance by 15%.`],
		wikiUrl: `https://remnant2.wiki.gg/Ghost_Shell`,
		location: { world: "Yaesha", dungeon: [`The Widow's Court`] },
	},
	{
		category: "MUTATOR",
		name: "Gladiator",
		subcategory: "melee",
		imageUrl: "items/mutators/gladiator.png",
		internalSlug: "MetaGem_Gladiator_C",
		id: "N4LpPR",
		dlc: "DLC2",
		searchableTags: [],
		description: [
			"While brandishing a Melee Weapon, receiving Enemy Damage increases Melee Damage by 25% - 50% for 5s.",
		],
		maxLevelBonus: [
			"Receiving Enemy Damage while brandishing a Melee Weapon grants 1 stack of BULWARK for 5s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Gladiator`,
		location: { world: "Yaesha", dungeon: ["Proving Grounds"] },
	},
	{
		category: "MUTATOR",
		name: "Guts",
		subcategory: "melee",
		imageUrl: "items/mutators/guts.png",
		internalSlug: "MetaGem_Guts_C",
		dlc: "DLC1",
		id: "961d6v",
		searchableTags: ["Melee Critical Chance", "Grey Health"],
		description: [
			"Increases Melee Critical Chance by 5% - 25% when Grey Health is present.",
		],
		maxLevelBonus: [
			`Increases Melee Critical Damage by 0.5% for every 1% of Grey Health.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Guts`,
		location: { world: "Losomn", dungeon: ["The Forgotten Commune"] },
	},
	{
		category: "MUTATOR",
		name: "Harmonizer",
		subcategory: "gun",
		imageUrl: "items/mutators/harmonizer.png",
		internalSlug: "MetaGem_Harmonizer_C",
		id: "jyl055",
		dlc: "BASE",
		searchableTags: ["Mod Damage", "Mod Power"],
		description: ["Attached Mod deals 10% - 20% additional Mod Damage."],
		maxLevelBonus: [`Generate 25% additional Mod Power for Stowed Weapon.`],
		wikiUrl: `https://remnant2.wiki.gg/Harmonizer`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "MUTATOR",
		name: "Hidden Power",
		subcategory: "gun",
		imageUrl: "items/mutators/hiddenpower.png",
		internalSlug: "MetaGem_HiddenPower_C",
		id: "9154v1",
		dlc: "BASE",
		searchableTags: ["Ranged Damage", "Reload Speed"],
		description: [
			"Increases the attached weapon's Ranged Damage by 15% -> 25% after being stowed for 2s. Lasts 7s upon being brandished.",
		],
		maxLevelBonus: [
			`Automatically reloads the attached weapon after being stowed for 2s.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Hidden_Power`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "MUTATOR",
		name: "Hyper Charger",
		subcategory: "melee",
		imageUrl: "items/mutators/hyper_charger.png",
		internalSlug: "MetaGem_HyperCharger_C",
		id: "mh4scd",
		dlc: "DLC3",
		searchableTags: [],
		description: [
			"Increases Charged Melee Stamina Cost by 65%. Increases Charged Melee Damage by 25% - 50%.",
		],
		maxLevelBonus: [
			"Charged Melee Hits increase Stamina Recovery Rate by 100% for 3s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Hyper_Charger`,
		location: { world: `N'Erud`, dungeon: ["Logistics Bridge"] },
	},
	{
		category: "MUTATOR",
		name: "Ingenuity",
		subcategory: "gun",
		imageUrl: "items/mutators/ingenuity.png",
		internalSlug: "MetaGem_Ingenuity_C",
		id: "mkbquc",
		dlc: "BASE",
		searchableTags: ["Heat Generation", "Reload Speed"],
		description: ["Reduces the Heat Generation of this weapon by 10% - 30%."],
		maxLevelBonus: [
			`Reload Speed is increased up to 55% based on this weapon's Heat accumulation.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Ingenuity`,
		location: { world: "Any", dungeon: "Aberration" },
	},
	{
		category: "MUTATOR",
		name: "Insulator",
		subcategory: "gun",
		imageUrl: "items/mutators/insulator.png",
		internalSlug: "MetaGem_Insulator_C",
		id: "9x521w",
		dlc: "DLC3",
		searchableTags: [],
		description: [
			"Spending 20% - 10% of this weapon's magazine grants a SHIELD for 5% of Max Health for 10s. Max 25% SHIELD.",
		],
		maxLevelBonus: [
			"Increases Ranged Critical Chance for this weapon by 10% when SHIELD is above 10% of Max Health.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Insulator`,
		location: { world: `N'Erud`, dungeon: ["Athenaeum Wek"] },
	},
	{
		category: "MUTATOR",
		name: "Kill Switch",
		subcategory: "gun",
		imageUrl: "items/mutators/kill_switch.png",
		internalSlug: "MetaGem_KillSwitch_C",
		id: "rzfptj",
		dlc: "BASE",
		description: [
			"Switching to this weapon creates an Explosive Burst which deals 50 - 250 Damage to all enemies within 7m.",
			"Can only happen once every 10s.",
		],
		maxLevelBonus: [
			"This weapon's kills with any Explosive Damage reduce Kill Switch cooldown by 1s.",
		],
		communityTags: [`AOE/Aura`, `Explosive Damage`],
		wikiUrl: `https://remnant2.wiki.gg/Kill_Switch`,
		location: { world: "Any", dungeon: "Aberration" },
	},
	{
		category: "MUTATOR",
		name: "Latency",
		subcategory: "melee",
		imageUrl: "items/mutators/latency.png",
		internalSlug: "MetaGem_Latency_C",
		id: "nft2cp",
		dlc: "BASE",
		searchableTags: ["Melee Special Ability"],
		description: [
			"Melee Weapons with special abilities which become readied by dealing Melee Damage require 10% - 35% less damage to charge.",
		],
		maxLevelBonus: [
			"Increases the power of readied Melee Special abilities by 25%.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Latency`,
		location: { world: "Any", dungeon: "Aberration" },
	},
	{
		category: "MUTATOR",
		name: "Lithely",
		subcategory: "gun",
		imageUrl: "items/mutators/lithely.png",
		internalSlug: "MetaGem_Lithely_C",
		id: "s2z9cc",
		dlc: "BASE",
		searchableTags: ["Reload Speed", "Ranged Damage"],
		description: [
			"Dealing 50% - 20% of the attached Weapon's Magazine Base Damage increases reload speed by 3%. Lasts 7s. Max 5 Stacks.",
		],
		maxLevelBonus: [
			`Reloading at Max Stacks increases Ranged Damage by 20% for 15s.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Lithely`,
		location: { world: "Losomn", dungeon: [`Harvester's Reach`] },
	},
	{
		category: "MUTATOR",
		name: "Maelstrom",
		subcategory: "gun",
		imageUrl: "items/mutators/maelstrom.png",
		internalSlug: "MetaGem_Maelstrom_C",
		dlc: "DLC1",
		id: "4m2lg1",
		searchableTags: ["Elemental Damage", "Status Effect", "Mod Power"],
		description: [
			"Increases this weapon's Elemental Damage by 5% - 10% for each unique Elemental Status Effect on the target.",
		],
		maxLevelBonus: [
			`Increases Mod Power Generation of Elemental Damage and Elemental Status damage by 20%.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Maelstrom`,
		location: { world: "Losomn", dungeon: ["Forlorn Coast"] },
	},
	{
		category: "MUTATOR",
		name: "Misfortune",
		subcategory: "melee",
		imageUrl: "items/mutators/misfortune.png",
		internalSlug: "MetaGem_Misfortune_C",
		id: "imqrfz",
		dlc: "BASE",
		searchableTags: ["Melee Damage", "Status Effect"],
		description: [
			"Increase Melee damage by 6% - 10%  for each unique Negative Status the target is suffering from.",
		],
		maxLevelBonus: [`Charge Melee Attacks apply SLOW for 3s.`],
		wikiUrl: `https://remnant2.wiki.gg/Misfortune`,
		location: { world: "Losomn", dungeon: ["Malefic Palace"] },
	},
	{
		category: "MUTATOR",
		name: "Momentum",
		subcategory: "gun",
		imageUrl: "items/mutators/momentum.png",
		internalSlug: "MetaGem_Momentum_C",
		id: "cvbjvd",
		dlc: "BASE",
		searchableTags: ["Critical Hit", "Critical Chance"],
		description: [
			"When this weapon scores a Critical Hit, it increases Critical Chance and Critical Damage by 1% - 2% for 3s. Max 10 stacks.",
		],
		maxLevelBonus: [
			`Critical Hits from this weapon add 2 stacks. Increases duration by 2s.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Momentum`,
		location: { world: "Yaesha", dungeon: ["Imperial Gardens"] },
	},
	{
		category: "MUTATOR",
		name: "Near-Sighted",
		subcategory: "gun",
		dlc: "DLC2",
		imageUrl: "items/mutators/near-sighted.png",
		internalSlug: "MetaGem_NearSighted_C",
		id: "7Y9hfZ",
		searchableTags: ["Ranged Damage", "Critical Chance"],
		description: [
			"Increases Ranged Damage of this weapon by 10% - 20% to enemies within 7m.",
		],
		maxLevelBonus: [
			"Increases Ranged Critical Chance of this weapon by 10% to enemies within 7m.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Near-Sighted`,
		location: { world: "Yaesha", dungeon: ["Infested Abyss"] },
	},
	{
		category: "MUTATOR",
		name: "Opportunist",
		subcategory: "melee",
		imageUrl: "items/mutators/opportunist.png",
		internalSlug: "MetaGem_Opportunist_C",
		id: "qca3zh",
		dlc: "BASE",
		searchableTags: ["Perfect Dodge", "Melee Critical Chance"],
		description: [
			"Perfect Dodge activates OPPORTUNITY which increases Melee Critical Chance by 50% - 100% for 2s.",
		],
		maxLevelBonus: [
			"While OPPORTUNITY is active, any Dodge or Combat Slide refreshes the duration.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Opportunist`,
		location: { world: "Any", dungeon: "Aberration" },
	},
	{
		category: "MUTATOR",
		name: "Overdrive",
		subcategory: "melee",
		imageUrl: "items/mutators/overdrive.png",
		internalSlug: "MetaGem_Overdrive_C",
		id: "mjzb0f",
		dlc: "BASE",
		searchableTags: [
			"Melee Critical Hit",
			"Critical Hit",
			"Critical Chance",
			"Critical Damage",
			"Melee Critical Damage",
		],
		description: [
			"Melee Critical Hits increase Melee Critical Chance by 2% - 5% for 10s. stacking up to 5 times.",
		],
		maxLevelBonus: [`Melee Critical Strikes deal 25% additional damage.`],
		wikiUrl: `https://remnant2.wiki.gg/Overdrive`,
		location: { world: "Yaesha", dungeon: ["The Lament"] },
	},
	{
		category: "MUTATOR",
		name: "Pressure Point",
		subcategory: "gun",
		imageUrl: "items/mutators/pressure_point.png",
		internalSlug: "MetaGem_PressurePoint_C",
		id: "EV4ULr",
		dlc: "DLC2",
		searchableTags: ["Mod Damage", "Ranged Damage", "Stagger"],
		description: [
			"Increases this weapon's Ranged and Mod Damage by 5% - 15% to enemies within 7m.",
		],
		maxLevelBonus: [
			"Activating this weapon's Mod triggers a fixed 7m blast, dealing 50 Explosive Damage per 100 Mod Power spent in a single cast. Inflicts 1.5 Stagger Damage.",
		],
		communityTags: [`Explosive Damage`],
		wikiUrl: `https://remnant2.wiki.gg/Pressure_Point`,
		location: { world: "Yaesha", dungeon: ["Ancient Canopy"] },
	},
	{
		category: "MUTATOR",
		name: "Prophecy",
		subcategory: "gun",
		imageUrl: "items/mutators/prophecy.png",
		internalSlug: "MetaGem_Prophecy_C",
		dlc: "DLC1",
		id: "lo6uce",
		searchableTags: ["Mod Power"],
		description: [
			"Using this weapon's Mod increases Mod Power Generation by 3% - 6% for 10s. Max 5 stacks.",
		],
		maxLevelBonus: [`Increases Movement Speed by 3% per stack.`],
		wikiUrl: `https://remnant2.wiki.gg/Prophecy`,
		location: { world: "Losomn", dungeon: ["Pathway of the Fallen"] },
	},
	{
		category: "MUTATOR",
		name: "Refunder",
		subcategory: "gun",
		imageUrl: "items/mutators/refunder.png",
		internalSlug: "MetaGem_Refunder_C",
		id: "fcl7u2",
		dlc: "BASE",
		searchableTags: ["Ammo Reserves"],
		description: [
			"Shots from this weapon have a 20% - 50% chance to return spent Ammo to reserves.",
		],
		maxLevelBonus: [
			`Refunded Ammo has a 25% chance to also be added to stowed weapon reserves.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Refunder`,
		location: { world: `N'Erud`, dungeon: ["Tower of the Unseen"] },
	},
	{
		category: "MUTATOR",
		name: "Reinvigorate",
		subcategory: "melee",
		imageUrl: "items/mutators/reinvigorate.png",
		internalSlug: "MetaGem_Reinvigorate_C",
		id: "5bfv3p",
		dlc: "BASE",
		searchableTags: ["Charged Melee", "Melee Critical Chance"],
		description: [
			"Reduces the Stamina Cost of all Charged Melee Attacks by 25% - 50%.",
		],
		maxLevelBonus: [
			`Melee Charge Attacks gain 20% additional damage and 10% Critical Chance.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Reinvigorate`,
		location: { world: "Yaesha", dungeon: ["Forgotten Field"] },
	},
	{
		category: "MUTATOR",
		name: "Repercussion",
		subcategory: "gun",
		imageUrl: "items/mutators/repercussion.png",
		internalSlug: "MetaGem_Repercussion_C",
		id: "jbrq12",
		dlc: "DLC3",
		searchableTags: ["Ranged Damage", "Critical Chance"],
		description: [
			"Each enemy hit by Primary Fire grants 1 stack of REPERCUSSION, increasing Ranged Damage by 3% - 6% per stack. Max 5 stacks. Shots consume stacks.",
		],
		maxLevelBonus: [
			`Increases this weapon's Critical Chance by 3% per stack of REPERCUSSION.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Repercussion`,
		location: {
			world: `N'Erud`,
			biome: `Towers of N'Erud`,
			injectable: "Crop Lab",
		},
	},
	{
		category: "MUTATOR",
		name: "Resentment",
		subcategory: "melee",
		imageUrl: "items/mutators/resentment.png",
		internalSlug: "MetaGem_Resentment_C",
		id: "ha3amj",
		dlc: "BASE",
		searchableTags: ["Melee Damage", "Grey Health", "Stagger"],
		description: ["Gain 15% - 35% Melee Damage when Grey Health is present."],
		maxLevelBonus: [`Reduces Stagger by 1 when using any Melee Attack.`],
		wikiUrl: `https://remnant2.wiki.gg/Resentment`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "MUTATOR",
		name: "Searing Wounds",
		subcategory: "gun",
		imageUrl: "items/mutators/searing_wounds.png",
		internalSlug: "MetaGem_SearingWounds_C",
		dlc: "DLC2",
		id: "9htako",
		searchableTags: ["Ranged Damage", "Critical Hit", "Status Effect"],
		description: [
			"Increases Ranged Damage of this weapon by 1% - 10% to BURNING targets.",
		],
		maxLevelBonus: [
			`This weapon's Ranged Weakspot and Ranged Critical Hits apply BURNING, dealing 50 FIRE damage over 5s.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Searing_Wounds`,
		location: { world: "Yaesha", dungeon: [`Goddess's Rest`] },
	},
	{
		category: "MUTATOR",
		name: "Sequenced Shot",
		subcategory: "gun",
		imageUrl: "items/mutators/sequenced_shot.png",
		internalSlug: "MetaGem_SequencedShot_C",
		id: "23ztdj",
		dlc: "BASE",
		searchableTags: ["Charged Shot", "Critical Chance"],
		description: [
			"This weapon's Charged Shots decrease the Charge time of Subsequent Charge Shots by 10% - 35%  for 5s.",
		],
		maxLevelBonus: [
			"While active, Charged Primary Shots grant 1% Ranged Critical Chance per round spent. Max 15%.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Sequenced_Shot`,
		location: { world: "Any", dungeon: "Aberration" },
	},
	{
		category: "MUTATOR",
		name: "Shielded Strike",
		internalSlug: "MetaGem_ShieldBreaker_C",
		subcategory: "melee",
		imageUrl: "items/mutators/shielded_strike.png",
		id: "bhov5r",
		dlc: "BASE",
		searchableTags: ["Charged Melee", "Melee Damage"],
		description: [
			"Melee Attacks grant a SHIELD for 3% - 6% of Max Health for 5s. Max 30% SHIELD.",
		],
		maxLevelBonus: [
			"Charged Melee Attacks deal 25% additional Melee Damage based on current SHIELD accumulation.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Shielded_Strike`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "MUTATOR",
		name: "Shocker",
		subcategory: "melee",
		imageUrl: "items/mutators/shocker.png",
		internalSlug: "MetaGem_Shocker_C",
		id: "7js906",
		dlc: "BASE",
		searchableTags: ["Charged Melee"],
		description: [
			"Empowers weapon after 3 hits. While empowered. the next Charged Melee Hit strikes all enemies within 7m with 50 - 100 SHOCK Damage.",
		],
		maxLevelBonus: [
			"The SHOCK  Damage now applies OVERLOADED dealing 125 - 375 SHOCK damage every 5s for 5s.",
		],
		communityTags: [`AOE/Aura`],
		wikiUrl: `https://remnant2.wiki.gg/Shocker`,
		location: { world: "Any", dungeon: "Aberration" },
	},
	{
		category: "MUTATOR",
		name: "Slayer",
		subcategory: "gun",
		imageUrl: "items/mutators/slayer1.png",
		internalSlug: "MetaGem_Slayer_C",
		id: "h98e7b",
		dlc: "BASE",
		searchableTags: ["Ranged Damage", "Reload Speed"],
		description: [
			"Reloading increases the damage of this weapon's next shot by 10% - 25%. Lasts 3s.",
		],
		maxLevelBonus: [`Increases Reload Speed by 15%.`],
		wikiUrl: `https://remnant2.wiki.gg/Slayer`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "MUTATOR",
		name: "Sleeper",
		subcategory: "gun",
		imageUrl: "items/mutators/sleeper.png",
		internalSlug: "MetaGem_Sleeper_C",
		dlc: "DLC1",
		id: "xim1sx",
		searchableTags: ["Critical Chance"],
		description: [
			"This weapon becomes EMPOWERED when stowed for 5 seconds, granting 25% Critical Chance for 5s - 10s  after it's drawn.",
		],
		maxLevelBonus: [
			"While EMPOWERED, increases Critical Damage of this weapon by 15%",
		],
		wikiUrl: `https://remnant2.wiki.gg/Sleeper`,
		location: { world: "Losomn", dungeon: ["Derelict Lighthouse"] },
	},
	{
		category: "MUTATOR",
		name: "Spellweaver",
		subcategory: "gun",
		imageUrl: "items/mutators/spellweaver.png",
		internalSlug: "MetaGem_Spellweaver_C",
		dlc: "BASE",
		id: "5Brz87",
		searchableTags: ["Mod Damage", "Mod Power", "Reduce Skill Cooldown"],
		description: [
			"Increases this weapon's Mod Damage and Mod Generation by 10% - 15% for 10s when activating a Skill.",
		],
		maxLevelBonus: [
			"Activating this weapon's Mod reduces Skill Cooldowns by 1% for every 100 Mod Power spent.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Spellweaver`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "MUTATOR",
		name: "Spirit Feeder",
		subcategory: "gun",
		internalSlug: "MetaGem_BottomFeeder_C",
		imageUrl: "items/mutators/bottom_feeder.png",
		id: "90i71b",
		dlc: "BASE",
		searchableTags: [],
		description: [
			"Reloading this weapon increases the damage of the Attached Mod by 10% - 30%. Lasts 7s.",
		],
		maxLevelBonus: [
			"Casting Attached Mod increases Reload Speed by 25%. Lasts 7s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Spirit_Feeder`,
		location: { world: "Any", dungeon: "Aberration" },
	},
	{
		category: "MUTATOR",
		name: "Spirit Healer",
		subcategory: "gun",
		imageUrl: "items/mutators/spirit_healer.png",
		internalSlug: "MetaGem_SpiritHealer_C",
		id: "hk1k7k",
		dlc: "BASE",
		searchableTags: ["Mod Power", "Heal"],
		description: [
			"Regenerate 2% Health over 10s for every 150 - 50 Mod Power spent.",
		],
		maxLevelBonus: [
			`Allies within 15m are healed for 50% of the primary effect.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Spirit_Healer`,
		location: { world: "Any", dungeon: "Aberration" },
	},
	{
		category: "MUTATOR",
		name: "Steadfast",
		subcategory: "melee",
		imageUrl: "items/mutators/steadfast.png",
		internalSlug: "MetaGem_Steadfast_C",
		id: "yibeww",
		dlc: "BASE",
		searchableTags: [
			"Charged Melee",
			"Damage Reduction",
			"Grey Health",
			"Stagger",
		],
		description: [
			"Charged Melee Attacks cannot be interrupted and gain 5% - 10% Damage Reduction from all sources.",
		],
		maxLevelBonus: [
			"All Damage taken during a Charged Melee Attack is converted to Grey Health.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Steadfast`,
		location: {
			world: "Losomn",
			biome: "Fae Palace",
			injectable: "As Above, So Below",
		},
	},
	{
		category: "MUTATOR",
		name: "Stormbringer",
		subcategory: "melee",
		imageUrl: "items/mutators/stormbringer.png",
		internalSlug: "MetaGem_Stormbringer_C",
		id: "m87yf6",
		dlc: "BASE",
		searchableTags: ["Status Effect", "Melee Damage", "Charged Melee"],
		description: [
			"Increases the Status Effect Damage applied by Melee Attacks by 25% - 50%.",
		],
		maxLevelBonus: [
			"Charged Melee Attacks lower enemy's Resistance to All Status damage by 10%. Lasts 10s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Stormbringer`,
		location: { world: "Any", dungeon: "Aberration" },
	},
	{
		category: "MUTATOR",
		name: "Striker",
		subcategory: "melee",
		imageUrl: "items/mutators/striker.png",
		internalSlug: "MetaGem_Striker_C",
		id: "27rynt",
		dlc: "BASE",
		searchableTags: ["Melee Damage", "Movement Speed"],
		description: [
			"Melee Hits increase Melee Damage by 3% - 6% for 5s. Max 5 Stacks.",
		],
		maxLevelBonus: [`Increases Movement Speed by 3% per stack.`],
		wikiUrl: `https://remnant2.wiki.gg/Striker`,
		location: { world: "Losomn", dungeon: ["Morrow Parish"] },
	},
	{
		category: "MUTATOR",
		name: "Supercharger",
		subcategory: "gun",
		imageUrl: "items/mutators/supercharger.png",
		internalSlug: "MetaGem_Supercharger_C",
		id: "omeu3c",
		dlc: "BASE",
		searchableTags: ["Charged Shot", "Critical Chance"],
		description: [
			"Increases Charge Speed for Bows and Fusion Rifles by 10% - 30%.",
		],
		maxLevelBonus: [
			`Charged Primary Shots of Bows and Fusion Rifles gain 15% Critical Chance.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Supercharger`,
		location: { world: "Root Earth", dungeon: ["Twilight Vale"] },
	},
	{
		category: "MUTATOR",
		name: "Superheated",
		subcategory: "gun",
		imageUrl: "items/mutators/superheated.png",
		internalSlug: "MetaGem_SuperHeated_C",
		id: "97fccn",
		dlc: "DLC3",
		searchableTags: ["Heat Generation", "Status Effect"],
		communityTags: ["Explosive Damage", "AOE/Aura"],
		description: [
			"When this weapon is above 25% Heat, a 7.5m Pulse deals 150 Explosive Damage once every  5s - 3s.",
		],
		maxLevelBonus: [
			"At Max Heat, a 10m Pulse deals 300 Explosive Damage which applies BURNING to all entities for 100 FIRE damage over 20s. Can only happen once every 3s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Superheated`,
		location: { world: `N'Erud`, dungeon: [`Stagnant Manufactory`] },
	},
	{
		category: "MUTATOR",
		name: "Tainted Blade",
		subcategory: "melee",
		imageUrl: "items/mutators/tainted_blade.png",
		internalSlug: "MetaGem_TaintedBlade_C",
		id: "f32skd",
		dlc: "BASE",
		searchableTags: ["Melee Damage", "Charged Melee"],
		description: [
			"Increases Melee Damage by 5% - 8% per stack of CORRODED on the target. Max 5 stacks.",
		],
		maxLevelBonus: [
			"Charged Melee Attacks apply CORRODED, dealing 250 ACID Damage over 10s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Tainted_Blade`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "MUTATOR",
		name: "Thousand Cuts",
		subcategory: "gun",
		imageUrl: "items/mutators/thousand_cuts.png",
		internalSlug: "MetaGem_ThousandCuts_C",
		id: "r8jxFF",
		dlc: "DLC2",
		searchableTags: ["Critical Chance", "Critical Damage", "Reload Speed"],
		description: [
			"Increases this weapon's Critical Chance and Critical Damage by 0.1% - 0.5% for each shot fired. Lasts 0.125s. Max 50 stacks.",
		],
		maxLevelBonus: [`Increases this weapon's Reload Speed by 1% per stack.`],
		wikiUrl: `https://remnant2.wiki.gg/Thousand_Cuts`,
		location: {
			world: "Yaesha",
			biome: "Floating Forests",
			injectable: "Shrine of the Doe",
		},
	},
	{
		category: "MUTATOR",
		name: "Timewave",
		subcategory: "gun",
		imageUrl: "items/mutators/timewave.png",
		internalSlug: "MetaGem_Timewave_C",
		id: "dynus4",
		dlc: "BASE",
		searchableTags: ["Ranged Damage", "Status Effect"],
		description: [
			"Increase this weapon's Ranged damage by 5% - 20% to enemies inflicted with SLOW status.",
		],
		maxLevelBonus: [
			`Mod Use applies SLOW status on all enemies within 10m for 5s. Can only happen once every 10s.`,
		],
		communityTags: [`AOE/Aura`],
		wikiUrl: `https://remnant2.wiki.gg/Timewave`,
		location: {
			world: `N'Erud`,
			biome: `Towers of N'Erud`,
			injectable: `Remains Below`,
		},
	},
	{
		category: "MUTATOR",
		name: "Top Heavy",
		subcategory: "gun",
		imageUrl: "items/mutators/top_heavy.png",
		internalSlug: "MetaGem_TopHeavy_C",
		id: "fknx4t",
		dlc: "BASE",
		searchableTags: ["Ranged Damage", "Weakspot Damage"],
		description: [
			"Increases this weapon's Ranged Damage by up to 7.5% - 15% based on how close the magazine capacity is to full.",
		],
		maxLevelBonus: [
			`Increases this weapon's Weakspot Damage by up to 20% based on how close the magazine capacity is to full.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Top_Heavy`,
		location: { world: "Any", dungeon: "Aberration" },
	},
	{
		category: "MUTATOR",
		name: "Transference",
		subcategory: "melee",
		imageUrl: "items/mutators/transference.png",
		internalSlug: "MetaGem_Transference_C",
		id: "0osd64",
		dlc: "BASE",
		searchableTags: ["Melee Damage", "Mod Power", "Ammo Reserves"],
		description: [
			"Melee Hits generate 5% of Max Ammo Capacity to the Reserves for both Firearms. Cooldown 10s- 5s.",
		],
		maxLevelBonus: [
			`After Ammo is Transferred, increase Reload Speed of this weapon by 50% for 5s.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Transference`,
		location: { world: `N'Erud`, dungeon: ["Void Vessel Facility"] },
	},
	{
		category: "MUTATOR",
		name: "Transpose",
		subcategory: "gun",
		imageUrl: "items/mutators/transpose.png",
		internalSlug: "MetaGem_Transpose_C",
		id: "1cxn5s",
		dlc: "BASE",
		searchableTags: ["Ranged Damage", "Ammo Reserves"],
		description: ["Gaining Ammo increases Ranged Damage by 5% - 15% for 15s."],
		maxLevelBonus: [
			"New Ammo gains are added directly to into this weapon's magazine.",
			"Bows: New Ammo gains grants this weapon Infinite Reserves for 15s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Transpose`,
		location: {
			world: `N'Erud`,
			biome: `N'Erud Underworld`,
			injectable: `Robot Hangar`,
		},
	},
	{
		category: "MUTATOR",
		name: "Twisting Wounds",
		subcategory: "gun",
		imageUrl: "items/mutators/twisting_wounds.png",
		internalSlug: "MetaGem_TwistingWounds_C",
		id: "7eodps",
		dlc: "BASE",
		searchableTags: ["Ranged Damage", "Critical Hit", "Weakspot Hit"],
		description: [
			"Increases Ranged damage of this weapon by 1% - 10% to BLEEDING targets.",
		],
		maxLevelBonus: [
			"This weapon's Ranged Weakspot and Ranged Critical Hits apply BLEEDING, dealing 150 - 450 BLEED damage over 20s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Twisting_Wounds`,
		location: {
			world: "Losomn",
			biome: "Burning City",
			injectable: "Oink",
		},
	},
	{
		category: "MUTATOR",
		name: "Vampire Blade",
		subcategory: "melee",
		imageUrl: "items/mutators/vampire_blade.png",
		internalSlug: "MetaGem_VampireBlade_C",
		id: "dhwqt4",
		dlc: "BASE",
		searchableTags: ["Melee Damage", "Lifesteal"],
		communityTags: ["AOE/Aura"],
		description: [
			"Increases Melee Damage by 10% - 30% while within 10m of a BLEEDING entity.",
		],
		maxLevelBonus: [
			`Melee Hits vs BLEEDING targets will Lifesteal 3% of base damage dealt.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Vampire_Blade`,
		location: { world: "Yaesha", dungeon: [`Endaira's End`] },
	},
	{
		category: "MUTATOR",
		name: "Volatile Strike",
		subcategory: "melee",
		imageUrl: "items/mutators/volatilestrike.png",
		internalSlug: "MetaGem_VolatileStrike_C",
		id: "qej6k5",
		dlc: "BASE",
		searchableTags: ["Melee Damage", "Movement Speed"],
		communityTags: ["AOE/Aura", "Explosive Damage"],
		description: [
			"Dealing Melee Damage creates a 3m blast which deals 50 - 150 Explosive Damage. Can only happen once every 1s.",
		],
		maxLevelBonus: [
			`When Volatile Strike triggers a blast, increases Movement Speed by 20% for 5s.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Volatile_Strike`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "MUTATOR",
		name: "Vengeful Strike",
		subcategory: "melee",
		imageUrl: "items/mutators/vengeful_strike.png",
		internalSlug: "MetaGem_VengefulStrike_C",
		id: "8h8a9w",
		dlc: "BASE",
		searchableTags: ["Melee Damage", "Critical Chance"],
		description: [
			"Increases Melee damage by 25% - 50% when below 50% Max Health.",
		],
		maxLevelBonus: [
			`Increases Melee Critical Chance by 15% when below 50% Max Health.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Vengeful_Strike`,
		location: { world: "Labyrinth", dungeon: ["Labyrinth"] },
	},
	{
		category: "MUTATOR",
		name: "Weaponlord",
		subcategory: "melee",
		imageUrl: "items/mutators/weaponlord.png",
		internalSlug: "MetaGem_WeaponLord_C",
		id: "w6gpz2",
		dlc: "BASE",
		searchableTags: ["Melee Damage", "Charged Melee", "Critical Chance"],
		description: [
			"Basic Melee Attacks increase the next Charge Attack by 7% - 15%. Max 3 stacks.",
		],
		maxLevelBonus: [
			`At Max Stacks, the next Charge Attack gains 100% Critical Chance.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Weaponlord`,
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
];

export { MUTATORS, type Remnant2MutatorItem };
