import type { BaseRemnant2Item } from "#/games/remnant2/core/types";

type Remnant2PerkItem = BaseRemnant2Item<
	"prime" | "damage" | "team" | "utility" | "relic"
> & {};

const PERKS: Remnant2PerkItem[] = [
	{
		category: "PERK",
		name: "Dead to Rights",
		internalSlug: "Perk_DeadToRightsV3_C",
		imageUrl: "items/perks/hunter_deadtorights.png",
		subcategory: "prime",
		id: "s8eytq",
		dlc: "BASE",
		searchableTags: ["Weakspot Damage"],
		description: [
			"Level 1:\nDealing 65 Base Ranged or Melee Weakspot Damage extends the duration of active Hunter Skills by 2.5s. Can extend timer beyond its initial duration.",
			"Level 5:\nDealing 60 Base Ranged or Melee Weakspot Damage extends the duration of active Hunter Skills by 3s. Can extend timer beyond its initial duration.",
			"Level 10:\nDealing 55 Base Ranged or Melee Weakspot Damage extends the duration of active Hunter Skills by 3.5s. Can extend timer beyond its initial duration.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Dead_to_Rights`,
		linkedItems: {
			archetype: {
				name: "Hunter",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Deadeye",
		internalSlug: "Perk_Deadeye_C",
		imageUrl: "items/perks/hunter_deadeye.png",
		subcategory: "damage",
		id: "c4fx8u",
		dlc: "BASE",
		searchableTags: ["Ranged Damage", "Weakspot Damage", "Critical Chance"],
		description: [
			"Level 1:\nGain 4% Ranged Damage and 1.5% Weakspot Damage.Increases with Hunter Level.",
			"Level 6:\nGain 24% Ranged Damage and 9% Weakspot Damage and 5% Ranged Critical Chance.Damage increases with Hunter Level.",
			"Level 10:\nGain 40% Ranged Damage and 15% Weakspot Damage and 5% Ranged Critical Chance.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Deadeye`,
		linkedItems: {
			archetype: {
				name: "Hunter",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Return to Sender",
		internalSlug: "Perk_ReturnToSender_C",
		imageUrl: "items/perks/hunter_returntosender.png",
		subcategory: "team",
		id: "oyjp3t",
		dlc: "BASE",
		searchableTags: ["Critical Hit", "Weakspot Hit"],
		description: [
			"Level 2:\nKills due to Weakspot and Critical Hits increase Ammo drops by 25%.",
			"Level 7:\nKills due to Weakspot and Critical Hits increase Ammo drops by 50% and double the chance of Ammo drops.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Return_to_Sender`,
		linkedItems: {
			archetype: {
				name: "Hunter",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Urgency",
		internalSlug: "Perk_Urgency_C",
		imageUrl: "items/perks/hunter_urgency.png",
		subcategory: "utility",
		id: "98yqyq",
		dlc: "BASE",
		searchableTags: ["Reload Speed", "Movement Speed"],
		description: [
			"Level 3:\nKills increase Reload Speed by 15%. Lasts 3s.",
			"Level 8:\nKills increase Reload Speed by 15% and Movement Speed by 15%. Lasts 5s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Urgency`,
		linkedItems: {
			archetype: {
				name: "Hunter",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Intuition",
		internalSlug: "Perk_Intuition_C",
		imageUrl: "items/perks/hunter_intuition.png",
		id: "8d4diq",
		dlc: "BASE",
		subcategory: "relic",
		searchableTags: ["Relic Use Speed"],
		description: [
			"Level 4:\nUsing a Relic extends the duration of any active Hunter Skill by 5s. Effect degrades with each subsequent use.",
			"Level 9:\nUsing a Relic extends the duration of any active Hunter Skill by 10s. Effect degrades with each subsequent use. Weakspot kills against MARKED enemies increase speed of next relic use within 15s by 5%. Stacks 10x.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Intuition`,
		linkedItems: {
			archetype: {
				name: "Hunter",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Bonded",
		internalSlug: "Perk_Bonded_C",
		imageUrl: "items/perks/handler_bonded.png",
		id: "d58t4k",
		dlc: "BASE",
		subcategory: "prime",
		description: [
			"Base:\nWhen Handler is downed, Companion will attempt to revive them at 50% Max Health. Can be used to revive allies with Command. Downed ally must have a Relic charge.\nCooldown: 120s",
			"Level 5:\nWhen Handler is downed, Companion will attempt to revive them at 50% Max Health. Can be used to revive allies with Command. Downed ally must have a Relic charge.\nCooldown: 105s",
			"Level 10:\nWhen Handler is downed, Companion will attempt to revive them at 50% Max Health. Can be used to revive allies with Command. Downed ally must have a Relic charge.\nCooldown: 90s",
		],
		wikiUrl: `https://remnant2.wiki.gg/Bonded`,
		linkedItems: {
			archetype: {
				name: "Handler",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Pack Hunter",
		internalSlug: "Perk_PackHunter_C",
		imageUrl: "items/perks/handler_packhunter.png",
		subcategory: "damage",
		id: "485uc9",
		dlc: "BASE",
		searchableTags: ["Ranged Damage", "Skill Damage", "Critical Chance"],
		description: [
			"Level 1:\nGain 3% Ranged, Melee, and Skill Damage while Companion is active and within 40m of the Handler.Increases with Handler Level.",
			"Level 6:\nGain 18% Ranged, Melee, and Skill Damage and 5% Ranged, Melee, and Skill Critical Chance while Companion is active and within 40m of the Handler.Damage increases with Handler Level.",
			"Level 10:\nGain 30% Ranged, Melee, and Skill Damage and 5% Ranged, Melee, and Skill Critical Chance while Companion is active and within 40m of the Handler.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Pack_Hunter`,
		communityTags: [`AOE/Aura`],
		linkedItems: {
			archetype: {
				name: "Handler",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Spirit of the Wolf",
		internalSlug: "Perk_HeartOfThePack_C",
		imageUrl: "items/perks/handler_spiritofthewolf.png",
		subcategory: "team",
		id: "z3sz58",
		dlc: "BASE",
		searchableTags: ["Movement Speed", "Stamina"],
		description: [
			`Level 2:\nIncreases Movement Speed by 10%. All allies within 10m of the Handler gain the Handler's Movement Speed (if faster).`,
			`Level 7:\nIncreases Movement Speed by 10%. All allies within 10m of the Handler gain the Handler's Movement Speed (if faster). Reduces the Stamina Cost of actions for allies by 15%.`,
		],
		wikiUrl: `https://remnant2.wiki.gg/Spirit_of_the_Wolf`,
		communityTags: [`AOE/Aura`],
		linkedItems: {
			archetype: {
				name: "Handler",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Teamwork",
		internalSlug: "Perk_Teamwork_C",
		imageUrl: "items/perks/handler_teamwork.png",
		subcategory: "utility",
		id: "y36q6p",
		dlc: "BASE",
		searchableTags: ["Damage Reduction"],
		description: [
			"Level 3:\nHandler and Companion gain 15% increased Revive Speed.",
			"Level 8:\nHandler and Companion gain 15% increased Revive Speed. While Handler or Companion are reviving, they receive 50% less damage.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Teamwork`,
		linkedItems: {
			archetype: {
				name: "Handler",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Best Friend",
		internalSlug: "Perk_BestFriend_C",
		imageUrl: "items/perks/handler_bestfriend.png",
		subcategory: "relic",
		id: "8vh7yq",
		dlc: "BASE",
		searchableTags: ["Damage Reduction", "All Damage"],
		description: [
			"Level 4:\nUsing a Relic fully restores the Companion's health.",
			"Level 9:\nUsing a Relic fully restores the Companion's health and grants them 25% Damage and 35% Damage Resistance for 15s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Best_Friend`,
		linkedItems: {
			archetype: {
				name: "Handler",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Regenerator",
		internalSlug: "Perk_Regenerator_C",
		imageUrl: "items/perks/medic_regenerator.png",
		subcategory: "prime",
		id: "io3m7t",
		dlc: "BASE",
		description: [
			"Base:\nAfter restoring 350 Total Health to allies, regain a spent Relic charge.Resting or Respawning at a Worldstone resets healing accumulation. Each additional player increases the healing requirement by 50%.",
			"Level 5:\nAfter restoring 300 Total Health to allies, regain a spent Relic charge.Resting or Respawning at a Worldstone resets healing accumulation. Each additional player increases the healing requirement by 50%.",
			"Level 10:\nAfter restoring 250 Total Health to allies, regain a spent Relic charge.Resting or Respawning at a Worldstone resets healing accumulation. Each additional player increases the healing requirement by 50%.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Regenerator`,
		linkedItems: {
			archetype: {
				name: "Medic",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Invigorated",
		internalSlug: "Perk_Invigorated_C",
		imageUrl: "items/perks/medic_invigorated.png",
		subcategory: "damage",
		id: "errks7",
		dlc: "BASE",
		searchableTags: ["All Damage", "Critical Chance"],
		description: [
			"Base:\nGrants a 2.5% increase to All Damage.Increases with Medic Level.",
			"Level 6:\nGrants a 15% increase to All Damage and 5% Critical Chance.Damage increases with Medic Level.",
			"Level 10:\nGrants a 25% increase to All Damage and 5% Critical Chance.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Invigorated`,
		linkedItems: {
			archetype: {
				name: "Medic",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Benevolence",
		internalSlug: "Perk_Benevolence_C",
		imageUrl: "items/perks/medic_benevolence.png",
		subcategory: "team",
		id: "t2fc7j",
		dlc: "BASE",
		description: [
			"Level 2:\nIncreases Relic Efficacy by 15% and heals nearby allies for 30% of the total healing value.",
			"Level 7:\nIncreases Relic Efficacy by 15% and heals nearby allies for 30% of the total healing value, increasing to 60% for any ally below 35% max health.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Benevolence`,
		linkedItems: {
			archetype: {
				name: "Medic",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Backbone",
		internalSlug: "Perk_Backbone_C",
		imageUrl: "items/perks/medic_backbone.png",
		subcategory: "utility",
		id: "z2xo76",
		dlc: "BASE",
		searchableTags: ["Grey Health"],
		description: [
			"Level 3:\nIncreases the hits Medic can take before losing Grey Health by 1.",
			"Level 8:\nIncreases the hits Medic can take before losing Grey Health by 2.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Backbone`,
		linkedItems: {
			archetype: {
				name: "Medic",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Benefactor",
		internalSlug: "Perk_Benefactor_C",
		imageUrl: "items/perks/medic_benefactor.png",
		subcategory: "relic",
		id: "bp9pr7",
		dlc: "BASE",
		searchableTags: ["Relic Use Speed", "Stagger"],
		description: [
			"Level 4:\nIncreases Relic Use Speed by 20%.",
			"Level 9:\nIncreases Relic Use Speed by 20%. Relic Use gains -1 Stagger.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Benefactor`,
		linkedItems: {
			archetype: {
				name: "Medic",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Loaded",
		internalSlug: "Perk_Loaded_C",
		imageUrl: "items/perks/gunslinger_loaded.png",
		subcategory: "prime",
		id: "m6pvhd",
		dlc: "BASE",
		searchableTags: ["Reload Speed", "Ammo Reserves"],
		description: [
			"Base:\nWhen activating any Gunslinger Skill, both weapons are instantly reloaded, and gain infinite reserve ammo on all weapons for 5s .[sic]",
			"Level 5:\nWhen activating any Gunslinger Skill, both weapons are instantly reloaded, and gain infinite reserve ammo on all weapons for 6.5s .[sic]",
			"Level 10:\nWhen activating any Gunslinger Skill, both weapons are instantly reloaded, and gain infinite reserve ammo on all weapons for 8s .[sic]",
		],
		wikiUrl: `https://remnant2.wiki.gg/Loaded`,
		linkedItems: {
			archetype: {
				name: "Gunslinger",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Swift Shot",
		internalSlug: "Perk_SwiftShot_C",
		imageUrl: "items/perks/gunslinger_swiftshot.png",
		subcategory: "damage",
		id: "7mbvc3",
		dlc: "BASE",
		searchableTags: ["Fire Rate", "Ranged Damage", "Critical Chance"],
		description: [
			"Level 1:\nGain 1.5% Fire Rate and 2.5% Ranged Damage.Increases with Gunslinger Level.",
			"Level 6:\nGain 9% Fire Rate, 15% Ranged Damage, and 5% Crit Chance for all firearms.Fire Rate and Damage increases with Gunslinger Level.",
			"Level 10:\nGain 15% Fire Rate, 25% Ranged Damage, and 5% Crit Chance for all firearms.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Swift_Shot`,
		linkedItems: {
			archetype: {
				name: "Gunslinger",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Posse Up",
		internalSlug: "Perk_PosseUp_C",
		imageUrl: "items/perks/gunslinger_posseup.png",
		subcategory: "team",
		id: "ajobx6",
		dlc: "BASE",
		searchableTags: ["Ammo Reserves"],
		description: [
			"Level 2:\nAmmo pickups award 20% additional Ammo per player with the bonus split equally among teammates.",
			"Level 7:\nAmmo pickups award 30% additional Ammo per player with the bonus split equally among teammates. Causes Ammo Box to drop additional ammo on the ground.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Posse_Up`,
		linkedItems: {
			archetype: {
				name: "Gunslinger",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Quick Hands",
		internalSlug: "Perk_QuickHands_C",
		imageUrl: "items/perks/gunslinger_quickhands.png",
		subcategory: "utility",
		id: "496x8y",
		dlc: "BASE",
		searchableTags: ["Reload Speed"],
		description: [
			"Level 3:\nFirearms gain 10% Reload Speed.",
			"Level 8:\nFirearms gain 10% Reload Speed. Bonus is DOUBLED if magazine is empty.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Quick_Hands`,
		linkedItems: {
			archetype: {
				name: "Gunslinger",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Sleight of Hand",
		internalSlug: "Perk_SleightOfHand_C",
		imageUrl: "items/perks/gunslinger_sleightofhand.png",
		subcategory: "relic",
		id: "fspt8u",
		dlc: "BASE",
		searchableTags: ["Reload Speed", "Ranged Damage"],
		description: [
			"Level 4:\nUsing a Relic reloads equipped Firearm.",
			"Level 9:\nUsing a Relic reloads equipped Firearm and increases Ranged Damage by 15% for 10s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Sleight_of_Hand`,
		linkedItems: {
			archetype: {
				name: "Gunslinger",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Die Hard",
		internalSlug: "Perk_DieHard_C",
		imageUrl: "items/perks/challenger_diehard.png",
		subcategory: "prime",
		id: "je27uv",
		dlc: "BASE",
		searchableTags: ["Heal"],
		description: [
			"Base:\nWhen receiving fatal damage, the Challenger becomes invulnerable for 2s and regenerates 50% of Max Health.While on cooldown, the Challenger gains 1 Stack of BULWARK. Can only happen once every 10 minutes. Resets at Worldstone or on death.",
			"Level 5:\nWhen receiving fatal damage, the Challenger becomes invulnerable for 2.5s and regenerates 75% of Max Health.While on cooldown, the Challenger gains 1 Stack of BULWARK. Can only happen once every 10 minutes. Resets at Worldstone or on death.",
			"Level 10:\nWhen receiving fatal damage, the Challenger becomes invulnerable for 3s and regenerates 100% of Max Health.While on cooldown, the Challenger gains 1 Stack of BULWARK. Can only happen once every 10 minutes. Resets at Worldstone or on death.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Die_Hard`,
		linkedItems: {
			archetype: {
				name: "Challenger",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Close Quarters",
		internalSlug: "Perk_CloseQuarters_C",
		imageUrl: "items/perks/challenger_closequarters.png",
		subcategory: "damage",
		id: "f4jx9k",
		dlc: "BASE",
		searchableTags: ["All Damage", "Critical Chance"],
		description: [
			"Level 1:\nGrants a 3.5% increase to All Damage to enemies within 10m. Damage bonus tapers off until 20m.Increases with Challenger Level.",
			"Level 6:\nGrants a 21% increase to All Damage to enemies within 10m. Damage bonus tapers off until 20m. Critical Chance is increased by 5%.Damage increases with Challenger Level.",
			"Level 10:\nGrants a 35% increase to All Damage to enemies within 10m. Damage bonus tapers off until 20m. Critical Chance is increased by 5%.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Close_Quarters`,
		linkedItems: {
			archetype: {
				name: "Challenger",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Intimidating Presence",
		internalSlug: "Perk_IntimidatingPresence_C",
		imageUrl: "items/perks/challenger_intimidatingpresence.png",
		subcategory: "team",
		id: "c92847",
		dlc: "BASE",
		searchableTags: ["Damage Reduction"],
		description: [
			"Level 2:\nAfter activating a Challenger Skill, enemies within 15m deal 10% less damage for 15s.",
			"Level 7:\nAfter activating a Challenger Skill, enemies within 15m deal 10% less damage for 15s, with an additional 2.5% damage reduction per enemy affected. (Max 10%).",
		],
		wikiUrl: `https://remnant2.wiki.gg/Intimidating_Presence`,
		communityTags: [`AOE/Aura`],
		linkedItems: {
			archetype: {
				name: "Challenger",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Powerlifter",
		internalSlug: "Perk_PowerLifter_C",
		imageUrl: "items/perks/challenger_powerlifter.png",
		subcategory: "utility",
		id: "8p55rw",
		dlc: "BASE",
		searchableTags: ["Stamina", "Encumbrance"],
		description: [
			"Level 3:\nThe Stamina Cost increase for each weight bracket is reduced by 50%.",
			"Level 8:\nBoth the Stamina cost increase for each weight bracket and Stamina Regen Delay are reduced by 50%.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Powerlifter`,
		linkedItems: {
			archetype: {
				name: "Challenger",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Face of Danger",
		internalSlug: "Perk_FaceOfDanger_C",
		imageUrl: "items/perks/challenger_faceofdanger.png",
		subcategory: "relic",
		id: "7dvm5a",
		dlc: "BASE",
		searchableTags: ["Damage Reduction", "All Damage"],
		description: [
			"Level 4:\nUsing a Relic within 10m of an enemy grants 2 stacks of BULWARK for 10s.",
			"Level 9:\nUsing a Relic within 10m of an enemy grants 2 stacks of BULWARK and 10% Increased Damage for 10s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Face_of_Danger`,
		linkedItems: {
			archetype: {
				name: "Challenger",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Spirited",
		internalSlug: "Perk_Spirited_C",
		imageUrl: "items/perks/alchemist_spirited.png",
		subcategory: "prime",
		id: "rx6e2w",
		dlc: "BASE",
		searchableTags: ["Concoction"],
		description: [
			"Base:\nAlchemist can have 1 additional Concoction buff active.",
			"Level 5:\nAlchemist can have 2 additional Concoction buffs active.",
			"Level 10:\nAlchemist can have 3 additional Concoction buffs active.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Spirited`,
		linkedItems: {
			archetype: {
				name: "Alchemist",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Liquid Courage",
		internalSlug: "Perk_LiquidCourage_C",
		imageUrl: "items/perks/alchemist_liquidcourage.png",
		subcategory: "damage",
		id: "5exhee",
		dlc: "BASE",
		searchableTags: ["All Damage", "Critical Chance"],
		description: [
			"Level 1:\nGrant a 2.5% increase to All Damage.Increases with Alchemist Level.",
			"Level 6:\nGrant a 15% increase to All Damage and 5% Critical Chance.Damage increasees with Alchemist Level.",
			"Level 10:\nGrant a 25% increase to All Damage and 5% Critical Chance.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Liquid_Courage`,
		linkedItems: {
			archetype: {
				name: "Alchemist",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Panacea",
		internalSlug: "Perk_Panacea_C",
		imageUrl: "items/perks/alchemist_panacea.png",
		subcategory: "team",
		id: "49i5jm",
		dlc: "BASE",
		searchableTags: ["Damage Reduction"],
		description: [
			"Level 2:\nCurative effects apply to all allies within 15m, and grant 15 additional Resistance.",
			"Level 7:\nCurative effects apply to all allies within 15m, and grant 15 additional Resistance. Allies affected by Panacea gain 10 Status and Blight Resistance.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Panacea`,
		linkedItems: {
			archetype: {
				name: "Alchemist",
			},
		},
		modifiers: {
			resistFire: 15,
			resistShock: 15,
			resistBlight: 15,
			resistBleed: 15,
			resistToxin: 15,
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Gold to Lead",
		internalSlug: "Perk_GoldToLead_C",
		imageUrl: "items/perks/alchemist_goldtolead.png",
		subcategory: "utility",
		id: "3a9dd2",
		dlc: "BASE",
		searchableTags: ["Ammo Reserves"],
		description: [
			"Level 3:\nPicking up Scrap has a 15% chance to also award Ammo to the Alchemist.",
			"Level 8:\nPicking up Scrap or Metals has a 15% chance to award Ammo to the Alchemist.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Gold_To_Lead`,
		linkedItems: {
			archetype: {
				name: "Alchemist",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Experimentalist",
		internalSlug: "Perk_Experimentalist_C",
		imageUrl: "items/perks/alchemist_experimentalist.png",
		subcategory: "relic",
		id: "cxnnz9",
		dlc: "BASE",
		description: [
			"Level 4:\nUsing a Relic applies a random buff on the Alchemist for 30s. Cannot be overriden.",
			"Level 9:\nUsing a Relic applies a random buff on the Alchemist and all allies within 20m for 60s. Cannot be overriden.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Experimentalist`,
		linkedItems: {
			archetype: {
				name: "Alchemist",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Tempest",
		internalSlug: "Perk_Tempest_C",
		imageUrl: "items/perks/archon_tempest.png",
		subcategory: "prime",
		id: "dh2wih",
		dlc: "BASE",
		searchableTags: ["Mod Power"],
		description: [
			"Base:\nAutomatically generate 5 Mod Power per second. Casting a Mod doubles this value for 10s.",
			"Level 5:\nAutomatically generate 10 Mod Power per second. Casting a Mod doubles this value for 10s.",
			"Level 10:\nAutomatically generate 15 Mod Power per second. Casting a Mod doubles this value for 10s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Tempest`,
		linkedItems: {
			archetype: {
				name: "Archon",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Amplify",
		internalSlug: "Perk_Amplify_C",
		imageUrl: "items/perks/archon_amplify.png",
		subcategory: "damage",
		id: "yro37y",
		dlc: "BASE",
		searchableTags: ["Mod Damage", "Critical Chance"],
		description: [
			"Level 1:\nIncreases Mod Damage by 5%.Increases with Archon Level.",
			"Level 5:\nIncreases Mod Damage by 25% and grants 10% Mod Critical Chance.Increases with Archon Level.",
			"Level 10:\nIncreases Mod Damage by 50% and grants 10% Mod Critical Chance.Increases with Archon Level.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Amplify`,
		linkedItems: {
			archetype: {
				name: "Archon",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Power Creep",
		internalSlug: "Perk_PowerCreep_C",
		imageUrl: "items/perks/archon_powercreep.png",
		subcategory: "team",
		id: "7ay3kh",
		dlc: "BASE",
		searchableTags: ["Mod Power"],
		description: [
			"Level 1:\nAfter casting a Mod, 10% of the Mod Power spent will be regenerated by all allies over 10s.",
			"Level 7:\nAfter casting a Mod, 10% of the Mod Power spent will be regenerated by all allies over 10s. While Power Creep is active, allies will also gain 10% Mod Power Generation.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Power_Creep`,
		linkedItems: {
			archetype: {
				name: "Archon",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Spirit Within",
		internalSlug: "Perk_SpiritWithin_C",
		imageUrl: "items/perks/archon_spiritwithin.png",
		subcategory: "utility",
		id: "5fz7xr",
		dlc: "BASE",
		searchableTags: ["Mod Power"],
		description: [
			"Level 3:\nReduces Mod Power requirement per charge by 5%",
			"Level 8:\nReduces Mod Power requirement per charge by 10%.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Spirit_Within`,
		linkedItems: {
			archetype: {
				name: "Archon",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Power Leak",
		internalSlug: "Perk_PowerLeak_C",
		imageUrl: "items/perks/archon_powerleak.png",
		subcategory: "relic",
		id: "h42e2n",
		dlc: "BASE",
		searchableTags: ["Mod Power"],
		description: [
			"Level 4:\nUsing a Relic grants 100 Mod Power for both equipped Mods.",
			"Level 9:\nUsing a Relic grants 100 Mod Power for both equipped Mods, and an additional 100 to current Mod.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Power_Leak`,
		linkedItems: {
			archetype: {
				name: "Archon",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "High Tech",
		internalSlug: "Perk_HighTech_C",
		imageUrl: "items/perks/engineer_hightech.png",
		subcategory: "prime",
		id: "98qnpc",
		dlc: "BASE",
		description: [
			"Base:\nHolding the SKILL button will Overclock a Carried or Deployed Heavy Weapon. Overclocking grants Infinite Ammo, Increased Fire Rate, and a 25% Damage increase for 15s.\nCooldown: 60s",
			"Level 5:\nHolding the SKILL button will Overclock a Carried or Deployed Heavy Weapon. Overclocking grants Infinite Ammo, Increased Fire Rate, and a 25% Damage increase for 20s.\nCooldown: 60s",
			"Level 10:\nHolding the SKILL button will Overclock a Carried or Deployed Heavy Weapon. Overclocking grants Infinite Ammo, Increased Fire Rate, and a 25% Damage increase for 25s.\nCooldown: 60s",
		],
		wikiUrl: `https://remnant2.wiki.gg/High_Tech`,
		linkedItems: {
			archetype: {
				name: "Engineer",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Metalworker",
		internalSlug: "Perk_Metalworker_C",
		imageUrl: "items/perks/engineer_metalworker.png",
		subcategory: "damage",
		id: "2hcif5",
		dlc: "BASE",
		searchableTags: ["Skill Damage", "Critical Chance"],
		description: [
			"Level 1:\nIncreases Skill Damage by 5% and Ranged Damage by 2.5%.Heavy Weapons gain 5% Ammo Capacity and 2.5% Max Health.\n",
			"Level 6:\nIncreases Skill Damage by 25% and Ranged Damage by 12.5%, and grants 5% Skill and Ranged Critical Chance.Heavy Weapons gain 25% Ammo Capacity, 12.5% Max Health, and 25% Weakspot Damage.\n",
			"Level 10:\nIncreases Skill Damage by 50% and Ranged Damage by 25%, and grants 5% Skill and Ranged Critical Chance.Heavy Weapons gain 50% Ammo Capacity, 25% Max Health, and 25% Weakspot Damage.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Metalworker`,
		linkedItems: {
			archetype: {
				name: "Engineer",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Magnetic Field",
		internalSlug: "Perk_MagneticField_C",
		imageUrl: "items/perks/engineer_magneticfield.png",
		subcategory: "team",
		id: "w6v2o6",
		dlc: "BASE",
		searchableTags: ["Damage Reduction", "Ammo Reserves"],
		description: [
			"Level 2:\nHeavy Weapons grant 15% Damage Reduction to all allies within 2.5m.",
			"Level 7:\nHeavy Weapons grant 15% Damage Reduction and gradually restore Ammo to all allies within 2.5m.",
		],
		communityTags: [`AOE/Aura`],
		wikiUrl: `https://remnant2.wiki.gg/Magnetic_Field`,
		linkedItems: {
			archetype: {
				name: "Engineer",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Heavy Mobility",
		internalSlug: "Perk_HeavyMobility_C",
		imageUrl: "items/perks/engineer_heavymobility.png",
		subcategory: "utility",
		id: "htf7h4",
		dlc: "BASE",
		searchableTags: ["Movement Speed"],
		description: [
			"Level 3:\nMovement Speed while Carrying a Heavy Weapon is increased by 35%.",
			"Level 8:\nWhile Carrying a Heavy Weapon, Movement Speed is increased by 35%, and both Evade Speed and Evade Distance are increased by 25%.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Heavy_Mobility`,
		linkedItems: {
			archetype: {
				name: "Engineer",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Surplus",
		internalSlug: "Perk_Surplus_C",
		imageUrl: "items/perks/engineer_surplus.png",
		subcategory: "relic",
		id: "2k4yzk",
		dlc: "BASE",
		description: [
			"Level 4:\nUsing a Relic refills 15% of Heavy Weapon Ammo. Bonus is doubled when Heavy Weapon is stowed.",
			"Level 9:\nUsing a Relic refills 15% of Heavy Weapon ammo. Bonus is doubled when Heavy Weapon is stowed. If the Stowed Heavy Weapon is overfilled, the Engineer will drop additional Ammo based on the surplus.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Surplus`,
		linkedItems: {
			archetype: {
				name: "Engineer",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Lucky",
		internalSlug: "Perk_Lucky_C",
		imageUrl: "items/perks/explorer_lucky.png",
		subcategory: "prime",
		id: "82y94m",
		dlc: "BASE",
		description: [
			"Base:\nGrants a 10% chance to spawn additional items and rarer drops when defeating stronger enemies.",
			"Level 5:\nGrants a 20% chance to spawn additional items and rarer drops when defeating stronger enemies.",
			"Level 10:\nGrants a 35% chance to spawn additional items and rarer drops when defeating stronger enemies.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Lucky`,
		linkedItems: {
			archetype: {
				name: "Explorer",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Scavenger",
		internalSlug: "Perk_Lucky_C",
		imageUrl: "items/perks/explorer_scavenger.png",
		subcategory: "damage",
		id: "y6x5dr",
		dlc: "BASE",
		searchableTags: ["All Damage", "Critical Chance"],
		description: [
			"Level 1:\nPickups increase All Damage dealt by 0.5% per stack for 20s. Additional Stacks increase Duration up to 60s. Max 5 stacks.Effect increase with Explorer level.",
			"Level 6:\nPickups increase All Damage dealt by 3% per stack for 20s and All Crit Chance by 5%. Additional Stacks increase Duration up to 60s. Max 5 stacks.Damage increases with Explorer level.",
			"Level 10:\nPickups increase All Damage dealt by 5% per stack for 20s and All Crit Chance by 5%. Additional Stacks increase Duration up to 60s. Max 5 stacks.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Scavenger`,
		linkedItems: {
			archetype: {
				name: "Explorer",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Metal Detector",
		internalSlug: "Perk_MetalDetector_C",
		imageUrl: "items/perks/explorer_metaldetector.png",
		subcategory: "team",
		id: "w838yg",
		dlc: "BASE",
		description: [
			"Level 2:\nIncrease Ammo, Currency, and Metal Drop Rate Chance for entire party by 10%.",
			"Level 7:\nIncrease Ammo, Currency, and Metal Drop Rate Chance for entire party by 10% and increases the chance of Consumables being rewarded from Chests.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Metal_Detector`,
		linkedItems: {
			archetype: {
				name: "Explorer",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Prospector",
		internalSlug: "Perk_Prospector_C",
		imageUrl: "items/perks/explorer_prospector.png",
		subcategory: "utility",
		id: "o5q3p9",
		dlc: "BASE",
		description: [
			"Level 3:\nRelic Fragments discovered by the Explorer drop at a higher quality.",
			"Level 8:\nRelic Fragments discovered by the Explorer drop at a higher quality. When picking up a Fragment, the Explorer has a 5% chance of picking up a second one of the same type & quality.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Prospector`,
		linkedItems: {
			archetype: {
				name: "Explorer",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Self Discovery",
		internalSlug: "Perk_SelfDiscovery_C",
		imageUrl: "items/perks/explorer_selfdiscovery.png",
		subcategory: "relic",
		id: "rvb63g",
		dlc: "BASE",
		description: [
			"Level 4:\nUsing a Relic instantly fills Scavenger Stacks and prevents Stack Decay for 15s.",
			"Level 9:\nUsing a Relic instantly fills Scavenger Stacks, grants +1 Stack, and prevents Stack Decay for 30s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Self_Discovery`,
		linkedItems: {
			archetype: {
				name: "Explorer",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Shadow",
		internalSlug: "Perk_ShadowNEW_C",
		imageUrl: "items/perks/invader_shadow.png",
		subcategory: "prime",
		id: "yg77rq",
		dlc: "BASE",
		searchableTags: ["All Damage"],
		description: [
			"Base:\nCasting an Invader Skill leaves a Decoy for 3s which draws enemy fire. Deal 5% additional damage to enemies not targeting Invader.",
			"Level 5:\nCasting an Invader Skill leaves a Decoy for 3s which draws enemy fire. Deal 10% additional damage to enemies not targeting Invader.",
			"Level 10:\nCasting an Invader Skill leaves a Decoy for 3s which draws enemy fire. Deal 15% additional damage to enemies not targeting Invader.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Shadow`,
		linkedItems: {
			archetype: {
				name: "Invader",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "S.H.A.R.K.",
		internalSlug: "Perk_SHARK_C",
		imageUrl: "items/perks/invader_shark.png",
		subcategory: "damage",
		id: "59swqq",
		dlc: "BASE",
		searchableTags: [
			"Ranged Damage",
			"Melee Damage",
			"Melee Critical Chance",
			"Critical Chance",
		],
		description: [
			"Base:\nSprinting for 1s or Evading adds 1 Stack of Momentum which increases Ranged and Melee damage by 0.7% for 10s. Max 5 Stacks.Perfect Dodges instantly add 5 Stacks.Damage increases with Invader level.",
			"Level 6:\nSprinting for 1s or Evading adds 1 Stack of Momentum which increases Ranged and Melee damage by 3.5% and Ranged and Melee Critical Chance by 1% for 10s. Max 5 Stacks.Perfect Dodges instantly add 5 Stacks.Damage increases with Invader level.",
			"Level 10:\nSprinting for 1s or Evading adds 1 Stack of Momentum which increases Ranged and Melee damage by 7% and Ranged and Melee Critical Chance by 1% for 10s. Max 5 Stacks.Perfect Dodges instantly add 5 Stacks.Damage increases with Invader level.",
		],
		wikiUrl: `https://remnant2.wiki.gg/S.H.A.R.K.`,
		linkedItems: {
			archetype: {
				name: "Invader",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Loophole",
		internalSlug: "Perk_Loophole_C",
		imageUrl: "items/perks/invader_loophole.png",
		subcategory: "team",
		id: "d5qedi",
		dlc: "BASE",
		searchableTags: ["Lifesteal"],
		description: [
			"Level 2:\nAll ally Ranged and Melee damage against enemies distracted by the Invader's Decoy grants 5% base damage as Lifesteal.",
			"Level 7:\nAll ally Ranged and Melee damage against enemies distracted by the Invader's Decoy grants 7.5% base damage as Lifesteal.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Loophole`,
		linkedItems: {
			archetype: {
				name: "Invader",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Circumvent",
		internalSlug: "Perk_Bypass_C",
		imageUrl: "items/perks/invader_circumvent.png",
		subcategory: "utility",
		id: "i9tjgk",
		dlc: "BASE",
		searchableTags: [
			"Perfect Neutral Evade",
			"Neutral Dodge",
			"Perfect Dodge",
			"Stamina",
		],
		description: [
			"Level 3:\nReduce Cost of Evade and Combat Slide by 10%.",
			"Level 8:\nReduce Cost of Evade and Combat Slide by 15% Perfect Dodges gain an additional 15% reduction.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Circumvent`,
		linkedItems: {
			archetype: {
				name: "Invader",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Override",
		internalSlug: "Perk_Override_C",
		imageUrl: "items/perks/invader_override.png",
		subcategory: "relic",
		id: "decoy8",
		dlc: "BASE",
		description: [
			"Level 4:\nUsing a Relic reduces Threat Generation by 25% for 10s. While Override is active, the next Evade leaves an Empowered Decoy which lasts 4s.",
			"Level 9:\nUsing a Relic reduces Threat Generation by 25% for 10s. While Override is active, the next Evade leaves an Empowered Decoy which lasts 5.5s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Override`,
		linkedItems: {
			archetype: {
				name: "Invader",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Ruthless",
		internalSlug: "Perk_Ruthless_C",
		imageUrl: "items/perks/summoner_ruthless.png",
		subcategory: "prime",
		id: "tmc2tk",
		dlc: "BASE",
		searchableTags: ["Summon"],
		description: [
			"Base:\nWhen the Summoner deals damage to their Minion, it causes them to ENRAGE. While ENRAGED, Minions gain 10% Attack Speed along with 30% increased Damage and Movement Speed. Lasts 20s.",
			"Level 5:\nWhen the Summoner deals damage to their Minion, it causes them to ENRAGE. While ENRAGED, Minions gain 15% Attack Speed along with 40% increased Damage and Movement Speed. Lasts 30s.",
			"Level 10:\nWhen the Summoner deals damage to their Minion, it causes them to ENRAGE. While ENRAGED, Minions gain 20% Attack Speed along with 50% increased Damage and Movement Speed. Lasts 40s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Ruthless`,
		linkedItems: {
			archetype: {
				name: "Summoner",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Dominator",
		internalSlug: "Perk_Dominator_C",
		imageUrl: "items/perks/summoner_dominator.png",
		subcategory: "damage",
		id: "tu8pcp",
		dlc: "BASE",
		searchableTags: [
			"Mod Damage",
			"Skill Damage",
			"Ranged Damage",
			"Melee Damage",
			"Critical Chance",
			"Melee Critical Chance",
		],
		description: [
			"Level 1:\nGrants a 3.5% increase to Mod, Skill, and Explosive Damage.Increases with Summoner Level.",
			"Level 5:\nGrants a 17.5% increase to Mod, Skill, and Explosive Damage, and 5% Mod, Skill, and Explosive Critical Chance.Damage increases with Summoner Level.",
			"Level 10:\nGrants a 35% increase to Mod, Skill, and Explosive Damage, and 5% Mod, Skill, and Explosive Critical Chance.",
		],
		communityTags: [`Explosive Damage`],
		wikiUrl: `https://remnant2.wiki.gg/Dominator`,
		linkedItems: {
			archetype: {
				name: "Summoner",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Residue",
		internalSlug: "Perk_Residue_C",
		imageUrl: "items/perks/summoner_residue.png",
		subcategory: "team",
		id: "fzywc2",
		dlc: "BASE",
		searchableTags: ["Heal", "Healing Effectiveness"],
		description: [
			"Level 2:\nMinions that expire leave a 3m Aura which heals 2.5% Health per second. Lasts 10s.",
			"Level 7:\nMinions that expire leave a 3m Aura which heals 2.5% Health per second and increases Healing by 20%. Lasts 10s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Residue`,
		linkedItems: {
			archetype: {
				name: "Summoner",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Outrage",
		internalSlug: "Perk_Outrage_C",
		imageUrl: "items/perks/summoner_outrage.png",
		subcategory: "utility",
		id: "t8bb9k",
		dlc: "BASE",
		searchableTags: ["Lifesteal", "Movement Speed"],
		description: [
			"Level 3:\nSacrifice grants 3% Lifesteal for each Minion Sacrificed. Lasts 10s.",
			"Level 8:\nSacrifice grants 3% Lifesteal for each Minion Sacrificed, and increases Movement Speed by 15%. Lasts 10s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Outrage`,
		linkedItems: {
			archetype: {
				name: "Summoner",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Incite",
		internalSlug: "Perk_Incite_C",
		imageUrl: "items/perks/summoner_incite.png",
		subcategory: "relic",
		id: "d82mwz",
		dlc: "BASE",
		description: [
			"Level 4:\nUsing a Relic grants Minions 5% Max HP per second, and increases their damage dealt by 15%. Lasts 30s.",
			"Level 9:\nUsing a Relic grants Minions 5% Max HP per second, and increases their damage dealt by 15% and Crit Chance by 15%. Lasts 30s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Incite`,
		linkedItems: {
			archetype: {
				name: "Summoner",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Vile",
		internalSlug: "PrimePerk_Vile_C",
		imageUrl: "items/perks/ritualist_vile.png",
		subcategory: "prime",
		id: "qewh6t",
		dlc: "BASE",
		searchableTags: ["Status Effect"],
		description: [
			"Base:\nNegative Status Effects applied by Ritualist inflict INFECTED.INFECTED: Victim receives 5% more Status Effect damage. On death, spreads all statuses to nearby enemies within 5m.\n",
			"Level 5:\nNegative Status Effects applied by Ritualist inflict INFECTED.INFECTED: Victim receives 10% more Status Effect damage. On death, spreads all statuses to nearby enemies within 10m.\n",
			"Level 10:\nNegative Status Effects applied by Ritualist inflict INFECTED.INFECTED: Victim receives 15% more Status Effect damage. On death, spreads all statuses to nearby enemies within 15m.",
		],
		communityTags: [`AOE/Aura`],
		wikiUrl: `https://remnant2.wiki.gg/Vile`,
		linkedItems: {
			archetype: {
				name: "Ritualist",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Wrath",
		internalSlug: "Perk_Wrath_C",
		imageUrl: "items/perks/ritualist_wrath.png",
		subcategory: "damage",
		id: "6wc56t",
		dlc: "BASE",
		searchableTags: ["All Damage", "Critical Chance", "Status Effect"],
		description: [
			"Level 1:\nIncreases all damage to enemies affected by a Negative Status Effect by 2.5%.Increases with Ritualist Level.\n",
			"Level 6:\nIncreases all damage to enemies affected by a Negative Status Effect by 15%. Increases all Critical Chance against enemies affected by a Negative Status Effect by 5%.Damage increases with Ritualist Level.\n",
			"Level 10:\nIncreases all damage to enemies affected by a Negative Status Effect by 25%. Increases all Critical Chance against enemies affected by a Negative Status Effect by 5%.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Wrath`,
		linkedItems: {
			archetype: {
				name: "Ritualist",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Terrify",
		internalSlug: "Perk_Terrify_C",
		imageUrl: "items/perks/ritualist_terrify.png",
		subcategory: "team",
		id: "h3ag53",
		dlc: "BASE",
		searchableTags: ["Damage Reduction", "Ammo Reserves"],
		description: [
			"Level 2:\nKilling an entity applies TERRIFIED to all enemies within 5m of killed entity for 20s.TERRIFIED: Victim deals 5% less damage.",
			"Level 7:\nKilling an entity applies TERRIFIED to all enemies within 5m of killed entity for 20s. TERRIFIED enemies are more likely to drop additional Ammo on death.TERRIFIED: Victim deals 5% less damage.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Terrify`,
		linkedItems: {
			archetype: {
				name: "Ritualist",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Dark Blood",
		internalSlug: "Perk_DarkBlood_C",
		imageUrl: "items/perks/ritualist_darkblood.png",
		subcategory: "utility",
		id: "qqhkw9",
		dlc: "BASE",
		searchableTags: ["Damage Reduction"],
		description: [
			"Level 3:\nReduces damage received from Negative Status Effects by 25%.",
			"Level 8:\nReduces damage received from Negative Status Effects by 25%. Reduces Blight Buildup by 50%.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Dark_Blood`,
		linkedItems: {
			archetype: {
				name: "Ritualist",
			},
		},
		location: undefined,
		modifiers: {
			resistBlight: 50,
		},
	},
	{
		category: "PERK",
		name: "Purge",
		internalSlug: "Perk_Purge_C",
		imageUrl: "items/perks/ritualist_purge.png",
		subcategory: "relic",
		id: "tr5r38",
		dlc: "BASE",
		searchableTags: ["Status Effect"],
		description: [
			"Level 4:\nOn Relic Use, cleanses all Negative Status Effects.",
			"Level 9:\nOn Relic Use, cleanses all Negative Status Effects. Negative Status Effects cleansed by Purge are applied to all enemies within 7.5m.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Purge`,
		linkedItems: {
			archetype: {
				name: "Ritualist",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Visionary",
		internalSlug: "PrimePerk_Visionary_C",
		imageUrl: "items/perks/invoker_visionary.png",
		subcategory: "prime",
		id: "hYsQ4M",
		dlc: "DLC2",
		searchableTags: ["Reduce Skill Cooldown"],
		description: [
			"Base:\nDoubles Base Skill Charges for all Archetypes. Skill activation reduces all Skill Cooldowns by 3%.For Heavy Weapons, doubles Heavy Base Ammo instead.",
			"Level 5:\nDoubles Base Skill Charges for all Archetypes. Skill activation reduces all Skill Cooldowns by 6%.For Heavy Weapons, doubles Heavy Base Ammo instead.",
			"Level 10:\nDoubles Base Skill Charges for all Archetypes. Skill activation reduces all Skill Cooldowns by 10%.For Heavy Weapons, doubles Heavy Base Ammo instead.",
		],
		wikiUrl: "https://remnant2.wiki.gg/Visionary",
		linkedItems: {
			archetype: {
				name: "Invoker",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Entranced",
		internalSlug: "Perk_Entranced_C",
		imageUrl: "items/perks/invoker_entranced.png",
		subcategory: "damage",
		id: "Y9Tj7F",
		dlc: "DLC2",
		searchableTags: [],
		description: [
			"Level 1:\nIncreases Skill Damage by 3%, Elemental Damage by 1.5%.Increases with Invoker Level.",
			"Level 6:\nIncreases Skill Damage by 16%, Elemental Damage by 9%, and Skill and Elemental Critical Chance by 5%.Damage increases with Invoker Level.",
			"Level 10:\nIncreases Skill Damage by 30%, Elemental Damage by 15%, and Skill and Elemental Critical Chance by 5%.",
		],
		wikiUrl: "https://remnant2.wiki.gg/Entranced",
		linkedItems: {
			archetype: {
				name: "Invoker",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Communion",
		internalSlug: "Perk_Communion_C",
		imageUrl: "items/perks/invoker_communion.png",
		subcategory: "team",
		id: "GV9bDr",
		dlc: "DLC2",
		searchableTags: [],
		description: [
			"Level 2:\nReduces Skill Cooldowns by 1% once every 3s for allies while an Invoker Skill is active.",
			"Level 7:\nReduces Skill Cooldowns by 1% and Heals 2% Max Health once every 3s for allies while an Invoker Skill is active.",
		],
		wikiUrl: "https://remnant2.wiki.gg/Communion",
		linkedItems: {
			archetype: {
				name: "Invoker",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Mind and Body",
		internalSlug: "Perk_MindAndBody_C",
		imageUrl: "items/perks/invoker_mindandbody.png",
		subcategory: "utility",
		id: "T2U4dZ",
		dlc: "DLC2",
		searchableTags: [],
		description: [
			"Level 3:\nIncreases Movement Speed by 5% while an Invoker Skill is active.",
			"Level 8:\nIncreases Movement Speed by 5% and Damage Reduction by 5% while an Invoker Skill is active.",
		],
		wikiUrl: "https://remnant2.wiki.gg/Mind_and_Body",
		linkedItems: {
			archetype: {
				name: "Invoker",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Soothsayer",
		internalSlug: "Perk_Soothsayer_C",
		imageUrl: "items/perks/invoker_soothsayer.png",
		subcategory: "relic",
		id: "j7e5Bb",
		dlc: "DLC2",
		searchableTags: ["Relic Use Speed", "Skill Duration"],
		description: [
			"Level 4:\nOn Relic use, extend the duration of active Invoker skills by 20% of the base duration. Cannot exceed base duration.",
			"Level 9:\nOn Relic use, extend the duration of active Invoker skills by 20% of the base duration. Cannot exceed base duration.Relic Use Speed increased by 25% while an Invoker Skill is active.",
		],
		wikiUrl: "https://remnant2.wiki.gg/Soothsayer",
		linkedItems: {
			archetype: {
				name: "Invoker",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Dynamic",
		internalSlug: "Perk_Dynamic_C",
		imageUrl: "items/perks/warden_dynamic.png",
		subcategory: "prime",
		id: "no6oxo",
		dlc: "DLC3",
		searchableTags: [],
		description: [
			`After 10s of not being damaged, the Warden generates a SHIELD for 20% of their Max Health over 2s.`,
			`Increases base N'Erudian Energy Reserves for Turret and Drone by 100%.`,
		],
		wikiUrl: "https://remnant2.wiki.gg/Dynamic",
		communityTags: [],
		linkedItems: {
			archetype: {
				name: "Warden",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Galvanize",
		internalSlug: "Perk_WardenGalvanize_C",
		imageUrl: "items/perks/warden_galvanize.png",
		subcategory: "damage",
		id: "1yfbk0",
		dlc: "DLC3",
		searchableTags: ["All Damage", "Critical Chance"],
		description: [
			`Increases All Damage by 25% and grants 5% Critical Chance.`,
			`Damage increases with Warden Level.`,
		],
		wikiUrl: "https://remnant2.wiki.gg/Galvanize",
		communityTags: [],
		linkedItems: {
			archetype: {
				name: "Warden",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Safeguard",
		internalSlug: "Perk_WardenSafeguard_C",
		imageUrl: "items/perks/warden_safeguard.png",
		subcategory: "team",
		id: "w3gyt0",
		dlc: "DLC3",
		searchableTags: ["Damage Reduction", "Healing Effectiveness"],
		description: [
			"The Warden's Drone grants 1 stack of BULWARK and increases incoming Healing Effectiveness by 10% to its Warded Target.",
		],
		wikiUrl: "https://remnant2.wiki.gg/Safeguard",
		communityTags: [],
		linkedItems: {
			archetype: {
				name: "Warden",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Contingency",
		internalSlug: "Perk_WardenContingency_C",
		imageUrl: "items/perks/warden_contingency.png",
		subcategory: "utility",
		id: "odd85z",
		dlc: "DLC3",
		searchableTags: ["Movement Speed"],
		description: [
			`When the Warden's Health drops below 25%, gain a SHIELD for 25% of Max Health. Lasts 10s. Can only happen once every 30s.`,
			`While active, increases Movement Speed by 15%.`,
		],
		wikiUrl: "https://remnant2.wiki.gg/Contingency",
		communityTags: [],
		linkedItems: {
			archetype: {
				name: "Warden",
			},
		},
		location: undefined,
	},
	{
		category: "PERK",
		name: "Energize",
		internalSlug: "Perk_WardenEnergize_C",
		imageUrl: "items/perks/warden_energize.png",
		subcategory: "relic",
		id: "c6k3ke",
		dlc: "DLC3",
		searchableTags: [],
		description: [
			`On Relic Use, grants a SHIELD for 25% of Max Health Cannot stack with itself. Lasts 10s or until SHIELD is removed by damage.`,
			`While active, actions which consume N'Erudian Energy have no cost.`,
		],
		wikiUrl: "https://remnant2.wiki.gg/Energize",
		communityTags: [],
		linkedItems: {
			archetype: {
				name: "Warden",
			},
		},
		location: undefined,
	},
];

export { PERKS, type Remnant2PerkItem };
