import type { BaseRemnant2Item } from "#/games/remnant2/core/types";

type Remnant2PrismItem = BaseRemnant2Item & {};

const PRISMS: Remnant2PrismItem[] = [
	{
		category: "PRISM",
		name: "Prism of Greed",
		id: "zn2x47",
		dlc: "BASE",
		imageUrl: "items/prisms/prismofgreed.png",
		internalSlug: "PrismOfGreed_C",
		description: [],
		wikiUrl: "https://remnant2.wiki.gg/Prism",
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "PRISM",
		name: "Prism of Hatred",
		id: "t15adx",
		dlc: "BASE",
		imageUrl: "items/prisms/prismofhatred.png",
		internalSlug: "PrismOfHatred_C",
		description: [],
		wikiUrl: "https://remnant2.wiki.gg/Prism",
		location: { world: "Any", dungeon: "Quest" },
	},
	{
		category: "PRISM",
		name: "Prism of Jealousy",
		id: "ked8b3",
		dlc: "BASE",
		imageUrl: "items/prisms/prismofjealousy.png",
		internalSlug: "PrismOfJealousy_C",
		description: [],
		wikiUrl: "https://remnant2.wiki.gg/Prism",
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "PRISM",
		name: "Prism of Lethargy",
		id: "0nbaj2",
		dlc: "BASE",
		imageUrl: "items/prisms/prismoflethargy.png",
		internalSlug: "PrismOfLethargy_C",
		description: [],
		wikiUrl: "https://remnant2.wiki.gg/Prism",
		location: { world: "Ward 13", dungeon: "Vendor" },
	},
	{
		category: "PRISM",
		name: "Prism of Passion",
		id: "j2uus8",
		dlc: "BASE",
		imageUrl: "items/prisms/prismofpassion.png",
		internalSlug: "PrismOfPassion_C",
		description: [],
		wikiUrl: "https://remnant2.wiki.gg/Prism",
		location: { world: "Any", dungeon: "Quest" },
	},
	{
		category: "PRISM",
		name: "Prism of Pride",
		id: "03034f",
		dlc: "BASE",
		imageUrl: "items/prisms/prismofpride.png",
		internalSlug: "PrismOfPride_C",
		description: [],
		wikiUrl: "https://remnant2.wiki.gg/Prism",
		location: { world: "Any", dungeon: "Quest" },
	},
	{
		category: "PRISM",
		name: "Prism of Voracity",
		id: "16tce1",
		dlc: "BASE",
		imageUrl: "items/prisms/prismofvoracity.png",
		internalSlug: "PrismOfVoracity_C",
		description: [],
		wikiUrl: "https://remnant2.wiki.gg/Prism",
		location: { world: "Any", dungeon: "Quest" },
	},
];

export { PRISMS, type Remnant2PrismItem };
