import type { BaseRemnant2Item } from "#/games/remnant2/core/types";

type Remnant2PylonItem = BaseRemnant2Item & {};

const PYLONS: Remnant2PylonItem[] = [
	{
		category: "PYLON",
		name: "Accelerator",
		imageUrl: "items/pylons/accelerator.png",
		id: "92Ros5",
		dlc: "BASE",
		searchableTags: ["Melee Speed"],
		description: ["Increases melee speed by 7.5% -> 37.5%"],
		wikiUrl: `https://remnant2.wiki.gg/Boss_rush`,
		location: undefined,
	},
	{
		category: "PYLON",
		name: "Charger",
		imageUrl: "items/pylons/charger.png",
		id: "iuLVM7",
		dlc: "BASE",
		searchableTags: [],
		description: ["Increases mod buildup by 20% -> 100%"],
		wikiUrl: `https://remnant2.wiki.gg/Boss_rush`,
		location: undefined,
	},
	{
		category: "PYLON",
		name: "Chopper",
		imageUrl: "items/pylons/chopper.png",
		id: "2GyUmM",
		dlc: "BASE",
		searchableTags: ["Melee Damage"],
		description: ["Increases all melee damage by 15% -> 75%"],
		wikiUrl: `https://remnant2.wiki.gg/Boss_rush`,
		location: undefined,
	},
	{
		category: "PYLON",
		name: "Detonate",
		imageUrl: "items/pylons/detonate.png",
		id: "D04fKt",
		dlc: "BASE",
		searchableTags: [],
		description: [
			"Buildup, then release a shockwave when taking direct damage",
		],
		wikiUrl: `https://remnant2.wiki.gg/Boss_rush`,
		location: undefined,
	},
	{
		category: "PYLON",
		name: "Explosive",
		imageUrl: "items/pylons/explosive.png",
		id: "5KmdJi",
		dlc: "BASE",
		searchableTags: [],
		communityTags: ["Explosive Damage"],
		description: ["Enemies explode on death"],
		wikiUrl: `https://remnant2.wiki.gg/Boss_rush`,
		location: undefined,
	},
	{
		category: "PYLON",
		name: "Frantic",
		imageUrl: "items/pylons/frantic.png",
		id: "wtc7JH",
		dlc: "BASE",
		searchableTags: ["Reduce Skill Cooldown"],
		description: ["Reduces skill cooldown by -10% -> -50%"],
		wikiUrl: `https://remnant2.wiki.gg/Boss_rush`,
		location: undefined,
	},
	{
		category: "PYLON",
		name: "Hardened",
		imageUrl: "items/pylons/hardened.png",
		id: "kO0r7o",
		dlc: "BASE",
		searchableTags: ["Damage Reduction"],
		description: ["Increases damage reduction by 5% -> 25%"],
		wikiUrl: `https://remnant2.wiki.gg/Boss_rush`,
		location: undefined,
	},
	{
		category: "PYLON",
		name: "Healer",
		imageUrl: "items/pylons/healer.png",
		id: "Rv407e",
		dlc: "BASE",
		searchableTags: ["Healing Effectiveness"],
		description: ["Increases healing effectiveness by 10% -> 50%"],
		wikiUrl: `https://remnant2.wiki.gg/Boss_rush`,
		location: undefined,
	},
	{
		category: "PYLON",
		name: "Healing Orbs",
		imageUrl: "items/pylons/healing-orbs.png",
		id: "n2ooKj",
		dlc: "BASE",
		searchableTags: [],
		description: ["Chance to spawn healing orbs on kill"],
		wikiUrl: `https://remnant2.wiki.gg/Boss_rush`,
		location: undefined,
	},
	{
		category: "PYLON",
		name: "Hexer",
		imageUrl: "items/pylons/hexer.png",
		id: "9dgyUD",
		dlc: "BASE",
		searchableTags: [],
		description: ["Fire homing projectiles when taking Direct damage"],
		wikiUrl: `https://remnant2.wiki.gg/Boss_rush`,
		location: undefined,
	},
	{
		category: "PYLON",
		name: "Intensity",
		imageUrl: "items/pylons/intensity.png",
		id: "VLw3Bt",
		dlc: "BASE",
		searchableTags: [],
		description: ["Increases status damage by 10% -> 50%"],
		wikiUrl: `https://remnant2.wiki.gg/Boss_rush`,
		location: undefined,
	},
	{
		category: "PYLON",
		name: "Magnify",
		imageUrl: "items/pylons/magnify.png",
		id: "tQ82Lm",
		dlc: "BASE",
		searchableTags: ["Critical Damage"],
		description: ["Increases Critical Hit Damage by 10% -> 50%"],
		wikiUrl: `https://remnant2.wiki.gg/Boss_rush`,
		location: undefined,
	},
	{
		category: "PYLON",
		name: "Magus",
		imageUrl: "items/pylons/magus.png",
		id: "5e2NTe",
		dlc: "BASE",
		searchableTags: ["Mod Damage"],
		description: ["Increases mod damage by 10% -> 50%"],
		wikiUrl: `https://remnant2.wiki.gg/Boss_rush`,
		location: undefined,
	},
	{
		category: "PYLON",
		name: "Nimble Hands",
		imageUrl: "items/pylons/nimble-hands.png",
		id: "M8RcjQ",
		dlc: "BASE",
		searchableTags: ["Reload Speed"],
		description: ["Increases reload speed by 20% -> 100%"],
		wikiUrl: `https://remnant2.wiki.gg/Boss_rush`,
		location: undefined,
	},
	{
		category: "PYLON",
		name: "Precision",
		imageUrl: "items/pylons/precision.png",
		id: "kZ0vG7",
		dlc: "BASE",
		searchableTags: ["Weakspot Damage"],
		description: ["Increases weakspot damage by 10% -> 50%"],
		wikiUrl: `https://remnant2.wiki.gg/Boss_rush`,
		location: undefined,
	},
	{
		category: "PYLON",
		name: "Ranger",
		imageUrl: "items/pylons/ranger.png",
		id: "F5FId6",
		dlc: "BASE",
		searchableTags: ["Ranged Damage"],
		description: ["Increases all ranged damage by 10% -> 50%"],
		wikiUrl: `https://remnant2.wiki.gg/Boss_rush`,
		location: undefined,
	},
	{
		category: "PYLON",
		name: "Renewal",
		imageUrl: "items/pylons/renewal.png",
		id: "PVXD5h",
		dlc: "BASE",
		searchableTags: [],
		description: ["Increases health regeneration by 0.4% -> 2%"],
		wikiUrl: `https://remnant2.wiki.gg/Boss_rush`,
		location: undefined,
	},
	{
		category: "PYLON",
		name: "Reserve",
		imageUrl: "items/pylons/reserve.png",
		id: "6qLosL",
		dlc: "BASE",
		searchableTags: ["Ammo Reserves"],
		description: ["Increases ammo reserves by 30% -> 150%"],
		wikiUrl: `https://remnant2.wiki.gg/Boss_rush`,
		location: undefined,
	},
	{
		category: "PYLON",
		name: "Shocking",
		imageUrl: "items/pylons/shocking.png",
		id: "RYWP5h",
		dlc: "BASE",
		searchableTags: [],
		description: ["Create lightning strikes on successful charged melee"],
		wikiUrl: `https://remnant2.wiki.gg/Boss_rush`,
		location: undefined,
	},
	{
		category: "PYLON",
		name: "Spinner",
		imageUrl: "items/pylons/spinner.png",
		id: "J9Fg4X",
		dlc: "BASE",
		searchableTags: [],
		description: ["Gain Spinning Orbs to Damage enemies on contact"],
		wikiUrl: `https://remnant2.wiki.gg/Boss_rush`,
		location: undefined,
	},
	{
		category: "PYLON",
		name: "Stamina",
		imageUrl: "items/pylons/stamina.png",
		id: "9Q0Cpt",
		dlc: "BASE",
		searchableTags: ["Stamina"],
		description: ["Increases maximum stamina by 10 -> 50"],
		wikiUrl: `https://remnant2.wiki.gg/Boss_rush`,
		location: undefined,
	},
	{
		category: "PYLON",
		name: "Staves",
		imageUrl: "items/pylons/staves.png",
		id: "MmH8iM",
		dlc: "BASE",
		searchableTags: [],
		description: ["Chance to summon a root staff on kill"],
		wikiUrl: `https://remnant2.wiki.gg/Boss_rush`,
		location: undefined,
	},
	{
		category: "PYLON",
		name: "Technique",
		imageUrl: "items/pylons/technique.png",
		id: "901wcX",
		dlc: "BASE",
		searchableTags: ["Skill Damage"],
		description: ["Increases skill damage by 10% -> 50%"],
		wikiUrl: `https://remnant2.wiki.gg/Boss_rush`,
		location: undefined,
	},
	{
		category: "PYLON",
		name: "Trapper",
		imageUrl: "items/pylons/trapper.png",
		id: "3Umm36",
		dlc: "BASE",
		searchableTags: [],
		description: ["Chance to drop glitch puddles on hit"],
		wikiUrl: `https://remnant2.wiki.gg/Boss_rush`,
		location: undefined,
	},
	{
		category: "PYLON",
		name: "Trigger Finger",
		imageUrl: "items/pylons/trigger-finger.png",
		id: "Ka0EgY",
		dlc: "BASE",
		searchableTags: ["Fire Rate"],
		description: ["Increases fire rate by 7.5% -> 37.5%"],
		wikiUrl: `https://remnant2.wiki.gg/Boss_rush`,
		location: undefined,
	},
	{
		category: "PYLON",
		name: "Velocity",
		imageUrl: "items/pylons/velocity.png",
		id: "dRhU3j",
		dlc: "BASE",
		searchableTags: ["Movement Speed"],
		description: ["Increases movement speed by 10% -> 50%"],
		wikiUrl: `https://remnant2.wiki.gg/Boss_rush`,
		location: undefined,
	},
	{
		category: "PYLON",
		name: "Vigor",
		imageUrl: "items/pylons/vigor.png",
		id: "A9dgyw",
		dlc: "BASE",
		searchableTags: ["Health"],
		description: ["Increases maximum health by 10 -> 50"],
		wikiUrl: `https://remnant2.wiki.gg/Boss_rush`,
		location: undefined,
	},
	{
		category: "PYLON",
		name: "Volatile",
		imageUrl: "items/pylons/volatile.png",
		id: "6yhiBu",
		dlc: "BASE",
		searchableTags: [],
		communityTags: ["Explosive Damage"],
		description: ["Increases explosive damage by 10% -> 50%"],
		wikiUrl: `https://remnant2.wiki.gg/Boss_rush`,
		location: undefined,
	},
	{
		category: "PYLON",
		name: "Vortex",
		imageUrl: "items/pylons/vortex.png",
		id: "w1eARX",
		dlc: "BASE",
		searchableTags: [],
		description: ["Chance to spawn a black hole on hit"],
		wikiUrl: `https://remnant2.wiki.gg/Boss_rush`,
		location: undefined,
	},
];

export { PYLONS, type Remnant2PylonItem };
