import type { BaseRemnant2Item } from "#/games/remnant2/core/types";

type WeaponItemModifiers = {
	isRusty: boolean;
	damage: number;
	accuracy: number;
	ammo: number;
	crit: number;
	falloff: number;
	ideal: number;
	magazine: number;
	rps: number;
	stagger: number;
	weakspot: number;
};

type Remnant2WeaponItem = BaseRemnant2Item<
	"long gun" | "melee" | "hand gun"
> & {
	weaponModifiers?: Partial<WeaponItemModifiers>;
};

const WEAPONS: Remnant2WeaponItem[] = [
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Alpha / Omega",
		imageUrl: "items/weapons/alphaomega.png",
		internalSlug: "Weapon_AlphaOmega_C",
		id: "1ub6k9",
		dlc: "BASE",
		description: [
			"Charge shot fires a burst of five energy bolts. Each hit reduces charge time by 0.1s and increases damage by 10% for 1.5s. Stacks 5x.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Alpha_/_Omega`,
		location: { world: "Root Earth", dungeon: ["Blackened Citadel"] },
		linkedItems: {
			mod: {
				name: "Beta Ray",
			},
		},
		weaponModifiers: {
			damage: 14,
			rps: 6.89,
			magazine: 55,
			accuracy: 95,
			ideal: 24,
			falloff: 70,
			ammo: 275,
			crit: 10,
			weakspot: 100,
			stagger: 0,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Aphelion",
		internalSlug: "Weapon_Aphelion_C",
		imageUrl: "items/weapons/aphelion.png",
		id: "3wprfw",
		dlc: "BASE",
		description: [
			"Fires a hypercharged wide-arching line that passes through targets.",
		],
		location: { world: `N'Erud`, dungeon: [`Sentinel's Keep`] },
		linkedItems: {
			mod: {
				name: "Supernova",
			},
		},
		wikiUrl: `https://remnant2.wiki.gg/Aphelion`,
		weaponModifiers: {
			damage: 70,
			rps: 1.85,
			magazine: 8,
			accuracy: 95,
			ideal: 20,
			falloff: 65,
			ammo: 56,
			crit: 10,
			weakspot: 100,
			stagger: -10,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: 'AS-10 "Bulldog"',
		internalSlug: "Weapon_AutoShotgun_C",
		imageUrl: "items/weapons/bulldog.png",
		id: "va7cfd",
		dlc: "BASE",
		description: [
			"A brutal drum-fed fully-automatic 10 gauge shotgun designed for close-quarters combat.",
		],
		location: { world: "Ward 13", dungeon: "Vendor" },
		wikiUrl: `https://remnant2.wiki.gg/AS-10_"Bulldog"`,
		weaponModifiers: {
			damage: 60,
			rps: 3.5,
			magazine: 12,
			accuracy: 60,
			ideal: 10,
			falloff: 40,
			ammo: 60,
			crit: 5,
			weakspot: 100,
			stagger: 10,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Blackmaw AR-47",
		internalSlug: "Weapon_AssaultRifle_C",
		imageUrl: "items/weapons/blackmawar47.png",
		id: "phh1xe",
		dlc: "BASE",
		description: [
			"A fully automatic rifle with a medium capacity. Highly effective with controlled bursts.",
		],
		location: { world: "Ward 13", dungeon: "Vendor" },
		wikiUrl: `https://remnant2.wiki.gg/Blackmaw_AR-47`,
		weaponModifiers: {
			damage: 17,
			rps: 7.3,
			magazine: 40,
			accuracy: 95,
			ideal: 20,
			falloff: 60,
			ammo: 200,
			crit: 10,
			weakspot: 100,
			stagger: 0,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Black Greatsword",
		internalSlug: "Weapon_BlackGreatsword_C",
		imageUrl: "items/weapons/blackgreatsword.png",
		id: "71k6w5",
		dlc: "BASE",
		searchableTags: ["Encumbrance", "Charged Melee"],
		description: [
			"A massive weapon of pure destruction. Attacks can be enhanced by Charging at the cost of Stamina over time. Increases Encumbrance by 15.",
		],
		location: { world: "Ward 13", dungeon: "Vendor" },
		linkedItems: {
			mod: {
				name: "Indomitable Strike",
			},
		},
		wikiUrl: `https://remnant2.wiki.gg/Black_Greatsword`,

		modifiers: {
			weight: 15,
		},
		weaponModifiers: {
			damage: 120,
			crit: 15,
			weakspot: 110,
			stagger: 25,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Chicago Typewriter",
		internalSlug: "Weapon_TommyGun_C",
		imageUrl: "items/weapons/tommygun.png",
		id: "59oddb",
		dlc: "BASE",
		description: [
			"A classic Tommy Gun with large ammo capacity and a slow reload. Poor initial accuracy which improves while holding down the trigger.",
		],
		location: { world: "Ward 13", dungeon: "World Drop" },
		wikiUrl: `https://remnant2.wiki.gg/Chicago_Typewriter`,
		weaponModifiers: {
			damage: 10,
			rps: 11.75,
			magazine: 80,
			accuracy: 80,
			ideal: 17,
			falloff: 55,
			ammo: 320,
			crit: 10,
			weakspot: 105,
			stagger: 0,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Coach Gun",
		imageUrl: "items/weapons/coachgun.png",
		internalSlug: "Weapon_CoachGun_C",
		id: "i0hvy8",
		dlc: "BASE",
		description: [
			"A double-barrel over/under shotgun modified to fire powerful slugs. High damage with a decent fire rate, but very low magazine capacity.",
		],
		location: { world: "Ward 13", dungeon: "Vendor" },
		wikiUrl: `https://remnant2.wiki.gg/Coach_Gun`,
		weaponModifiers: {
			damage: 115,
			rps: 2.3,
			magazine: 2,
			accuracy: 95,
			ideal: 16,
			falloff: 35,
			ammo: 28,
			crit: 5,
			weakspot: 100,
			stagger: 10,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Corrupted Aphelion",
		imageUrl: "items/weapons/corruptedaphelion.png",
		internalSlug: "Weapon_CorruptedAphelion_C",
		id: "w85ya8",
		dlc: "BASE",
		description: [
			"A laser shotgun that fires three hypercharged arc lines that penetrate targets.",
		],
		location: { world: "Ward 13", dungeon: "Vendor" },
		linkedItems: {
			mod: {
				name: "Micronova",
			},
		},
		wikiUrl: `https://remnant2.wiki.gg/Corrupted_Aphelion`,
		weaponModifiers: {
			damage: 33,
			rps: 1.45,
			magazine: 8,
			accuracy: 95,
			ideal: 15,
			falloff: 40,
			ammo: 40,
			crit: 5,
			weakspot: 100,
			stagger: 10,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Corrupted Arbalest",
		imageUrl: "items/weapons/corruptedarbalest.png",
		internalSlug: "Weapon_CorruptedTwistedArbalest_C",
		id: "Gkemt8",
		dlc: "BASE",
		description: [
			"Fully automatic mechanisms launch a bouncing Energy Disc that can hit up to 2 enemies in close proximity. Damage is reduced after bouncing.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Corrupted_Arbalest`,
		linkedItems: {
			mod: {
				name: `Guardian's Fury`,
			},
		},
		location: { world: "Ward 13", dungeon: "Vendor" },
		weaponModifiers: {
			damage: 69,
			rps: 1.3,
			magazine: 8,
			accuracy: 95,
			ideal: 20,
			falloff: 70,
			ammo: 40,
			crit: 5,
			weakspot: 100,
			stagger: 0,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Corrupted Deceit",
		imageUrl: "items/weapons/corrupteddeceit.png",
		internalSlug: "Weapon_CorruptedDeceit_C",
		id: "k9w4yh",
		dlc: "BASE",
		description: [
			"A pinpoint accurate split-barreled rifle that fires two penetrating rails. High base damage, but cannot score Weakspot hits. Charge to fire.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Corrupted_Deceit`,
		linkedItems: {
			mod: {
				name: "Windfall",
			},
		},
		location: { world: "Ward 13", dungeon: "Vendor" },
		weaponModifiers: {
			damage: 66,
			rps: 3,
			magazine: 12,
			accuracy: 95,
			ideal: 26,
			falloff: 75,
			ammo: 48,
			crit: 10,
			weakspot: 90,
			stagger: 0,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Corrupted Merciless",
		internalSlug: "Weapon_CorruptedMerciless_C",
		imageUrl: "items/weapons/corruptedmerciless.png",
		id: "8i85za",
		dlc: "BASE",
		description: ["Fires high-powered nails. Limited magazine size."],
		wikiUrl: `https://remnant2.wiki.gg/Corrupted_Merciless`,
		linkedItems: {
			mod: {
				name: "Bloodshot",
			},
		},
		location: { world: "Ward 13", dungeon: "Vendor" },
		weaponModifiers: {
			damage: 90,
			rps: 1.7,
			magazine: 3,
			accuracy: 90,
			ideal: 25,
			falloff: 70,
			ammo: 36,
			crit: 5,
			weakspot: 105,
			stagger: 10,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Corrupted Savior",
		imageUrl: "items/weapons/corruptedsavior.png",
		internalSlug: "Weapon_CorruptedSavior_C",
		id: "W6n2mT",
		dlc: "BASE",
		searchableTags: ["Hardcore Reward"],
		description: [
			"A Black Crystal weapon which gains increased Fire Rate as Mod Power is generated. Mod power drains after 3s of not dealing damage.",
		],
		wikiUrl: "https://remnant2.wiki.gg/Corrupted_Savior",
		linkedItems: {
			mod: {
				name: "Fusion Cannon",
			},
		},
		location: { world: "Ward 13", dungeon: "Vendor" },
		weaponModifiers: {
			damage: 17,
			rps: 3.15,
			magazine: 50,
			accuracy: 95,
			ideal: 20,
			falloff: 60,
			ammo: 200,
			crit: 10,
			weakspot: 100,
			stagger: 0,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Crescent Moon",
		imageUrl: "items/weapons/crescentmoon.png",
		internalSlug: "Weapon_CrescentMoon_C",
		id: "p7wc7k",
		dlc: "BASE",
		description: [
			"An ethereal weapon that seems to resonate.",
			"Can be charged for more damage. Perfect release after Charge for maximum damage.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Crescent_Moon`,
		linkedItems: {
			mod: {
				name: "Moonlight Barrage",
			},
		},
		location: { world: "Losomn", dungeon: ["Nimue's Retreat"] },
		weaponModifiers: {
			damage: 87,
			rps: 4.1,
			magazine: 1,
			accuracy: 100,
			ideal: 25,
			falloff: 65,
			ammo: 38,
			crit: 5,
			weakspot: 70,
			stagger: -15,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Crossbow",
		imageUrl: "items/weapons/crossbow.png",
		internalSlug: "Weapon_Crossbow_C",
		id: "x94ze2",
		dlc: "BASE",
		description: [
			"An accurate and deadly single-shot crossbow with a low sound profile.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Crossbow`,
		location: { world: "Yaesha", dungeon: ["Imperial Gardens"] },
		weaponModifiers: {
			damage: 125,
			rps: 2.5,
			magazine: 1,
			accuracy: 100,
			ideal: 26,
			falloff: 75,
			ammo: 30,
			crit: 10,
			weakspot: 120,
			stagger: 20,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Deceit",
		internalSlug: "Weapon_Deceit_C",
		imageUrl: "items/weapons/deceit.png",
		id: "hlmpjl",
		dlc: "BASE",
		description: [
			"A pinpoint accurate split-barreled rifle that fires two penetrating rails. High base damage, but cannot score Weakspot hits. Charge to fire.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Deceit`,
		location: { world: "Losomn", dungeon: ["Beatific Gallery"] },
		linkedItems: {
			mod: {
				name: "Ouroboros",
			},
		},
		weaponModifiers: {
			damage: 120,
			rps: 2,
			magazine: 6,
			accuracy: 95,
			ideal: 28,
			falloff: 75,
			ammo: 30,
			crit: 15,
			weakspot: 90,
			stagger: 5,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Ford's Scattergun",
		internalSlug: "Weapon_Shotgun_C",
		imageUrl: "items/weapons/shotgun.png",
		id: "8n3e07",
		dlc: "BASE",
		description: [
			"An incredibly powerful 12 gauge shotgun with a wide spread. High damage, slow reload.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Ford's_Scattergun`,
		location: { world: "Yaesha", dungeon: ["The Red Throne"] },
		weaponModifiers: {
			damage: 130,
			rps: 1.2,
			magazine: 10,
			accuracy: 95,
			ideal: 10,
			falloff: 35,
			ammo: 30,
			crit: 5,
			weakspot: 100,
			stagger: 10,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Genesis",
		internalSlug: "Weapon_Genesis_C",
		imageUrl: "items/weapons/genesis.png",
		id: "okmk07",
		dlc: "DLC3",
		searchableTags: ["Charged Shot"],
		description: [
			"N'Erudian tool with low energy reserves that generates energy bolts. Charging turbines generates additional projectiles. Max 5.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Genesis`,
		location: { world: `N'Erud`, dungeon: ["Withered Necropolis"] },
		linkedItems: {
			mod: {
				name: "Mega Drive",
			},
		},
		weaponModifiers: {
			damage: 50,
			rps: 5,
			ammo: 20,
			magazine: 1,
			ideal: 22,
			falloff: 65,
			crit: 10,
			weakspot: 115,
			stagger: 5,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Huntmaster M1",
		internalSlug: "Weapon_Huntmaster_C",
		imageUrl: "items/weapons/huntmaster.png",
		id: "cda7lb",
		dlc: "BASE",
		description: [
			"A high-powered long range bolt-action rifle with exceptional accuracy and a 2.5x magnification scope.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Huntmaster_M1`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		weaponModifiers: {
			damage: 105,
			rps: 1.05,
			magazine: 7,
			accuracy: 95,
			ideal: 27,
			falloff: 75,
			ammo: 35,
			crit: 5,
			weakspot: 110,
			stagger: 5,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Merciless",
		internalSlug: "Weapon_Merciless_C",
		imageUrl: "items/weapons/merciless.png",
		id: "g3esv1",
		dlc: "BASE",
		description: [
			"Fires tooth-like flechettes. When weapon reticle is fully compressed, flechettes apply 200 → 600 BLEED damage over 10s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Merciless`,
		location: { world: "Yaesha", dungeon: ["Ravager's Lair"] },
		linkedItems: {
			mod: {
				name: "Bloodline",
			},
		},
		weaponModifiers: {
			damage: 13,
			rps: 8.6,
			magazine: 50,
			accuracy: 90,
			ideal: 20,
			falloff: 45,
			ammo: 250,
			crit: 10,
			weakspot: 100,
			stagger: 0,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Monarch",
		imageUrl: "items/weapons/monarch.png",
		internalSlug: "Weapon_Monarch_C",
		dlc: "DLC1",
		id: "76622z",
		description: [
			"An once-beautiful weapon, rumored to corrupt its wielder with absolute power.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Monarch`,
		location: { world: "Losomn", dungeon: ["Chamber of the Faithless"] },
		linkedItems: {
			mod: {
				name: "Chain of Command",
			},
		},
		weaponModifiers: {
			damage: 12,
			rps: 10.5,
			magazine: 60,
			accuracy: 95,
			ideal: 20,
			falloff: 45,
			ammo: 300,
			crit: 10,
			weakspot: 105,
			stagger: 0,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Monolith",
		imageUrl: "items/weapons/monolith.png",
		internalSlug: "Weapon_Monolith_C",
		dlc: "DLC2",
		id: "WjE2nZ",
		description: [
			"Fires concentrated sand. Sustained primary fire and Sandstorm hits apply EXPOSED for 3s. Max 15s.",
			"EXPOSED: Target receives 15% additional damage from all sources.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Monolith`,
		location: { world: "Yaesha", dungeon: ["Bloodless Throne"] },
		linkedItems: {
			mod: {
				name: "Sandstorm",
			},
		},
		weaponModifiers: {
			damage: 11,
			rps: 12,
			magazine: 80,
			accuracy: 95,
			ideal: 17,
			falloff: 30,
			ammo: 320,
			crit: 5,
			weakspot: 85,
			stagger: -20,
		},
	},
	{
		category: "WEAPON",
		name: "Monorail",
		subcategory: "long gun",
		internalSlug: "Weapon_Monorail_C",
		imageUrl: "items/weapons/monorail.png",
		id: "oz9amG",
		dlc: "DLC3",
		description: [
			"A mysterious relic that fires super-dense penetrating rails. Can be charged to unleash violent levels of energy. Warning: Overcharging may have catastrophic results.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Monorail`,
		location: { world: `N'Erud`, dungeon: "Quest" },
		linkedItems: {
			mod: {
				name: "Recoil Dampener",
			},
		},
		weaponModifiers: {
			damage: 125,
			rps: 60,
			ammo: 27,
			magazine: 3,
			ideal: 35,
			falloff: 85,
			crit: 5,
			weakspot: 110,
			stagger: 5,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Nightfall",
		imageUrl: "items/weapons/nightfall.png",
		internalSlug: "Weapon_Nightfall_C",
		id: "2fdvrf",
		dlc: "BASE",
		description: [
			"A device forged of pure evil. Fires hardened bone shards at a brisk rate dealing bonus stagger. Semi-automatic with a medium kick.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Nightfall`,
		location: { world: "Losomn", dungeon: ["Tormented Asylum"] },
		linkedItems: {
			mod: {
				name: "Dreadwalker",
			},
		},
		weaponModifiers: {
			damage: 28,
			rps: 4.95,
			magazine: 13,
			accuracy: 95,
			ideal: 18,
			falloff: 50,
			ammo: 117,
			crit: 5,
			weakspot: 105,
			stagger: 15,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Plasma Cutter",
		imageUrl: "items/weapons/plasmacutter.png",
		internalSlug: "Weapon_PlasmaCutter_C",
		id: "7nwwzn",
		dlc: "BASE",
		description: [
			"An energy-based cutting tool that increases damage when focused on a target. Can overheat.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Plasma_Cutter`,
		location: {
			world: `N'Erud`,
			biome: `N'Erud Wasteland`,
			injectable: `Titan's Reach`,
		},
		linkedItems: {
			mod: {
				name: "Heat Sink",
			},
		},
		weaponModifiers: {
			damage: 7,
			rps: 13,
			magazine: 100,
			accuracy: 95,
			ideal: 17,
			falloff: 30,
			ammo: 300,
			crit: 5,
			weakspot: 80,
			stagger: -20,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Polygun",
		imageUrl: "items/weapons/polygun.png",
		internalSlug: "Weapon_Polygun_C",
		id: "polgun",
		dlc: "BASE",
		description: [
			"ERROR: Unable to load description.ERROR: Unable to load description.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Polygun`,
		location: {
			world: "Labyrinth",
			dungeon: ["Labyrinth"],
		},
		linkedItems: {
			mod: {
				name: "77 79 68",
			},
		},
		weaponModifiers: {
			damage: 69,
			rps: 2.15,
			magazine: 99,
			accuracy: 95,
			ideal: 15,
			falloff: 30,
			ammo: 999,
			crit: 5,
			weakspot: 100,
			stagger: 10,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Pulse Rifle",
		imageUrl: "items/weapons/pulserifle.png",
		internalSlug: "Weapon_PulseRifle_C",
		id: "vldebv",
		dlc: "BASE",
		description: [
			"An extremely accurate, high-tech pulse rifle which shoots quick three-round bursts.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Pulse_Rifle`,
		location: {
			world: `N'Erud`,
			dungeon: ["Ascension Spire"],
		},
		weaponModifiers: {
			damage: 16,
			rps: 7.8,
			magazine: 30,
			accuracy: 75,
			ideal: 22,
			falloff: 65,
			ammo: 210,
			crit: 10,
			weakspot: 105,
			stagger: 5,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Repulsor",
		imageUrl: "items/weapons/repulsor.png",
		internalSlug: "Weapon_Repulsor_C",
		id: "v6zmn3",
		dlc: "BASE",
		description: [
			"Converted from experimental Dreamer tech, ideal for mid-range combat. Weapon becomes more accurate the longer AIM is held.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Repulsor`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		linkedItems: {
			mod: {
				name: "Banish",
			},
		},
		weaponModifiers: {
			damage: 100,
			rps: 1.6,
			magazine: 5,
			accuracy: 95,
			ideal: 13,
			falloff: 35,
			ammo: 35,
			crit: 5,
			weakspot: 100,
			stagger: 10,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Royal Hunting Bow",
		internalSlug: "Weapon_Bow_C",
		imageUrl: "items/weapons/royalhuntingbow.png",
		id: "8ouocq",
		dlc: "BASE",
		description: [
			"A lightweight, easy handling bow designed for hunting. High critical chance, bonus damage on Weakspot hits, and a low sound profile.",
			"Can be charged for more damage. Perfect release after Charge for maximum damage.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Royal_Hunting_Bow`,
		location: { world: "Losomn", dungeon: [`Postulant's Parlor`] },
		weaponModifiers: {
			damage: 80,
			rps: 5.3,
			magazine: 1,
			accuracy: 100,
			ideal: 25,
			falloff: 65,
			ammo: 40,
			crit: 10,
			weakspot: 115,
			stagger: 10,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Rusty Lever Action",
		internalSlug: "Weapon_LeverAction_Rusty_C",
		imageUrl: "items/weapons/leveractionrusted.png",
		id: "gv6yzu",
		dlc: "BASE",
		description: ["A well-worn lever-action rifle."],
		wikiUrl: `https://remnant2.wiki.gg/Rusty_Lever_Action`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		weaponModifiers: {
			damage: 55,
			isRusty: true,
			rps: 1.8,
			magazine: 10,
			accuracy: 80,
			ideal: 30,
			falloff: 80,
			ammo: 60,
			crit: 0,
			weakspot: 100,
			stagger: 0,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Sagittarius",
		imageUrl: "items/weapons/sagittarius.png",
		internalSlug: "Weapon_Sagittarius_C",
		id: "t0cb8d",
		dlc: "BASE",
		description: [
			"A high-powered Bow which deals bonus damage to Weakspots. Can be charged for increased effect. Perfect release after Charge for maximum damage.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Sagittarius`,
		location: { world: "Yaesha", dungeon: [`Cathedral of Omens`] },
		linkedItems: {
			mod: {
				name: "Starfall",
			},
		},
		weaponModifiers: {
			damage: 98,
			rps: 4.5,
			magazine: 1,
			accuracy: 100,
			ideal: 25,
			falloff: 65,
			ammo: 32,
			crit: 10,
			weakspot: 115,
			stagger: 5,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Savior",
		imageUrl: "items/weapons/savior.png",
		internalSlug: "Weapon_Savior_C",
		id: "2jrbvl",
		dlc: "BASE",
		searchableTags: ["Hardcore Reward"],
		description: [
			"An old Fusion Rifle refactored to store and violently release energy in each shot. Can be charged for more damage. Perfect release after Charge for maximum damage.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Savior`,
		linkedItems: {
			mod: {
				name: "Shatterstar",
			},
		},
		location: { world: "Ward 13", dungeon: "Vendor" },
		weaponModifiers: {
			damage: 50,
			rps: 2.1,
			magazine: 6,
			accuracy: 95,
			ideal: 25,
			falloff: 75,
			ammo: 36,
			crit: 10,
			weakspot: 115,
			stagger: 0,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Sparkfire Shotgun",
		dlc: "DLC1",
		internalSlug: "Weapon_Sparkfire_C",
		imageUrl: "items/weapons/sparkfireshotgun.png",
		id: "3r9jm7",
		description: [
			"Fires incendiary shells that apply BURNING which deals 30 → 90 FIRE damage over 3 seconds.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Sparkfire_Shotgun`,
		location: { world: "Losomn", dungeon: ["Derelict Lighthouse"] },
		weaponModifiers: {
			damage: 100,
			rps: 1.3,
			magazine: 7,
			accuracy: 98,
			ideal: 12,
			falloff: 30,
			ammo: 35,
			crit: 5,
			weakspot: 100,
			stagger: 10,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Sporebloom",
		imageUrl: "items/weapons/sporebloom.png",
		internalSlug: "Weapon_Sporebloom_C",
		id: "q3fgj2",
		dlc: "BASE",
		description: [
			"An exceptionally powerful single-shot weapon that deals bonus stagger damage. Must reload after each round fired.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Sporebloom`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		linkedItems: {
			mod: {
				name: "Spore Shot",
			},
		},
		weaponModifiers: {
			damage: 250,
			rps: 1.95,
			magazine: 1,
			accuracy: 95,
			ideal: 10,
			falloff: 25,
			ammo: 21,
			crit: 5,
			weakspot: 100,
			stagger: 20,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Starkiller",
		imageUrl: "items/weapons/starkiller.png",
		internalSlug: "Weapon_Starkiller_C",
		id: "hzmyu1",
		dlc: "BASE",
		description: [
			"Alien rifle that shoots high velocity rails which penetrate enemies. Equipped with a 2.5x magnification scope. Double Tap AIM to Scope.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Starkiller`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		linkedItems: {
			mod: {
				name: "Gravity Core",
			},
		},
		weaponModifiers: {
			damage: 88,
			rps: 1.45,
			magazine: 8,
			accuracy: 95,
			ideal: 30,
			falloff: 80,
			ammo: 40,
			crit: 5,
			weakspot: 110,
			stagger: 0,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Thorn",
		internalSlug: "Weapon_Thorn_C",
		dlc: "DLC2",
		imageUrl: "items/weapons/thorn.png",
		id: "13hsqd",
		description: [
			"Fires homing needles which deal 5 - 15 Explosive Damage after sticking for 2s. When 5  needles are stuck in a target at once, BLOWBACK triggers, dealing 50 - 150 Explosive Damage instead.",
		],
		communityTags: [`Explosive Damage`],
		wikiUrl: `https://remnant2.wiki.gg/Thorn`,
		location: { world: "Yaesha", dungeon: ["Glittering Grotto"] },
		linkedItems: {
			mod: {
				name: "Deadwood",
			},
		},
		weaponModifiers: {
			damage: 7,
			rps: 8.85,
			magazine: 30,
			accuracy: 95,
			ideal: 19,
			falloff: 39,
			ammo: 300,
			crit: 10,
			weakspot: 100,
			stagger: -10,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Twisted Arbalest",
		internalSlug: "Weapon_TwistedArbalest_C",
		imageUrl: "items/weapons/twistedarbalest.png",
		id: "13hsq0",
		dlc: "BASE",
		description: [
			"A strange device which fires a bouncing Energy Disc that can hit up to 5 enemies in close proximity. Damage is reduced with each bounce.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Twisted_Arbalest`,
		location: { world: "Yaesha", dungeon: ["The Great Bole"] },
		linkedItems: {
			mod: {
				name: "Guardian's Call",
			},
		},
		weaponModifiers: {
			damage: 80,
			rps: 2,
			magazine: 1,
			accuracy: 85,
			ideal: 20,
			falloff: 70,
			ammo: 22,
			crit: 5,
			weakspot: 100,
			stagger: 5,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Trinity Crossbow",
		internalSlug: "Weapon_Trinitycrossbow_C",
		imageUrl: "items/weapons/trinitycrossbow.png",
		id: "13hsq6",
		dlc: "DLC2",
		description: [
			"A powerful Pan crossbow designed for mid-range combat. Fires 3 bolts at a time.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Trinity_Crossbow`,
		location: { world: "Yaesha", dungeon: ["Ancient Canopy"] },
		weaponModifiers: {
			damage: 44,
			rps: 0.78,
			magazine: 18,
			accuracy: 100,
			ideal: 24,
			falloff: 70,
			ammo: 90,
			crit: 10,
			weakspot: 115,
			stagger: -65,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Widowmaker",
		internalSlug: "Weapon_SniperRifle_C",
		imageUrl: "items/weapons/sniperrifle.png",
		id: "fqdvas",
		dlc: "BASE",
		description: [
			"A powerful single-shot sniper rifle with excellent range and pinpoint accuracy. Comes with a 3x scope. Tap SCOPE to toggle.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Widowmaker`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		weaponModifiers: {
			damage: 150,
			rps: 2.4,
			magazine: 1,
			accuracy: 95,
			ideal: 35,
			falloff: 85,
			ammo: 27,
			crit: 10,
			weakspot: 120,
			stagger: 20,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: "Wrangler 1860",
		internalSlug: "Weapon_LeverAction_C",
		imageUrl: "items/weapons/leveraction.png",
		id: "5aninv",
		dlc: "BASE",
		description: [
			"A well-rounded lever-action rifle effective at most ranges, hampered only by a slow reload.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Wrangler_1860`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		weaponModifiers: {
			damage: 55,
			rps: 2.25,
			magazine: 10,
			accuracy: 80,
			ideal: 25,
			falloff: 70,
			ammo: 60,
			crit: 10,
			weakspot: 110,
			stagger: 0,
		},
	},
	{
		category: "WEAPON",
		subcategory: "long gun",
		name: 'XMG57 "Bonesaw"',
		internalSlug: "Weapon_LMG_C",
		imageUrl: "items/weapons/bonesaw.png",
		id: "rbpz53",
		dlc: "BASE",
		description: [
			"An experimental infantry support weapon used for prolonged suppressive fire. High capacity, long reload, and prone to overheating. Becomes more accurate while holding down the trigger.",
		],
		wikiUrl: `https://remnant2.wiki.gg/XMG57_"Bonesaw"`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		weaponModifiers: {
			damage: 12,
			rps: 9.65,
			magazine: 150,
			accuracy: 75,
			ideal: 19,
			falloff: 55,
			ammo: 300,
			crit: 10,
			weakspot: 100,
			stagger: 0,
		},
	},

	// #region Melee
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Abyssal Hook",
		imageUrl: "items/weapons/abyssalhook.png",
		internalSlug: "Weapon_AbyssalHook_C",
		dlc: "DLC1",
		id: "sd4nzf",
		description: [
			"A hammer-like anchor that swings with an exceptionally irregular ferocity.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Abyssal_Hook`,
		location: { world: "Losomn", dungeon: ["Forlorn Coast"] },
		linkedItems: {
			mod: {
				name: "Fathomless Deep",
			},
		},
		weaponModifiers: {
			damage: 101,
			crit: 6,
			weakspot: 85,
			stagger: 80,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Assassin's Dagger",
		imageUrl: "items/weapons/assassinsdagger.png",
		internalSlug: "Weapon_AssassinsDagger_C",
		id: "bv9wps",
		dlc: "BASE",
		description: [
			"Lightweight. Silent. Deadly. It's rumored that the blade is meant to bestow a slow, agonizing death.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Assassin's_Dagger`,
		location: { world: "Losomn", dungeon: ["Council Chamber"] },
		linkedItems: {
			mod: {
				name: "Bloodthirst",
			},
		},
		weaponModifiers: {
			damage: 35,
			crit: -3,
			weakspot: 110,
			stagger: -15,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Atom Smasher",
		imageUrl: "items/weapons/atomsmasher.png",
		internalSlug: "Weapon_AtomSmasher_C",
		id: "lrk5hf",
		dlc: "BASE",
		description: [
			"A powerful crushing device that harnesses rocket technology to increase smashing force.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Atom_Smasher`,
		location: { world: `N'Erud`, dungeon: [`Terminus Station`] },
		linkedItems: {
			mod: {
				name: "Accelerator",
			},
		},
		weaponModifiers: {
			damage: 72,
			crit: 5,
			weakspot: 95,
			stagger: 11,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Atom Splitter",
		imageUrl: "items/weapons/atomsplitter.png",
		internalSlug: "Weapon_AtomSplitter_C",
		id: "e7c88o",
		dlc: "BASE",
		description: ["A giant tool for splitting heavy rocks."],
		wikiUrl: `https://remnant2.wiki.gg/Atom_Splitter`,
		location: {
			world: `N'Erud`,
			biome: `N'Erud Underworld`,
			injectable: `The Claw`,
		},
		linkedItems: {
			mod: {
				name: "Fission Strike",
			},
		},
		weaponModifiers: {
			damage: 100,
			crit: 6,
			weakspot: 95,
			stagger: 7,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Blade of Gul",
		imageUrl: "items/weapons/bladeofgul.png",
		internalSlug: "Weapon_BladeOfGul_C",
		id: "nxfxlp",
		dlc: "BASE",
		description: [
			"A short, but thick sword, used by Gul Warriors. Its compact design makes for swift yet hard-hitting blows. An excellent close-range option.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Blade_of_Gul`,
		location: { world: "Yaesha", dungeon: "Vendor" },
		weaponModifiers: {
			damage: 57,
			crit: 4,
			weakspot: 100,
			stagger: 6,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Bone Chopper",
		imageUrl: "items/weapons/bonechopper.png",
		internalSlug: "Weapon_BoneChopper_C",
		id: "e6y7fy",
		dlc: "BASE",
		description: [
			"A razor-sharp hand axe. Excellent for separating flesh from bone. Charge for double attacks.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Bone_Chopper`,
		location: { world: "Losomn", dungeon: ["The Great Hall"] },
		weaponModifiers: {
			damage: 58,
			crit: 7,
			weakspot: 105,
			stagger: -3,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Crystal Staff",
		imageUrl: "items/weapons/crystalstaff.png",
		internalSlug: "Weapon_CrystalStaff_C",
		id: "CMo9vJ",
		dlc: "DLC2",
		description: [
			"The staff hums with energy. A destructive power within yearns to be released.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Crystal_Staff`,
		location: { world: "Yaesha", dungeon: ["Infested Abyss"] },
		linkedItems: {
			mod: {
				name: "Power Stone",
			},
		},
		weaponModifiers: {
			damage: 42,
			crit: 5,
			weakspot: 95,
			stagger: 3,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Decayed Claws",
		imageUrl: "items/weapons/decayedclaws.png",
		internalSlug: "Weapon_DecayedClaws_C",
		id: "y1a0bu",
		dlc: "BASE",
		description: [
			"Makeshift claws fashioned from decayed root and rusted metal.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Decayed_Claws`,
		location: { world: "Root Earth", dungeon: ["Corrupted Harbor"] },
		weaponModifiers: {
			damage: 49,
			crit: 16,
			weakspot: 110,
			stagger: -4,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Dark Matter Gauntlets",
		imageUrl: "items/weapons/darkmattergauntlets.png",
		internalSlug: "Weapon_DarkMatterGauntlets_C",
		id: "p1o9av",
		dlc: "DLC3",
		description: [
			"The gauntlets harness the power of a neutron star and a black hole. When merged, cosmic forces are unleashed.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Dark_Matter_Gauntlets`,
		location: { world: `N'Erud`, dungeon: "Quest" },
		linkedItems: {
			mod: {
				name: "Kilonova",
			},
		},
		weaponModifiers: {
			damage: 50,
			crit: 5,
			weakspot: 110,
			stagger: 5,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Dreamcatcher",
		imageUrl: "items/weapons/dreamcatcher.png",
		internalSlug: "Weapon_Dreamcatcher_C",
		id: "3sxr9y",
		dlc: "BASE",
		description: [
			"A magical stave capable of harnessing the energy of nearby enemies.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Dreamcatcher`,
		location: { world: "Losomn", dungeon: ["Tormented Asylum"] },
		linkedItems: {
			mod: {
				name: "Dreamwave",
			},
		},
		weaponModifiers: {
			damage: 58,
			crit: 5,
			weakspot: 95,
			stagger: 3,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Edge of the Forest",
		imageUrl: "items/weapons/edgeoftheforest.png",
		internalSlug: "Weapon_EdgeOfTheForest_C",
		id: "6c7rqm",
		dlc: "BASE",
		description: [
			"An elegant, yet light blade, designed to bring beauty to bloodshed. Unstoppable in the hands of a master swordsman.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Edge_of_the_Forest`,
		location: { world: "Yaesha", dungeon: ["Imperial Gardens"] },
		weaponModifiers: {
			damage: 59,
			crit: 11,
			weakspot: 105,
			stagger: -15,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Feral Judgement",
		internalSlug: "Weapon_FeralJudgment_C",
		imageUrl: "items/weapons/feraljudgement.png",
		id: "umb305",
		dlc: "BASE",
		description: [
			"A pair of gauntlets with sharp bone blades that strike with vicious speed and velocity.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Feral_Judgement`,
		linkedItems: {
			mod: {
				name: "Death Sentence",
			},
		},
		location: { world: "Yaesha", dungeon: [`Ravager's Lair`] },
		weaponModifiers: {
			damage: 53,
			crit: 13,
			weakspot: 110,
			stagger: -15,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Gas Giant",
		internalSlug: "Weapon_TalRatha_Hammer_C",
		imageUrl: "items/weapons/gasgiant.png",
		id: "c58759",
		dlc: "BASE",
		description: [
			"Dealing damage unleashes the dormant Toxic Gas within the head. When infused, Basic Attacks apply CORRODED for 5s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Gas_Giant`,
		location: { world: `N'Erud`, dungeon: [`Forgotten Prison`] },
		linkedItems: {
			mod: {
				name: "Dying Breath",
			},
		},
		weaponModifiers: {
			damage: 74,
			crit: 3,
			weakspot: 95,
			stagger: 8,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Godsplitter",
		imageUrl: "items/weapons/godsplitter.png",
		internalSlug: "Weapon_Godsplitter_C",
		id: "a23oaa",
		dlc: "BASE",
		description: [
			"An expertly balanced blade that is the product of advanced Fae metallurgy. Cannot score Weakspot hits without its Mod behavior.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Godsplitter`,
		location: { world: "Losomn", dungeon: ["Malefic Gallery"] },
		linkedItems: {
			mod: {
				name: "Fracture",
			},
		},
		weaponModifiers: {
			damage: 38,
			crit: 2,
			weakspot: 50,
			stagger: -20,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Harvester Scythe",
		imageUrl: "items/weapons/harvesterscythe.png",
		internalSlug: "Weapon_HarvesterScythe_C",
		id: "5xx5zt",
		dlc: "DLC3",
		description: [
			"Harvester automaton limb fitted with a plasma torch. The system breach of a Drzyr phantom initiated jettisoned protocols, trapping strange properties within the makeshift weapon.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Harvester_Scythe`,
		location: { world: `N'Erud`, dungeon: [`Agronomy Sector`] },
		linkedItems: {
			mod: {
				name: "Phantom Blade",
			},
		},
		weaponModifiers: {
			damage: 65,
			crit: 12,
			weakspot: 100,
			stagger: -33.4,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Hero's Sword",
		imageUrl: "items/weapons/herossword.png",
		internalSlug: "Weapon_HerosSword_C",
		id: "5o3cq4",
		dlc: "BASE",
		description: [
			"An ancient, quick, and versatile blade suited for many situations. Contains a hidden power.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Hero's_Sword`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		linkedItems: {
			mod: {
				name: "Energy Wave",
			},
		},
		weaponModifiers: {
			damage: 51,
			crit: 5,
			weakspot: 90,
			stagger: -10,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Huntress Spear",
		imageUrl: "items/weapons/huntressspear.png",
		internalSlug: "Weapon_HuntressSpear_C",
		id: "0jefkc",
		dlc: "BASE",
		description: [
			"A battle-worn spear worthy of the finest hunters. Charge Melee Attacks apply CORROSION dealing 100 ACID damage over 5s.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Huntress_Spear`,
		location: {
			world: "Losomn",
			biome: "Streets of Losomn",
			injectable: `Briella's Garden`,
		},
		linkedItems: {
			mod: {
				name: "Javelin",
			},
		},
		weaponModifiers: {
			damage: 63,
			crit: 5,
			weakspot: 110,
			stagger: -5,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Iron Greatsword",
		imageUrl: "items/weapons/irongreatsword.png",
		internalSlug: "Weapon_Greatsword_C",
		id: "5wy88e",
		dlc: "BASE",
		description: [
			"A giant broadsword made from flattened railroad tracks. Dozens of ridges cut in the side for causing irreparable damage.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Iron_Greatsword`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		weaponModifiers: {
			damage: 105,
			crit: 5,
			weakspot: 95,
			stagger: 13,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Knuckle Dusters",
		imageUrl: "items/weapons/knuckledusters.png",
		internalSlug: "Weapon_KnuckleDusters_C",
		id: "as4bt4",
		dlc: "BASE",
		description: [
			"Steel knuckles with rusty sawblade tips, designed to boost Unarmed damage.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Knuckle_Dusters`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		weaponModifiers: {
			damage: 43,
			crit: 5,
			weakspot: 110,
			stagger: 5,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Krell Axe",
		imageUrl: "items/weapons/krellaxe.png",
		internalSlug: "Weapon_KrellAxe_C",
		id: "5gl3la",
		dlc: "BASE",
		description: [
			"Infused with Krell Shock magic, can be thrown if the wielder has stamina. Axe will magically reappear in hand. Charge to throw.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Krell_Axe`,
		location: { world: "Yaesha", dungeon: [`Endaira's End`] },
		linkedItems: {
			mod: {
				name: "Krell Edge",
			},
		},
		weaponModifiers: {
			damage: 54,
			crit: 3,
			weakspot: 85,
			stagger: -10,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Labyrinth Staff",
		imageUrl: "items/weapons/labyrinthstaff.png",
		internalSlug: "Weapon_LabyrinthStaff_C",
		id: "gts5dh",
		dlc: "BASE",
		description: [
			"Basic Strikes generate 10% additional Mod Power. Charge Attacks perform an AOE which strikes all enemies within 2m, dealing 75 Damage. AOE Damage generates 50% additional Mod Power.",
		],
		communityTags: [`AOE/Aura`],
		location: { world: "Labyrinth", dungeon: ["Labyrinth"] },
		wikiUrl: `https://remnant2.wiki.gg/Labyrinth_Staff`,
		weaponModifiers: {
			damage: 64,
			crit: 8,
			weakspot: 95,
			stagger: 5,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Mirage",
		imageUrl: "items/weapons/mirage.png",
		internalSlug: "Weapon_Mirage_C",
		dlc: "DLC2",
		id: "6j7c6k",
		description: [
			"The mace whirs as if living harmonics hold its shape. When swung, a breath of sand tethers to the rock crown for extended reach and lethal momentum.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Mirage`,
		location: { world: "Yaesha", dungeon: [`Goddess's Rest`] },
		linkedItems: {
			mod: {
				name: "Cyclone",
			},
		},
		weaponModifiers: {
			damage: 48,
			crit: 3,
			weakspot: 100,
			stagger: -10,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Nightshade",
		imageUrl: "items/weapons/nightshade.png",
		internalSlug: "Weapon_Nightshade_C",
		id: "6j7czk",
		dlc: "BASE",
		description: [
			"Fast striking claws with a high Critical Hit chance. Neutral Dodge grants the power of Lifesteal.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Nightshade`,
		location: { world: "Losomn", dungeon: [`Tormented Asylum`] },
		linkedItems: {
			mod: {
				name: "Beyond the Veil",
			},
		},
		weaponModifiers: {
			damage: 47,
			crit: 18,
			weakspot: 110,
			stagger: -20,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Ornate Blade",
		imageUrl: "items/weapons/ornateblade.png",
		internalSlug: "Weapon_OrnateBlade_C",
		id: "0wto7p",
		dlc: "BASE",
		description: [
			"An intricately-forged elongated sword. Designed to keep stronger enemies at bay, while remaining light enough for agile maneuvers.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Ornate_Blade`,
		location: { world: "Losomn", dungeon: ["Council Chamber"] },
		weaponModifiers: {
			damage: 52,
			crit: 11,
			weakspot: 105,
			stagger: -5,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Ornate Flail",
		imageUrl: "items/weapons/ornateflail.png",
		internalSlug: "Weapon_OrnateFlail_C",
		id: "pwuhho",
		dlc: "BASE",
		description: [
			"An intricately-forged flail with uniquely designed airways. Allows smaller wielders to get the weapon up to speed much quicker.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Ornate_Flail`,
		location: {
			world: "Losomn",
			biome: "Fae Palace",
			injectable: "As Above, So Below",
		},
		weaponModifiers: {
			damage: 63,
			crit: 11,
			weakspot: 100,
			stagger: -3,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Rebellion Spear",
		imageUrl: "items/weapons/rebellionspear.png",
		internalSlug: "Weapon_RebellionSpear_C",
		id: "qy94qr",
		dlc: "BASE",
		description: [
			"A spear perfect for staying at a distance. Has excellent range, great recovery, and focused direct damage for one on one combat.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Rebellion_Spear`,
		location: { world: "Yaesha", dungeon: [`The Forbidden Grove`] },
		weaponModifiers: {
			damage: 60,
			crit: 13,
			weakspot: 110,
			stagger: 2,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Red Doe Staff",
		imageUrl: "items/weapons/reddoestaff.png",
		internalSlug: "Weapon_RedDoeStaff_C",
		id: "oazjm0",
		dlc: "BASE",
		description: [
			"A magical stave rumored to contain a healing spirit within. Strikes with wide swings.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Red_Doe_Staff`,
		location: { world: "Yaesha", dungeon: [`Ravager's Lair`] },
		linkedItems: {
			mod: {
				name: "Lifeline",
			},
		},
		weaponModifiers: {
			damage: 62,
			crit: 3,
			weakspot: 95,
			stagger: 8,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Ritualist Scythe",
		dlc: "DLC1",
		imageUrl: "items/weapons/scytheritualist.png",
		internalSlug: "Weapon_RitualistScythe_C",
		id: "7hoogs",
		description: [
			"An evil-fueled reaping tool that deals additional damage to suffering targets.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Ritualist_Scythe`,
		location: { world: "Losomn", dungeon: ["The Forgotten Commune"] },
		linkedItems: {
			mod: {
				name: "Reaver",
			},
		},
		weaponModifiers: {
			damage: 51,
			crit: 5,
			weakspot: 100,
			stagger: -19,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Royal Broadsword",
		imageUrl: "items/weapons/royalbroadsword.png",
		internalSlug: "Weapon_RoyalBroadsword_C",
		id: "wogdou",
		dlc: "BASE",
		description: [
			"Standard issue Greatsword for the Empress' Royal Guards. Razor-sharp edges, extremely heavy, yet perfectly balanced.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Royal_Broadsword`,
		location: { world: "Yaesha", dungeon: ["The Red Throne"] },
		weaponModifiers: {
			damage: 102,
			crit: 7,
			weakspot: 95,
			stagger: 11,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Rusted Claws",
		imageUrl: "items/weapons/rustedclaws.png",
		internalSlug: "Weapon_Claws_C",
		id: "6odjqi",
		dlc: "BASE",
		description: [
			"A pair of old-canine training bracers converted into deadly claws. Used for slashing and ripping.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Rusted_Claws`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		weaponModifiers: {
			damage: 51,
			crit: 14,
			weakspot: 110,
			stagger: -9,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Scrap Hammer",
		internalSlug: "Weapon_Hammer_C",
		imageUrl: "items/weapons/hammer.png",
		location: { world: "Ward 13", dungeon: "Vendor" },
		id: "a88cg7",
		dlc: "BASE",
		description: [
			"A large, heavy warhammer cobbled together from engine core. It is a slow-but-devastating weapon meant to destroy anything it hits.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Scrap_Hammer`,
		weaponModifiers: {
			damage: 83,
			crit: 8,
			weakspot: 95,
			stagger: 9,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Scrap Hatchet",
		internalSlug: "Weapon_Hatchet_C",
		imageUrl: "items/weapons/hatchet.png",
		location: { world: "Ward 13", dungeon: "Vendor" },
		id: "wtj6mq",
		dlc: "BASE",
		description: [
			"A common chopping tool that has been repurposed for combat. Rapidly cycles attacks from right to left. Charge attacks strike twice.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Scrap_Hatchet`,
		weaponModifiers: {
			damage: 57,
			crit: 6,
			weakspot: 105,
			stagger: 1,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Scrap Staff",
		internalSlug: "Weapon_Staff_C",
		imageUrl: "items/weapons/scrapstaff.png",
		id: "fp5yi4",
		dlc: "BASE",
		description: [
			"A staff made from old plumbing parts used for controlling wide swaths in front of the wielder.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Scrap_Staff`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		weaponModifiers: {
			damage: 65,
			crit: 6,
			weakspot: 95,
			stagger: 8,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Shovel",
		imageUrl: "items/weapons/shovel.png",
		internalSlug: "Weapon_BasicShovel_C",
		id: "vpEWS5",
		dlc: "BASE",
		description: ["It's a shovel."],
		wikiUrl: `https://remnant2.wiki.gg/Shovel`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		weaponModifiers: {
			damage: 55,
			crit: 15,
			weakspot: 100,
			stagger: 0,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Smolder",
		imageUrl: "items/weapons/smolder.png",
		internalSlug: "Weapon_Smolder_C",
		id: "d0usz6",
		dlc: "BASE",
		description: ["A scorched blade imbued with FIRE."],
		wikiUrl: `https://remnant2.wiki.gg/Smolder`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		linkedItems: {
			mod: {
				name: "Blaze",
			},
		},
		weaponModifiers: {
			damage: 46,
			crit: 4,
			weakspot: 95,
			stagger: 1,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Spectral Blade",
		imageUrl: "items/weapons/spectralblade.png",
		internalSlug: "Weapon_SpectralBlade_C",
		id: "l3zte1",
		dlc: "BASE",
		description: [
			"A super-heated laser sword with an infinitely sharp edge. Perfect for cutting... anything.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Spectral_Blade`,
		location: { world: `N'Erud`, dungeon: [`Sentinel's Keep`] },
		linkedItems: {
			mod: {
				name: "Whirlwind",
			},
		},
		weaponModifiers: {
			damage: 53,
			crit: 8,
			weakspot: 105,
			stagger: -25,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Steel Flail",
		internalSlug: "Weapon_Flail_C",
		imageUrl: "items/weapons/steelflail.png",
		id: "ji6tpl",
		dlc: "BASE",
		description: [
			"An unorthodox weapon meant to convert momentum into destruction. Some attacks can continuously chain overhead swings.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Steel_Flail`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		weaponModifiers: {
			damage: 69,
			crit: 4,
			weakspot: 100,
			stagger: 6,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Steel Katana",
		internalSlug: "Weapon_Katana_C",
		imageUrl: "items/weapons/steelkatana.png",
		id: "0cnwdx",
		dlc: "BASE",
		description: [
			"An old piece of steel with serrations cut into one side. Pipe handle provides limited grip.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Steel_Katana`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		weaponModifiers: {
			damage: 56,
			crit: 13,
			weakspot: 105,
			stagger: -10,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Steel Scythe",
		internalSlug: "Weapon_Scythe_C",
		imageUrl: "items/weapons/scythescrap.png",
		id: "2po1q8",
		dlc: "BASE",
		description: ["A ruthless threshing device."],
		wikiUrl: `https://remnant2.wiki.gg/Steel_Scythe`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		weaponModifiers: {
			damage: 55,
			crit: 10,
			weakspot: 100,
			stagger: -15,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Steel Spear",
		internalSlug: "Weapon_Spear_C",
		imageUrl: "items/weapons/steelspear.png",
		id: "vbzlfk",
		dlc: "BASE",
		description: [
			"A spear perfect for staying at range with quick, focused attacks. High, single-target damage.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Steel_Spear`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		weaponModifiers: {
			damage: 61,
			crit: 9,
			weakspot: 110,
			stagger: -4,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Steel Sword",
		internalSlug: "Weapon_Sword_C",
		imageUrl: "items/weapons/sword.png",
		id: "zsb5g1",
		dlc: "BASE",
		description: [
			"A long, sharp blade hammered out of vehicle leaf springs. Well-rounded for most situations.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Steel_Sword`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		weaponModifiers: {
			damage: 56,
			crit: 7,
			weakspot: 100,
			stagger: 2,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Stonebreaker",
		imageUrl: "items/weapons/stonebreaker.png",
		internalSlug: "Weapon_Stonebreaker_C",
		id: "b4g4q0",
		dlc: "BASE",
		description: [
			"A massive Greatsword which contains the harnessed magic of a corrupted Guardian. Can summon small shockwaves.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Stonebreaker`,
		location: { world: `Yaesha`, dungeon: ["The Great Bole"] },
		linkedItems: {
			mod: {
				name: "Faultline",
			},
		},
		weaponModifiers: {
			damage: 103,
			crit: 4,
			weakspot: 95,
			stagger: 5,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Vice Grips",
		imageUrl: "items/weapons/vicegrips.png",
		internalSlug: "Weapon_ViceGrips_C",
		id: "ygwrpd",
		dlc: "BASE",
		description: [
			"A N'Erudian tool converted into a ruthless ripping device. High raw damage.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Vice_Grips`,
		location: {
			world: `N'Erud`,
			dungeon: "Vendor",
		},
		weaponModifiers: {
			damage: 55,
			crit: 6,
			weakspot: 110,
			stagger: -18,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "World's Edge",
		imageUrl: "items/weapons/worldsedge.png",
		internalSlug: "Weapon_WorldsEdge_C",
		id: "gilcfn",
		dlc: "BASE",
		description: [
			"A glowing Greatsword forged from shards of a shattered Worldstone. Charge attacks cast waves.",
		],
		wikiUrl: `https://remnant2.wiki.gg/World's_Edge`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		linkedItems: {
			mod: {
				name: "Horizon Strike",
			},
		},
		weaponModifiers: {
			damage: 96,
			crit: 3,
			weakspot: 85,
			stagger: -20,
		},
	},
	{
		category: "WEAPON",
		subcategory: "melee",
		name: "Wrathbringer",
		dlc: "DLC1",
		imageUrl: "items/weapons/wrathbringer.png",
		internalSlug: "Weapon_Wrathbringer_C",
		id: "mq5fnr",
		description: [
			"A massive hammer infused with the souls of deceased Dran. Its dormant power can be awakened by taking damage.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Wrathbringer`,
		location: { world: "Losomn", dungeon: ["Chamber of the Faithless"] },
		linkedItems: {
			mod: {
				name: "Awakening",
			},
		},
		weaponModifiers: {
			damage: 101,
			crit: 6,
			weakspot: 85,
			stagger: 80,
		},
	},

	// #region Hand Guns
	{
		category: "WEAPON",
		subcategory: "hand gun",
		name: "Anguish",
		imageUrl: "items/weapons/anguish.png",
		internalSlug: "Weapon_Anguish_C",
		dlc: "DLC1",
		id: "r2o474",
		description: [
			"Fires heated bits of molten slag. Can be charged to fire a single explosive rod at the cost of causing damage to the wielder while charging.",
		],
		communityTags: [`Explosive Damage`],
		wikiUrl: `https://remnant2.wiki.gg/Anguish`,
		location: { world: "Losomn", dungeon: ["Tormented Asylum"] },
		linkedItems: {
			mod: {
				name: "Loathe the Weak",
			},
		},
		weaponModifiers: {
			damage: 92,
			rps: 1.85,
			magazine: 5,
			accuracy: 95,
			ideal: 16,
			falloff: 35,
			ammo: 35,
			crit: 5,
			weakspot: 100,
			stagger: 0,
		},
	},
	{
		category: "WEAPON",
		subcategory: "hand gun",
		name: "Bolt Driver",
		imageUrl: "items/weapons/boltdriver.png",
		internalSlug: "Weapon_BoltDriver_C",
		id: "d388ma",
		dlc: "BASE",
		description: [
			"An ingenius Gul rifle designed to harness energy from Pan crystals. Charge to fire a 3-shot burst.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Bolt_Driver`,
		location: { world: "Yaesha", dungeon: ["The Forbidden Grove"] },
		weaponModifiers: {
			damage: 26,
			rps: 7.63,
			magazine: 24,
			accuracy: 90,
			ideal: 18,
			falloff: 52,
			ammo: 96,
			crit: 10,
			weakspot: 105,
			stagger: -10,
		},
	},
	{
		category: "WEAPON",
		subcategory: "hand gun",
		name: "Corrupted Cube Gun",
		imageUrl: "items/weapons/corruptedcubegun.png",
		internalSlug: "Weapon_CorruptedCubeGun_C",
		id: "mSSxW6",
		dlc: "BASE",
		description: [
			"Fusion charged auto-cannon generates cubes which penetrate. Infinite ammo capacity. Can overheat. Cannot score Weakspot hits.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Corrupted_Cube_Gun`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		linkedItems: {
			mod: {
				name: "Cube Room",
			},
		},
		weaponModifiers: {
			damage: 66,
			rps: 2.2,
			magazine: 99,
			accuracy: 95,
			ideal: 15,
			falloff: 35,
			ammo: 105,
			crit: 5,
			weakspot: 0,
			stagger: 0,
		},
	},
	{
		category: "WEAPON",
		subcategory: "hand gun",
		name: "Corrupted Meridian",
		imageUrl: "items/weapons/corruptedmeridian.png",
		internalSlug: "Weapon_CorruptedMeridian_C",
		id: "yw1btj",
		dlc: "BASE",
		description: [
			"Fires rocket that deals AOE damage within 2m. Charging the weapon can load additional rockets. (Max 3). Cannot Weakspot.",
		],
		communityTags: [`AOE/Aura`, `Explosive Damage`],
		wikiUrl: `https://remnant2.wiki.gg/Corrupted_Meridian`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		linkedItems: {
			mod: {
				name: "Deadpoint",
			},
		},
		weaponModifiers: {
			damage: 90,
			rps: 1.9,
			magazine: 6,
			accuracy: 98,
			ideal: 15,
			falloff: 30,
			ammo: 36,
			crit: 0,
			weakspot: 0,
			stagger: 0,
		},
	},
	{
		category: "WEAPON",
		subcategory: "hand gun",
		name: "Corrupted Nebula",
		imageUrl: "items/weapons/corruptednebula.png",
		internalSlug: "Weapon_CorruptedNebula_C",
		id: "8u8j4G",
		dlc: "BASE",
		description: [
			"Semi-automatic laser weapon. Weakspot hits and kills create a Nano-bot for 8s that seeks enemies within 20m and repeatedly attacks dealing 6 → 18 ACID damage per hit. Max 5 Nano-bots.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Corrupted_Nebula`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		linkedItems: {
			mod: {
				name: "Nano Phase",
			},
		},
		weaponModifiers: {
			damage: 24,
			rps: 5.2,
			magazine: 15,
			accuracy: 95,
			ideal: 17,
			falloff: 56,
			ammo: 105,
			crit: 5,
			weakspot: 105,
			stagger: 0,
		},
	},
	{
		category: "WEAPON",
		subcategory: "hand gun",
		name: "Corrupted Rune Pistol",
		imageUrl: "items/weapons/corruptedrunepistol.png",
		internalSlug: "Weapon_CorruptedRunePistol_C",
		id: "id5pbt",
		dlc: "BASE",
		description: [
			"A pistol infused with erroneous properties. Fires energy, allowing the trigger to be held for continuous fire.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Corrupted_Rune_Pistol`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		linkedItems: {
			mod: {
				name: "Death Brand",
			},
		},
		weaponModifiers: {
			damage: 17,
			rps: 6.3,
			magazine: 25,
			accuracy: 95,
			ideal: 17,
			falloff: 53,
			ammo: 150,
			crit: 10,
			weakspot: 100,
			stagger: 0,
		},
	},
	{
		category: "WEAPON",
		subcategory: "hand gun",
		name: "Corrupted Sorrow",
		id: "zrP64k",
		dlc: "BASE",
		internalSlug: "Weapon_CorruptedSorrow_C",
		imageUrl: "items/weapons/corruptedsorrow.png",
		description: [
			"Innately cannot harm allies. Fires bolts which anchor to targets for 6s. Max 10 bolts anchored at once.",
		],
		linkedItems: {
			mod: {
				name: "Will of the Wisp",
			},
		},
		wikiUrl: `https://remnant2.wiki.gg/Corrupted_Sorrow`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		weaponModifiers: {
			damage: 42,
			rps: 2.6,
			magazine: 10,
			accuracy: 95,
			ideal: 17,
			falloff: 52,
			ammo: 60,
			crit: 8,
			weakspot: 105,
			stagger: 0,
		},
	},
	{
		category: "WEAPON",
		subcategory: "hand gun",
		name: "Cube Gun",
		internalSlug: "Weapon_CubeGun_C",
		imageUrl: "items/weapons/cubegun.png",
		id: "zn3boo",
		dlc: "BASE",
		description: [
			"Projectiles return on hit or after reaching max range. Reloading retrieves shot projectiles. Max 5 fired projectiles. Infinite ammo. Can overheat.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Cube_Gun`,
		location: { world: "Labyrinth", dungeon: ["Labyrinth"] },
		linkedItems: {
			mod: {
				name: "Cube Shield",
			},
		},
		weaponModifiers: {
			damage: 15,
			rps: 7.5,
			magazine: 5,
			accuracy: 90,
			ideal: 20,
			falloff: 50,
			ammo: 105,
			crit: 5,
			weakspot: 85,
			stagger: 0,
		},
	},
	{
		category: "WEAPON",
		subcategory: "hand gun",
		name: "Double Barrel",
		internalSlug: "Weapon_ShortBarrel_C",
		imageUrl: "items/weapons/shortbarrel.png",
		id: "ztz84h",
		dlc: "BASE",
		description: [
			"A double-barrel shotgun which can deal massive damage at close range with back to back shots.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Double_Barrel`,
		location: { world: "Losomn", dungeon: ["Morrow Parish"] },
		weaponModifiers: {
			damage: 105,
			rps: 2.25,
			magazine: 2,
			accuracy: 60,
			ideal: 8,
			falloff: 20,
			ammo: 24,
			crit: 5,
			weakspot: 100,
			stagger: 10,
		},
	},
	{
		category: "WEAPON",
		subcategory: "hand gun",
		name: "Enigma",
		imageUrl: "items/weapons/enigma.png",
		internalSlug: "Weapon_Enigma_C",
		id: "d06hjq",
		dlc: "BASE",
		description: [
			"Fires an electrical stream that jumps to nearby targets within 7.5m, dealing 30% reduced damage per jump. Applies OVERLOADED.",
		],
		communityTags: [`AOE/Aura`],
		wikiUrl: `https://remnant2.wiki.gg/Enigma`,
		location: { world: "Labyrinth", dungeon: ["Labyrinth"] },
		linkedItems: {
			mod: {
				name: "Chaos Driver",
			},
		},
		weaponModifiers: {
			damage: 22,
			rps: 4,
			magazine: 25,
			accuracy: 60,
			ideal: 12,
			falloff: 12,
			ammo: 125,
			crit: -10,
			weakspot: 0,
			stagger: -15,
		},
	},
	{
		category: "WEAPON",
		subcategory: "hand gun",
		name: "Hellfire",
		imageUrl: "items/weapons/hellfire.png",
		internalSlug: "Weapon_Hellfire_C",
		id: "797iqq",
		dlc: "BASE",
		description: [
			"Spews flames that apply BURNING which deals 300 → 900 FIRE damage over 10 seconds.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Hellfire`,
		location: { world: "Root Earth", dungeon: ["Ashen Wasteland"] },
		linkedItems: {
			mod: {
				name: "Explosive Shot",
			},
		},
		weaponModifiers: {
			damage: 13,
			rps: 6,
			magazine: 60,
			accuracy: 15,
			ideal: 8,
			falloff: 8,
			ammo: 180,
			crit: 0,
			weakspot: 0,
			stagger: -15,
		},
	},
	{
		category: "WEAPON",
		subcategory: "hand gun",
		name: "Meridian",
		internalSlug: "Weapon_Meridian_C",
		imageUrl: "items/weapons/meridian.png",
		id: "1ziutf",
		dlc: "BASE",
		description: [
			"Fires grenades that explode on contact with enemies and deal AOE damage within 4m. Dormant grenades eventually explode and can be shot to detonate early. Cannot Weakspot.",
		],
		communityTags: [`AOE/Aura`, `Explosive Damage`],
		wikiUrl: `https://remnant2.wiki.gg/Meridian`,
		location: {
			world: "Losomn",
			biome: "Losomn Sewers",
			injectable: "Rising Tides",
		},
		linkedItems: {
			mod: {
				name: "Screamer",
			},
		},
		weaponModifiers: {
			damage: 82,
			rps: 1.9,
			magazine: 5,
			accuracy: 100,
			ideal: 15,
			falloff: 30,
			ammo: 40,
			crit: 0,
			weakspot: 0,
			stagger: 0,
		},
	},
	{
		category: "WEAPON",
		subcategory: "hand gun",
		name: "MP60-R",
		imageUrl: "items/weapons/mp60r.png",
		internalSlug: "Weapon_SMG_C",
		id: "ty2gsi",
		dlc: "BASE",
		description: [
			"A small-caliber sub-machine gun best suited for close range skirmishes.",
		],
		wikiUrl: `https://remnant2.wiki.gg/MP60-R`,
		location: { world: "Ward 13", dungeon: "Ward 13" },
		weaponModifiers: {
			damage: 9,
			rps: 14.2,
			magazine: 42,
			accuracy: 95,
			ideal: 17,
			falloff: 50,
			ammo: 294,
			crit: 10,
			weakspot: 100,
			stagger: 0,
		},
	},
	{
		category: "WEAPON",
		subcategory: "hand gun",
		name: "Nebula",
		internalSlug: "Weapon_Nebula_C",
		imageUrl: "items/weapons/nebula.png",
		id: "p7tsxr",
		dlc: "BASE",
		description: [
			"Fires a stream of superhot ACID gas which applies CORRODED effect, dealing 300 - 900 CORROSIVE Damage over 10s. Killing targets CORRODED by Nebula spawns a gas cloud which applies its on-hit effect. Gas clouds lasts 2s and can be refreshed.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Nebula`,
		location: { world: `N'Erud`, dungeon: [`Forgotten Prison`] },
		linkedItems: {
			mod: {
				name: "Nano Swarm",
			},
		},
		weaponModifiers: {
			damage: 12,
			rps: 8,
			magazine: 55,
			accuracy: 15,
			ideal: 8,
			falloff: 8,
			ammo: 220,
			crit: 0,
			weakspot: 0,
			stagger: -15,
		},
	},
	{
		category: "WEAPON",
		subcategory: "hand gun",
		name: "Repair Tool",
		internalSlug: "Weapon_RepairTool_C",
		imageUrl: "items/weapons/repairtool.png",
		id: "5go8dn",
		dlc: "DLC3",
		communityTags: [],
		description: [
			"Fires a stream of nanomachines, dealing damage to enemies or healing allies for 3% of their Max Health per second. The nano-tech also restores N'Erudian Energy to Turrets and Drones.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Repair_Tool`,
		location: { world: `N'Erud`, dungeon: [`Agronomy Sector`] },
		weaponModifiers: {
			damage: 10,
			rps: 11,
			magazine: 150,
			accuracy: 100,
			ideal: 16,
			falloff: 30,
			ammo: 300,
			crit: 5,
			weakspot: 80,
			stagger: -20,
		},
	},
	{
		category: "WEAPON",
		subcategory: "hand gun",
		name: "Redeemer",
		imageUrl: "items/weapons/redeemer.png",
		internalSlug: "Weapon_Redeemer_C",
		id: "0kob6g",
		dlc: "DLC3",
		description: [
			"Fires a tight grouping of World Stone slugs. Hits rip away a small portion of the enemy, sending it to another realm.",
			"Incapable of standard Mod Generation.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Redeemer`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		linkedItems: {
			mod: {
				name: "Aftermath",
			},
		},
		weaponModifiers: {
			damage: 69,
			rps: 2.5,
			magazine: 6,
			ammo: 36,
			ideal: 20,
			falloff: 60,
			crit: 5,
			weakspot: 100,
			stagger: -35,
		},
	},
	{
		category: "WEAPON",
		subcategory: "hand gun",
		name: "Repeater Pistol",
		internalSlug: "Weapon_Repeater_C",
		imageUrl: "items/weapons/repeater.png",
		id: "pbtmmj",
		dlc: "BASE",
		description: [
			"An accurate semi-automatic pistol that can rapidly fire small-caliber bullets.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Repeater_Pistol`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		weaponModifiers: {
			damage: 16,
			rps: 8.1,
			magazine: 20,
			accuracy: 95,
			ideal: 18,
			falloff: 52,
			ammo: 160,
			crit: 5,
			weakspot: 105,
			stagger: -10,
		},
	},
	{
		category: "WEAPON",
		subcategory: "hand gun",
		name: "Rune Pistol",
		imageUrl: "items/weapons/runepistol.png",
		internalSlug: "Weapon_RunePistol_C",
		id: "2pblgq",
		dlc: "BASE",
		description: [
			"A pistol infused with mysterious Fae magic. Rapidly fires 3-round bursts of energy. Trigger can be held to continuously fire.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Rune_Pistol`,
		location: { world: "Losomn", dungeon: ["Tormented Asylum"] },
		linkedItems: {
			mod: {
				name: "Soul Brand",
			},
		},
		weaponModifiers: {
			damage: 16,
			rps: 6.6,
			magazine: 45,
			accuracy: 95,
			ideal: 18,
			falloff: 53,
			ammo: 180,
			crit: 10,
			weakspot: 105,
			stagger: 0,
		},
	},
	{
		category: "WEAPON",
		subcategory: "hand gun",
		name: "Rupture Cannon",
		imageUrl: "items/weapons/rupturecannon.png",
		internalSlug: "Weapon_RuptureCannon_C",
		id: "xzlpao",
		dlc: "BASE",
		description: [
			"A mid-range Pistol Shotgun with a brisk fire rate and medium recoil. Slower reload.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Rupture_Cannon`,
		location: { world: `N'Erud`, dungeon: [`Vault of the Formless`] },
		weaponModifiers: {
			damage: 42,
			rps: 2.75,
			magazine: 12,
			accuracy: 90,
			ideal: 14,
			falloff: 35,
			ammo: 60,
			crit: 5,
			weakspot: 100,
			stagger: 10,
		},
	},
	{
		category: "WEAPON",
		subcategory: "hand gun",
		name: "Rusty Repeater",
		internalSlug: "Weapon_Repeater_Rusty_C",
		imageUrl: "items/weapons/rustyrepeater.png",
		id: "t412us",
		dlc: "BASE",
		description: ["An old antique pistol."],
		wikiUrl: `https://remnant2.wiki.gg/Rusty_Repeater`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		weaponModifiers: {
			damage: 15,
			isRusty: true,
			rps: 7.2,
			magazine: 15,
			accuracy: 95,
			ideal: 17,
			falloff: 55,
			ammo: 180,
			crit: 0,
			weakspot: 100,
			stagger: -10,
		},
	},
	{
		category: "WEAPON",
		subcategory: "hand gun",
		name: "Service Pistol",
		imageUrl: "items/weapons/servicepistol.png",
		internalSlug: "Weapon_ServicePistol_C",
		id: "g34ywl",
		dlc: "BASE",
		description: [
			"A standard issue military spec sidearm known for its reliability and accuracy.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Service_Pistol`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		weaponModifiers: {
			damage: 24,
			rps: 6.5,
			magazine: 12,
			accuracy: 85,
			ideal: 20,
			falloff: 50,
			ammo: 120,
			crit: 5,
			weakspot: 105,
			stagger: 0,
		},
	},
	{
		category: "WEAPON",
		subcategory: "hand gun",
		name: "Silverback Model 500",
		internalSlug: "Weapon_Magnum_C",
		imageUrl: "items/weapons/magnum.png",
		id: "46cwa6",
		dlc: "BASE",
		description: [
			"A powerful hand cannon with a low capacity cylinder. High damage and a heavy kick.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Silverback_Model_500`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		weaponModifiers: {
			damage: 55,
			rps: 2.4,
			magazine: 6,
			accuracy: 95,
			ideal: 20,
			falloff: 60,
			ammo: 48,
			crit: 5,
			weakspot: 105,
			stagger: 20,
		},
	},
	{
		category: "WEAPON",
		subcategory: "hand gun",
		name: "Sorrow",
		internalSlug: "Weapon_Sorrow_C",
		imageUrl: "items/weapons/sorrow.png",
		id: "u2z8i3",
		dlc: "BASE",
		description: [
			"The last vestiges of a fallen sister, this mystical crossbow pistol has the ability to recall its bolts to heal the wielder.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Sorrow`,
		location: {
			world: "Yaesha",
			biome: "Jungles of Yaesha",
			injectable: "Dappled Glade",
		},
		linkedItems: {
			mod: {
				name: "Eulogy",
			},
		},
		weaponModifiers: {
			damage: 45,
			rps: 2.6,
			magazine: 5,
			accuracy: 95,
			ideal: 19,
			falloff: 52,
			ammo: 45,
			crit: 10,
			weakspot: 115,
			stagger: 5,
		},
	},
	{
		category: "WEAPON",
		subcategory: "hand gun",
		name: "Star Shot",
		imageUrl: "items/weapons/starshot.png",
		internalSlug: "Weapon_StarShot_C",
		id: "tldnuq",
		dlc: "BASE",
		description: [
			"Fires a fast moving projectile which explodes on contact. Explosion has no damage falloff.",
		],
		communityTags: [`AOE/Aura`, `Explosive Damage`],
		wikiUrl: `https://remnant2.wiki.gg/Star_Shot`,
		location: { world: `N'Erud`, dungeon: [`The Dark Conduit`] },
		linkedItems: {
			mod: {
				name: "Big Bang",
			},
		},
		weaponModifiers: {
			damage: 22,
			rps: 2.5,
			magazine: 10,
			accuracy: 95,
			ideal: 21,
			falloff: 54,
			ammo: 60,
			crit: 5,
			weakspot: 110,
			stagger: 10,
		},
	},
	{
		category: "WEAPON",
		subcategory: "hand gun",
		name: "Sureshot",
		internalSlug: "Weapon_HuntingPistol_C",
		imageUrl: "items/weapons/huntingpistol.png",
		id: "50i9nj",
		dlc: "BASE",
		description: [
			"A high-caliber single-shot hunting pistol that inflicts heavy damage at mid to long range.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Sureshot`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		weaponModifiers: {
			damage: 115,
			rps: 3,
			magazine: 1,
			accuracy: 80,
			ideal: 22,
			falloff: 75,
			ammo: 24,
			crit: 10,
			weakspot: 115,
			stagger: 20,
		},
	},
	{
		category: "WEAPON",
		subcategory: "hand gun",
		name: "Tech 22",
		imageUrl: "items/weapons/tech22.png",
		internalSlug: "Weapon_MachinePistol_C",
		id: "xj5syj",
		dlc: "BASE",
		description: [
			"A suppressed small-caliber automatic pistol with medium magazine capacity and a high fire rate.",
		],
		wikiUrl: `https://remnant2.wiki.gg/Tech_22`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		weaponModifiers: {
			damage: 9,
			rps: 15,
			magazine: 32,
			accuracy: 95,
			ideal: 15,
			falloff: 45,
			ammo: 352,
			crit: 10,
			weakspot: 100,
			stagger: -10,
		},
	},
	{
		category: "WEAPON",
		subcategory: "hand gun",
		name: "Western Classic",
		internalSlug: "Weapon_Revolver_C",
		imageUrl: "items/weapons/westernclassic.png",
		id: "hk5uls",
		dlc: "BASE",
		description: ["A classic six-shooter. Tough. Dependable."],
		wikiUrl: `https://remnant2.wiki.gg/Western_Classic`,
		location: { world: "Ward 13", dungeon: "Vendor" },
		weaponModifiers: {
			damage: 36,
			rps: 5.75,
			magazine: 6,
			accuracy: 95,
			ideal: 18,
			falloff: 48,
			ammo: 72,
			crit: 5,
			weakspot: 110,
			stagger: 5,
		},
	},
];

export { type Remnant2WeaponItem, WEAPONS };
