const LOSOMN_DUNGEONS = [
	"Morrow Parish",
	"Forsaken Quarter",
	"Tormented Asylum",
	"Beatific Palace",
	"Ironborough",
	"Brocwithe Quarter",
	"Malefic Palace",
	"Beatific Gallery",
	"Malefic Gallery",
	`Nimue's Retreat`,
	`Cotton's Kiln`,
	`The Great Sewers`,
	`Gilded Chambers`,
	"Shattered Gallery",
	`Butcher's Quarter`,
	"Council Chamber",
	"The Great Hall",
	`Harvester's Reach`,
	`Postulant's Parlor`,
	`Tiller's Rest`,
	`Briella's Garden`,
	`Briella's Reverie`,
	`Hewdas Clock`,
	"Lemark District",
	`Oracle's Refuge`,
	`Forlorn Coast`,
	`Palace of the One True King`,
	`Chamber of the Faithless`,
	`Glistering Cloister`,
	`Sunken Haunt`,
	`Derelict Lighthouse`,
	`The Forgotten Commune`,
	`Pathway of the Fallen`,
	`Walk of Rememberance`,
] as const satisfies string[];
type LosomnDungeon = (typeof LOSOMN_DUNGEONS)[number];

export { LOSOMN_DUNGEONS, type LosomnDungeon };
