const YAESHA_DUNGEONS = [
	`The Red Throne`,
	`Withering Weald`,
	`The Far Woods`,
	`The Widow's Court`,
	`The Great Bole`,
	`The Forbidden Grove`,
	`Faithless Thicket`,
	`Ravager's Lair`,
	`The Expanding Glade`,
	`Kaeula's Rest`,
	`The Nameless Nest`,
	`The Twisted Chantry`,
	`Cathedral of Omens`,
	`The Chimney`,
	`Endaira's End`,
	`Forgotten Field`,
	`Imperial Gardens`,
	`The Lament`,
	`Dappled Glade`,
	`Kaora Kuri Nest`,
	`Root Nexus`,
	`The Forgotten Grove`,
	"Floating Forests",
	"Infested Abyss",
	"Ancient Canopy",
	"Proving Grounds",
	`Goddess's Rest`,
	`Deserted Atelier`,
	`Bloodless Throne`,
	`Glittering Grotto`,
	"Luminous Vale",
	"Earthen Coliseum",
] as const satisfies string[];
type YaeshaDungeon = (typeof YAESHA_DUNGEONS)[number];

export { YAESHA_DUNGEONS, type YaeshaDungeon };
