/**
 * Searchable tags for allow for grouping of items where there are
 * inconsistencies in the item descriptions. The community decided
 * on these tags to ensure that items could be found reliably.
 *
 * For example, `chance to crit` versus `critical chance` would miss some
 * items if the user searched for `critical chance` only. These tags allow
 * both to be found under the `Critical Chance` tag when searching.
 */
const SEARCHABLE_ITEM_TAGS = [
	"Ammo Reserves", // only need plural due to wording in game
	"All Damage",
	"Armor Increase",
	"Charged Melee Damage",
	"Charged Melee",
	"Charged Shot",
	"Concoction",
	"Consumable",
	"Critical Chance",
	"Critical Damage",
	"Critical Hit",
	"Damage Reduction",
	"Elemental Damage",
	"Encumbrance",
	"Firearm Swap Speed",
	"Fire Rate",
	"Grenade",
	"Grey Health",
	"Hardcore Reward",
	"Heal",
	"Healing Effectiveness",
	"Health",
	"Heat Generation",
	"Lifesteal",
	"Magazine Capacity",
	"Melee Attack Speed",
	"Melee Charge Speed",
	"Melee Critical Chance",
	"Melee Critical Damage",
	"Melee Critical Hit",
	"Melee",
	"Melee Damage",
	"Melee Hit",
	"Melee Special Ability",
	"Melee Speed",
	"Mod Cast Speed",
	"Mod Cooldown",
	"Mod Cost",
	"Mod Damage",
	"Mod Duration",
	"Mod Power",
	"Movement Speed",
	"Neutral Backdash",
	"Neutral Dodge",
	"Perfect Dodge",
	"Perfect Neutral Evade",
	"Projectile Speed",
	"Range",
	"Ranged Damage",
	"Recoil",
	"Reduce Skill Cooldown",
	"Relic Use Speed",
	"Reload Speed",
	"Skill Cast Speed",
	"Skill Damage",
	"Skill Duration",
	"Spread",
	"Stagger",
	"Stamina",
	"Status Duration",
	"Status Effect",
	"Summon",
	"Weakspot Critical Chance",
	"Weakspot Damage",
	"Weakspot Hit",
	"Weapon Damage",
] as const satisfies string[];

export { SEARCHABLE_ITEM_TAGS };
