const NERUD_DUNGEONS = [
	`Seeker's Rest`,
	"Phantom Wasteland",
	"Timeless Horizon",
	`Sentinel's Keep`,
	`Forgotten Prison`,
	`Abyssyal Rift`,
	`The Eon Vault`,
	`Tal'Ratha's Refuge`,
	`Astropath's Respite`,
	`The Hatchery`,
	`The Putrid Domain`,
	`Spectrum Nexus`,
	`The Dark Conduit`,
	`Dormant N'Erudian Facility`,
	`Terminus Station`,
	`Tower of the Unseen`,
	`Vault of the Formless`,
	`Void Vessel Facility`,
	`Extraction Hub`,
	`Titan's Reach`,
	`Alepsis-Taura`,
	"Ascension Spire",
	`Stagnant Manufactory`,
	`Withered Necropolis`,
	"Detritus Foundry",
	"Logistics Bridge",
	"Agronomy Sector",
	"Athenaeum Wek",
	"Mucid Terrarium",
	"Bicentennial Man",
	"Devoid Quietus",
] as const satisfies string[];
type NErudDungeon = (typeof NERUD_DUNGEONS)[number];

export { NERUD_DUNGEONS, type NErudDungeon };
