/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as ProfileRouteRouteImport } from './routes/profile/route'
import { Route as GameIdRouteRouteImport } from './routes/$gameId/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as ProfileLikedBuildsRouteImport } from './routes/profile/liked-builds'
import { Route as ProfileCreatedBuildsRouteImport } from './routes/profile/created-builds'
import { Route as ProfileCollectionStatsRouteImport } from './routes/profile/collection-stats'
import { Route as ProfileBuildCollectionsRouteImport } from './routes/profile/build-collections'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as GameIdItemsRouteImport } from './routes/$gameId/items'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AccountProfileUserIdRouteRouteImport } from './routes/account/profile/$userId/route'
import { Route as AccountProfileUserIdIndexRouteImport } from './routes/account/profile/$userId/index'
import { Route as AccountProfileUserIdLikedBuildsRouteImport } from './routes/account/profile/$userId/liked-builds'
import { Route as AccountProfileUserIdDataSyncRouteImport } from './routes/account/profile/$userId/data-sync'
import { Route as AccountProfileUserIdCreatedBuildsRouteImport } from './routes/account/profile/$userId/created-builds'
import { Route as AccountProfileUserIdCollectionStatsRouteImport } from './routes/account/profile/$userId/collection-stats'
import { Route as AccountProfileUserIdBuildCollectionsRouteImport } from './routes/account/profile/$userId/build-collections'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRouteRoute = ProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIdRouteRoute = GameIdRouteRouteImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileLikedBuildsRoute = ProfileLikedBuildsRouteImport.update({
  id: '/liked-builds',
  path: '/liked-builds',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileCreatedBuildsRoute = ProfileCreatedBuildsRouteImport.update({
  id: '/created-builds',
  path: '/created-builds',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileCollectionStatsRoute = ProfileCollectionStatsRouteImport.update({
  id: '/collection-stats',
  path: '/collection-stats',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileBuildCollectionsRoute = ProfileBuildCollectionsRouteImport.update({
  id: '/build-collections',
  path: '/build-collections',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIdItemsRoute = GameIdItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => GameIdRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountProfileUserIdRouteRoute =
  AccountProfileUserIdRouteRouteImport.update({
    id: '/account/profile/$userId',
    path: '/account/profile/$userId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountProfileUserIdIndexRoute =
  AccountProfileUserIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AccountProfileUserIdRouteRoute,
  } as any)
const AccountProfileUserIdLikedBuildsRoute =
  AccountProfileUserIdLikedBuildsRouteImport.update({
    id: '/liked-builds',
    path: '/liked-builds',
    getParentRoute: () => AccountProfileUserIdRouteRoute,
  } as any)
const AccountProfileUserIdDataSyncRoute =
  AccountProfileUserIdDataSyncRouteImport.update({
    id: '/data-sync',
    path: '/data-sync',
    getParentRoute: () => AccountProfileUserIdRouteRoute,
  } as any)
const AccountProfileUserIdCreatedBuildsRoute =
  AccountProfileUserIdCreatedBuildsRouteImport.update({
    id: '/created-builds',
    path: '/created-builds',
    getParentRoute: () => AccountProfileUserIdRouteRoute,
  } as any)
const AccountProfileUserIdCollectionStatsRoute =
  AccountProfileUserIdCollectionStatsRouteImport.update({
    id: '/collection-stats',
    path: '/collection-stats',
    getParentRoute: () => AccountProfileUserIdRouteRoute,
  } as any)
const AccountProfileUserIdBuildCollectionsRoute =
  AccountProfileUserIdBuildCollectionsRouteImport.update({
    id: '/build-collections',
    path: '/build-collections',
    getParentRoute: () => AccountProfileUserIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$gameId': typeof GameIdRouteRouteWithChildren
  '/profile': typeof ProfileRouteRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/$gameId/items': typeof GameIdItemsRoute
  '/api/health': typeof ApiHealthRoute
  '/profile/build-collections': typeof ProfileBuildCollectionsRoute
  '/profile/collection-stats': typeof ProfileCollectionStatsRoute
  '/profile/created-builds': typeof ProfileCreatedBuildsRoute
  '/profile/liked-builds': typeof ProfileLikedBuildsRoute
  '/profile/': typeof ProfileIndexRoute
  '/account/profile/$userId': typeof AccountProfileUserIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/account/profile/$userId/build-collections': typeof AccountProfileUserIdBuildCollectionsRoute
  '/account/profile/$userId/collection-stats': typeof AccountProfileUserIdCollectionStatsRoute
  '/account/profile/$userId/created-builds': typeof AccountProfileUserIdCreatedBuildsRoute
  '/account/profile/$userId/data-sync': typeof AccountProfileUserIdDataSyncRoute
  '/account/profile/$userId/liked-builds': typeof AccountProfileUserIdLikedBuildsRoute
  '/account/profile/$userId/': typeof AccountProfileUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$gameId': typeof GameIdRouteRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/$gameId/items': typeof GameIdItemsRoute
  '/api/health': typeof ApiHealthRoute
  '/profile/build-collections': typeof ProfileBuildCollectionsRoute
  '/profile/collection-stats': typeof ProfileCollectionStatsRoute
  '/profile/created-builds': typeof ProfileCreatedBuildsRoute
  '/profile/liked-builds': typeof ProfileLikedBuildsRoute
  '/profile': typeof ProfileIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/account/profile/$userId/build-collections': typeof AccountProfileUserIdBuildCollectionsRoute
  '/account/profile/$userId/collection-stats': typeof AccountProfileUserIdCollectionStatsRoute
  '/account/profile/$userId/created-builds': typeof AccountProfileUserIdCreatedBuildsRoute
  '/account/profile/$userId/data-sync': typeof AccountProfileUserIdDataSyncRoute
  '/account/profile/$userId/liked-builds': typeof AccountProfileUserIdLikedBuildsRoute
  '/account/profile/$userId': typeof AccountProfileUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$gameId': typeof GameIdRouteRouteWithChildren
  '/profile': typeof ProfileRouteRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/$gameId/items': typeof GameIdItemsRoute
  '/api/health': typeof ApiHealthRoute
  '/profile/build-collections': typeof ProfileBuildCollectionsRoute
  '/profile/collection-stats': typeof ProfileCollectionStatsRoute
  '/profile/created-builds': typeof ProfileCreatedBuildsRoute
  '/profile/liked-builds': typeof ProfileLikedBuildsRoute
  '/profile/': typeof ProfileIndexRoute
  '/account/profile/$userId': typeof AccountProfileUserIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/account/profile/$userId/build-collections': typeof AccountProfileUserIdBuildCollectionsRoute
  '/account/profile/$userId/collection-stats': typeof AccountProfileUserIdCollectionStatsRoute
  '/account/profile/$userId/created-builds': typeof AccountProfileUserIdCreatedBuildsRoute
  '/account/profile/$userId/data-sync': typeof AccountProfileUserIdDataSyncRoute
  '/account/profile/$userId/liked-builds': typeof AccountProfileUserIdLikedBuildsRoute
  '/account/profile/$userId/': typeof AccountProfileUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$gameId'
    | '/profile'
    | '/changelog'
    | '/sign-in'
    | '/sign-up'
    | '/$gameId/items'
    | '/api/health'
    | '/profile/build-collections'
    | '/profile/collection-stats'
    | '/profile/created-builds'
    | '/profile/liked-builds'
    | '/profile/'
    | '/account/profile/$userId'
    | '/api/auth/$'
    | '/account/profile/$userId/build-collections'
    | '/account/profile/$userId/collection-stats'
    | '/account/profile/$userId/created-builds'
    | '/account/profile/$userId/data-sync'
    | '/account/profile/$userId/liked-builds'
    | '/account/profile/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$gameId'
    | '/changelog'
    | '/sign-in'
    | '/sign-up'
    | '/$gameId/items'
    | '/api/health'
    | '/profile/build-collections'
    | '/profile/collection-stats'
    | '/profile/created-builds'
    | '/profile/liked-builds'
    | '/profile'
    | '/api/auth/$'
    | '/account/profile/$userId/build-collections'
    | '/account/profile/$userId/collection-stats'
    | '/account/profile/$userId/created-builds'
    | '/account/profile/$userId/data-sync'
    | '/account/profile/$userId/liked-builds'
    | '/account/profile/$userId'
  id:
    | '__root__'
    | '/'
    | '/$gameId'
    | '/profile'
    | '/changelog'
    | '/sign-in'
    | '/sign-up'
    | '/$gameId/items'
    | '/api/health'
    | '/profile/build-collections'
    | '/profile/collection-stats'
    | '/profile/created-builds'
    | '/profile/liked-builds'
    | '/profile/'
    | '/account/profile/$userId'
    | '/api/auth/$'
    | '/account/profile/$userId/build-collections'
    | '/account/profile/$userId/collection-stats'
    | '/account/profile/$userId/created-builds'
    | '/account/profile/$userId/data-sync'
    | '/account/profile/$userId/liked-builds'
    | '/account/profile/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameIdRouteRoute: typeof GameIdRouteRouteWithChildren
  ProfileRouteRoute: typeof ProfileRouteRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiHealthRoute: typeof ApiHealthRoute
  AccountProfileUserIdRouteRoute: typeof AccountProfileUserIdRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$gameId': {
      id: '/$gameId'
      path: '/$gameId'
      fullPath: '/$gameId'
      preLoaderRoute: typeof GameIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/liked-builds': {
      id: '/profile/liked-builds'
      path: '/liked-builds'
      fullPath: '/profile/liked-builds'
      preLoaderRoute: typeof ProfileLikedBuildsRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/created-builds': {
      id: '/profile/created-builds'
      path: '/created-builds'
      fullPath: '/profile/created-builds'
      preLoaderRoute: typeof ProfileCreatedBuildsRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/collection-stats': {
      id: '/profile/collection-stats'
      path: '/collection-stats'
      fullPath: '/profile/collection-stats'
      preLoaderRoute: typeof ProfileCollectionStatsRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/build-collections': {
      id: '/profile/build-collections'
      path: '/build-collections'
      fullPath: '/profile/build-collections'
      preLoaderRoute: typeof ProfileBuildCollectionsRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$gameId/items': {
      id: '/$gameId/items'
      path: '/items'
      fullPath: '/$gameId/items'
      preLoaderRoute: typeof GameIdItemsRouteImport
      parentRoute: typeof GameIdRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/profile/$userId': {
      id: '/account/profile/$userId'
      path: '/account/profile/$userId'
      fullPath: '/account/profile/$userId'
      preLoaderRoute: typeof AccountProfileUserIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/profile/$userId/': {
      id: '/account/profile/$userId/'
      path: '/'
      fullPath: '/account/profile/$userId/'
      preLoaderRoute: typeof AccountProfileUserIdIndexRouteImport
      parentRoute: typeof AccountProfileUserIdRouteRoute
    }
    '/account/profile/$userId/liked-builds': {
      id: '/account/profile/$userId/liked-builds'
      path: '/liked-builds'
      fullPath: '/account/profile/$userId/liked-builds'
      preLoaderRoute: typeof AccountProfileUserIdLikedBuildsRouteImport
      parentRoute: typeof AccountProfileUserIdRouteRoute
    }
    '/account/profile/$userId/data-sync': {
      id: '/account/profile/$userId/data-sync'
      path: '/data-sync'
      fullPath: '/account/profile/$userId/data-sync'
      preLoaderRoute: typeof AccountProfileUserIdDataSyncRouteImport
      parentRoute: typeof AccountProfileUserIdRouteRoute
    }
    '/account/profile/$userId/created-builds': {
      id: '/account/profile/$userId/created-builds'
      path: '/created-builds'
      fullPath: '/account/profile/$userId/created-builds'
      preLoaderRoute: typeof AccountProfileUserIdCreatedBuildsRouteImport
      parentRoute: typeof AccountProfileUserIdRouteRoute
    }
    '/account/profile/$userId/collection-stats': {
      id: '/account/profile/$userId/collection-stats'
      path: '/collection-stats'
      fullPath: '/account/profile/$userId/collection-stats'
      preLoaderRoute: typeof AccountProfileUserIdCollectionStatsRouteImport
      parentRoute: typeof AccountProfileUserIdRouteRoute
    }
    '/account/profile/$userId/build-collections': {
      id: '/account/profile/$userId/build-collections'
      path: '/build-collections'
      fullPath: '/account/profile/$userId/build-collections'
      preLoaderRoute: typeof AccountProfileUserIdBuildCollectionsRouteImport
      parentRoute: typeof AccountProfileUserIdRouteRoute
    }
  }
}

interface GameIdRouteRouteChildren {
  GameIdItemsRoute: typeof GameIdItemsRoute
}

const GameIdRouteRouteChildren: GameIdRouteRouteChildren = {
  GameIdItemsRoute: GameIdItemsRoute,
}

const GameIdRouteRouteWithChildren = GameIdRouteRoute._addFileChildren(
  GameIdRouteRouteChildren,
)

interface ProfileRouteRouteChildren {
  ProfileBuildCollectionsRoute: typeof ProfileBuildCollectionsRoute
  ProfileCollectionStatsRoute: typeof ProfileCollectionStatsRoute
  ProfileCreatedBuildsRoute: typeof ProfileCreatedBuildsRoute
  ProfileLikedBuildsRoute: typeof ProfileLikedBuildsRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteRouteChildren: ProfileRouteRouteChildren = {
  ProfileBuildCollectionsRoute: ProfileBuildCollectionsRoute,
  ProfileCollectionStatsRoute: ProfileCollectionStatsRoute,
  ProfileCreatedBuildsRoute: ProfileCreatedBuildsRoute,
  ProfileLikedBuildsRoute: ProfileLikedBuildsRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteRouteWithChildren = ProfileRouteRoute._addFileChildren(
  ProfileRouteRouteChildren,
)

interface AccountProfileUserIdRouteRouteChildren {
  AccountProfileUserIdBuildCollectionsRoute: typeof AccountProfileUserIdBuildCollectionsRoute
  AccountProfileUserIdCollectionStatsRoute: typeof AccountProfileUserIdCollectionStatsRoute
  AccountProfileUserIdCreatedBuildsRoute: typeof AccountProfileUserIdCreatedBuildsRoute
  AccountProfileUserIdDataSyncRoute: typeof AccountProfileUserIdDataSyncRoute
  AccountProfileUserIdLikedBuildsRoute: typeof AccountProfileUserIdLikedBuildsRoute
  AccountProfileUserIdIndexRoute: typeof AccountProfileUserIdIndexRoute
}

const AccountProfileUserIdRouteRouteChildren: AccountProfileUserIdRouteRouteChildren =
  {
    AccountProfileUserIdBuildCollectionsRoute:
      AccountProfileUserIdBuildCollectionsRoute,
    AccountProfileUserIdCollectionStatsRoute:
      AccountProfileUserIdCollectionStatsRoute,
    AccountProfileUserIdCreatedBuildsRoute:
      AccountProfileUserIdCreatedBuildsRoute,
    AccountProfileUserIdDataSyncRoute: AccountProfileUserIdDataSyncRoute,
    AccountProfileUserIdLikedBuildsRoute: AccountProfileUserIdLikedBuildsRoute,
    AccountProfileUserIdIndexRoute: AccountProfileUserIdIndexRoute,
  }

const AccountProfileUserIdRouteRouteWithChildren =
  AccountProfileUserIdRouteRoute._addFileChildren(
    AccountProfileUserIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameIdRouteRoute: GameIdRouteRouteWithChildren,
  ProfileRouteRoute: ProfileRouteRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiHealthRoute: ApiHealthRoute,
  AccountProfileUserIdRouteRoute: AccountProfileUserIdRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
